### ISSUE TITLE
Pptx Recipe: pptxTable not working 

### ISSUE THREAD

**Issue by benben-user** [jsreport/jsreport#1003]
Yet not documented but also not working , not creating new table row.
See attached example link (originally forked from Pptx basic)
https://playground.jsreport.net/w/benben-user/4_1PI_16

![image](https://user-images.githubusercontent.com/109515157/202276758-ef5a50f4-81c8-4cf0-aa7e-96376333b91e.png)

ps also try use docxTable.. working but same issue

**Comment by bjrmatos** [comment]
hi! thanks for the issue, i will take a look.

> ps also try use docxTable.. working but same issue

do you mean that you tried to use docxTable in pptx recipe? it is expected that it does not work just FYI, that is why the helpers have `docx..., pptx...` prefixes as a signal that the helpers are specific
