### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by geoffatsource** [jsreport/jsreport#1005]
https://github.com/jsreport/jsreport/blob/b9beeebb536d5acde804f43d47a0d7c1a50fdeaa/packages/jsreport-pdf-utils/lib/worker.js#L12

**Comment by bjrmatos** [comment]
thanks, fixed here https://github.com/jsreport/jsreport/commit/0f6aeb64b8a99f1c69212d3218fd54449b9d8d22
