### ISSUE TITLE
components handlabars hash support

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#1007]
I've updated the components docs with an extra example of passing args to the components and it seems this should work by default.
https://jsreport.net/learn/components

The component call would look like this then
```
{{component "customer" prop1="A" prop2=@root.prop}} 
```

I think this would be the comfortable mainstream of passing extra args to the component and should be the default.
@bjrmatos  what do you think?

**Comment by bjrmatos** [comment]
i think it makes sense such merging to be the default.

in a world where handlebars is the only engine we care about i would like the most that we use the standard [data variables](https://handlebarsjs.com/api-reference/data-variables.html#root) to pass those props/hash, so you can access it in the component like `@props.prop1`, `@props.prop2`.

but considering the compatibility with other engines it seems fine that we just merge it in the context data

**Comment by pofider** [comment]
After discussion, we decided to just merge into context instead of scoping into `@props`.
