### ISSUE TITLE
html to xlsx recipe: stdout maxBuffer Exceeded

### ISSUE THREAD

**Issue by kdbo** [jsreport/jsreport#102]
Hi Jan,

I got a maxBuffer Exceeded error when trying to create a large report ( basically just a dump from a table into an xlsx document ) 
This table has about 60 entries in it for now, but has 21 fields., so not really big.
Any way I can easily set the maxBuffer higher? ( seems to be related to child-process.exec function)

**Comment by pofider** [comment]
This was fixed in the latest jsreport 0.8.2. Do you have the latest?

**Comment by kdbo** [comment]
hah no, I have 0.8.1, will try to update it now

**Comment by kdbo** [comment]
Yups that certainly helped! got it to 0.8.2 now, problem solved.
Thanks Jan!
