### ISSUE TITLE
odata does not support "ne" (NotEqual) in SQL providers

### ISSUE THREAD

**Issue by zewar96** [jsreport/jsreport#1025]
when trying to use 
/odata/folders?$filter=name%20ne%20%27tags%27%20and%20name%20ne%20%27shared%27

It works fine when using the fs provider, but fails when using PostgreSQL as a provider.  Gives the following error

{"error":{"code":500,"message":"Cannot read properties of undefined (reading 'toNode')","stack":"TypeError: Cannot read properties of undefined (reading 'toNode')\n at normalizeNode (/app-rprt/node_modules/jsreport-sql-2/lib/node/where.js:27:18)\n at constructor.add (/app-rprt/node_modules/jsreport-sql-2/lib/node/where.js:51:12)\n at constructor.where (/app-rprt/node_modules/jsreport-sql-2/lib/node/query.js:157:22)\n at module.exports (/app-rprt/node_modules/@jsreport/odata-to-sql/lib/filter.js:102:16)\n at module.exports (/app-rprt/node_modules/@jsreport/odata-to-sql/lib/query.js:66:11)\n at Object.query (/app-rprt/node_modules/@jsreport/odata-to-sql/lib/transformer.js:46:14)\n at Cursor.toArray (/app-rprt/node_modules/@jsreport/sql-store/lib/sqlProvider.js:22:29)\n at replay (/app-rprt/node_modules/@jsreport/jsreport-core/lib/main/store/collection.js:53:21)\n at /app-rprt/node_modules/@jsreport/jsreport-core/lib/main/store/collection.js:60:18\n at runMicrotasks (<anonymous>)","target":"/folders?$filter=name%20ne%20%27tags%27%20and%20name%20ne%20%27shared%27","details":[]},"innererror":{}}

I have also posted to the forum, but wanted to list it as an actual issue.  I believe the issue is in 
https://github.com/jsreport/jsreport/blob/master/packages/odata-to-sql/lib/filter.js

**Comment by pofider** [comment]
The `ne` support was missing. It's now implemented and will be part of the next jsreport release.
