### ISSUE TITLE
evaluate docxChild handlebars

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#1029]
the child docx nodes are copied to the main document as expected, however the handlebars is not evaluated.

https://playground.jsreport.net/w/Poumm/R5BFhDXg

**Comment by mmoye** [comment]
Any update on this one? We could really use this functionality in a big way.

**Comment by bjrmatos** [comment]
thanks for the heads up. this feature has not been prioritized yet, we will discuss it when preparing the backlog in the next days/week

**Comment by mmoye** [comment]
Thanks for the response! Looking forward to hearing if this one will be incorporated in the next release. We just bought a 3.x license!

**Comment by mmoye** [comment]
Hi @bjrmatos does closing this mean this functionality is now included?

**Comment by pofider** [comment]
The implementation hasn't been released yet. It will be part of the next release 4.2.0 which will be shipped during the next week(s).

**Comment by mmoye** [comment]
That's great news! Thank you so much!
