### ISSUE TITLE
Docx Recipe: docxStyle not working with expressions  

### ISSUE THREAD

**Issue by benben-user** [jsreport/jsreport#1030]
docxStyle currently allow only static text to be use.
Please allow to use docxStyle with expressions 
like : 

```
 {{#docxStyle textColor ='FF0000'}} {{a}} {{/docxStyle}}
```
example : 
https://playground.jsreport.net/w/benben-user/2WArTPwe

**Comment by pofider** [comment]
That should work. You just forgot to link the input data.
https://playground.jsreport.net/w/anon/v9U_18R1
