### ISSUE TITLE
Docx Recipe: add table cell backgroundColor support for docxStyle

### ISSUE THREAD

**Issue by benben-user** [jsreport/jsreport#1031]
Please add option to update table cell backgroundColor using docxStyle 

current option is for text only like in this image : 
![image](https://user-images.githubusercontent.com/109515157/219415487-97cf19cb-ae80-41ca-b710-ee02a54a5a2e.png)

https://playground.jsreport.net/w/benben-user/2WArTPwe

**Comment by alwyn974** [comment]
Hi, sorry for bumping this issue, but do you have any ETA for this feature ?
