### ISSUE TITLE
Using afterRender return an Error on API call

### ISSUE THREAD

**Issue by benben-user** [jsreport/jsreport#1032]
Using the follow stack : 
docx + handlebars + templateAsset + unoconv , 
When adding afterRender in the studio with asset the call work as expected , But using API with templateAsset as Base64 the call fail with the follow error 
```
{
    "message": "Cannot set property offset of [object Object] which has only a getter",
    "stack": "TypeError: Cannot set property offset of [object Object] which has only a getter\n    at merge (/app/node_modules/@jsreport/jsreport-scripts/lib/worker.js:174:20)\n    at merge (/app/node_modules/@jsreport/jsreport-scripts/lib/worker.js:176:11)\n    at merge (/app/node_modules/@jsreport/jsreport-scripts/lib/worker.js:176:11)\n    at merge (/app/node_modules/@jsreport/jsreport-scripts/lib/worker.js:176:11)\n    at merge (/app/node_modules/@jsreport/jsreport-scripts/lib/worker.js:176:11)\n    at Scripts._runScript (/app/node_modules/@jsreport/jsreport-scripts/lib/worker.js:195:7)\n    at async Scripts.handleAfterRender (/app/node_modules/@jsreport/jsreport-scripts/lib/worker.js:117:9)\n    at async ListenerCollection.fire (/app/node_modules/@jsreport/jsreport-core/lib/shared/listenerCollection.js:157:21)\n    at async afterRender (/app/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:103:5)\n    at async WorkerReporter._render (/app/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:148:7)"
}
```

body looks like this (see postman example attached)

![image](https://user-images.githubusercontent.com/109515157/219472933-0edfdc17-c4ef-466a-90f2-dd6be7da8797.png)

Here is an export for the stack:
[afterRender_APIBUG.jsrexport.zip](https://github.com/jsreport/jsreport/files/10760195/afterRender_APIBUG.jsrexport.zip)

I create a  server using jsreport/jsreport:3.10.0-full to test this (will be available for short time) 
Please find a postmen collection to reproduce the issue 
[jsBug.postman_collection.json.zip](https://github.com/jsreport/jsreport/files/10760126/jsBug.postman_collection.json.zip)

**Comment by bjrmatos** [comment]
hi!, thanks for opening new issue.

i've found that we have an issue with this specific case, just for the sake of simplicity i am going to describe my findings here: 

the problematic part is our [`merge` function](https://github.com/jsreport/jsreport/blob/master/packages/jsreport-scripts/lib/worker.js#L167) that we use in scripts extension, in this specific case our internal `req` object ends containing buffer, and because of that our merge tries to deeply merge this buffer, and because of that produces the error you are seeing.

a possible fix can be changing the `merge` function to be aware of Buffers, like this:

```js
function merge (obj, obj2) {
  for (const key in obj2) {
    if (typeof obj2[key] === 'undefined') {
      continue
    }

    if (Buffer.isBuffer(obj2[key])) {
      obj[key] = Buffer.from(obj2[key])
    } else if (Object.prototype.toString.call(obj2[key]) === '[object Uint8Array]') {
      const newBuf = Buffer.from(obj2[key].buffer)

      if (obj2[key].byteLength !== obj2[key].buffer.byteLength) {
        newBuf = newBuf.slice(obj2[key].byteOffset, obj2[key].byteOffset + obj2[key].byteLength)
      }

      obj[key] = newBuf
    } else if (typeof obj2[key] !== 'object' || typeof obj[key] === 'undefined') {
      obj[key] = obj2[key]
    } else {
      merge(obj[key], obj2[key])
    }
  }
}
```

anyway we are going to check this and decide the best solution, thanks again for the bug report.

**Comment by pofider** [comment]
Yes, this is the right approach, we are going to fix it in the next hotfix/release.
