### ISSUE TITLE
pdfjs-dist installed twice on a clean installation 

### ISSUE THREAD

**Issue by benben-user** [jsreport/jsreport#1033]
Clean installation of Jsreport using cli install pdfjs-dist in node_modules twice:
1. stanalone module : _ver:2.12.313_ **35.7 MB**
2. @jsrerpot/pdfjs/node_modules/pdfjs-dist :  _ver:2.14.305_ **35.76MB**

can we remove one of this installation to reduce size ?

**Comment by bjrmatos** [comment]
hi, yes this looks something that we can check and fix, thanks for opening the issue
