### ISSUE TITLE
Feature request: string interpolation in localization

### ISSUE THREAD

**Issue by sammeel** [jsreport/jsreport#1034]
It seems that the localization process does not allow to do string interpolation.

It would be nice if this feature was added. This would help to avoid segregation of localized strings. 
For example suppose you have a page numbering like this:
`p. 1 of 15`

Currently we need to define 2 translation keys for this single purpose, 1 for the "p." and one for the "of". This makes the purpose of the translation keys unclear as well as who should define the spaces before and after the "of".

It would be nicer if we could interpolate the correct values into the string:
`{{ localize "footer.page-number" "../translations" pageNumber totalPages }}`

The template string value could look like `p. {0} of {1}`

**Comment by pofider** [comment]
You can implement your own extended `localize` function like this
```js
const vm = require('vm')
const interpolate = (tmpl, vars) => {
    return vm.runInNewContext('`' + tmpl + '`', vars)    
}

async function localizeExt(key, folder, opts) {  
    const v = await localize(key, folder)
    return interpolate(v, opts.hash)
}
```
https://playground.jsreport.net/w/anon/3O_g94m1

**Comment by pofider** [comment]
I've updated the docs to include this example.
Perhaps in time, we add it to the `localization` function as well, but for now we keep it in docs.

**Comment by sammeel** [comment]
Thanks for that suggestion. That looks usable enough for us for now. And thanks for updating the documentation.
