### ISSUE TITLE
Chart generation with PPTX

### ISSUE THREAD

**Issue by illianechesa** [jsreport/jsreport#1038]
Currently, I am trying to find a way how to generate a chart in JSReport. As the data must be introduced via an excel file, would it be somehow possible to fetch a JSON with this data, inject it on an XLSX, and use it as an engine for the population of the PPTX template? So far I did not find any approach like this, just wondering if it's something I should even consider.

Another approach you commented on is using setting chart specifications using openxml. But not sure if this is something feasible for custom charts on PPTX.

**Comment by pofider** [comment]
Unfortunately, the PPTX recipe is limited and doesn't support charts so far.
We have a plan to merge there docx/xlsx helpers so more advanced cases like this one will work there as well.
We should get to it later this year.

**Comment by illianechesa** [comment]
Okay, thank you for the heads up 👍

**Comment by bjrmatos** [comment]
this is now covered in https://github.com/jsreport/jsreport/commit/9776cf31b3bd680ec0bafa792788e385e1434174, and it will be part of next release
