### ISSUE TITLE
Users with edit permissions can not login when use the freeze extension

### ISSUE THREAD

**Issue by jorisdebock** [jsreport/jsreport#1040]
jsreport: 3.4.2
authentication: 3.2.0
authorization: 3.2.0
freeze: 3.0.1

I am using the freeze extension to allow users to use jsreport in read-only mode. 

But I noticed today that users which also have edit permissions (in my case on a folder) they get the following error when trying to login. Admin or users with only read access can always login

```
Editing is frozen through jsreport-freeze extension.
```

I would expect that any user can login and view the templates

**Comment by pofider** [comment]
I've tried with the latest 3.10.0 the following.

- Login as admin
- Create folder
- Create user
- Edit folder and assign edit permissions to the custom user
- Logout admin and login with the custom user
- I can login and see no errors....

Could you check this flow?

**Comment by jorisdebock** [comment]
I have tested it with the latest version and I can not reproduce it
