### ISSUE TITLE
{{if}} conditions on the same line causes JSReport to fail PDF generation.

### ISSUE THREAD

**Issue by MuhammadHasham23** [jsreport/jsreport#1041]
I am trying to export a PDF file from a MS-word template with engine as handlebars. The weird this is that this works within the template:

```
{{#if location.plan}} 
.......
{{/if}}
{{#if attachments.length}}
.....
```

But this does not:

```
{{#if location.plan}} 
.......
{{/if}}{{#if attachments.length}}
.....
```

So in conclusion when `{{\if}} and new `{{#if}}` are on the same line it doesn't work. This is the error message that I get from JSReport

```
xmldom element parse error: Error: Hierarchy request error: Only one element can be added and only after doctype
```

**Comment by pofider** [comment]
Thank you. Does this mean you use the `docx` recipe and type the handlebars tags inside ms word?
Would you be able to share a simple playground replicating the issue? Thank you
https://playground.jsreport.net/
