### ISSUE TITLE
JsReport 3.10 missing from JsReport.DotNet.Binary

### ISSUE THREAD

**Issue by foggerty** [jsreport/jsreport#1044]
Hi, I created an issue on the JsReport.Binary repo (https://github.com/jsreport/jsreport-dotnet-binary/issues/3) a few days ago, but there hasn't been any activity there for a few months :-)

As the subject says, the most recent version of JsReport.Binary is 3.9, having access to 3.10 also would be great!

Cheers,

Matt.

**Comment by pofider** [comment]
The latest 3.11.0 has been just released.
