### ISSUE TITLE
jsreport docker images: issue with permissions on jsreport volume

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#1045]
context: https://forum.jsreport.net/topic/2717/docker-compose-example

looks like our jsreport user/group is using uid, gid that gets mixed with system user/groups on ubuntu.

analyze [this post](https://nickjanetakis.com/blog/running-docker-containers-as-a-non-root-user-with-a-custom-uid-and-gid) and provide a solution by allowing customize the uid and gid of the jsreport user/group, and use a default value of >= 1000

**Comment by colangiuli** [comment]
Any update on this?

**Comment by bjrmatos** [comment]
we have not assigned any priority to this yet, but we will check when preparing the next release
