### ISSUE TITLE
docker: update node.js version 

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#1050]
node.js v16 goes end of life this year ([https://endoflife.date/nodejs#:~:text=The End-of-Life date,1 on September 11th%2C 2023.)](https://endoflife.date/nodejs#:~:text=The%20End%2Dof%2DLife%20date,1%20on%20September%2011th%2C%202023.))

we need to update our docker files to work against different base image than node 16

**Comment by pofider** [comment]
Done in 3.13.0
