### ISSUE TITLE
Upgrade of vm2 (security vulnerability)

### ISSUE THREAD

**Issue by wouterdeman** [jsreport/jsreport#1052]
Could the vm2 dependency be upgraded? 

The current version has open security vulnerabilities: https://security.snyk.io/package/npm/vm2

Thanks in advance.

**Comment by pofider** [comment]
Yes, we are working on it. It will be in the next update.

**Comment by wouterdeman** [comment]
Perfect, thanks for the fast response ;)

**Comment by vatsalpatel68** [comment]
@pofider Does it fix in @jsreport/jsreport-core@3.11.4?

**Comment by pofider** [comment]
yes...

https://github.com/jsreport/jsreport/blob/3.11.3/packages/jsreport-core/package.json#L74
