### ISSUE TITLE
Xlsx recipe: data containing \u000b results in faulty result

### ISSUE THREAD

**Issue by mm3141** [jsreport/jsreport#1053]
Our customer creates an Xlsx report out of data containing some "\u000b" characters. Using these untreated in the Xlsx recipe results in Excel files which Office complains about ("needs repair").

This can be reproduced in the playground:

playground version: 3.10.1
jsreport version: 3.10.0

pick the 'xlsx invoice' example, put \u000b into some text and run the report:
```
{
    "invoiceNumber": "T-123",
    "company": {
        "name": "jsreport",
        "address": "Prague 345",
        "email": "foo",
        "phone": "phone"
    },
    "date": "07/02/22",
    "items": [{
        "name": "Product\u000b 1",
        "taxed": false,
        "amount": 2375
    }, {
        "name": "Service 1",
        "taxed": true,
        "amount": 235
    }]
}
```
![image](https://user-images.githubusercontent.com/7443263/233953749-f9c80077-de1e-49b9-8d90-8f7a17d15609.png)

**Comment by bjrmatos** [comment]
thanks for the report, we are going to automatically remove those characters in the xlsx content
