### ISSUE TITLE
JsReport ChromePdf receive is not retaining the accurate width and height of any element.

### ISSUE THREAD

**Issue by AhsanArshad004** [jsreport/jsreport#1054]
I am writing to report an issue we are facing while generating PDF reports using JsReport in our C# application. As per the JsReport documentation, we have followed all the necessary steps to generate the PDF, but we have noticed that the measurement of the HTML provided to JsReport is disturbed during the process.

To investigate this issue, I have conducted a test using the online JsReport playground and noticed that when I specified the header height as 8mm in the header-footer file, the generated PDF automatically changed the header height to around 7.5mm. I have attached an image for your reference, where you can see that I have used the Adobe measuring tool to verify the measurement.
![image](https://user-images.githubusercontent.com/44299880/236442995-2a459be9-5cf5-42f2-a5fa-7e0e99cd8f3a.png)

Playground URL: https://playground.jsreport.net/w/anon/5dJ0a4UC

I would appreciate it if you could look into this issue and provide us with a solution or workaround to fix the measurement problem.

**Comment by pofider** [comment]
I apologize for the later answer...

jsreport does nothing with the sizes in the pdf. What you get is what we get out of the chrome.
With this in mind, I've tried to step by step-check what styling in your template can change the size of the particular element.
I've found it is the following:

```
 .footer {
              width: 100%;
            max-height: 10mm;
            /****** the following affects the size of the header bar *****/
            margin-bottom: 7mm;
            margin-left: 9.5mm;
            margin-right: 5mm;
           /******* end *****/
        }
```
If you replace the footer css margin with the page margins in the header-footer template's chrome settings, you should get the 8mm size.

I can't explain why. It's how chrome evaluates that flex structure. I'm not an expert on CSS layouts so I can't tell you more.
