### ISSUE TITLE
Recipe HtmlEmbeddedInDocx

### ISSUE THREAD

**Issue by herbat73** [jsreport/jsreport#1055]
I am having problem with export html with embedded images to doc.
After exporting, docx document does not contain images and charts.
Works well with exporting to pdf by Recipe ChromePdf.

In html source I have images like

`<img src="[/uploads/workspaces/1/editor/4e82b6ac65a545df8a88e5a08215c07a.jpg](http://localhost:53186/uploads/workspaces/1/editor/4e82b6ac65a545df8a88e5a08215c07a.jpg)" width="626" style="cursor: nwse-resize;">`

JsReport is running on external docker 

code:

```
            HttpContext.JsReportFeature()
                .Recipe(Recipe.HtmlEmbeddedInDocx)
                .Configure(c => c.Options.Base = _configuration["JsReportConfiguration:HostUri"])
                .Configure(c => c.Template.Name = urlFriendlyFileName);
```

Tried on jsreport playground and it is not exporting to docx properly

```
<!DOCTYPE html>
<html>
<head>
    <title>Raport</title>    
</head>
<body>
    <p>foo bar</p>
    <img src="https://www.rainforest-alliance.org/wp-content/uploads/2021/06/scarlet-macaw-square-2-400x400.jpg"/>
</body>
</html>
```

I have found a workaround. All you need is to covert source of image to base64 and embed it and make it as full self containing web page.

```
<!DOCTYPE html>
<html>
<head>
    <title>Raport</title>    
</head>
<body>
    <p>foo bar</p>
    <img src="data:image/png;base64,iVBORw0KGg ... =="/>
</body>
</html>
```

Do you know any other option.

**Comment by pofider** [comment]
I apologize for the late answer. Yes, you need to use base64 encoded images. The word format for inline HTML is limited.

I've updated docs mentioning this with a demo for converting images to base64 using a custom helper.
