### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by jfreak53** [jsreport/jsreport#106]
When I run on my VPS server I get the error in the title of this issue. It works perfectly fine on my localhost machine. The second I upload it to my VPS and run it there I get this problem.

I have checked the VPS and the VPS does "not" have IPTables even running, let alone any ports blocked.

This is the debug output:

```
# node index.js
info Initializing embedded storage at /root/reportdev/node_modules/jsreport/data
info Searching for available extensions in /root/reportdev/node_modules/jsreport
info Found 23 extensions
info Using extension html
info Using extension templates
info Using extension data
info Using extension phantom-pdf
info Extensions loaded.
info Initializing embedded storage at /root/reportdev/node_modules/jsreport/data
info reporter initialized
info Starting rendering request 1 (user: null)
debug Inline data specified.
debug Pdf recipe start.
error Error when processing render request Error during rendering report: connect ECONNREFUSED Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
From previous event:
    at Reporter.render (/root/reportdev/node_modules/jsreport/lib/reporter.js:147:8)
    at /root/reportdev/node_modules/jsreport/index.js:84:38
```

Here is the config file:

```
{
    "certificate": {
        "key": "certificates/jsreport.net.key",
        "cert": "certificates/jsreport.net.cert"
    },
    "connectionString": { "name": "neDB" },
    "httpPort": 8088,
    "blobStorage": "fileSystem",
    "cluster": {
      "numberOfWorkers": 2,
      "enabled":  false
    },
    "phantom": {
        "numberOfWorkers" : 2,
        "strategy": "dedicated-process",
        "timeout": 180000
    },
    "tasks": {
        "numberOfWorkers" : 2,
        "strategy": "dedicated-process",
        "timeout": 10000
    }
}
```

I've tried with and without the `strategy` param. I've also tried different `httpPort`'s. I know for positive that 8088 is not blocked, as if I start up apache on that port it works fine.

I cannot setup as a standalone server and connect to it, so I really need to figure out why it's doing this please.

Node version on the server is 0.12.7 and on my localhost is 0.12.4.

**Comment by pofider** [comment]
Hi, which version of jsreport you have?  It would be also interesting to know if the plain html recipe works for you. Since 0.8.1 the dedicated-process strategy should be the default one and it should fix this issue. The support for this strategy was introduced in the 0.7.0 but, not sure how it was actually working, I would need to check on the particular version you have.

Please check this blog post for understanding the strategy configuration
http://jsreport.net/blog/performance-impacting-change-in-v08

I see from the logs you are using jsreport rendering shortcut:
`require("jsreport").render(...)`
In this case jsreport is skipping `express` extension which is responsible for starting an external http server. This means that it also ignores `httpPort` configuration value you provided. The exception comes during the rendering process which signalizes problem in the communication between jsreport node process and phantomjs or process responsible for rendering the templating engines.

**Comment by jfreak53** [comment]
Well that could be my problem, I downloaded JSReport from the site and inserted it into `node_modules`. According to my JSON config I'm running 0.5.0 :(

How would I go about upgrading from CLI using NPM?

This is my current code for running it:

```
require('jsreport').render({
	template: {
		content: content,
		engine: 'handlebars'
	},
	recipe: 'phantom-pdf',
	data: data,
	phantom: {
		numberOfWorkers: 1,
		timeout: 180000,
		allowLocalFilesAccess: false
	}
}).then(function ( out ) {
	out.result.pipe(res);
}).catch(function ( e ) {
	res.end(e.message);
});
```

The `content` variable being used is straight HTML in Handlebars format. I'm also not using express as this is a very simple API system I am running. I am running a straight HTTP server by `http.createServer` on port 8080.

```
http.createServer(function ( req, res ) {
  //Code for jsreport from above
}).listen(config.port);
```

**Comment by pofider** [comment]
Hi,

deleting jsreport folder and typing `npm install jsreport` should work fine for you.

In the latest version of jsreport it uses inter process communication and there is no need for setting up a port for it. It should just work.

Please do the update and let me know.

**Comment by jfreak53** [comment]
Perfect! Now it's working like a charm! Thanks for the help.

Quick question for you since I have this open. At this point in time doing what I'm about to ask is not possible. But for future reference I would like to know as we plan on scaling the system later.

At what point would it be hoove of me to change from the process of jsreport internal to a separate jsreport server and client connecting inside the main node app? 500 reports a day? More?

Just so I have an idea of what number is going to start showing significant speed loss due to too many PDF generating.

**Comment by pofider** [comment]
It is about 300ms slower for one rendering. Lets say you won't see a big difference when you run less than 60 reports per minute.
