### ISSUE TITLE
BlobName is empty for new records VersionType and ProfileType

### ISSUE THREAD

**Issue by jorisdebock** [jsreport/jsreport#1062]
jsreport: 3.11.2
jsreport-oracle-store: 3.2.1
jsreport-version-control: 3.1.2

blobName is empty in jsreport_VersionType and jsreport_ProfileType table for new records

causing the blob not to be found e.g.
```
Error: Blob null wasn't found at module.exports (node_modules/@jsreport/jsreport-core/lib/shared/createError.js:10:13) 
at MainReporter.createError (node_modules/@jsreport/jsreport-core/lib/shared/reporter.js:49:12) 
at Object.read (node_modules/@jsreport/jsreport-core/lib/main/blobStorage/blobStorage.js:8:24)
at async node_modules/@jsreport/jsreport-core/lib/main/blobStorage/mainActions.js:4:17 
at async node_modules/@jsreport/advanced-workers/lib/threadWorker.js:80:38...
```

steps:
1. start an empty jsreport instance
2. create a new template
3. save
4. version control: save uncommited changes

same error when opening a profiler log

**Comment by pofider** [comment]
Thank you. 
Fixed with https://github.com/jsreport/jsreport/commit/758d397acf6e8423503528406a1977bcce6519a9
Released in @jsreport/jsreport-oracle-store@3.2.2
