### ISSUE TITLE
ARM on AWS

### ISSUE THREAD

**Issue by ly-ericp** [jsreport/jsreport#1065]
The latest-full won't stay running in AWS, looks like the oracledb extension is missing. I have tried previous versions as well, no luck.

6/5/2023, 2:08:19 PM EDT	Error: Error when loading extension oracle-store@3.2.1	-	-
6/5/2023, 2:08:19 PM EDT	Error: Cannot find module 'oracledb'	-	-
6/5/2023, 2:08:19 PM EDT	Require stack:	-	-
6/5/2023, 2:08:19 PM EDT	- /app/node_modules/@jsreport/jsreport-oracle-store/lib/main.js	-	-
6/5/2023, 2:08:19 PM EDT	- /app/node_modules/@jsreport/jsreport-core/lib/main/extensions/extensionsManager.js	-	-
6/5/2023, 2:08:19 PM EDT	- /app/node_modules/@jsreport/jsreport-core/lib/main/reporter.js	-	-
6/5/2023, 2:08:19 PM EDT	- /app/node_modules/@jsreport/jsreport-core/index.js	-	-
6/5/2023, 2:08:19 PM EDT	- /app/node_modules/jsreport/index.js	-	-
6/5/2023, 2:08:19 PM EDT	- /app/server.js

**Comment by bjrmatos** [comment]
i think this should be fixed in jsreport 3.13.0, please check again.
