### ISSUE TITLE
Handlebars/Chrome-pdf problem with broken fonts (starts with version 3.9.0)

### ISSUE THREAD

**Issue by wsolara** [jsreport/jsreport#1069]
Hello. 

We used jspreport v3.4.1. 
We have a template with engine handlebars and recipe chrome-pdf.

We recently updated jsreport to the latest version and found that fonts were broken in our pdf.

Using a binary search method, we found that the problem starts with the version 3.9.0.

Can you suggest how we can solve this problem. Thank you.

![image](https://github.com/jsreport/jsreport/assets/69395209/d74a0f91-96ff-402f-82d7-4ec2150019f4)

**Comment by pofider** [comment]
Please share minimal, few lines html, which doesn't work for you.

**Comment by wsolara** [comment]
I also need to say that everything works fine in the jsreport studio, it does not work only when called from node-js client (https://github.com/jsreport/nodejs-client)

**Comment by pofider** [comment]
There is no reason that it shouldn't work when called from the API. The logic for printing is the same.
Try to render the HTML recipe and inspect what is different in the output when called from API and when called from studio.
