### ISSUE TITLE
JSReport XLSX render in Viewer or Download

### ISSUE THREAD

**Issue by jfreak53** [jsreport/jsreport#107]
So I've done some searching through the docs and can't find anything on this. In the JSreport demo site when demoing XLSX it previews in Office Viewer inline:

![Preview1] (http://cdn.microthosting.com/imgs/Screenshot_at_2015-09-01_09-31-09.png)

But when doing this in my script it shows it in the browser as something else entirely haha:

![img2] (http://cdn.microthosting.com/imgs/Screenshot_at_2015-09-01_09-31-57.png)

Kind of like it does with a PDF. So I guess my question is, is there a way to get it to render "to" Office Viewer as the JSReport demo here does:
https://playground.jsreport.net/#/playground/YBjmBsPFa

Or make the browser download the XLSX file instead of displaying?

Here is my code:

```
require('jsreport').render({
	template: {
		content: content,
		engine: 'handlebars'
	},
	recipe: 'xlsx',
	data: data,
	phantom: {
		numberOfWorkers: 1,
		timeout: 180000,
		allowLocalFilesAccess: false
	}
}).then(function ( out ) {
	out.result.pipe(res);
}).catch(function ( e ) {
	res.end(e.message);
});
```

**Comment by pofider** [comment]
1. 
you should set the recipe to the template
```
.render({
    template: {
        content: content,
        recipe: "xlsx",
        engine: 'handlebars'
    },
```
2.
you need to add xlsx recipe to the config
```
require("jsreport").renderDefaults.extensions.push("xlsx");
```
3.
afterwards you get back xlsx stream. if you want to get html with iframe pointing to office online instead, you shoud set `options.preview = true` to the request
```
.render({
    template: { },
    options: { preview: true }
```

**Comment by jfreak53** [comment]
Aha! Let me try that now. Is this in the documentation somewhere that I missed?
