### ISSUE TITLE
Update package?

### ISSUE THREAD

**Issue by zewar96** [jsreport/jsreport#1072]
Is there a specific reason that "liftoff": "3.1.0" is used instead of 4.0.0?  I ask because of some nested dependencies on 3.1.0 that are showing as vulnerable (the different versions of "kind-of").  I know they are probably not an issue, but I figure I would ask if there was an issue before I have to do a writeup on a false positive for our scan results.

**Comment by zewar96** [comment]
While looking at this, i also noticed some inconsistencies in versions used within your own packages.  For example:

jsreports-cli
jsreports
jsreports-core

all use different versions of "semver".  Again...i know this isn't an issue, i just wanted to point it out in case it could be updated to the latest version across all packages.  If there is a better way for me to help, maybe create a PR for you guys or something, please let me know.  I know this is a time consuming pain to try to keep up with all of these constant changes.  Since I am required to scan and go through this anyway for my job, i would be willing to help where i can or however i can.

**Comment by bjrmatos** [comment]
hi @zewar96

yes, the audits always report something new between releases, thanks for creating the issue.

we are going to try to update both the `liftoff` and `semver` (and using same version) in the next jsreport version.

we updates the deps at the last step of our release process so we are going to handle it, thanks for offering help anyway
