### ISSUE TITLE
Improve pdf accessibility PDF/UA

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#1075]
https://forum.jsreport.net/topic/2858/accessibility-issues-on-blank-pdf

**Comment by bobsyourgrannie** [comment]
Hi Jan, adding accessibility in our PDFs for our customers is becoming a much more important issue for them and by extension for us to keep using jsreport as a solution. I expect other customers might be encountering this issue more and more as well. I am happy to upload some example files that contain issues within their content if it is useful to provide some accessibility validation against them.

[Report_Test Print 2_DRAFT_2023-03-15.pdf](https://github.com/jsreport/jsreport/files/12115419/Report_Test.Print.2_DRAFT_2023-03-15.pdf)
[Report_ANZ Test 2 March 2023_V6_2023-07-20.pdf](https://github.com/jsreport/jsreport/files/12115420/Report_ANZ.Test.2.March.2023_V6_2023-07-20.pdf)
