### ISSUE TITLE
docx: docxImage support for svg files

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#1078]
context: https://github.com/jsreport/jsreport-images/issues/2#issuecomment-1647971229

make sure to test case when it is downloaded from remote src.

test remote svg file: https://upload.wikimedia.org/wikipedia/commons/4/4f/SVG_Logo.svg

**Comment by mdarkawi** [comment]
Hi again
it still does not work for remote or svg+xml base64 string
can you give your feed back.
https://playground.jsreport.net/w/anon/dzrQmtR2

**Comment by bjrmatos** [comment]
this is what you see in the preview when generating your example

![Screenshot 2024-09-12 at 10  53 52@2x](https://github.com/user-attachments/assets/8fdb509f-b823-40db-8813-eb48a80ef8dd)

i think you assume it is not working because the preview shows that, however if you open the document in word you will see it works.

![Screenshot 2024-09-12 at 10  54 52@2x](https://github.com/user-attachments/assets/740534ca-c496-47e1-8e04-11c28ea359b6)

we are aware of this, it is a limitation, when using svg the document expects that you add another image (.jpg or .png) for the preview. 

For now, we don't want to complicate the code or add code to generate these previews, because it will require adding some dependency to handle conversion. maybe in the future we will let the user pass the preview/fallback image instead.

**Comment by mdarkawi** [comment]
indeed svg are correctly generated, with remote url or base64 starting with "data:image/**svg+xml**;base64,..."

Thanks for your responsiveness.
