### ISSUE TITLE
jsreport server does not start (v 0.8.1.0)

### ISSUE THREAD

**Issue by fduverger** [jsreport/jsreport#108]
Hi Jan!

I have been using your tool in my project for a while now and I have no complain about it. Great job and Thanks!

I had to change my personal computer and now when I try to run one of my asp.net mvc 4 projects that uses jsreport it crashes in the Global.asax on the line:
EmbeddedReportingServer.StartAsync().Wait();

Error message:
"...Failed to start jsreport server. Examine ServerStandardOutput and ServerErrorOutput properties for details"

ServerStandardOutput and ServerErrorOutput properties are "" and null respectively.

When I check my localhost:2000 there is no jsreport running. Before I was able to see it running.

I have node version 0.12.7 globally installed in my new computer  and was able to run jsreport from the command prompt.

I am running on a Windows 8 computer

Thanks for your help

**Comment by pofider** [comment]
Hi,
please try following:

- run jsreport from the command line and your bin folder : node server.js --httpPort 2000
what does it do?
- try to run jsreport.embedded outside the bin folder
```js
var embeddedServer = new EmbeddedReportingServer() { RelativePathToServer = "../App_Data" };
await embeddedServer.StartAsync();
```
- try to increase start timeout
```js
var embeddedServer = new EmbeddedReportingServer() { StartTimeout = new TimeSpan(0.0.2.0);};
await embeddedServer.StartAsync();
```
- maybe you are not able to bind to http://localhost on your pc, try our local ip address
```js
var embeddedServer = new EmbeddedReportingServer() { EmbeddedServerUri = "http://196.168.x.x:200";
await embeddedServer.StartAsync();
```

- try different port

**Comment by fduverger** [comment]
Thanks for taking the time to answer me. 

I was able to start the jsreport from the command promt. Please see the images below:
![started jsreport](https://cloud.githubusercontent.com/assets/5233709/9634241/b8f1b68a-515e-11e5-80ac-326de5faf05b.png)
![jsreport sudio running](https://cloud.githubusercontent.com/assets/5233709/9634244/bb7f1b04-515e-11e5-8eff-6b0e4482ec5b.png)

 I did all of the other suggestions but they didn,t work in my case. I am still getting the same error

**Comment by pofider** [comment]
There could be a problem with windows limit for  maximum 260 length for file path. 

Could you try to copy-paste the project somewhere up the tree, like to c:\work and try again?

**Comment by fduverger** [comment]
You were completely right. 
Thanks for your help
