### ISSUE TITLE
docx: docxImage allow remove placeholder if src empty

### ISSUE THREAD

**Issue by benben-user** [jsreport/jsreport#1081]
Currently if the src attribute is empty the doc creation is failed with error. 
The FR is to add another attribute to allow the src to be empty, and in this use case to remove the image place holder. 

currently we are using If condition around the image place holder and check it the src (base64 or https URL) is empty.

**Comment by pofider** [comment]
I appologize, we are now busy solving more critical things.
This seems to have a workaround, so we get to it later.

**Comment by bjrmatos** [comment]
this is supported with the use of `failurePlaceholderAction` configured to `remove`
