### ISSUE TITLE
How to launch docker containers from JSReport in docker container?

### ISSUE THREAD

**Issue by fedoranvar** [jsreport/jsreport#1083]
good day to you!

i'm launching jsreport in docker and trying to improve performance in handling parallel rendering by using docker-workers extension, but my jsreport can't ping docker workers

![image](https://github.com/jsreport/jsreport/assets/52028706/42f80d4c-c5f0-47f2-9e00-ef659c3eeaac)

can you help me?

**Comment by pofider** [comment]
Closing because there is no additional information provided. Don't hesitate to continue and write comment.
