### ISSUE TITLE
After upgrading to v3.13.0 the shortid is no longer visible under settings gear-> API

### ISSUE THREAD

**Issue by iii-james** [jsreport/jsreport#1089]
v2.6.1
![image](https://github.com/jsreport/jsreport/assets/46497848/28372b6c-c341-439b-96e0-05bf1093433f)

v3.13.0
![image](https://github.com/jsreport/jsreport/assets/46497848/c7252d3f-1743-4677-a189-8a424a534de5)

**Comment by pofider** [comment]
It's in the url

![image](https://github.com/jsreport/jsreport/assets/2041960/d9290c8f-4bc7-4658-9d9f-8f71a72d11f6)

Or when you inspect the template

![image](https://github.com/jsreport/jsreport/assets/2041960/6bc4d006-c8b1-440a-bb63-a50ed398f34e)
