### ISSUE TITLE
The cli v4 is unable to start

### ISSUE THREAD

**Issue by sammeel** [jsreport/jsreport#1092]
We noticed that the jsreport cli is unable to start with the latest version.

To reproduce, you can run `npx @jsreport/jsreport-cli -v`

![image](https://github.com/jsreport/jsreport/assets/1624852/72d30ad9-8604-4099-b3c8-91201ba119d8)

Or run the example from the docs:
![image](https://github.com/jsreport/jsreport/assets/1624852/917f085e-e2ad-4b89-a251-5c4b3d324fcf)

**Comment by pofider** [comment]
Apologies, we are in the middle of the releasing. This will be fixed today.
