### ISSUE TITLE
Multiple issues with 4.0.0 release

### ISSUE THREAD

**Issue by hswami** [jsreport/jsreport#1095]
Using Docker container to run latest image with v4.0.0, on a report containing 8 cols and 5,766 rows:

PDF render (using chrome-pdf recipe) causes Docker Desktop VM to crash hard - requires a VM restart
Excel render (using xlsx recipe) causes XML errors inside the engine and renders an Excel file that Excel refuses to open

**Comment by hswami** [comment]
We found the issue with the Excel render ... it appears that an '&' character in the data causes malformed XML to be rendered. We tried setting the configuration "extensions : xlsx : escapeAmp" to both "true" and "false" and got the same behavior with file being rendered that Excel refuses to open.

No idea still on what is causing the PDF render to crash the system so hard.

**Comment by hswami** [comment]
This is the jsreport.config.json used for the Docker container:

{
	"httpPort": 5488,
	"allowLocalFilesAccess": true,
	"reportTimeout": 60000,
	"enableRequestReportTimeout": true,
	"logger": {
		"console": {
			"transport": "console",
			"level": "debug"
		},
		"file": {
			"transport": "file",
			"level": "info",
			"filename": "logs/reporter.log"
		},
		"error": {
			"transport": "file",
			"level": "error",
			"filename": "logs/error.log"
		}
	},
	"chrome": {
		"timeout": 60000
	},
	"templatingEngines": {
		"numberOfWorkers": 8,
		"timeout": 60000,
		"strategy": "http-server"
	},
	"extensions": {
		"authentication": {
			"enabled": false
		},
		"studio": {
			"enabled": true
		},
		"express": {
			"enabled": true,
			"inputRequestLimit": "300mb"
		}
	}
}

**Comment by hswami** [comment]
I can replicate both these problems in 3.13.0 and 3.12.0 so this is not new in 4.0.0.

**Comment by pofider** [comment]
I've tried the following template with docker image `jsreport/jsreport:4.0.0`. It works for me
https://playground.jsreport.net/w/anon/MJFQOZT7
Could you share a **minimal** playground template that doesn't work for you?

Regarding the `&` in xlsx.. Could you also share a minimal playground? Thank you.

**Comment by pofider** [comment]
There are strict limits for memory in playground and long pdf tables are badly performing in chrome
https://github.com/puppeteer/puppeteer/issues/8070
There is not much we can do about it. If you get the same error, you will need to make sure you provide more resources and if it doesn't help, you would need to replace `table` with `div`s.

**Comment by hswami** [comment]
https://playground.jsreport.net/w/hswami/2Z0WXVZx

![image](https://github.com/jsreport/jsreport/assets/3248104/a487c3f6-1cc8-46c4-9a2d-96c73c474727)

![image](https://github.com/jsreport/jsreport/assets/3248104/3bd47281-7b79-4a21-80ba-92845d05e815)

I hope this helps.

**Comment by hswami** [comment]
Are there any updates on this? I am encountering both problems with local docker containers (large PDFs and Excel with '&' in the data).

**Comment by bjrmatos** [comment]
@hswami I've checked the example on the playground but i don't see the `&` being used in the data, is this expected? because you mention that you get an invalid xml document when using the `&` in data, but i don't such character being used, can you specify which line of the data has this character? i've trying searching for it but not able to find it.

you are right about that using the `&` character produces an invalid document (short and simple evidence of it [here](https://playground.jsreport.net/w/anon/zdSPvdSY)) and we are going to analyze the best fix for it, however, i don't understand why your example which seems to not be using the `&` still produces bad xlsx.

**Comment by hswami** [comment]
@bjrmatos line #9449

![image](https://github.com/jsreport/jsreport/assets/3248104/6fc6de38-87fc-45c7-bf92-d06c66b074f5)

**Comment by hswami** [comment]
The underlying value is '&' ... Newtonsoft is serializing it to \u0026

**Comment by hswami** [comment]
@bjrmatos Is that escaping causing the problem with the Excel render?

**Comment by bjrmatos** [comment]
i see, so you were using the unicode representation of the character, yes it causes the problem when using any of the characters (either raw `&` or `\u0026`).

will investigate how to make it work generally, thanks for the issue report. i will switch to this task when finishing other bug fixes i am working on right now

**Comment by bjrmatos** [comment]
this should be fixed with jsreport `4.1.0`
