### ISSUE TITLE
[jsreport-express] Allow disable/enable Profile custom headers

### ISSUE THREAD

**Issue by benben-user** [jsreport/jsreport#1096]
Add configuration option to allow disable/enable Profile custom headers

1. Profile-Id
2. Profile-Location

https://github.com/jsreport/jsreport/blob/5742d6c46befd4a4d55097ee54c825516cb5f063/packages/jsreport-express/lib/main.js#L288

**Comment by pofider** [comment]
Yes, we can do this.

Just a question... Why do you need to disable it?

**Comment by pofider** [comment]
Please comment what is the use-case when this is needed so we can evaluate if it is reasonable.
I am closing this till then. Then we reopen if we decide this should be implemented.
