### ISSUE TITLE
Support multiple closing tags in single row?

### ISSUE THREAD

**Issue by gouldingken** [jsreport/jsreport#1098]
It doesn't currently seem to be possible to have nested report content without introducing blank rows between nested elements. For single line repeating blocks it is permissible to include closing tags (see the `loop-and-nested-loops.xlsx` example). 

I was hoping to be able to achieve the same thing with multiple closures on the same row in order to prevent the need for introducing new blank rows between content, however I am getting the following error when I try this approach:

```
TypeError: Cannot read properties of null (reading 'parentNode')
  at processOpeningTag (lib\generation\preprocess\loop.js:1221:14)
  at module.exports (lib\generation\preprocess\loop.js:569:9)
  at module.exports (lib\generation\preprocess\preprocess.js:7:3)
```
Here is an example using a modified version of the `loop-multiple-rows-and-nested-multiple-loops.xlsx` 

[sas-loop-multiple-rows-and-nested-multiple-loops.xlsx](https://github.com/jsreport/jsreport/files/12719877/sas-loop-multiple-rows-and-nested-multiple-loops.xlsx)

[desired result.xlsx](https://github.com/jsreport/jsreport/files/12719878/desired.result.xlsx)

**Comment by bjrmatos** [comment]
@gouldingken  thanks for the bug report, i will check how to fix this because it should be possible for this kind of output to work.

do you mind sharing the data you are planning to use to get the `desired result.xlsx`? i can create it myself but just asking in case you have the json already available, thanks.

**Comment by bjrmatos** [comment]
@gouldingken nevermind i just noticed that i can use the same data from my tests, thanks for basing your example on a previous test 😁
