### ISSUE TITLE
Rendering loop with header or footer (phantom-pdf)

### ISSUE THREAD

**Issue by gberthalon** [jsreport/jsreport#110]
Hi,
when i create a header or footer in a template with phantom-pdf like :
<div style='text-align:center'>{#pageNum}/{#numPages}</div>
the rendering process create render loop.

Have you got an idea to fix it?

**Comment by pofider** [comment]
Hi,

you mean an endless loop? I am not able to reproduce such a behavior. In this example it seems to work fine: https://playground.jsreport.net/#playground/-JAhcJchre/2.

**Comment by gberthalon** [comment]
Hi,

yes it is an endless loop, the report rendering process loop.

the report have 23 pages.

In my report i have header, script and helpers.
The process rendering is called with : 

jsreportFacade=require("jsreport-client")(jsReportURL);
jsreportFacade.render(
            {
                template:
                {
                    shortid: reportId,
                    dataSources:reportDataSources                    
                }
            },
            function(error, response)
            {
                if (error)
                {
                    self.emit("contentError", error);
                }
                else
                    self.emit("contentAvailable", response);
            });
Let me know

**Comment by pofider** [comment]
And why do you assume it is an endless loop, based on the logs? What is your script actually doing?

Please note that jsreport runs the whole rendering process for the main page content and then also again for the header, but this doesn't mean it is an endless loop. To skip running the script for the header you can do following:

```js
function afterRender(done) {
    //filter out script execution for phantom header
    if (request.options.isChildRequest)
      return done();

    //your script
    done();
}
```

**Comment by gberthalon** [comment]
Hi,

i see in the console rendering messages like  :

--------------------------------

POST /api/jsreports/datas 200 142ms - 201.57kb
express deprecated req.host: Use req.hostname instead node_modules\jsreport\node
_modules\toner-phantom\node_modules\node.extend\lib\extend.js:42:23
2015-09-09T21:35:09.876Z - info: Rendering template {shortid:NkSAUHZn, recipe:ht
ml,engine:jsrender}
POST /api/parameters?refresh=1441834509868 200 15ms - 509b
2015-09-09 21:13:48
2015-09-09 21:33:48
POST /api/jsreports/datas 200 134ms - 201.57kb
2015-09-09T21:35:10.787Z - info: Rendering template {shortid:NkSAUHZn, recipe:ht
ml,engine:jsrender}
2015-09-09 21:13:48
2015-09-09 21:33:48
POST /api/jsreports/datas 200 117ms - 201.57kb
2015-09-09T21:35:11.666Z - info: Rendering template {shortid:NkSAUHZn, recipe:ht
ml,engine:jsrender}
POST /api/parameters?refresh=1441834511891 200 8ms - 509b
2015-09-09 21:13:48
2015-09-09 21:33:48
POST /api/jsreports/datas 200 116ms - 201.57kb
--------------------------------

If you wait 5 minutes, process continue.

My script get a lot of data with webservices call (async request).

The given code in afterRender has no effects.

Thanks

**Comment by pofider** [comment]
I was trying for a long time to simulate this on version 0.7.2 also the latest 0.8.2 and no luck. You probably need to simplify your solution to find the problem. If you send me a zipped jsreport data folder so I can quickly simulate this issue, I will happily look at it.

**Comment by gberthalon** [comment]
The problem was caused by a custom extension, i ve created :
The use of 'if (!request.options.isChildRequest)' fix the problem (thanks Jan @pofider )

function _handleBeforeRender(reporter, request, response) {
   
    if (!request.options.isChildRequest)
    {
//script here
    }
}
