### ISSUE TITLE
Indentation is incorrectly added after linebreaks when rendering using <pre> and handlebars partials

### ISSUE THREAD

**Issue by AndreasPresthammer** [jsreport/jsreport#1101]
JSReport rendering a `<pre>` tag from inside a partial will prepend newlines with indentation. This is only happens when rendering using handlebar partials.

See repro here:
https://playground.jsreport.net/w/anon/fSaXbKQ0

This does _not_ seem to be handlebars issue since the following seem to be working correctly (using handlebars 4.7.8):
https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B%3E%20new_partial%20%7D%7D%5Cn%22%2C%22partials%22%3A%5B%7B%22name%22%3A%22new_partial%22%2C%22content%22%3A%22%3Cpre%3E%7B%7Btext%7D%7D%3C%2Fpre%3E%22%7D%5D%2C%22input%22%3A%22%7B%5Cn%20%20text%3A%20%5C%22foo%5C%5Cnbar%5C%22%5Cn%7D%5Cn%22%2C%22output%22%3A%22%3Cpre%3Efoo%5Cnbar%3C%2Fpre%3E%22%2C%22preparationScript%22%3A%22%22%2C%22handlebarsVersion%22%3A%224.7.8%22%7D

**Comment by pofider** [comment]
This seems like handlebar behavior. The handlebars simply add indentation to every line of the partial output line based on the indentation of the partial call line. 

While this creates indentation
```html
{{#*inline "myPartial"}}
    <pre>a
b
c
</pre>
{{/inline}}  
   {{> myPartial  }}  
```

this doesn't

```html
{{#*inline "myPartial"}}
    <pre>a
b
c
</pre>
{{/inline}}  
{{> myPartial  }}  
```

**Comment by AndreasPresthammer** [comment]
Thanks @pofider !

You're right. Example:

https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B%3E%20new_partial%20%7D%7D%5Cn%5Cn%20%20%7B%7B%3E%20new_partial%20%7D%7D%5Cn%22%2C%22partials%22%3A%5B%7B%22name%22%3A%22new_partial%22%2C%22content%22%3A%22%3Cpre%3E%7B%7Btext%7D%7D%3C%2Fpre%3E%22%7D%5D%2C%22input%22%3A%22%7B%5Cn%20%20text%3A%20%5C%22foo%5C%5Cnbar%5C%22%5Cn%7D%5Cn%22%2C%22output%22%3A%22%3Cpre%3Efoo%5Cnbar%3C%2Fpre%3E%5Cn%20%20%3Cpre%3Efoo%5Cn%20%20bar%3C%2Fpre%3E%22%2C%22preparationScript%22%3A%22%22%2C%22handlebarsVersion%22%3A%224.7.8%22%7D
