### ISSUE TITLE
Azure FS Store error on JS Report v4 - argument for doesBlobExist is not defined

### ISSUE THREAD

**Issue by JustinRickard** [jsreport/jsreport#1104]
Replication steps:

1. Ensure Node v20 is installed (I used 20.9.0)
2. Ensure you have an Azure Storage Container set up
3. Pull [this bug reproduction repository](https://github.com/JustinRickard/jsreportv4-fs-store-bug)
4. Update jsreport.config.json with `fs-store-azure-storage-persistence` details and `authentication.cookieSession.secret`
5. Run the report server (`jsreport start` or `npm start`)
6. Notice the errors `Required argument blob for function doesBlobExist is not defined`

My colleagues and I investigated and found a work-around that appears to allow the report server to work:
[change the customUtils.js](https://github.com/jsreport/jsreport/blob/master/packages/jsreport-fs-store/lib/customUtils.js#L123) file to continue if targetPath is empty.

Dockerfile with this workaround:
```
FROM jsreport/jsreport:4.1.0-full
RUN npm i @jsreport/jsreport-fs-store-azure-storage-persistence handlebars-helpers --save
RUN sed -i '123s/.*/const targetPath = fs.path.join(ptarget, dir.path.replace(psource, ''));if (!targetPath) continue;/' /app/node_modules/@jsreport/jsreport-fs-store/lib/customUtils.js
```

**Comment by pofider** [comment]
Thank you for the problem replication. We are checking on this...

**Comment by pofider** [comment]
This is now fixed in the `jsreport/jsreport-fs-store-azure-storage-persistence@4.0.1`

I apologize for the inconvenience.

**Comment by JustinRickard** [comment]
@pofider  Thank you for fixing this.
