### ISSUE TITLE
docx：Error will be reported when docx contains a directory

### ISSUE THREAD

**Issue by right11112** [jsreport/jsreport#1106]
Report "main" render failed.

Error while executing docx recipe
(because) could not find default style for heading
Error: Could not find default style for heading

**Comment by right11112** [comment]
![image](https://github.com/jsreport/jsreport/assets/45585783/778bfdfc-8a72-4589-9afb-872f4f008e1c)

**Comment by pofider** [comment]
Could you please replicate the problem in the playground?
https://playground.jsreport.net/

**Comment by right11112** [comment]
https://playground.jsreport.net/w/anon/AzJejUHL

**Comment by pofider** [comment]
Thank you. We will check on that and come back to you.

**Comment by xGreylee** [comment]
same question, the report generated failed after i insert the TOC part, plz help my friend  @pofider 
https://playground.jsreport.net/w/xGreylee/m3QTY9oo

**Comment by pofider** [comment]
@right11112 The Word document has some strange invalid TOC. How did you create it? You should use the following tutorial to create a table of contents. Using that will also create TOC default style which is missing in your template. Please try to follow the tutorial and let me know if that helped.
https://support.microsoft.com/en-us/office/insert-a-table-of-contents-882e8564-0edb-435e-84b5-1d8552ccf0c0#:~:text=Put%20your%20cursor%20where%20you,contents%20and%20choosing%20Update%20Field.

If this doesn't help. please also explain what you mean by "when docx contains a directory ".

**Comment by right11112** [comment]
@pofider Maybe  What i used is chinese office,so jsreport cannot recongnize the style of content

**Comment by right11112** [comment]
@xGreylee  你可以试试把office语言改成英语，中文目录好像不能识别。

**Comment by pofider** [comment]
@xGreylee Adding the style to your TOC should help
![image](https://github.com/jsreport/jsreport/assets/2041960/b39f00e5-7092-4e42-8bbd-91ddce8172a4)

**Comment by xGreylee** [comment]
原来word是需要整个系统设置成英语才可以切换语言。。蛋疼啊哈哈，我切换了英语作为系统语言之后，插入TOC没问题了！感谢你兄弟！！> @xGreylee 你可以试试把office语言改成英语，中文目录好像不能识别。

**Comment by xGreylee** [comment]
@right11112 原来word是需要整个系统设置成英语才可以切换语言。。蛋疼啊哈哈，我切换了英语作为系统语言之后，插入TOC没问题了！感谢你兄弟！！

**Comment by xGreylee** [comment]
seems is my default language cause this error, i used Chinese for default language before, one i change to English as the default, the issue is solved, thx my friend @pofider

**Comment by pofider** [comment]
Thank you. I am able to replicate the problem and have submitted a more accurate issue to fix.
https://github.com/jsreport/jsreport/issues/1108
