### ISSUE TITLE
Facing issues while running jsreport in docker container with MongoDB as Template Store.

### ISSUE THREAD

**Issue by saineshwar** [jsreport/jsreport#1107]
**Issue:- Application keep loading it does not show editor.**

I am using docker file in this we have written code for pulling base image of jsreport. along with we are storing templates and other assets into MongoDB.

` "mongodb-store": {
      "uri": "mongodb+srv://test.net/TestDatabase?retryWrites=true&w=majority"
  }`

**Code Written in Docker File.**

`FROM jsreport/jsreport:4.1.0-full

WORKDIR /app

COPY . /app/

EXPOSE 5488

CMD ["node", "server.js"]
`
**jsreport.config.json**

{
  "httpPort": 5488,
  "store": {
    "provider": "mongodb"
  },
  "blobStorage": {
    "provider": "mongodb"
  },
  "logger": {
    "console": {
      "transport": "console",
      "level": "debug"
    },
    "file": {
      "transport": "file",
      "level": "info",
      "filename": "logs/reporter.log"
    },
    "error": {
      "transport": "file",
      "level": "error",
      "filename": "logs/error.log"
    }
  },
  "trustUserCode": true,
  "reportTimeout": 60000,
  "workers": {
    "numberOfWorkers": 2
  },
  "extensions": {
    "sample-template": {
      "createSamples": true
    },
    "mongodb-store": {
      "uri": "mongodb+srv://test.net/TestDatabase?retryWrites=true&w=majority"
  }
  }
}

![image](https://github.com/jsreport/jsreport/assets/8281689/bc0dfcf3-c6d5-466b-a7a5-49b7ffc9ebe3)

**Comment by pofider** [comment]
Have you tried hitting CTRL+F5 or running with a cleared browser cache? It looks strange I see in the browser tab the title `jsreport 2.11.0 prod`.

Does the same happen with the empty db?

What do you have inside the working dir when building the image? Just the config file?

**Comment by saineshwar** [comment]
**Have you tried hitting CTRL+F5 or running with a cleared browser cache? It looks strange I see in the browser tab the title?**
-Yes tried clear cache still same issue.

**Does the same happen with the empty db?**
-Ya it creates new Database in MongoDB and collections also 

**What do you have inside the working dir when building the image? Just the config file?**
-I have shared snapshot of working directory


I am trying Demo where I want to build custom **docker Image** and want to store Templates in **Mongo Database**. 
I have tried what I saw in [docker article](https://jsreport.net/learn/docker)

**Issue I am facing**

- Jsreport is able to create database but it does not load Jsreport Editor 

**Docker file.**
![image](https://github.com/jsreport/jsreport/assets/8281689/0d6e41aa-50aa-4d3d-8729-282f88a9c5c5)



**Working JS Report Project for which building Image**
![image](https://github.com/jsreport/jsreport/assets/8281689/c57b0d82-6576-4b69-acef-b1d12f5b115b)

**Storing Templates in MongoDB for that added Connection String**

`"mongodb-store": {
      "uri": "mongodb+srv://stest:.8tswohr.mongodb.net/TestDatabase?retryWrites=true&w=majority"
  }`

**Database Created in MongoDB by JSReport**
![image](https://github.com/jsreport/jsreport/assets/8281689/6a712868-6f73-49e0-967e-7e0587467efd)

**jsreport.config.json which I am using**

`{
  "httpPort": 5488,
  "store": {
    "provider": "mongodb"
  },

  "blobStorage": {
    "provider": "mongodb"
  },

  "logger": {
    "console": {
      "transport": "console",
      "level": "debug"
    },

    "file": {
      "transport": "file",
      "level": "info",
      "filename": "logs/reporter.log"
    },

    "error": {
      "transport": "file",
      "level": "error",
      "filename": "logs/error.log"
    }
  },

  "trustUserCode": true,

  "reportTimeout": 60000,
  "workers": {
    "numberOfWorkers": 2
  },
  "extensions": {
    "sample-template": {
      "createSamples": true
    },
    "mongodb-store": {
      "uri": "mongodb+srv://stest:.8tswohr.mongodb.net/TestDatabase?retryWrites=true&w=majority"
  }
  }
} `

**Comment by pofider** [comment]
Thanks, what I've tried now...

In a folder run `jsreport init` and let it install jsreport app.
Update `jsreport.config.json` with your config.
Create the `Dockerfile` as you have.
`docker build . -t test`
`docker run -p 5488:5488 test`

The app is running and the studio is properly loaded. In other words, I can't reproduce what you describe so far.
I've noticed you don't have `.dockerignore` file in the root so maybe docker copies all the `node_modules` to your image. That would be wrong.

Would you be able to email me a compressed content of your app folder (without node_modules)? I would check whats happening. Email is here https://github.com/pofider
