### ISSUE TITLE
Directory hierarchy problem on windows : Filepath is too long (>256 caracters)

### ISSUE THREAD

**Issue by gberthalon** [jsreport/jsreport#111]
Hi,

In my project, i can't copy all the files include in Jsreport.
The problem is caused by node_modules hierarchy and filepath > 256 caracters in jsreport dependencies.

In Node projects the problem is known : https://github.com/npm/npm/issues/3697....

Install Npm 3 (https://github.com/felixrieseberg/npm-windows-upgrade) fix the problem with Dedupe and flatten module (https://www.npmjs.com/package/flatten-packages).

I've test these installs with no result.

Perhaps have you got a solution?

**Comment by pofider** [comment]
Hi,

I use `npm shrinkwrap` https://docs.npmjs.com/cli/shrinkwrap
and then `flatten-packages`  https://www.npmjs.com/package/flatten-packages

I should probably add this to the faq or somewhere.

**Comment by pofider** [comment]
This is now in the FAQ
