### ISSUE TITLE
How to generate correct page numbers and TOC in the conditionally appended or script generated templates

### ISSUE THREAD

**Issue by jitendra5792** [jsreport/jsreport#1111]
Please check this workspace:
https://playground.jsreport.net/w/jitendra.shah/hAno7wK8

Forum: https://forum.jsreport.net/topic/2997/how-to-generate-correct-page-numbers-and-table-of-contents-in-the-conditionally-appended-templates

I am appending a landscape page and a portrait page to the main template page.
The landscape page is going to get integrated conditionally. How to generate page numbers correctly and also update the TOC.

**Comment by pofider** [comment]
Please be patient don't duplicate it. We get to it soon.
There are just many customers we need to support and don't have ultimate resources for it.
