### ISSUE TITLE
Issue while Connecting Jsreport with Azure CosmosDB

### ISSUE THREAD

**Issue by saineshwar** [jsreport/jsreport#1112]
Using the connection string provided by Azure CosmosDB
```
"mongodb-store": {
     "uri": "mongodb://a-dev-cosmosdb:dUX2D3y1qB1bBYK5yY@v-dev-cosmosdb.mongo.cosmos.azure.com:1025?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@v-dev-cosmosdb@"
},
```
As recommended in docs using   "store.transactions.enabled" : false,

![image](https://github.com/jsreport/jsreport/assets/8281689/c15eb32b-12bd-44dd-b638-ea6ab9da4afa)

![image](https://github.com/jsreport/jsreport/assets/8281689/d2d345a2-fbb6-43f0-a7a0-7a986858870e)

Is there anything I am doing wrong to Connect to Azure CosmosDB with jsreport.

**Comment by pofider** [comment]
I've answered here
https://forum.jsreport.net/topic/3005/how-to-configure-the-extension-for-azure-cosmos-db-for-mongodb
