### ISSUE TITLE
[Bug]: Docx html with nested ul/li, not rendering/ordered properly

### ISSUE THREAD

**Issue by alwyn974** [jsreport/jsreport#1119]
Hi, I found this bug while trying to make a list from ul/li. Here some screenshot

![image](https://github.com/jsreport/jsreport/assets/47529956/1caba92d-c296-4e0b-8dbe-21558fa529d8)

It should look like this 
![image](https://github.com/jsreport/jsreport/assets/47529956/52878448-a6a7-4e1d-9f73-44c5ac36ecd7)

Here the playground link https://playground.jsreport.net/w/anon/Ss9nTwkk

Jsreport version: 4.2.0-full

**Comment by alwyn974** [comment]
bump? or if anyone can tell me where to find the code that manages ul/li, I might be able to make a PR?

**Comment by bjrmatos** [comment]
Ups, i forgot to add a comment here, i was working on this and it is fixed, we dont have a estimate when it will be released, we are triaging issues and preparing everything for the next release
