### ISSUE TITLE
Reference error when nodejs app also uses handle bars with same version

### ISSUE THREAD

**Issue by claytonwells** [jsreport/jsreport#112]
Hi

My node js app also is using handle bars 3.0.3 and in jsreport, it references a dependency called toner-handlebars which references handlebars version 3.0.3. The problem comes because jsreport seem to direct reference this dependency of a dependency which results in an error 

```
Cannot find module '/var/app/current/node_modules/jsreport/node_modules/toner-handlebars/node_modules/handlebars'
```

my current workaround is to have my app run a different version of handle bars to ensure that handlebars is also downloaded in the toner-handlebars module.

**Comment by pofider** [comment]
I guess this commit should fix it. Thanks for this bug report.
