### ISSUE TITLE
Full profiling fails when using AuthorizationServer account with no jsreport user defined.

### ISSUE THREAD

**Issue by AlexGoris-KasparSolutions** [jsreport/jsreport#1120]
I have JSreport setup with an external authorization server. Since I'm not interested in managing users in JSReport, I have only defined groups, and assigned permissions to those groups. Those groups then get assigned on my authorization server in the generated access token.
It seems this should be supported (and works except for this scenario), from [the docs](https://jsreport.net/learn/authentication#authentication-using-an-authorization-server):
> jsreport needs to know how to associate the users from your authorization server to users/groups in jsreport, .... to do this you will have to do **any** of the following:
> - associate the jsreport username ....
> - associate the jsreport group name of an existing jsreport group with a claim....

So to clarify, I am doing the 2nd option.

This works mostly, except when enabling full profiling. When full profiling is enabled, in the JSreport logs we can see the following exception being thrown:
```
2024-02-08T08:48:15.220Z - warn: Failed persist profile Cannot read properties of undefined (reading 'toString') stack=TypeError: Cannot read properties of undefined (reading 'toString')
    at AsyncFunction.<anonymous> (/app/node_modules/@jsreport/jsreport-authorization/lib/modificationListeners.js:33:90)
    at ListenerCollection.fire (/app/node_modules/@jsreport/jsreport-core/lib/shared/listenerCollection.js:157:32)
    at async Object.insert (/app/node_modules/@jsreport/jsreport-core/lib/main/store/collection.js:141:5)
    at async /app/node_modules/@jsreport/jsreport-core/lib/main/profiler.js:184:7
    at async /app/node_modules/@jsreport/jsreport-core/lib/main/profiler.js:63:11
```

As the stack trace shows this is the culprit:
https://github.com/jsreport/jsreport/blob/9df8658724f2ec5aa097a755ebf0265cb5b292b8/packages/jsreport-authorization/lib/modificationListeners.js#L33C13-L34C1
```javascript
doc.readPermissions = mergeArrays(doc.readPermissions, [req.context.user._id.toString()])
```

I am assuming, that because I only do group name mapping in my access tokens, the whole `req.context.user` object is null/undefined.
And it looks like the same exception would be thrown on line 34, 36 and 37 as well.

**Comment by bjrmatos** [comment]
thanks for the details, we will take a look and fix this

**Comment by bjrmatos** [comment]
hi @AlexGoris-KasparSolutions are you using latest jsreport (4.2.0)? i've tried to replicate the issue creating a group, and also mapping just the group name (with a `group` field), after it i use the "Run (full profile)" button from studio

![Screenshot 2024-02-21 at 1  28 29@2x](https://github.com/jsreport/jsreport/assets/4262050/9b2643cd-64ff-4dc1-bdaf-135ded5f89d8)

however i can not replicate this, anything else you are doing? how the template you are using to render looks like?

**Comment by bjrmatos** [comment]
the strange thing is that the line you get in error points to a path in which it should only enter when the user is not a group

![Screenshot 2024-02-21 at 1  43 57@2x](https://github.com/jsreport/jsreport/assets/4262050/03166efe-a21f-46f8-a928-e6e3b75b0570)

>I am assuming, that because I only do group name mapping in my access tokens, the whole req.context.user object is null/undefined.

we have code that normalizes this, so no matter if you login as group or normal user the req.context.user should not be null, this is also validated because in the error you get to a path in which can only be possible if the `req.context.user` contains value, however it seems that because something else the thing that is null is `req.context.user._id` but i don't get to replicate this

**Comment by bjrmatos** [comment]
ah ok, i missed the part that you were actually sending a token with http request,  i can replicate the issue now, will fix
