### ISSUE TITLE
HTML embedded in docx: <ol> not working

### ISSUE THREAD

**Issue by ThiboHoffman** [jsreport/jsreport#1125]
The lists made in my rich text editor aren't shown in the docx using doccHtml content.

Data:
`{priceDescription: <ol><li><p>een</p></li><li><p>twee</p></li><li><p>dri</p></li><li><p>vier</p></li><li><p>vijf</p></li></ol>}`

JSReport template:
<img width="414" alt="Screenshot 2024-03-21 at 11 43 31" src="https://github.com/jsreport/jsreport/assets/47555318/54510b08-eacc-4960-8f0c-fbf183e0cd7c">

Output docx:
<img width="340" alt="Screenshot 2024-03-21 at 11 29 24" src="https://github.com/jsreport/jsreport/assets/47555318/62b947b1-3b62-411f-86aa-c4095d36d5a3">

**Comment by bjrmatos** [comment]
thanks, we will check

**Comment by ThiboHoffman** [comment]
Hello,

I tested it again and nothing changed. Any advice?

Thanks

**Comment by bjrmatos** [comment]
is the same case not working? i've tested and it works with jsreport 4.3.1

![Screenshot 2024-04-02 at 11  40 56@2x](https://github.com/jsreport/jsreport/assets/4262050/f456a581-71b1-4716-bcdd-8244e5e725ac)

```json
{
    "priceDescription": "<ol><li><p>een</p></li><li><p>twee</p></li><li><p>dri</p></li><li><p>vier</p></li><li><p>vijf</p></li></ol>"
}
```

**Comment by ThiboHoffman** [comment]
I use jsreport studio, i see it uses an old version of jsreport?

<img width="196" alt="Screenshot 2024-04-08 at 13 02 57" src="https://github.com/jsreport/jsreport/assets/47555318/e0680830-9306-4dbd-bcc6-452f1eb4c231">

**Comment by ThiboHoffman** [comment]
I'm using jsReport Studio which uses 3.13.0. Any idea on when it might get updated? @bjrmatos 

Thanks

**Comment by pofider** [comment]
You mean jsreportonline SaaS right? We will try to schedule when we update, we were waiting till things stabilized. Likely in a month.

**Comment by ThiboHoffman** [comment]
Okay, thanks!
