### ISSUE TITLE
Failed to launch the browser process!

### ISSUE THREAD

**Issue by imhofdaniel** [jsreport/jsreport#1126]
We are running jsreport as a single executable. With version 4.3.0 and 4.3.1 we get the following error:
```
Report "invoice-main" render failed.

Failed to launch the browser process! undefined


TROUBLESHOOTING: https://pptr.dev/troubleshooting

Error: Failed to launch the browser process! undefined


TROUBLESHOOTING: https://pptr.dev/troubleshooting

  at ChildProcess.onClose (C:\snapshot\jsreport\node_modules\@puppeteer\browsers\lib\cjs\launch.js:267:24)
  at ChildProcess.emit (node:events:525:35)
  at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by pofider** [comment]
Thanks for reporting the issue. I've fixed it here https://github.com/jsreport/jsreport/commit/f4396579d26ba3fc329f820bcf2ffc811f9a9baa 
and you can already download the updated windows binary here 
https://github.com/jsreport/jsreport/releases/tag/4.3.1
