### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by thiagobutignon** [jsreport/jsreport#1127]
I already set the `<body aria-hidden="true"` but some of my repports are really big. I also removed all the children elements on the files, I just have the header with footer and body with my dynamic content. And in the end of day, still taking 1 minute to generated some reports. 

I am using the latest version. How I can improve more the performance of some pdfs?

**Comment by pofider** [comment]
Have you checked also the image size problem?
https://jsreport.net/learn/chrome-pdf#images-increasing-pdf-size

I believe the chrome-pdf rendering is the bottleneck, right? You can see this in the studio profile tab...
In this case, I would recommend trying to isolate what part of your HTML is the most time consuming to print.
Is it a long table? Perhaps you can simplify some CSS. Or is it a chart? Maybe you need to disable the library animations...
The chrome is a black box for us as well so we can't troubleshoot its performance deeper. The only approach is trying to find the bottleneck in the HTML and try to rewrite it.

**Comment by pofider** [comment]
I close this as there is nothing we can do further on our end.
