### ISSUE TITLE
Post / Patch Schedule : nextRun can't be change

### ISSUE THREAD

**Issue by gberthalon** [jsreport/jsreport#113]
Hi,

i want to change the nextRun of a schedule with API with no results.

Any help?

thks ;)

**Comment by pofider** [comment]
Hi,

the `nextRun` is just a read only calculated property.

You should update the `cron` property to set the scheduling pattern.

**Comment by gberthalon** [comment]
Hi,

actually i want to execute a execute the task every week but i set the first execution in five minutes.
I've no way to do this feature.
I have searched in lib/scheduling to do that without results,

any idea?

**Comment by pofider** [comment]
The CRON pattern is:

1. Seconds: 0-59
2. Minutes: 0-59
3. Hours: 0-23
4. Day of Month: 1-31
5. Months: 0-11
6. Day of Week: 0-6

So if you set this to `cron` it should start in 5 minutes and run every week
```
(now.seconds) (now.minutes+5) (now.hours) * * (now.dayOfWeek)
```

**Comment by gberthalon** [comment]
Hi Jan,

I have a problem with a afterRender in 2 script,
The function is never executed.
Have you an idea to fix this problem?

This is an extract of my script :
var r =require('request');
var moment = require('moment');
moment().format();
var scriptHelper = require('./../../../../../controllers/JSReportScriptHelper');
var values;
var uidDatas;

function afterRender(done)
{
  //filter out script execution for phantom header
    if (request.options.isChildRequest)
      return done();

  scriptHelper.log("ok");
  if(request.options.scheduling != undefined)
  {
    scriptHelper.log(request.options.scheduling.schedule.customOptions);
    if(request.options.scheduling.schedule != undefined)
    {
        var toPrint=request.options.scheduling.schedule.customOptions.toPrint;
        if(toPrint==true)
        {
          scriptHelper.printContent(response.content);
            done(true);

        }
    }
  }
  else
  {
    scriptHelper.log("nok");
      done(true);

  }
}
function beforeRender(done)
{

  scriptHelper.log("neok");
        var dataSources;
        if(request.options.scheduling === undefined)
            dataSources=request.template.dataSources;
        else
            dataSources=request.options.scheduling.schedule.customOptions.dataSources;
        // on récupère les datasources
        values={};
        uidDatas={};
…..

Bien cordialement / Best regards / Pozdrawiam

[cid:72D8D0C9-6E0B-48DD-B00E-387DD8C3D94D]


Guilhem Berthalon

Directeur technique


06.85.96.29.69

gberthalon@bertek.fr<mailto:gberthalon@bertek.fr>


Immeuble F&J

Parc de l’aéroport

145 rue Jeremy Bentham

34470 PEROLS

http://www.bertek.fr<http://www.bertek.fr/>


Warsaw Trade Tower

Chłodna 51

00-867 Warszawa

POLSKA

http://www.bertek.pl<http://www.bertek>
