### ISSUE TITLE
Node 21 Support

### ISSUE THREAD

**Issue by aaroncrawford** [jsreport/jsreport#1130]
We're evaluating JSReport now, and it appears node 21 isn't supported through your dependency of pdf.js.  See [this issue.](https://github.com/mozilla/pdf.js/issues/15728#issuecomment-2071150068).

As soon as you add a header-footer, as I guess pdf-utils gets called, then you'll get an ambiguous "includes" error because it's looking for the global navigator object, which used to be undefined in node.  But in 21 they added it as an empty object, which throws that type error.  Are you all aware of any workaround or do we have to use node 20?

**Comment by pofider** [comment]
Thank you for tracking the error. So far I don't know the workaround.

Please stick with node 20, because jsreport is currently tested with node 18 and 20. 
We will look into testing it with the node 22 soon.

**Comment by aaroncrawford** [comment]
Great, thanks.  It was working great on 21 until I added the header/footer pdf util.  I'm guessing it'll rear it's head in 22 as well as I doubt Node gets rid of that global navigator object, just as a heads up.

**Comment by pofider** [comment]
It seems it works fine with node 22 and fails only in the 21. Could you please double check?
If this is the case we gonna ignore missing support for 21 and close this.

**Comment by aaroncrawford** [comment]
Seems to work with 22 on my side too.  So 20 and 22 work, but not 21.

**Comment by pofider** [comment]
Thank you.
I close this because the 21 was just a temporary version so we don't need to invest time there.
