### ISSUE TITLE
Allow phantom-server strategy when running on iisnode

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#114]
Just open this to keep track of pofider/phantom-workers#6

**Comment by bjrmatos** [comment]
the only thing left is to update phantom-html-to-pdf y html-to-xlsx dependencies

**Comment by pofider** [comment]
This should work no in 0.9.1

**Comment by bjrmatos** [comment]
i will test it in production in the coming weeks :)

**Comment by pofider** [comment]
This should be already working.
