### ISSUE TITLE
Phantom pdf recipe printing trigger

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#116]
Users should  be able to grammatically specify when pdf printing starts. Right now users can just set the static print delay time.

**Comment by bjrmatos** [comment]
later, i will elaborate (with an example) how i plan to do this

**Comment by bjrmatos** [comment]
discussion about implementation details in pofider/phantom-html-to-pdf#14, pofider/phantom-html-to-pdf#15

**Comment by pofider** [comment]
Done, thanks to @bjrmatos . Published in 0.9.1. [Documentation](http://jsreport.net/learn/phantom-pdf) update on the way.

**Comment by bjrmatos** [comment]
I just want to add a checkbox in jsreport studio to enable/disable this behaviour.. I will submit a PR later

**Comment by bjrmatos** [comment]
oh sorry, i just noticed that you implemented the checkbox :D
