### ISSUE TITLE
JS Report Taking Excessive Time with Multiple Pages

### ISSUE THREAD

**Issue by tgs-vaibhav-tt0055** [jsreport/jsreport#1164]
We are experiencing significant delays when generating reports with multiple pages in JS Report. The output takes much longer than expected.

You can review the issue using this link: 
[https://playground.jsreport.net/w/Bhoomi2105/7qVlHDy~.](https://playground.jsreport.net/w/Bhoomi2105/7qVlHDy~)

Ref. Video Link:
https://drive.google.com/file/d/1ON5LhLry76a6gg461j5s9H8xS-thR_LN/view?usp=sharing

Please provide guidance or solutions to improve the performance.

**Comment by pofider** [comment]
duplicate
https://forum.jsreport.net/topic/3280/js-report-taking-excessive-time-with-multiple-pages
