### ISSUE TITLE
@jsreport/nodejs-client uses vulnerable Axios version

### ISSUE THREAD

**Issue by progys** [jsreport/jsreport#1169]
Hello,
would it be possible to update Axios version  to 1.7.4 used by  `@jsreport/nodejs-client`. Currently this client uses Axios version which has vulnerability.

![image](https://github.com/user-attachments/assets/a57aeb25-9471-432a-90f9-9992b47cf7b1)

Thanks!

**Comment by pofider** [comment]
Yes, we update it in the upcoming release.

**Comment by progys** [comment]
thank you.

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by pofider** [comment]
The `@jsreport/nodejs-client@4.7.0` is now released.
