### ISSUE TITLE
docxhtml lists bug

### ISSUE THREAD

**Issue by DaniloOliveira28** [jsreport/jsreport#1173]
Hi,

We use jsreport to generate customized reports to our clients and we found three errors related on ordered lists `<ol>`

# 1) First Problem numeration

The ordered list is not resetting across different components. The next component continues numbering from the previous one.

**Template**
![Screenshot from 2024-09-19 11-35-43](https://github.com/user-attachments/assets/00de4dbb-efdc-45df-85a1-5e9a597e1ccd)
Template Text

```
Comments

{{#each comments}}
{{docxHtml content=html}}
________________________________________
{{/each}}


```

**Data**

```JSON
{
  "comments": [
    {
      "html": "<div><ol><li><p>Ok</p></li></ol></div>"
    },
    {
      "html": "<div><ol><li>Step one</li><li>Steo two</li></ol></div>"
    }
  ]
}
```

**Results**
The second list start on 2, it should start on 1.
![Screenshot from 2024-09-19 11-45-06](https://github.com/user-attachments/assets/039382ff-18f1-491c-a798-ca2cd3c5a957)

# 2) Second Problem, `<ol>` does not support start attribute

reference: [ol start attribute](https://www.w3schools.com/tags/att_ol_start.asp)

**Template**
![Screenshot from 2024-09-19 11-35-43](https://github.com/user-attachments/assets/00de4dbb-efdc-45df-85a1-5e9a597e1ccd)
Template Text

```
Comments

{{#each comments}}
{{docxHtml content=html}}
________________________________________
{{/each}}


```

**Data**

```JSON
{
  "comments": [
    {
      "html": "<div><ol><li><p>Ok</p></li></ol></div>"
    },
    {
      "html": "<div><ol start='13'><li>Step one</li><li>Steo two</li></ol></div>"
    }
  ]
}

```

**Results**
The second list start on 2, not on 13.
![Screenshot from 2024-09-19 11-45-06](https://github.com/user-attachments/assets/039382ff-18f1-491c-a798-ca2cd3c5a957)

# 3) third problem, using ol in our data, generates invalid file

Both tests above generete an invalid document

**Template**
![Screenshot from 2024-09-19 11-35-43](https://github.com/user-attachments/assets/00de4dbb-efdc-45df-85a1-5e9a597e1ccd)

```
Comments

{{#each comments}}
{{docxHtml content=html}}
________________________________________
{{/each}}


```

**Data**

```JSON
{
  "comments": [
    {
      "html": "<div><ol><li><p>Ok</p></li></ol></div>"
    },
    {
      "html": "<div><ol><li>Step one</li><li>Steo two</li></ol></div>"
    }
  ]
}
```

**Result**
![Screenshot from 2024-09-19 11-40-16](https://github.com/user-attachments/assets/dd807f91-ae53-483f-91b6-a1c14c05b6c6)

The image below is in portuguese, but it says that the file is invalid

![Screenshot from 2024-09-19 11-48-37](https://github.com/user-attachments/assets/bd014d17-a130-4088-a789-c05c903e45ef)

Environment
JSREPORT 4.6
Engine: handlebars
recipe: docx

**Comment by bjrmatos** [comment]
we are going to take a look at this, thanks for the bug report

**Comment by pofider** [comment]
We will check on that next week most likely. I apologize for the delay. There are many open requests to prioritize.

**Comment by bjrmatos** [comment]
@DaniloOliveira28 

what version of jsreport are you using? i have tested your three problems and 2 of them work okay on latest version of jsreport (4.6.0)

## 1) First Problem numeration (WORKS OK ON JSREPORT 4.6.0)

![Screenshot 2024-10-04 at 1  59 01@2x](https://github.com/user-attachments/assets/4ff53942-cba0-4441-bbf7-eab02de2d062)

## 2) Second Problem, `<ol>` does not support start attribute (I'VE ADDED SUPPORT FOR THIS ON)

![Screenshot 2024-10-04 at 2  01 00@2x](https://github.com/user-attachments/assets/b661bb14-d6b9-4ff9-b8b9-22ba99f62c43)

## 3) third problem, using ol in our data, generates invalid file (WORKS OK ON JSREPORT 4.6.0)

![Screenshot 2024-10-04 at 2  02 16@2x](https://github.com/user-attachments/assets/c3e676ed-5243-4483-82eb-02e6f82815d3)

please verify problem 1 and 3 on latest version, and for the problem 2 just wait for next release (likely done on next week)

**Comment by bjrmatos** [comment]
hmm using our `4.6.0-full` image, i am getting the correct results for problem 1 and 3.

i started docker with `docker run --platform=linux/arm64 -p 5488:5488 -e "chrome_launchOptions_executablePath=/usr/bin/chromium-browser" jsreport/jsreport:4.6.0-full` and imported these entities [export.zip](https://github.com/user-attachments/files/17282491/export.zip). each data file in the export file contains the data needed for each problem.

what about trying outside docker? from normal npm install does still fail for you? maybe you can try running the default full image just like i did and tell us what are your results, theoretically, nothing should change between using a custom docker file but who knows.

**Comment by effivitypk-cyber** [comment]
Hi, this problem is reproducible in jsreport playgroud.

playground.jsreport.net/w/anon/ozsGk5zU

Find the above link to repro this.

**Comment by bjrmatos** [comment]
@effivitypk-cyber thanks for the repro, i can confirm that this bug is solved already, you can see it in the output of the latest jsreport (4.12.0).

<img width="2628" height="1436" alt="Image" src="https://github.com/user-attachments/assets/8ee01432-a676-48b0-bab2-b0d1fa646cd7" />
