### ISSUE TITLE
npm release @jsreport/jsreport-core 4.4.1 - missing files when bundling with esbuild

### ISSUE THREAD

**Issue by EverardB** [jsreport/jsreport#1175]
Code:
const jsreport = require("@jsreport/jsreport-core")()

Problem:
It complains about these missing files when bundling with esbuild
'./test/store/common.js'
'./test/blobStorage/common.js'

My fix:
The 'test' folder/files are missing in the npm package so commenting 'module.exports.tests' in 'node_modules/@jsreport/jsreport-core/index.js' is needed to remove the error

Is there an alternate fix that can be applied?

**Comment by pofider** [comment]
I've tried it in the following minimal repo
https://github.com/pofider/jsreportesbuild

Running these commands seems to work
```
npm i
.\node_modules\.bin\esbuild index.js --bundle --platform=node --outfile=out.js
node out.js
```

Maybe you can modify the repo that replicates your problem?

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by pofider** [comment]
I am closing because I don't have any comment back. But please don't hesitate to add comments, I still watch this.

**Comment by EverardB** [comment]
@pofider I just saw your comments/suggestion. I will try to see if I can find the difference between your example and my implementation in the next days...

Of note, I can not use '--platform=node' on my esbuild command as it causes other negative side-effects.

**Comment by EverardB** [comment]
@pofider Alas, still the same error in both the 4.4.1 and 4.5.0 npm packages

The 'test' folder/files are missing in the npm package so commenting 'module.exports.tests' in 'node_modules/@jsreport/jsreport-core/index.js' is needed to remove the error

```
23:00:53 js.1          | ✘ [ERROR] Could not resolve "./test/store/common.js"
23:00:53 js.1          | 
23:00:53 js.1          |     node_modules/@jsreport/jsreport-core/index.js:26:31:
23:00:53 js.1          |       26 │   documentStore: () => require('./test/store/common.js'),
23:00:53 js.1          |          ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~
23:00:53 js.1          | 
23:00:53 js.1          | ✘ [ERROR] Could not resolve "./test/blobStorage/common.js"
23:00:53 js.1          | 
23:00:53 js.1          |     node_modules/@jsreport/jsreport-core/index.js:27:29:
23:00:53 js.1          |       27 │   blobStorage: () => require('./test/blobStorage/common.js'),
23:00:53 js.1          |          ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
23:00:53 js.1          | 
23:00:53 js.1          | ✘ [ERROR] Could not resolve "./test/extensions/validExtensions/listeners/jsreport.dontdiscover.config"
23:00:53 js.1          | 
23:00:53 js.1          |     node_modules/@jsreport/jsreport-core/index.js:28:27:
23:00:53 js.1          |       28 │ ...> require('./test/extensions/validExtensions/listeners/jsreport...
23:00:53 js.1          |          ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by pofider** [comment]
How about [my repo when I tried to replicate it](https://github.com/jsreport/jsreport/issues/1175#issuecomment-2390943934)? Does that work for you?

What is different?

**Comment by EverardB** [comment]
The difference is that we use ruby-on-rails 7.x with @hotwired/stimulus.
If we use --platform=node with esbuild, then stimulus fails during runtime (with or without @jsreport).

The main point is that the content of the ./test folder which is referenced in @jsreport/jsreport-core/index.js is missing from the npm packages, so it should probably not be excluded during the npm packaging process.

**Comment by EverardB** [comment]
I missed including the esbuild command:
esbuild app/javascript/*.* --bundle --sourcemap --format=esm --outdir=app/assets/builds --public-path=/assets

**Comment by EverardB** [comment]
> How about [my repo when I tried to replicate it](https://github.com/jsreport/jsreport/issues/1175#issuecomment-2390943934)? Does that work for you?
> 
> What is different?

@pofider 
We found the 'difference'... We use yarn as the package manager and the .yarnclean file had 'test' listed as one of the folders to clean. The problem described does not actually exist.

Thanks for your time looking into this.
