### ISSUE TITLE
Vulnerability in body-parser, used by jsreport-express

### ISSUE THREAD

**Issue by lobax** [jsreport/jsreport#1177]
There is a high severity vulnerability in body-parser, which is used by jsreport-express. 

Vulnerability: 
https://security.snyk.io/vuln/SNYK-JS-BODYPARSER-7926860 

Package referance: 
https://github.com/jsreport/jsreport/blob/1464e6f330ffe4646bcf1bb170355d754025f025/packages/jsreport-express/package.json#L30

This can be remediated by updating to 1.20.3

**Comment by pofider** [comment]
Thank you for the notice. We will update the body-parse dep with the next jsreport release.

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by pofider** [comment]
Thank you for the notice. 
We update the vulnerable dependencies during our release process. 
This has happened now, the jsreport 4.7.0 is live with updated deps.
