### ISSUE TITLE
How to insert barcode in docx using helper?

### ISSUE THREAD

**Issue by drik** [jsreport/jsreport#1194]
I have a docx template and would like to insert barcode inside it (qrCode)
Her is what I tried, but not working. Please, can someone telle how to achieve this.
Screentip :
{{docxImage src=barcodeHerper "qrcode" data.invoiceNumber}}

helper function :

```
const bwipjs = require('bwip-js')

function barcodeHelper(barcodeType, text) {
return bwipjs.toBuffer({
bcid: barcodeType,
text: text
}).then(p => 'data:image/png;base64,' + p.toString('base64'))
}
```

**Comment by pofider** [comment]
[Answered on forum](https://forum.jsreport.net/topic/3374/how-to-insert-barcode-in-docx-using-helper)
