### ISSUE TITLE
SQL drivers

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#120]
It should be possible to store report templates and other metadata inside sql database. It is still more common and very requested in the enterprise.

**Comment by pofider** [comment]
The implementation consists of 3 steps each including a single standalone repository 
 
**odata-to-sql**
- transforming odata edm model to sql DDL statements, just what need for jsreport like create tables, no foreign keys or constraints, only complex types
- transforming odata queries into sql statements
- use library https://github.com/goodybag/mongo-sql
- MIT

**simple-odata-server-mssql**
- sql server adapter for https://github.com/pofider/node-simple-odata-server
- use odata-to-sql and https://github.com/patriksimek/node-mssql
- MIT

**jsreport-mssql-store**
- use previou package to implement final support for mssql in jsreport
- reuse support for creating schema and CRUD from simple-odata-server-mssql
- similar to https://github.com/jsreport/jsreport-mongodb-store
- no licence, will be used for future jsreport enterprise

**Comment by pofider** [comment]
This enhancement is ready for development. There will be a comment here when someone starts with actual implementation.

**Comment by bjrmatos** [comment]
i don't have experience with odata, but will dive into it in order to make suggestions/improvements :)

**Comment by pofider** [comment]
I have started to implement this and already have significant part done. It looks this will be released very soon.

**Comment by pofider** [comment]
We support now mssql and postgres
https://github.com/jsreport/jsreport-postgres-store
https://github.com/jsreport/jsreport-mssql-store
