### ISSUE TITLE
Script report : AfterRender not fire

### ISSUE THREAD

**Issue by gberthalon** [jsreport/jsreport#123]
I have a problem with a afterRender in 2 script,
The function is never executed.
It work with the jsreport web client but not with the my big script report...
Have you an idea to fix this problem?

This is an extract of my script :
```js
var r =require('request');
var moment = require('moment');
moment().format();
var scriptHelper = require('./../../../../../controllers/JSReportScriptHelper');
var values;
var uidDatas;

function afterRender(done) 
{
  //filter out script execution for phantom header
    if (request.options.isChildRequest)
      return done();
    
  scriptHelper.log("ok");
  if(request.options.scheduling != undefined)
  {
    scriptHelper.log(request.options.scheduling.schedule.customOptions);
    if(request.options.scheduling.schedule != undefined)
    {
        var toPrint=request.options.scheduling.schedule.customOptions.toPrint;
        if(toPrint==true)
        {
          scriptHelper.printContent(response.content);
            done(true);

        }
    }
  }
  else
  {
    scriptHelper.log("nok");
      done(true);

  }
}
function beforeRender(done)
{

  scriptHelper.log("neok");
        var dataSources;
        if(request.options.scheduling === undefined)
            dataSources=request.template.dataSources;
        else
            dataSources=request.options.scheduling.schedule.customOptions.dataSources;
        // on récupère les datasources
        values={};
        uidDatas={};
```

**Comment by pofider** [comment]
I am currently at the vacation with limited possibilities to check this. I will take a deeper look at it on Monday.

**Comment by gberthalon** [comment]
Hi Jan,

No soucy,

i’ve found the answer…
The problem was my code…

Bien cordialement / Best regards / Pozdrawiam

[cid:D0FAC7E7-25E8-4210-8A0A-84DD16228543]


Guilhem Berthalon

Directeur technique


06.85.96.29.69

gberthalon@bertek.fr<mailto:gberthalon@bertek.fr>


Immeuble F&J

Parc de l’aéroport

145 rue Jeremy Bentham

34470 PEROLS

http://www.bertek.fr<http://www.bertek.fr/>


Warsaw Trade Tower

Chłodna 51

00-867 Warszawa

POLSKA

http://www.bertek.pl<http://www.bertek>
