### ISSUE TITLE
npm Install jsreport error

### ISSUE THREAD

**Issue by nkesar** [jsreport/jsreport#124]
I'm trying to install jsreport using npm in command prompt and it always throws an error. 
Please see the error attached.
![jsreportinstallerror](https://cloud.githubusercontent.com/assets/10842796/10234131/7b5af85e-6847-11e5-9ac8-b422df959f7f.jpg)

**Comment by bjrmatos** [comment]
seems like a problem with your network.. i just installed jsreport and all works fine!

![image](https://cloud.githubusercontent.com/assets/4262050/10234287/277de608-6859-11e5-9756-c5654bb7b390.png)

![image](https://cloud.githubusercontent.com/assets/4262050/10234303/3b8cc9e8-6859-11e5-8203-70db53753fa2.png)
