### ISSUE TITLE
Pdf content is blank when using jsreport online rest api in GWT (probably some sort of encoding issue)

### ISSUE THREAD

**Issue by gdavalos** [jsreport/jsreport#127]
This is likely related to [this issue](https://github.com/jsreport/jsreport/issues/79)

When I try viewing the generated reports using the urls provided by jsreport online everything works just fine, but when I try to use a REST client the encoding just randomly changes to "latin-1".

I can understand if it doesn't work with chrome's advanced rest client (like how you mentioned in the issue I quoted), but I use [GWT](http://www.gwtproject.org/) for my web apps and [RestyGWT](https://resty-gwt.github.io/index.html) to access REST APIs and I could make the html reports work but I get this problem with the phantom-pdf recipe.

I think the problem is encoding-related and I tried to change the headers to no avail, do you have any ideas of what I could try to make this work?

**Comment by pofider** [comment]
I am not very familiar with GWT so it is hard to tell what could be the problem. 

However you may try to do a simple form submit into _blank target and let the browser to display the pdf. This should work without any further parsing or library in use.

**Comment by gdavalos** [comment]
The thing is that we don't want our users to have a login access to our jsreport online account and, since you can't send headers in form submits, a form doesn't work for our case.

GWT basically just compiles Java into javascript and RestyGWT helps make REST requests, as I mentioned before, so far, we can actually use RestyGWT to make requests to the server and get html reports without a hitch, but when we try to use the Phantom-pdf recipe, it seems the encoding is changed and they don't display properly,

What I want to know is if we need to use some specific headers for the request (other than the Authorization header) to work with the API, we've tried setting the various Accept headers but that hasn't helped.

**Comment by pofider** [comment]
No, just authorization and content type is enough.

Here is a discussion about requesting jsreport form the browser
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jsreport/2f9ZX8IYteA/MMayROOYCAAJ

Btw If you use GWT to compile java to javascript which runs on the client, you anyway expose your credentials, or not?
It looks to me you should rather "proxy" requests through your server. I mean to do a post to your server which adds credentials and then sends request to jsreport online.
