### ISSUE TITLE
load js libraries locally

### ISSUE THREAD

**Issue by Siafu** [jsreport/jsreport#131]
I would like to load my external JavaScript libraries locally, what's the best way to accomplish this ? I have been using CDNS.

**Comment by pofider** [comment]
One option is to add your script as a [child template](http://jsreport.net/learn/child-templates).
Another option is to copy your js files to `jsreport\extension\express\public\` and then reference it as `<jsreport url like localhost>/yourscript.js`

**Comment by bjrmatos** [comment]
mmm i think we can do it better, since it is a common use case we should support an easy way to do this :)

@Siafu any ideas?

maybe a `staticResources` configuration would be enough, if it is present then jsreport would load any resources from there (css/js, etc).

if someone reference a resource like this: `<script src="/script.js"></script>` (or maybe `<script src="script.js"></script>` jsreport would search for it in `<staticResources path>/script.js`.

this should be implemented in pofider/phantom-html-to-pdf

**Comment by pofider** [comment]
Yes, it is a common use case, lets talk about it.

@bjrmatos solution will work for phantom-pdf recipe, but I'm afraid there is the same requirement for html, wkhtmltopdf and other recipes. How to do this globally just once.. ?

How about exposing a configurable directory through http and let the resource to be linked like 
`<script src="{{:$staticResources}}/script.js"></script>`. The `$staticResources` would be input data property provided to templating engines by jsreport and contained the url with the user resources. 

I'm still thinking about it... I personally wrap scripts in child templates. I understand it is not obvious solution (maybe it just need to be documented?) and has an overhead, but on the other hand you have everything at once place and it works with jsreportonline.

**Comment by bjrmatos** [comment]
> @bjrmatos solution will work for phantom-pdf recipe, but I'm afraid there is the same requirement for html, wkhtmltopdf and other recipes. How to do this globally just once.. ?

sometimes i forget that there is more to support than just phantomjs

> How about exposing a configurable directory through http and let the resource to be linked like 
> <script src="{{:$staticResources}}/script.js"></script>. The $staticResources would be input data property provided to templating engines by jsreport and contained the url with the user resources.

this is the global solution, sounds great for me :)



> I'm still thinking about it... I personally wrap scripts in child templates. I understand it is not obvious solution (maybe it just need to be documented?) and has an overhead, but on the other hand you have everything at once place and it works with jsreportonline.

you're right, it works with child templates but there are other scenarios where that solution wouldn't be so cool (example: the developer wants to use stylus, sass or postcss to develop css or babel for js, it wants to compile those files and output the final result to a custom directory, like `build`, so the developer will want to configure `staticResources` to point to the `build` path) .. is just about providing more options to the users and cover all posible use cases

**Comment by pofider** [comment]
Ok. Looks like we have nothing better...

I will publish a prototype of such an extension and we can further discuss it directly.

**Comment by pofider** [comment]
Here is the extension with previously described functionalities.

[jsreport-static-resources](https://github.com/jsreport/jsreport-static-resources)

**Comment by bjrmatos** [comment]
i'm happy with the solution (the extensibility of jsreport is very powerful) :)

@Siafu can you try jsreport-static-resources and provide some feedback?

i think this feature is done! feel free to keep comment

**Comment by Siafu** [comment]
Thanks guys, I'll try it out sometime this week.

**Comment by lucasmoglia** [comment]
Hi! I'm trying to do the same in a personal project but i still have a problem. Is a command line application without express or http extensions...

My jsreport configuration:

var jsreport = require('jsreport-core')(
		{
			tasks: { strategy: 'in-process' },
			'static-resources': {directory: path.join(__dirname, '../../', 'js')},
			autoTempCleanup: true
		});

I have created a dir called 'js' at the top of my project  and then in my html:
<script type="text/javascript" src="{{$staticResources}}/jquery.flot.min.js"></script>

but i get this message in logs:
Error: static-resources depends on express extension and requires http server to run.

Am i doing somthing wrong?

**Comment by pofider** [comment]
The recommended approach is to use assets extension which is part of the default installation now.
http://jsreport.net/learn/assets
