### ISSUE TITLE
afterRenderListeners is call twice

### ISSUE THREAD

**Issue by tatatananana** [jsreport/jsreport#135]
I want to write an extension, but for some reason my after render listener is called twice each report generated.

here my code:

main.js:

module.exports = function (reporter, definition) {
    reporter.afterRenderListeners.add("test",function(req, res){
      console.log("test");
  });
};

jsreport.config.js:

﻿module.exports = {
  "name": "test",
  "main": "main.js"
}

WHY?

**Comment by pofider** [comment]
Does the report contain a child template or a header or footer if the output is pdf?

**Comment by tatatananana** [comment]
yes i have a header and the output is pdf

**Comment by pofider** [comment]
jsreport currently by design calls the whole rendering process for header and footer separately. Same for child templates. This behavior is under consideration now, however you can filter out these request inside the listener using

```js
if (req.options.isChildRequest) {
   return;
}
```

**Comment by tatatananana** [comment]
Tnx!

**Comment by bjrmatos** [comment]
one task that we should do in the future is document all reporter methods/options etc :+1:
