### ISSUE TITLE
XLSX export: col A1 omited?

### ISSUE THREAD

**Issue by erzzo** [jsreport/jsreport#136]
Hi,
when I create my file in xlsx, in the jsreport viewer is the file shown like it should be. When I send it via API and download the file using https://github.com/eligrey/FileSaver.js/ the whole A1 column is blank. When I dump the response and view the sheet values:
![image](https://cloud.githubusercontent.com/assets/886192/10662843/64ce8238-78b7-11e5-9062-b5581979012d.png)
the A1 is ommited in !ref. Is that a problem with jsreport?

I've changed the response object wb.Sheets['Sheet 1']['!ref'].replace 'B1', 'A1' and it works, but that's not the right solution here.

**Comment by pofider** [comment]
Could you try first something simple like https://playground.jsreport.net/#/playground/YBjmBsPFa ?
Just to find out if the problem with the filesaver.js or the particular template. 

If I use the same template and store the stream as xlsx, I get both columns in excel correctly.

**Comment by erzzo** [comment]
![image](https://cloud.githubusercontent.com/assets/886192/10666343/5c07738e-78d1-11e5-9eb4-0f061aefc556.png)

It's the same. Console in the right corner shows output from client to the jsreport API server.

**Comment by pofider** [comment]
Would you be able to provide a sample code which reproduce this?

**Comment by erzzo** [comment]
Yes and it is making the same thing. Unfortunately when I used my free account on jsreport (https://fleetlog.jsreportonline.net/) the response came empty, with no sheets. But I tested it with the jsreport running on our servers, It worked, but I can't provide the credentials. So just fill up the things or you can give me some access to a jsreport server I will make the example work with the provided credentials.

https://jsfiddle.net/erzzo/0awL7jjo/

**Comment by pofider** [comment]
I have it working correctly if I remove the xlsx-js stuff. Do you need it for something or you have it there just for troubleshooting?

Here is the working example
https://playground.jsreport.net/#playground/bJ3jc0Wzug/2

**Comment by pofider** [comment]
The provided example runs for me just in FF because of some unrelated issues...

**Comment by erzzo** [comment]
When I run your example, open the downloaded file it says: File corrupt. No I use it because XHR2 can't pipe the binary stream from jsreport (https://groups.google.com/forum/#!topic/jsreport/2f9ZX8IYteA). But the used functions are from https://github.com/SheetJS/js-xlsx that jsreport uses. And it works, but with the column A, and without that I change it manually to !ref=A1:XX. If you insert the necessary values into the example it should show you the problem.

**Comment by pofider** [comment]
Hmmm.

Your example opens an empty excel for me and it also console.log undefined.
My example opens correct excel with two columns. 

I have excel 2013 installed.

**Comment by erzzo** [comment]
I tested in on ubuntu's libre office and on Excel 2016. Okey, last try. I've set the server for today without auth and I hope that it will work for you. https://jsfiddle.net/erzzo/0awL7jjo/1/ . I did what you in your example, it shows the missing colum. I don't know now what's wrong, because I used the same code as here https://github.com/SheetJS/js-xlsx#writing-workbooks

**Comment by erzzo** [comment]
I think we can close it. Jsreport is sending the right data, the problem is with the XLSX parsing. It omits the col sizing and the first column.

**Comment by pofider** [comment]
Ok, I was able to reproduce this with jsreport on ubuntu, but I also think the problem is rather in the XLSX parsing.
