### ISSUE TITLE
Images in xlsx engine?

### ISSUE THREAD

**Issue by jcfergus** [jsreport/jsreport#141]
Is there any plan to support embedded images in the xlsx recipe?

**Comment by pofider** [comment]
I am afraid we are using xlsx library which doesn't support images. (https://github.com/chuanyi/msexcel-builder/issues/30)

So we would need to implement this on our own or use different library. I quickly checked the xlsx format if this would have a quick solution, but it looks quite complex to me. I am not sure if have capacities to do it right now, maybe later. 

However let us know if you have a solution and we will happily merge it.

**Comment by pofider** [comment]
I proposed improvements for XLSX recipe which will add support for images. You can find it here #181

Closing this as a duplicate.

**Comment by pofider** [comment]
This have been implemented now in preview
http://jsreport.net/blog/excel-reports-with-charts-preview
https://github.com/jsreport/jsreport-excel
