### ISSUE TITLE
implement configuration to disable create/update/delete templates in jsreport studio

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#142]
Basically a configuration to disable these operations in jsreport studio.

at work we have an app in production, we would like to use jsreport-studio **only** to preview reports used in production, but we don't want that someone accidentally modify/delete a template affecting the template's source of the running app.

also, we're using [jsreport-fs-store](https://github.com/jsreport/jsreport-fs-store), so we don't want that someone create a template from jsreport-studio causing a new file being created in our source code.

i think what i have described matches a real world scenario and it is just a mechanism to protect the app in production.

what do you think?

**Comment by pofider** [comment]
Yes sure. This should be solved independently on the particular store implementation. I guess there is a same requirement when using mongo. Admin likely wants to freeze modifications in the production, good point. We should provide this.

I will analyze where to implement this. I think that an extension could listen to entity modifications and reject them. This would give us store agnostic solution.

**Comment by bjrmatos** [comment]
yeah exactly. let me know what are your thoughts about the implementation and if you would like me to do this

**Comment by pofider** [comment]
To summarize this. 

There will be a new extension `jsreport-freeze`. This extension blocks every change when one of these conditions is met:
1. there is configuration value `hardFreeze=true` 
or
2. there is settings value `freeze=true` provided by the admin user and the authorization extension is applied
or
3. there is settings value `freeze=true` and the authorization extension is not applied


Just to explain what I mean with settings... This is the core feature providing persistent key-value storage. The extensions use this to store some user based configurations.

In addition to blocking modifications the extension will add new UI action to the studio which lets the users to manually freeze or unfreeze editing (this updates the settings).

The usage:
1. jsreport is deployed to production with configuration `hardFreeze`. This is the master value which stops all the edits.
2. jsreport is deployed to production without `hardFreeze`. However the admin user is able to studio to `freeze` and `unfreeze` editing without required server restarts. 

The second option is designed mainly for jsreportonline, however I can imagine it is used also in the common on prem environments.

Which entities or collections should we actually freeze? It is clear we should freeze templates, however there are other entities we should not freeze. For example scheduling extension stores each background job run inside a task entity. Or statatistics extension stores some additional information about history of report rendering. For start lets just name entities we freeze, later we provide a meaningful attribute to these. 

We freeze: `templates`, `images`, `scripts`, `schedules`

I will do the first implementation...

**Comment by pofider** [comment]
Implemented in [jsreport-freeze](https://github.com/jsreport/jsreport-freeze)
