### ISSUE TITLE
Recipe to export report as image (png, jpg, etc.)

### ISSUE THREAD

**Issue by lu-ko** [jsreport/jsreport#143]
Do you have any plans to support export to image? For example, when I have a report with [leaflet](http://leafletjs.com/), export to PDF is working without problems but I need to export it to one image file.

**Comment by pofider** [comment]
This should be quick win as this is natively supported by phantomjs. It is just about changing configuration. We will look at it.

**Comment by lu-ko** [comment]
Thank you for quick answer. I look forward to see how to accomplish it in jsreport.

**Comment by bjrmatos** [comment]
@pofider it would be another recipe right? something like `phantom-image`? or you just plan to add this feature to `phantom-pdf recipe`?

**Comment by pofider** [comment]
Hmm. I have not decided yet.

Maybe having an extra recipe `phantom-image` which reuses implementation of `phantom-html-to-pdf` is the best.

**Comment by pofider** [comment]
Done. See [jsreport-phantom-image](https://github.com/jsreport/jsreport-phantom-image)
