### ISSUE TITLE
Version Control

### ISSUE THREAD

**Issue by Siafu** [jsreport/jsreport#147]
How do you add version control to an on premise install ? I tried creating a repository on the data\templates folder and IISNODE started to throw errors. Please advise.

**Comment by bjrmatos** [comment]
version control of templates is kind of tricky right now with the default installation, we are providing a solution for this with an extension [jsreport-fs-store](https://github.com/jsreport/jsreport-fs-store) (this extension will be the default in the future), the extension enables to store templates in the file system which enable to use version control systems (like git) very easy.

i recommend creating a repository in the root folder, with `server.js` file and others, not only the templates

**Comment by Siafu** [comment]
awesome, thank you. I'll check it out.

**Comment by bjrmatos** [comment]
i'm closing the issue.. feel free to keep comment :)
