### ISSUE TITLE
Corrupted PDF

### ISSUE THREAD

**Issue by TheCodeDestroyer** [jsreport/jsreport#149]
Hi/Ahoj!

I was playing around locally to see how this product works and when I came to API
calls I get back a corrupted PDF.
My request looked like [this](http://shrani.si/f/1r/2p/2AYA3ppK/postman.png) (With Content-Type: application/json).
I triple checked if IDs of [template](http://shrani.si/f/2o/o0/4BUjJPTv/template.png) and [data](http://shrani.si/f/1I/F9/4jmGJ1wB/data.png) are correct.

And the response file I get back looks like [this](http://shrani.si/f/2K/yc/1FlM51GX/pdf.png)

Info:
* OS: Linux Mint 17.1 Rebecca (Ubuntu fork)
* NodeJS: v5.0.0 and v0.12.7
* Rest Client: Postman
* Docker: Tested as well, but seems to be even more broken the web app doesn't work there

I hope I'm not missing something and I thank you in advance!

**Comment by pofider** [comment]
If you switch to html recipe it works for you?

In an old version of postman I had issue with saving pdf response directly. It was creating corrupt files, however this seems to be working in the latest one. Nevertheless I would recommend to try calling the API with something else to be sure it is not a postman problem.

**Comment by TheCodeDestroyer** [comment]
Switching to html returns [this](http://shrani.si/f/1N/13T/2y0QNE0g/html.png),
so I assume this is correct.
I'll try a different client and get back to you.

**Comment by TheCodeDestroyer** [comment]
OK I tried with Advanced Rest Client.
The [PDF](http://shrani.si/f/3x/pF/2Hk2FoO2/advanced-rest-client.png) can be opened, but it's empty.

**Comment by pofider** [comment]
Heh. Is the server ip public? I would try it with a simple nodejs or c# call.

**Comment by pofider** [comment]
I don't see a reason why it should not work through API when it works in jsreport studio where the call is actually the same.

**Comment by TheCodeDestroyer** [comment]
Sadly I'm testing this at work so I can't make this public.
Third option now is Heroku or OpenShift, I can set it up and see where that leads.
I'll do that tomorrow and since you are probably in CET as well its tomorrow for you also :)

**Comment by bjrmatos** [comment]
@TheCodeDestroyer don't need for Heroku or OpenShift, you can try [localtunnel](https://github.com/localtunnel/localtunnel)

**Comment by TheCodeDestroyer** [comment]
@bjrmatos sadly I'm not allowed to expose anything from out network...

**Comment by pofider** [comment]
I tested provided jsreport endpoint through email. The pdf was ok. The problem is probably somewhere in the used client. Closing.

**Comment by khancom1988** [comment]
Hello i was able to download the PDF file using https client but the file seems to be Corrupted. Here are my headers
        headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Basic SOMEKEY',
            'Accept-Charset': 'utf-8'
        }
