### ISSUE TITLE
Getting error on calling Report REST API

### ISSUE THREAD

**Issue by mfazal** [jsreport/jsreport#15]
When doing a POST on https://localhost:4000/api/report from RESTCLient in Firefox, the following error is appearing in the console:
**2014-07-30T09:17:16.037Z - error: Error during processing request: https://localhost:4000/api/report details: Could not parse report template, aren't you missing content type? undefined**

The following is the body being sent in the POST request:
{ 
"template": { "shortid" : "W13faln1W" },
["options": { "saveResult" : "true" }] 
}

When printing the request body in the console it is empty.

**Comment by Chandrakala14** [comment]
I am also getting same error . Please help me to come out of this?
