### ISSUE TITLE
Does jsreport needs to run apart from app?

### ISSUE THREAD

**Issue by feniixx** [jsreport/jsreport#150]
I mean, can't I install it in the same server where the app is running?

**Comment by pofider** [comment]
What app? What you mean? Please be more specific.

**Comment by feniixx** [comment]
I gave more details at [a SO question](http://stackoverflow.com/questions/33909359/install-jsreport-in-the-application-server), basically I wanted to know if same node.js instace works both for app and jsreport

**Comment by pofider** [comment]
Ok, you have the answer there now,
