### ISSUE TITLE
missing dependencies in lastest jsreport (0.10.0)

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#153]
i was testing lastest jsreport (0.10.0) on my PC (a fresh clone from github) and i noticed that there are some dependencies not listed in package.json.

and an error from [jsreport-xlsx](https://github.com/jsreport/jsreport-xlsx):

<img width="931" alt="captura de pantalla 2015-12-01 a las 8 06 09 p m" src="https://cloud.githubusercontent.com/assets/4262050/11519288/fd887d5c-9866-11e5-9172-d2970920ff89.png">

node version: 0.10.40
os: OSX Yosemite

**Comment by jcfergus** [comment]
I had similar issues when I upgraded, though I don't think it was those
particular dependencies.  :-/  I assumed it was user error, but figured I'd
say something in case it wasn't.  (I know, that's a really unhelpful bug
report.  Sorry.)

justin c ferguson          "Every jumbled pile of person has a
jferg at thedotin dot net  thinking part that wonders what the
jferg at lusars dot net    part that isn't thinking isn't
http://www.thedotin.net/   thinking of."           - TMBG

**Comment by bjrmatos** [comment]
@jcfergus feel free to ping me if you have any problems.. i will keep testing to see if i find another errors

**Comment by bjrmatos** [comment]
PR waiting in [jsreport-xlsx](https://github.com/jsreport/jsreport-xlsx/pull/2)
