### ISSUE TITLE
Statistics chart in JSreport studio

### ISSUE THREAD

**Issue by iu3564** [jsreport/jsreport#156]
Statistics in dashboard work only in development mode, need fix

**Comment by pofider** [comment]
Hi,

thank you for bug report.

I just fixed this in [jsreport-statistics@0.1.1](https://github.com/jsreport/jsreport-statistics/releases/tag/0.1.1)

If you are on NPM 3, you should be able to get it working with `npm install jsreport-statistics` and clear browser cache afterwards.

I will note here when is hotfixed jsreport with the new jsreport-statistics extension.

**Comment by pofider** [comment]
Release in 0.11.0
