### ISSUE TITLE
add gitter channel

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#157]
i think would be very cool to open a [gitter channel](https://gitter.im/) for jsreport, don't know if you would like to make it public.. if not, we can still use a private channel for internal communication.

toughts?

**Comment by pofider** [comment]
So it should be done and also linked from the readme. Is it right? I've never done it before. :)

**Comment by bjrmatos** [comment]
:tada: yes! feel free to ask me something i'm in the channel!
