### ISSUE TITLE
search box in Ace Editor not working in a custom express app

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#162]
![image](https://cloud.githubusercontent.com/assets/4262050/11885071/455341d0-a4ec-11e5-9cfc-340682f04996.png)

do you think that there are other routes affected?

**Comment by bjrmatos** [comment]
just for reference, the code that starts the app is:

```js
'use strict';

var app = require('express')(),
    jsreport = require('jsreport');

var PORT = process.env.PORT || 4500;

jsreport({
  express: {
    app: app
  }
}).init().then(function() {
  app.listen(PORT, function(err) {
    if (err) {
      console.error(err);
      throw err;
    }

    console.log('Report Server STARTED on:',
      this.address().address + ':' + this.address().port
    );
  });
});

```

**Comment by pofider** [comment]
Thanks for pointing this out.

Some time ago I decided to remove unused ACE files from the code base. Unfortunately I deleted also the "search box" extension. I thought extension needs to be manually required, but it is not true in the case of "search box". It looks it is the only case (https://github.com/ajaxorg/ace/wiki/Extensions). So I add this extension back and we should be fine.
(https://github.com/jsreport/jsreport-express/commit/b18541c454312495aedb704fc7bfd0b5a19d8c67)

**Comment by bjrmatos** [comment]
cool! i was missing the search box :smiley:

**Comment by pofider** [comment]
Should be fine since release 0.12.0

**Comment by bjrmatos** [comment]
awesomeee!!
