### ISSUE TITLE
jsreport-static-resources missing serve-static dependency

### ISSUE THREAD

**Issue by jcfergus** [jsreport/jsreport#164]
Finally getting around to updating my stage and prod (heroku) environments to 0.10/0.11 - it looks like jsreport-static-resources is missing a dependency on serve-static.

**Comment by bjrmatos** [comment]
you're rigth! let me fix it! happy new year! :)

**Comment by pofider** [comment]
The fix is released in jsreport-static-resources@0.2.1

**Comment by jcfergus** [comment]
Thanks, guys!
