### ISSUE TITLE
External font problem

### ISSUE THREAD

**Issue by kuba12kozak** [jsreport/jsreport#166]
Hi,
is it possible to add external font in css because this doesn't work for me:
@font-face { 
	font-family: Exo; 
	src: url('../font/Exo-Regular.otf'); 
} 

body {
	font-family: Exo;
}

Any help will be appreciated. Thanks.

**Comment by bjrmatos** [comment]
@kuba12kozak i think this is not supported right now, but let's figure out how to solve it

**Comment by pofider** [comment]
Font's are tricky, something works, something doesn't, see https://github.com/ariya/phantomjs/issues/10247 (keep in mind jsreport doesn't use phantomjs 2 yet)

I have tried Exo-Regular.otf and it works for me on the windows. The problem I see in your code is the use of relative path to the font file. This has to be a valid absolute url. 

With [jsreport-static-resources](https://github.com/jsreport/jsreport-static-resources) extension I can write following html and see the font rendered.

```html
<html>
    <head>
        <style>
            @font-face { 
                font-family: Exo; 
                src: url('{{$staticResources}}/Exo-Regular.otf'); 
            }
            
            body {
                font-family: Exo;
            }
        </style>
    </head>
    <body>
      Hello world
    </body>
</html>
```

**Comment by pofider** [comment]
1. As I mentioned already this font can be applied using jsreport-static-resources
2. Now also phantomjs2 can be used in jsreport http://jsreport.net/blog/phantomjs2
3. You can also check the latest improvements in using local resources http://jsreport.net/blog/using-local-scripts-and-other-resources

Closing this.

**Comment by sahin91** [comment]
It is possible now?

@font-face {
font-family: 'Roboto';
src: url(../fonts/Roboto-Regular.ttf);
format('ttf');
font-style: normal;
font-weight: 400;
}

.global-font {
font-family: 'Roboto', sans-serif;
}
