### ISSUE TITLE
How to set user as admin when not using jsreport-authentication .

### ISSUE THREAD

**Issue by jcfergus** [jsreport/jsreport#168]
I have JSReport embedded into a larger express.js application which uses Passport with express-session for authentication.  Happily, with JSReport authentication disabled, JSReport still seems to pick up my username/status and display them in the top menu bar, and all is well, except since my user is not an admin, I don't get the scheduling option in the top menu.  (I can enter the URL manually and get to the scheduling screen, though.)  Is there a way to set my user as an admin in my authentication routine in my larger app?

**Comment by pofider** [comment]
Please try setting `req.user.isAdmin = true` somewhere in your authentication middle-ware.

**Comment by jcfergus** [comment]
Thanks, works perfectly.
