### ISSUE TITLE
Angular chart doesn't render correctly 

### ISSUE THREAD

**Issue by abarmawi** [jsreport/jsreport#169]
i'm trying to generate a report and export it to pdf using recipe:phantom-pdf and engine: handlebars,

and the report contains 5 angular charts, and they aren't render correctly, see below
<img width="1440" alt="screen shot 2016-01-19 at 12 02 42 pm" src="https://cloud.githubusercontent.com/assets/5739235/12415595/2634a50a-bea5-11e5-937b-7ae0bfc14726.png">

and this is the same chart but in html page (it's working fine)

<img width="1440" alt="screen shot 2016-01-19 at 12 10 06 pm" src="https://cloud.githubusercontent.com/assets/5739235/12415674/accf1f00-bea5-11e5-917c-49db3c6e6aa3.png">

check this  file 

https://www.dropbox.com/s/le9mb1diek6wiql/details.html?dl=0

please advise.

**Comment by pofider** [comment]
Hi, it would be the best if you can simulate the issue in the [jsreport playground](https://playground.jsreport.net). Then we can very easily check it and propose a solution.

It is possible phantomjs is triggering the printing before the charts is completely rendered. Try to use phantomp-pdf setting "Print delay" or "Wait for printing trigger" to postpone rendering. You can find how to use the second one in the [docs](http://jsreport.net/learn/phantom-pdf)

**Comment by abarmawi** [comment]
how can i set these values "print delay",

i'm using nodejs like this

  var reportData = {
                template: {
                    content: data,
                    engine: "handlebars",
                    recipe: "phantom-pdf",
                    phantom: {
                        printDelay:true,
                        orientation: "portrait",//portrait
          
                    }
                }
            }


                jsreport.render(reportData).then(function (out) {
                out.stream.pipe(res);
            }).catch(function (e) {
                res.end(e.message);
            });

**Comment by pofider** [comment]
printDelay should be a number in milliseconds

**Comment by abarmawi** [comment]
thanks a lot it worked for me :)

i set the value to be 300 ms.

and it's working fine now.

but, what if i'm doing ajax request in the html?

**Comment by abarmawi** [comment]
can u please explain how to use "waitForJS" setting

**Comment by bjrmatos** [comment]
@abarmawi set `waitForJS` option to true, then in your code after doing something async (or in any place) set a special variable to true -> `window.JSREPORT_READY_TO_START = true;` that will tell `jsreport` to init the render process after your async operation.

```js
// somewhere in your code...

$.ajax({...}).done(function() {
  window.JSREPORT_READY_TO_START = true; // this will render your page after your ajax operation
});
```

**Comment by abarmawi** [comment]
thanks a lot guys, i did it and it's working now, but i used this flag window.PHANTOM_HTML_TO_PDF_READY
instead of window.JSREPORT_READY_TO_START

**Comment by bjrmatos** [comment]
@abarmawi are you using the last version of jsreport?
