### ISSUE TITLE
Fully async rendering?

### ISSUE THREAD

**Issue by jcfergus** [jsreport/jsreport#170]
Is there a way to submit a render request to the reports module that won't wait for the report to finish rendering before returning a Permanent-Link?  I have reports that take long enough to render (doing some data lookups in scripts, etc) that I'd like to be able to submit a render request, get back the permanent link, and poll every few seconds to see if the render has completed.  

I'm sure I could submit the request and then look up the most recent entry in the reports odata provider, but that could be problematic if I have multiple people running multiple reports.  

JF

**Comment by pofider** [comment]
Yes, I understand. Thank you for suggestion.

I will think about the solution for this, it doesn't look to be difficult to do so we should be able to add it to the reports extension.

**Comment by pofider** [comment]
This is now ready. 

`npm install jsreport-reports@0.3.0`

and see the docs for `async` option 
http://jsreport.net/learn/reports
