### ISSUE TITLE
JsReport bootstrap problem

### ISSUE THREAD

**Issue by anonimoaveces** [jsreport/jsreport#173]
I'm working on nodejs and I do the following:

- Install jsreport via: npm install jsreport --development --save
- Setup jsreport launching: node node_modules/jsreport --init
- Attach jsreport to my current express instance following: http://stackoverflow.com/questions/33909359/install-jsreport-in-the-application-server
- So when I run the server and jsreport instance init well but when I try to enter to "playground" (protocol:server:port/reporting) it popups a window with this message:

Cannot read property 'unique' of undefined
TypeError: Cannot read property 'unique' of undefined at module.exports (C:\zzzzzz\node_modules\jsreport\node_modules\jsreport-express\node_modules\simple-odata-server\lib\queryTransform.js:33:29) at module.exports (C:\zzzzzz\node_modules\jsreport\node_modules\jsreport-express\node_modules\simple-odata-server\lib\query.js:39:28) at Object.fn (C:\zzzzzz\node_modules\jsreport\node_modules\jsreport-express\node_modules\simple-odata-server\lib\odataServer.js:77:9) at Router.router.dispatch (C:\zzzzzz\node_modules\jsreport\node_modules\jsreport-express\node_modules\simple-odata-server\lib\router.js:64:20) at ODataServer.handle (C:\zzzzzz\node_modules\jsreport\node_modules\jsreport-express\node_modules\simple-odata-server\lib\odataServer.js:59:17) at C:\zzzzzz\node_modules\jsreport\node_modules\jsreport-express\lib\routes.js:117:17 at Layer.handle [as handle_request] (C:\zzzzzz\node_modules\express\lib\router\layer.js:95:5) at trim_prefix (C:\zzzzzz\node_modules\express\lib\router\index.js:312:13) at C:\zzzzzz\node_modules\express\lib\router\index.js:280:7 at Function.process_params (C:\zzzzzz\node_modules\express\lib\router\index.js:330:12) at next (C:\zzzzzz\node_modules\express\lib\router\index.js:271:10) at SendStream.error (C:\zzzzzz\node_modules\jsreport\node_modules\jsreport-express\node_modules\serve-static\index.js:120:7) at SendStream.emit (events.js:107:17) at SendStream.error (C:\zzzzzz\node_modules\jsreport\node_modules\jsreport-express\node_modules\serve-static\node_modules\send\index.js:245:17) at SendStream.onStatError (C:\zzzzzz\node_modules\jsreport\node_modules\jsreport-express\node_modules\serve-static\node_modules\send\index.js:356:12) at next (C:\zzzzzz\node_modules\jsreport\node_modules\jsreport-express\node_modules\serve-static\node_modules\send\index.js:630:16) at onstat (C:\zzzzzz\node_modules\jsreport\node_modules\jsreport-express\node_modules\serve-static\node_modules\send\index.js:619:14) at FSReqWrap.oncomplete (fs.js:95:15)

When I put on cancel, it crash my server and the output is:

TypeError: undefined is not a function
    at keys (C:\zzzzzz\node_modules\jsreport\n
ode_modules\jsreport-express\node_modules\simple-odata-server\lib\insert.js:5:18
)
    at sortProperties (C:\zzzzzz\node_modules\
jsreport\node_modules\jsreport-express\node_modules\simple-odata-server\lib\inse
rt.js:15:17)
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-express\node_modules\simple-odata-server\lib\insert.js:46:22
    at callback (C:\zzzzzz\node_modules\jsrepo
rt\node_modules\jsreport-fs-store\node_modules\nedb\lib\executor.js:30:17)
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\nedb\lib\datastore.js:295:12
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\nedb\lib\persistence.js:230:12
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\chokidar\node_modules\readdirp\node_modules
\graceful-fs\graceful-fs.js:42:10
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\fs-extra\node_modules\graceful-fs\graceful-
fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:95:15)
error!! TypeError: undefined is not a function
    at keys (C:\zzzzzz\node_modules\jsreport\n
ode_modules\jsreport-express\node_modules\simple-odata-server\lib\insert.js:5:18
)
    at sortProperties (C:\zzzzzz\node_modules\
jsreport\node_modules\jsreport-express\node_modules\simple-odata-server\lib\inse
rt.js:15:17)
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-express\node_modules\simple-odata-server\lib\insert.js:46:22
    at callback (C:\zzzzzz\node_modules\jsrepo
rt\node_modules\jsreport-fs-store\node_modules\nedb\lib\executor.js:30:17)
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\nedb\lib\datastore.js:295:12
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\nedb\lib\persistence.js:230:12
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\chokidar\node_modules\readdirp\node_modules
\graceful-fs\graceful-fs.js:42:10
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\fs-extra\node_modules\graceful-fs\graceful-
fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:95:15)
Error sending 500! TypeError: Cannot read property 'close' of undefined
    at Domain.<anonymous> (C:\zzzzzz\node_modu
les\jsreport\node_modules\jsreport-express\lib\clusterDomainMiddleware.js:20:13)

    at Domain.emit (events.js:107:17)
    at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
    at process._fatalException (node.js:233:33)
2016-01-21T18:02:20.246Z - error: Error when processing OData GET: /reporting/od
ata/templates?$filter=shortid%20eq%20%27EJwm3Z9dg%27&_=1453399338951&studio=norm
al TypeError: Cannot read property 'unique' of undefined
    at module.exports (C:\zzzzzz\node_modules\
jsreport\node_modules\jsreport-express\node_modules\simple-odata-server\lib\quer
yTransform.js:33:29)
    at module.exports (C:\zzzzzz\node_modules\
jsreport\node_modules\jsreport-express\node_modules\simple-odata-server\lib\quer
y.js:39:28)
    at Object.fn (C:\zzzzzz\node_modules\jsrep
ort\node_modules\jsreport-express\node_modules\simple-odata-server\lib\odataServ
er.js:77:9)
    at Router.router.dispatch (C:\zzzzzz\node_
modules\jsreport\node_modules\jsreport-express\node_modules\simple-odata-server\
lib\router.js:64:20)
    at ODataServer.handle (C:\zzzzzz\node_modu
les\jsreport\node_modules\jsreport-express\node_modules\simple-odata-server\lib\
odataServer.js:59:17)
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-express\lib\routes.js:117:17
    at Layer.handle [as handle_request] (C:\zzzzzz\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\zzzzzz\node_modules\exp
ress\lib\router\index.js:312:13)
    at C:\zzzzzz\node_modules\express\lib\rout
er\index.js:280:7
    at Function.process_params (C:\zzzzzz\node
_modules\express\lib\router\index.js:330:12)
    at next (C:\zzzzzz\node_modules\express\li
b\router\index.js:271:10)
    at SendStream.error (C:\zzzzzz\node_module
s\jsreport\node_modules\jsreport-express\node_modules\serve-static\index.js:120:
7)
    at SendStream.emit (events.js:107:17)
    at SendStream.error (C:\zzzzzz\node_module
s\jsreport\node_modules\jsreport-express\node_modules\serve-static\node_modules\
send\index.js:245:17)
    at SendStream.onStatError (C:\zzzzzz\node_
modules\jsreport\node_modules\jsreport-express\node_modules\serve-static\node_mo
dules\send\index.js:356:12)
    at next (C:\zzzzzz\node_modules\jsreport\n
ode_modules\jsreport-express\node_modules\serve-static\node_modules\send\index.j
s:630:16)
    at onstat (C:\zzzzzz\node_modules\jsreport
\node_modules\jsreport-express\node_modules\serve-static\node_modules\send\index
.js:619:14)
    at FSReqWrap.oncomplete (fs.js:95:15)
2016-01-21T18:02:31.885Z - error: TypeError: undefined is not a function
    at keys (C:\zzzzzz\node_modules\jsreport\n
ode_modules\jsreport-express\node_modules\simple-odata-server\lib\insert.js:5:18
)
    at sortProperties (C:\zzzzzz\node_modules\
jsreport\node_modules\jsreport-express\node_modules\simple-odata-server\lib\inse
rt.js:15:17)
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-express\node_modules\simple-odata-server\lib\insert.js:46:22
    at callback (C:\zzzzzz\node_modules\jsrepo
rt\node_modules\jsreport-fs-store\node_modules\nedb\lib\executor.js:30:17)
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\nedb\lib\datastore.js:295:12
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\nedb\lib\persistence.js:230:12
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\chokidar\node_modules\readdirp\node_modules
\graceful-fs\graceful-fs.js:42:10
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\fs-extra\node_modules\graceful-fs\graceful-
fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:95:15)
error!! TypeError: undefined is not a function
    at keys (C:\zzzzzz\node_modules\jsreport\n
ode_modules\jsreport-express\node_modules\simple-odata-server\lib\insert.js:5:18
)
    at sortProperties (C:\zzzzzz\node_modules\
jsreport\node_modules\jsreport-express\node_modules\simple-odata-server\lib\inse
rt.js:15:17)
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-express\node_modules\simple-odata-server\lib\insert.js:46:22
    at callback (C:\zzzzzz\node_modules\jsrepo
rt\node_modules\jsreport-fs-store\node_modules\nedb\lib\executor.js:30:17)
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\nedb\lib\datastore.js:295:12
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\nedb\lib\persistence.js:230:12
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\chokidar\node_modules\readdirp\node_modules
\graceful-fs\graceful-fs.js:42:10
    at C:\zzzzzz\node_modules\jsreport\node_mo
dules\jsreport-fs-store\node_modules\fs-extra\node_modules\graceful-fs\graceful-
fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:95:15)
Error sending 500! TypeError: Cannot read property 'close' of undefined
    at Domain.<anonymous> (C:\zzzzzz\node_modu
les\jsreport\node_modules\jsreport-express\lib\clusterDomainMiddleware.js:20:13)

    at Domain.emit (events.js:107:17)
    at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
    at process._fatalException (node.js:233:33)

My specs are:
     nodejs:   v0.12.4    
     express: v4.13.0
     jsreport: v0.11.0
     OS Windows 8.1 x64

Any help?

Thanks.

**Comment by pofider** [comment]
Unfortunately I was not able to replicate this. I was only using the latest node 5.4.1 but that won't be it.

Is there something else you could tell us? Were you trying this just on the empty express app or do you have there already something else like middlewares?

I cannot even find a possible reason when this exception could be thrown. Could you please navigate to 
`node_modules\...simple-odata-server\lib\queryTransform.js `
and check what is the incoming parameter in the first function which is causing the exception? Just write it to `console.log(JSON.stringify(query))` and copy paste it here.

You should be able to reach me in [jsreport gitter chat](https://gitter.im/jsreport/jsreport) for real-time troubleshooting this.

**Comment by anonimoaveces** [comment]
Hi pofider, it's an Express App with other middlewares. First, I'm going to try to start jsreport without any integration... only run jsreport with its default configuration.

I try to find out if there is any problem with any Thirdparty and Windows. 

Your hint can be helpful :).

Thanks for your support.

Keep in touch.

**Comment by pofider** [comment]
I have Windows as well, that should work fine.

**Comment by anonimoaveces** [comment]
I've just installed from zero and now run fine without integrate in a existent Express App. 

And this works :).

If I would try to integrate it again... and I have same problem or something, I communicate you about it.

Thanks for your support.

I'm going to close it as resolved.
