### ISSUE TITLE
Debug and log messages

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#175]
I got an idea for improving the developer experience in jsreport studio.....

Extensions will get an ability to write into "rendering request scoped" log and this log will be served into preview window if user enables debug checkbox instead of real content.

This can bring to user very valuable information like:
1. console.log messages from custom scripts
2. console.log messages from phantomjs
3. how long takes template rendering and how long pdf printing

**Comment by jcfergus** [comment]
Another thing that would be amazing would be a way to get the actual location/stack trace of an error within a custom script.

**Comment by pofider** [comment]
Thank you for your interest.

But this should already work, or not?

```js
function beforeRender(done) {
    function fnA() {
        done(new Error('Foo'));
    }
    
    fnA();
}
```

gives me

```
Error occured - Error during rendering report: Foo
Stak - Error: Foo
    at fnA (evalmachine.<anonymous>:3:14)
    at beforeRender (evalmachine.<anonymous>:6:5)
```

https://playground.jsreport.net/#playground/-kox8Bi3ag/1

**Comment by jcfergus** [comment]
My problem tends to be more with uncaught exceptions - usually I end up with something like:


```
/srv/nodejs/abcdef/node_modules/jsreport-jsrender/lib/jsrenderEngine.js:39
      throw error;
      ^
2016-02-09T18:51:11.992Z - error: Error when processing render request Error during rendering report: Cannot read property 'length' of undefined Error: Cannot read property 'length' of undefined
    at ChildProcess.<anonymous> (/srv/nodejs/abcdef/node_modules/script-manager/lib/manager-processes.js:38:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
From previous event:
    at /srv/nodejs/abcdef/node_modules/jsreport-core/lib/render/render.js:109:54
    at _fulfilled (/srv/nodejs/abcdef/node_modules/listener-collection/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/srv/nodejs/abcdef/node_modules/listener-collection/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/srv/nodejs/abcdef/node_modules/listener-collection/node_modules/q/q.js:756:13)
    at /srv/nodejs/abcdef/node_modules/listener-collection/node_modules/q/q.js:564:44
    at flush (/srv/nodejs/abcdef/node_modules/listener-collection/node_modules/q/q.js:110:17)
```

which makes it really hard to track down where in my script or template the error actually is.

**Comment by jcfergus** [comment]
(Actually, that one looks like an error in render and not in script - same issue applies, but I'll have to get a similar example from a script.)

**Comment by pofider** [comment]
I see. Unfortunately these information are not coming from templating engines. 

https://jsfiddle.net/17zmfxwr/

It would be nice to know at lease a helper name, but even this is not available. Does anyone know how to convince jsrender/handlebars to give us better errors? I may ask on their mailing list otherwise.

**Comment by jcfergus** [comment]
Here's another example where the error was actually occurring in the script:

`{"message":"Cannot read property 'forEach' of undefined","stack":"Error: Cannot read property 'forEach' of undefined\n at ChildProcess. (/srv/nodejs/abcdef/node_modules/script-manager/lib/manager-processes.js:38:23)\n at emitTwo (events.js:87:13)\n at ChildProcess.emit (events.js:172:7)\n at handleMessage (internal/child_process.js:686:10)\n at Pipe.channel.onread (internal/child_process.js:440:11)"}`

**Comment by pofider** [comment]
Back to original problem. The technical solution could work in the following way.

Extensions willing to add messages to the request scoped log adds the current request object as the last parameter to the logger method.
```js
reporter.logger.info("Hello world",request);
```

New extension `jsreport-request-logger` will be introduced. This extension will enhance the `reporter.logger[m]` with additional functionality which will add entry to `request.options.logs[]` if there is `request` parameter submitted. If the incoming `request.options.debug = true;`, it will replace the `response.content` with the logs instead of the recipe output.

I don't see any breaking changes doing it this way and also no additional logic needs to be added to `jsreport-core`.

**Comment by pofider** [comment]
@jcfergus Uh I was wrong. The line number on error in template helper is actually there. jsreport was swallowing it in `dedicated-process` scripting strategy, It works fine in `http-server` strategy. I will fix this in issue https://github.com/jsreport/jsreport/issues/176

**Comment by bjrmatos** [comment]
> Extensions will get an ability to write into "rendering request scoped" log and this log will be served into preview window if user enables debug checkbox instead of real content.

from what i understand you're planning to put the message in the preview content. why not create another tab ([Debug][Preview])? this will allow the developer to see the messages and the content at the same time

**Comment by pofider** [comment]
Maybe, but user can still run report rendering once to the new tab and then again with debug enabled to see it at the same time.

The problem is that we anyway need to do 2 requests to have both logs and pdf stream. This is because we do the preview in jsreport studio through plain synchronous post into iframe. Through artificial http form submit. So we don't have access to response headers where the logs could be provided.

**Comment by bjrmatos** [comment]
i didn't know about that limitation, seems ok to me. it will be more nice if it can be done in one request but if there is no other way is ok

**Comment by pofider** [comment]
Implemented in extension [jsreport-debug](https://github.com/jsreport/jsreport-debug) which is now part of the jsreport@0.13
