### ISSUE TITLE
Missing stack traces for scripts and helpers

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#176]
Created based on conversation here:
https://github.com/jsreport/jsreport/issues/175

jsreport swallows stack traces on errors when using `dedicated-process` for scripts and templates. This needs to be fixed in [script-manager](https://github.com/pofider/node-script-manager)

**Comment by jcfergus** [comment]
Fabulous, thanks!

**Comment by pofider** [comment]
Should be working with latest 0.12.1

**Comment by bjrmatos** [comment]
:+1:
