### ISSUE TITLE
PhantomJS 2 support

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#177]
Using phantomjs2 currently requires manual replace of phantom binary in the node_modules and the use of particular version cannot be done selectively based on the particular report template. 

I'm going to add the new template recipe option to `jsreport-phantom-pdf` which enable usage of custom phantomjs version which is not the default one. The recipe will then try to require [phantomjs-prebuilt](https://www.npmjs.com/package/phantomjs-prebuilt) and use it. This enables the end user to selectively use the default or particular additionally installed one.

**Comment by bjrmatos** [comment]
there will be no problems with the internal use of phantomjs (phantom-html-to-pdf)? i don't know if the API between phantom@1.x.x and phantom@2.x.x has changed but if it has changed then maybe is some incompatibility in somewhere

**Comment by pofider** [comment]
I didn't found any incompatibility yet. It just seems to work right away. There are neverending problems  with sizes and DPI, but that is a different thing.

**Comment by bjrmatos** [comment]
i see, then i think there will be no problem :smiley:

**Comment by jcfergus** [comment]
I've been using phantomjs2 for a while with jsreport and it works fine,
except for (as Jan mentions) the DPI problems, which I've worked around by
setting zoom: 68% on the body of all of my reports.  It's not perfect, but
works well enough for my purposes.

JF

**Comment by pofider** [comment]
This is not solved in the 0.13
http://jsreport.net/blog/phantomjs2
