### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#178]
It is almost two years since the very first version of jsreport was released. Since that time jsreport reached the stability and maturity and now it is time to show it and release version 1.0.

I don't plan to implement or include a additional fundamental features into this. I rather want to consolidate what we already have and show the promise to support the API for longer time. The release 1.0 is also opportunity to remove deprecated functionalities and make some breaking changes. Here I want to discuss it.

1. Remove [jsreport-embedded-store](https://github.com/jsreport/jsreport-embedded-store) from the official distribution package. It doesn't mean jsreport stops working with that. The users relying on this deprecated store will only need to additionally install it.

2. Remove support for older attributes and options in API
Currently jsreport supports many former API call options in duplicity form just to stay back compatible with very old versions. Reporting extension for example accepts parameter `options.saveResult: true` as well as `options.reports.save: true` and there are other cases in other extensions. We can get rid of it in release 1.0

3. Remove deprecated jsreport initialization through bootstrapper

4. Remove support for submitting templating engine helpers in form of object `{ helperA: function() {... }}` and support only the newer format with global functions

5. Remove or rewrite [embedding](http://jsreport.net/learn/embedding) extension. This extension was a bad experiment and the provided embeddable editor is probably not used. We should right now just extract and refactor the script used for invoking jsreport rendering API from the browser.

6. Remove the most of the script extension default modules. Right now scripts extension include many modules that are by default installed and enabled to be required in the scripts. This is the list `['handlebars', 'moment', 'request-json', 'feedparser', 'request', 'underscore', 'constants', 'sendgrid']`. I would personally remove everything and instruct user (through error message) to install desired packages and enabled them in the config.

7. Stop starting jsreport on default https and 443 port. Choose a http port which is usually free and start on that.

This is not all. I plan to add some other changes here, but need to rethink it a bit before. 

Please add your ideas and opinion. Right now is the best time for doing changes which may break something.

**Comment by bjrmatos** [comment]
:tada: i'll post some toughts later (need to find some time to analyse the list a little bit) but i'm really happy to see the roadmap :tada:

**Comment by pofider** [comment]
8. Templating engines should return function instead of just string output. This lets us to do caching.

**Comment by bjrmatos** [comment]
> Templating engines should return function instead of just string output. This lets us to do caching.

some notes in #117

**Comment by pofider** [comment]
> 5.Remove or rewrite embedding extension. This extension was a bad experiment and the provided embeddable editor is probably not used. We should right now just extract and refactor the script used for invoking jsreport rendering API from the browser.

I've created new extension [jsreport-browser-client](https://github.com/jsreport/jsreport-browser-client) which should replace the [embedding](http://jsreport.net/learn/embedding) one. I tried to cover these scenarios: 
1. Exporting pdf reports from browser
2. Drilling down into sub reports
3. Using third party WYSIWYG  editors like tinyMCE or CKEditor to edit templates outside of the jsreport studio.

The result is sufficient so I think we will remove the embedding extension from the official distribution in the release 1.

**Comment by pofider** [comment]
I will now evaluate the complexity of rewriting the jsreport studio into more modern webpack/react/flux stack and decide if the release 1 will wait for that or not.

I don't see any other task to do before releasing 1.0. The Excel Improvements #181 will be bring important value into jsreport, but it is not breaking things, so it can wait after 1.0 release

**Comment by bjrmatos** [comment]
> I've created new extension jsreport-browser-client

cool! i will try to play with it at work 

> I will now evaluate the complexity of rewriting the jsreport studio into more modern webpack/react/flux

thats great, let me know if you need to ask me something about that, also instead of flux look at `redux`, is the same principle of flux but better

**Comment by pofider** [comment]
Just updating here... I decided to rewrite the UI before releasing 1.0. I expect it should be in preview in one month. After it gets stable, there is nothing blocking for 1.0.

**Comment by pofider** [comment]
Just to note here. phantomjs seems to merged a fix that could help with uniting font sizes across platform. https://github.com/ariya/phantomjs/issues/12685

It would be worth it to check it and potentially update to phantomjs@2 in jsreport@1 and keep previous version as opt in.

**Comment by pofider** [comment]
Update:

Huge work of upgrading jsreport ui has been almost done, you can see beta in new playground
https://playground.jsreport.net/

The current plan is to finalize the UI code base and prepare beta release of jsreport@1 to npm.

This will take a week or two. I hope that in the meantime phantomjs team will release 2.2 and we will be able to use phantomjs@2 as default in the new version.

**Comment by ackzell** [comment]
Hi @pofider, I just started playing with jsreport last week and it came as a surprise that the UI changed on the examples I was looking at today.

Just wanted to congratulate you on this endeavor, great software you have here! Keep up the good work!

**Comment by pofider** [comment]
@ackzell  Thank you

phantomjs team doesn't seem to do any progress on the release. We will likely need to release with phantomjs@1, because next to the zoom size issue, there is also another major bug in version 2 (https://github.com/ariya/phantomjs/issues/13324).

I will start now with preparing pre-release of npm packages.

**Comment by bjrmatos** [comment]
@pofider will be good if you can release this version with the npm tag @next so we can play with it doing  `npm install jsreport@next`

**Comment by pofider** [comment]
@bjrmatos Yes, that is exactly what I had in mind. :)

**Comment by pofider** [comment]
jsreport 1 pre-release is now in npm, some minor changes, bug fixes and documentation on the way during the next few days...

`npm install jsreport@next`

**Comment by pofider** [comment]
jsreport@1 has been just released 
http://jsreport.net/blog/jsreport-10-is-here
