### ISSUE TITLE
XLSX recipe with charts

### ISSUE THREAD

**Issue by Orvacko** [jsreport/jsreport#179]
Hi, i any posibility to add charts using xlsx export ? [http://jsreport.net/learn/xlsx](http://jsreport.net/learn/xlsx)

I was trying to do it, also with your online playground, but .xlsx generate multiple .xml files, alone with chart and alone with sheet data.

Is there any solution? Can i merge this .xml files together ? Do you have some example or it is impossible?

Thank you very much

**Comment by pofider** [comment]
XLSX recipe currently adds just worksheet and stylesheet xmls.  This is also limitation of the underlying library it uses. https://github.com/jsreport/jsreport-xlsx/blob/master/lib/xlsx.js#L80

I am afraid you would need to add ChartSpace xml there as well.

After releasing jsreport@1 we plan to investigate some possibilities we have for more powerful excel and docs generation.

**Comment by pofider** [comment]
I proposed improvements for XLSX recipe which will add support for charts. You can find it here #181 

Closing this as a duplicate.

**Comment by pofider** [comment]
This have been implemented now in preview
http://jsreport.net/blog/excel-reports-with-charts-preview
https://github.com/jsreport/jsreport-excel
