### ISSUE TITLE
XLSX improvements

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#181]
I'm proposing redesign of Xlsx recipe which should then support really ultimately flexible excel creation as well as easiness of use for simple cases. I'm going to stick just with native office open xml format without any other thirdparty software used. So basically continue with what I started in xlsx recipe.  I came to this decision manly because....
1. I think that every document needs different care and that is why it is better to have dedicated format for excel. Converting html into xlsx will never work for more complex requirements
2. It is better to stick with the standard open xml format than to invent some kind of a xml... even when the open xml is really complex
3. The most of the c#/java libraries working with excel goes the imperative way which is something we don't like in jsreport
4. The format is quite difficult but I think that with good examples, the users will be able to handle it well

That was just to explain why we don't take another approach for excel generation. Back to the recipe redesign.

xlsx file is represented by many files zipped into one. Currently we let the developer to create `worksheet` and `stylesheet` files, which are the most important. Afterwards we zip this together with other required files and have the xlsx. This lets the developer to flexibly create worksheet using templating engines. However the problem comes when there is a chart or image presence in excel required, because this extra elements needs to be placed into other dedicated files. 

Proposed solution is to let the jsreport template to render every single file in xlsx and combine it into one big xml. jsreport xlsx recipe will then split this xml into the dedicated files and zip it into excel. The template would then look like the following one:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xlsx>
<xlsxFile path="xl/worksheets/sheet1.xml">
<worksheet>
  {{for data}} 
    <row><t><c>{{:val}}</c></t></row>
  {{/for}}
</worksheet>
</xlsxFile>
<xlsxFile path="xl/worksheets/_rels\sheet1.xml.rels">
<Relationships  .../>
</xlsxFile>
....
</xlsx>
```

This give the flexibility to create nearly every excel file. Only missing piece are binary files like images. However these files could be simply base64 encoded and marked.
```xml
<xlsxFile path="xl/media/image1.jpg" encoder="base64">
cascscsac561sac1as6c1sa6c16==
</xlsxFile>
```

Ok. This is now very flexible, but super complicated to create and read. To get over it the recipe would provide option to upload an existing excel file and replace just the interesting part. This should make life easier in the 99% cases because mostly you are only interested in pushing dynamic data into excel where pivot tables and charts can be already predefined.

Lets say we have already uploaded to jsreport styled excel file with pivot tables and charts. Now we need to replace the section containing data with dynamic data using templating engines.

First lets introduce handlebars block helper which does the replace on the `xlsxTemplate` input data property provided by the recipe.  `xlsxTemplate` will contain the original excel template uploaded to jsreport.
```js
function replace(data, pattern, options) {
    data.xlsxTemplate = data.xlsxTemplate.replace(pattern, options.fn(data));
}
```

The next we call this helper and replace first row with dynamically created data.
```html
{{#replace this /<row r="1".*<\/row>/}}
   {{#each this.people}}
     <row><c><v>{{firstName}}</v></c></row>
   {{/each}}
{{/replace}}

{{{xlsxTemplate}}}
```
At the end of the template we print the final output `{{{xlsxTemplate}}}` and the recipe will take care of zipping everything into excel file. This will mean that just couple of lines of code are required for creating excel file with charts, pivot tables....

Summary:
Xlsx recipe will be extended to be able to include multiple files into the final xlsx. To make it simple recipe will accept also real xlsx template file as a definition used by templating engines to replace just interesting parts.

Hope it is understandable. I will be glad for every question or suggestion before I start to implement this.

**Comment by mdavidcu** [comment]
Do you can provide graphics support?

**Comment by pofider** [comment]
This have been implemented now in preview
http://jsreport.net/blog/excel-reports-with-charts-preview
https://github.com/jsreport/jsreport-excel

**Comment by pofider** [comment]
jsreport@1 has been just released 
http://jsreport.net/blog/jsreport-10-is-here
