### ISSUE TITLE
Storing Rendered output to S3

### ISSUE THREAD

**Issue by fgauer** [jsreport/jsreport#182]
Just wanted to leave a note here that I have the basics of this working. I am going to improve it over the next week or two and if you're interested in linking to this extension, feel free to send me a message.

[https://github.com/fgauer/jsreport-s3-storage](https://github.com/fgauer/jsreport-s3-storage)

This saves the actual rendered output right to Amazon S3 in a nicely formatted bucket structure. More to some...

Thanks for your great work on jsreports.

**Comment by pofider** [comment]
That's great. I'm very interested, thank you.

Some comments on it...

My original idea was that [reports](http://jsreport.net/learn/reports) extension adds functionality for storing the reports' output and also provides the API and management UI. The implementation is using the storage abstraction where its concrete implementation then stores the blob to azure/amazon/file system.... The benefit is that the API and also UI stays the same no matter if you use azure or amazon storage. You can find an example of such storage implementation in [jsreport-azure-storage](https://github.com/jsreport/jsreport-azure-storage/blob/master/lib/main.js).

I would be very thankful if your extension follows that. 

I just see the following problem.

Current storage API (`storage.write(defaultBlobName, cb)`) doesn't provide you the template shortid. I would extend the signature to the following:
```js
storage.write(defaultBlobName, request, response).then(blobName) {

});
```
`storage.write` implementation can then calculate the blob name from shortid and date time and return it in promise value. The returned value would be then used in `storage.read` to find the right s3 blob.

Now if you agree with this, I can extend the storage API in the next minor release so you can adapt your extension. Afterwards I will enlist the extension in the official list.

**Comment by fgauer** [comment]
That sounds good. I originally tried to use the blob storage pattern, but then abandoned it because I did not have enough information to store the output on Amazon the way I would like to see it.

I will need:
shortId
file extension (pdf, csv, ...)

When you make the change, let me know and I will modify this extension to comply. 

Thank you!

**Comment by pofider** [comment]
Great. I let you know, probably in the next hours/days.

**Comment by pofider** [comment]
jsreport@0.13.2 contains the required changes for this.

You should implement `write` function in the following way....
```js
storage.write = function(defaultBlobName, buffer, request, response) {
  var blobName = request.template.shortid + (new Date().getTime()) + '.' + response.headers['File-Extension'];
 return s3.save(blobName, buffer).then(function() {
   return blobName;
 });
}
```

Keep in mind that the returned `blobName` is identifier later used in `blobStorage.read` so you should be able to find the blob from it.

Also please make sure the storage works also with "anonymous templates". It is very common to render dynamic template without shortid or name through API.

**Comment by pofider** [comment]
I've put it to our [roadmap](https://github.com/jsreport/jsreport#roadmap). We should get to it soon.

**Comment by pofider** [comment]
I released official [jsreport-aws-s3-storage](https://github.com/jsreport/jsreport-aws-s3-storage)
