### ISSUE TITLE
jsreport.embedded -  html to xlsx recipe: stdout maxBuffer Exceeded

### ISSUE THREAD

**Issue by MichaelB14** [jsreport/jsreport#184]
It appears this was fixed in 0.8.2 but jsreport.embedded is still 0.8.1

Any idea when jsreport.embedded will be updated?  Or anyway to manually update jsreport.embedded?

**Comment by pofider** [comment]
We plan some more investments into jsreport .NET part after we release jsreport@1.0. Which will take some weeks to finish.

Right now you can unzip `jsreport-net-embedd.zip`. Apply particular fix, which is this one https://github.com/pofider/html-to-xlsx/commit/50861318cbeddb2813d3bfce3b4d9efd76a24817

and zip it back.

**Comment by MichaelB14** [comment]
That worked.  Thanks
