### ISSUE TITLE
Generating PDF report from my own application.

### ISSUE THREAD

**Issue by viktordavidovich** [jsreport/jsreport#185]
Hi guys,

Is it possible to use jsreport as tool for generating PDF report from existing web-application?
For example:

I have my own application on the IIS server launched on **http://localhost:6677/engineering-module/report**
So, this application based on AngularJS framework and has a lot of charts and other complicated UI components. Before, I've prepared special web page with "@media print" css styles and good layout for making PDF.
Can I do something like this (pseudocode below):

```javascript
//imagine that we have some button on the web-page, such as generate report
//and we have callback function for event "click"
//...
generateReport(event) {
  //there we will make request to the some API - i guess it should be jsreport API
 //..
    reportingService.generateReport().then((data)=>{
       //..save blob      
    });

}

```

So the main idea is not using jsreport playground, or smth like this, I want just make a call some API, set some configuration object with URL of existing webpage for generating report based on phantomjs-html-to-pdf or smth.

I am newbie in this problem, sorry for the basic question.

**Comment by pofider** [comment]
You can POST to jsreport also URL of the page you would like to convert to PDF.

```
POST jsreport-url/report/api
BODY { template: { recipe: 'phantom-pdf', engine: 'none', phantom: { url: 'yoururl' } } }
```

However I'm not sure if jsreport is not just too much in this simple case.

**Comment by viktordavidovich** [comment]
@pofider Sounds good. This is what I wanted to use. Will try.

Also, could you please suggest "better solution" for my case?
I need 2 things:

  * Web page, with special html layout and styles, which looks really close to the future report, but without header, footers and other things.
  * PDF report, based on web page, but with all required things such as headers, footers, page number and etc.

Should I use jsreport, or phantomjs html to pdf converter with node server will be enough?

Thank you.

**Comment by pofider** [comment]
You can check for example [wkhtmltopdf](http://wkhtmltopdf.org/) utility.

**Comment by viktordavidovich** [comment]
@pofider ty
