### ISSUE TITLE
New Install Sample Report Error Occurred

### ISSUE THREAD

**Issue by brianmtully** [jsreport/jsreport#186]
I just installed jsreport. When trying to run(clicking the Run or Preview button) the sample report in the preview pane I get the following -

"Error occured - Could not parse report template, aren't you missing content type?"

This error happens both on local and remote install. I also created a new template, and that gives the same error.

**Comment by brianmtully** [comment]
After some more testing, this issue only happens when I attach jsreport to my existing express app, following the directions here http://jsreport.net/learn/adapting-jsreport

When I run it stand alone it is working properly. So it seems like the headers in the request are different when jsreport is attached to an existing express app.

**Comment by pofider** [comment]
I have tried to install clean jsreport and started the express app like this

```js
var express = require('express');
var app = express();

app.get('/', function (req, res) {
  res.send('Hello from the main application');
});

var reportingApp = express();
app.use('/reporting', reportingApp);

var jsreport = require('jsreport')({
  express: { app :reportingApp } 
});

jsreport.init().then(function() {
  app.listen(3000);
});
```

I am able to run the sample report in the studio. So I guess the issue can be that a one of your middlewares is modifying the request somehow. Can you check it?

**Comment by brianmtully** [comment]
The error was due to the bodyParser middleware. With that removed, it works properly. Closing this issue.
