### ISSUE TITLE
jsreport.embedded -  Method Not Found 'Simple.OData.Client.IBound...

### ISSUE THREAD

**Issue by MichaelB14** [jsreport/jsreport#187]
I started getting this error when I run my app (It builds fine).  It seems to happen when the build is trying to 'synchronize templates'  I have tried to clear the templates in the bin folder and clear the app data folder.

Any suggestions?

Method Not Found: 'Simple.OData.Client.IBoundCilent'1<!!0> Simple.OData.Client.ODataClient.For(System.String)

**Comment by pofider** [comment]
I would try to completely remove jsreport, [Simple.OData.Client](https://github.com/object/Simple.OData.Client) and [Micorosft.Data.OData](https://www.nuget.org/packages/Microsoft.Data.OData) dlls and then reinstall jsreport.Client nuget.

**Comment by pofider** [comment]
We removed the odata client from the latest jsreport for .net
