### ISSUE TITLE
Reading data from handlebars to set data in a jsreport render call

### ISSUE THREAD

**Issue by anonimoaveces** [jsreport/jsreport#188]
Hi, I have a template with following features:

Engine: handlebars
Recipe: wrapped-html

From this template I'm calling to another template with xlsx as recipe, but I'm struggling how to pass the {{data}} from the current template to the template called.

My javascript call is:

       var printTemplate = {"data":"{{this}}"};
       printTemplate.name = "templateXLS";
       printTemplate.recipe = "xlsx";
       printTemplate.engine = "handlebars";
       jsreport.render(printTemplate);

I put console outputs on render.js to see if data property is empty or not, and in this case goes empty.

However if "wrap" the {{this}} with an property name the value is received in render.js:

             var printTemplate = {"data":{"items":"{{this}}"}};

The content of {{this}} is an array like this:

[
    {
        "numbers": 2,
        "type": "Cars"
    },
    {
        "numbers": 2,
        "type": "Motorbikes"
    }
]

I would like maintain the data structure and not to add any extra property value, is it this possible?

Note: My environment is:

jsreport 0.13.1 (On windows 8.1 x64)

**Comment by anonimoaveces** [comment]
I've just found the solution, if any is interested, it's necessary to stringify the data creating a handlebars helper function:

function json(context) {
    return JSON.stringify(context);
}

And the call will be:

var printTemplate = {"data": {{{json this}}} };

Triple curlies to avoid handlebars escaping

**Comment by pofider** [comment]
Also linking here the blog post which elaborate on this. 

http://jsreport.net/blog/using-input-data-in-html-page-inline-javascript

Btw thank you for mentioning triple brackets, I fixed it now in the blog post.
