### ISSUE TITLE
Studio rewrite - webpack, react, redux...

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#189]
The jsreport UI part deserves technology stack upgrade. 

So I will make a prototype based on this starter kit https://github.com/este/este , because we use it on other projects and ask other for review afterwards.

**Comment by bjrmatos** [comment]
i'm sad to not being able to contribute in this change :disappointed:

**Comment by pofider** [comment]
Tell me about it. I did never like to do UI. :) I'll try to push the earliest bits soon and ask you for comments,it would be great if you contribute in this way.

**Comment by bjrmatos** [comment]
sure, i can!

**Comment by pofider** [comment]
Update:

we have prototype already running in playground https://playground.jsreport.net
repository is here: https://github.com/jsreport/jsreport-studio

**Comment by pofider** [comment]
jsreport@1 has been just released 
http://jsreport.net/blog/jsreport-10-is-here
