### ISSUE TITLE
Speed up jsreport startup time

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#192]
The problem and some solutions are described in #191

**Comment by pofider** [comment]
This is already implemented in jsreport-core, will be released in jsreport@1

Technically we store in the temp a file that contains the last modification date of node_modules folder and locations of found extensions during crawling. If the node_modules are not modified, we take the locations from this file and skip crawling of node_modules.

**Comment by bjrmatos** [comment]
@pofider i think that a great addition to this feature would be to add a way to disable it, i can easily see scenarios where i don't want this behaviour or maybe something could go wrong and i'll need to disable the caching.
