### ISSUE TITLE
Child templates parameters

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#194]
Executed child template currently inherits input data and options from the parent template. However there is no way to add additional parameter to the child template rendering.

How it can work
```js
{{#each someDataArray}}
    {#child myChildTemplate #data.paramA={{@index}}}
{{/each}}
```

The child template then can use something like
```js
{{someDataArray[paramA]}}
```

Or maybe pass the exact data into the child request
```js
{{#each someDataArray}}
    {#child myChildTemplate #data={{{toJSON someDataArray[@index]}}}}
{{/each}}
```

We need to think about the syntax, maybe this way user could alter also basic child template properties like recipe. In every case this sounds like a very valuable feature.

Oriignal problem posted here
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jsreport/-GmgW1JaR64/OMH3HR92BwAJ

**Comment by bjrmatos** [comment]
the name `data` seems to general, what about `context` ?

{{#each someDataArray}}
    {#child myChildTemplate #context.paramA={{@index}} #context.paramB={{5}}  }
{{/each}}

**Comment by bjrmatos** [comment]
don't know if it will cause some troubles but using `@` looks more good.

{{#each someDataArray}}
{#child myChildTemplate @context.paramA={{@index}} @context.paramB={{5}} }
{{/each}}

**Comment by pofider** [comment]
Thanks for hints. Using `@` looks really better. The idea behind naming it `data` was that it corresponds with jsreport API request

```js
jsreport.render({ template: {}, data: {}, options: {}})
```

I can correspondingly overwrite also template recipe or set the language culture for example
```html
{#child myChildTemplate @template.recipe=html @data.paramA=foo @options.language=sp}
```

I'll look at it deeply after I'm done with UI refactoring.

**Comment by bjrmatos** [comment]
> The idea behind naming it data was that it corresponds with jsreport API request

right, makes sense.

**Comment by bttlsgtmajor** [comment]
I've actually been digging through this all day today trying to figure out how/if this exact feature was possible. I for one could use this feature! Looking forward to when/if it makes it into the featureset.

**Comment by pofider** [comment]
This is now implemented, you can install it with npm install jsreport-child-templates@0.4.0

@bttlsgtmajor If you still needed, could you check it and give me feedback if it satisfy your needs?

Usage:
```html
{#child myChildTemplate @template.recipe=html @data.paramA=foo @options.language=sp}
```

**Comment by pofider** [comment]
It can be used with current jsreport by updating jsreport-child-templates.
It'll be included by default in jsreport@1
