### ISSUE TITLE
PDF Rendering

### ISSUE THREAD

**Issue by carlskii** [jsreport/jsreport#198]
Hi,

If run the HighCharts demo in the jsreport playground: 

```
https://playground.jsreport.net/#playground/e77zeliQO/2
```

The rendered PDF contains fully selectable text i.e. it doesn't seem to be just a rendered image.

However, If I run the same example on my Mac the text is not selectable and appears to be an image.

**Comment by pofider** [comment]
If don't think it is related to jsreport, but rather particular pdf viewer and I don't think there is something we can do regarding this.
