### ISSUE TITLE
Code samples and documentation 

### ISSUE THREAD

**Issue by carlskii** [jsreport/jsreport#199]
Hi,

First of all good job on the work you've done so far with jsreport. I spent the weekend evaluating it in a fair bit of detail. This tool shows some real promise. The ability to dispense with large cumbersome and bloated frameworks and other tooling for creating static visualisations and reports could finally be over.

I logged a couple of issues/questions which I think are mainly due to the lack of some complete end to end code samples and documentation. Some of your examples don't work as shown. This maybe specifically due to my use case where I really need to use jsreport-core as oppose to the full server.

Although I've pretty much got things working now, I could do with more complete code samples and descriptions as to whats happening. Especially with regards to capturing and handling errors. Also I needed to wrap my process.exit() within a timeout otherwise nothing gets written to files. Not sure if this is correct or just lack of my understanding.

Anything you have that provides more information as to whats happening would be very much appreciated.

**Comment by pofider** [comment]
Glad you have it running now.

We are constantly working on improving documentation and we will do review of current documentation just before releasing the next version. You are also welcome to send us PR if you improve something.

> Also I needed to wrap my process.exit() within a timeout otherwise nothing gets written to files.

@bjrmatos gave you example how to handle node.js stream end event and exit process after everything is written to file https://github.com/jsreport/jsreport/issues/197#issuecomment-205007713
I'm also linking hear issue in which this will be permanently solved https://github.com/jsreport/jsreport-core/issues/5

> Especially with regards to capturing and handling errors.

You need to catch the failed promise returned from `jsreport.render` to handle errors correctly. I fixed it in the docs now.

Closing this now. Feel free to open new issue with other specific problems.
