### ISSUE TITLE
End user report customization

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#20]
This is the highest requested feature and should be the breaking one. The main goal is to bring jsreport into the end user's browser. This means report customization will not be exclusive job for the jsreport integrator but it will give opportunity to the end users to customize invoices or what ever other report.

We will start simple in the first phase and provide just a simple report editor similar to one in jsreport studio. Later we may build a full WYSIWYG editor on the top of it.

## Concept
External web application embedding jsreport will download some jsreport init scripts first. When the user reaches a particular page or a button application triggers opening a lightweight jsreport designer. The designer will popup in the specified placeholder or in the dialog. The user should be able to preview and customize report there and save it back.

## Designer
jsreport lightweight designer could be the same as the [playground](https://playground.jsreport.net/) simplified studio. We only need to make it smaller so it fit to the placeholder.

## Security
We want to support also the scenario where jsreport is used in the multitenant environment. For this is crucial to guarantee that one tenant cannot see the templates from the other tenant and so on. This should be at least partially supported in jsreport otherwise every application needs to implement some kind of a authentication proxy in front of jsreport.

Mirroring users from another system or calling another authentication service is maybe an overhead at least for now. Let's provide security in easier way.

First, on premise version must get some kind of an admin account authentication. Admin should be specified in the standard config.

External application then should be able to call a specific jsreport REST method to get a restricted permission token for some specified id. The id can be a tenant id or user id of the external application. Retrieved token will then used when creating and accesing jsreport. jsreport will filter by the token only objects that were create with particular id.

## Widgets
We should not stick just to pdf reports. User should be able to easily design html live widgets running in the browser because it will be quite a quick win when we already have preview mechanisms and editor. The difference will be that recipe, javascript templating engine and script evaluation will run in the browser opposite to the typical server side rendering. We will introduce a client html recipe responsible for this.

jsreport server will be just a widget storage in this scenario.  But where are widgets will be pdf printing required and a lot of work for jsreport server.

## Implementation

Tasks need to be implemented:
1. enable CORS on the jsreport
2. test a playground jsreport studio embedding into an external web applications
3. add admin user authentication through config file
4. implement restricted permissions
5. implement client side html recipe

**Comment by pofider** [comment]
This is implemented as well as documented.

**Comment by pujie** [comment]
Hi, when I ran the example1.html,  I got following error in console: 
ReferenceError: jsreport is not defined.             example1.html (line 68, col 8)
What was going on ?

**Comment by pofider** [comment]
The up to date example can be found here
https://github.com/jsreport/examples/tree/master/customizableDashboard
http://jsreport.net/learn/customizable-dashboards-integration

In the example you point at is probably just wrong url to the embed.js, it should be
`http://local.net:2000/extension/embedding/public/js/embed.js`
But I need to check these examples again later and maybe delete them.

**Comment by pujie** [comment]
I have downloaded the files. 
How should I modify the home.html file ? It said "File not found", while the widget folder doesnt exists.
