### ISSUE TITLE
Ordered script execution?

### ISSUE THREAD

**Issue by jcfergus** [jsreport/jsreport#201]
Would it be a reasonable request to be able to select an order in which multiple scripts associated with a specific template are executed, in series rather than parallel (which seems to be the current manner if I'm reading the code right)?

**Comment by pofider** [comment]
The scripts are executed serially in the order specified in the studio. Try to deselect scripts in the studio and then select them in the desired order. It is not the best UX, but it works fine and usually you don't associate many scripts.

**Comment by PaulGrimshaw** [comment]
We have a server script that runs to fetch data.  We would like a client script to run before and after this server script - is there a way to make this happen?

**Comment by bjrmatos** [comment]
@PaulGrimshaw let's move the conversation [here](https://github.com/jsreport/jsreport/issues/337)

**Comment by PaulGrimshaw** [comment]
We have tried a few simple examples ordering 3 separate scripts, but the order seems very unpredictable. We know you can order them in the studio, and that this array corresponds to the array within the database, but we have found the rendering process doesn't follow this, and seems to stay the same regardless of the order specified.

A simple experiment with 3 scripts logging to the console, and trying to reorder should recreate this. Maybe it is to do with our environment... we're using the postgres storage.

Ideally we would be able to order global and extension scripts in combination with specific report scripts. Our basic pattern is to write database queries in a "query script" for each report. A global generic script (ideally an extension script) then fetches data from the database as per the query. We then have a final script sometimes to tailor the data for the report. This pattern is working great, just stuck with the ordering.

Any thoughts?

**Comment by bjrmatos** [comment]
yes, i know, i made a few comments [here](https://github.com/jsreport/jsreport/issues/337), let's try to comment in the other [issue](https://github.com/jsreport/jsreport/issues/337), just to keep the issue in context
