### ISSUE TITLE
Third party libraries and storage 

### ISSUE THREAD

**Issue by carlskii** [jsreport/jsreport#203]
Hi,

Whats the best way to deal storage ? I noticed there a storage folder in the data folder and was wondering if JSReports provide a storage mechanism for report data ? 

I'm considering using PouchDB (https://pouchdb.com/) to store some report data. If I use this library, where should it be located so that it can be accessed from `script` ? 

Thanks.

**Comment by pofider** [comment]
Hi, this storage is for output report documents.

You can check the following article which explains how to load data from the SQL Server. It'll be conceptually the same as with pouchdb

http://jsreport.net/blog/pdf-reports-in-sql-server
