### ISSUE TITLE
right to left in none english languages

### ISSUE THREAD

**Issue by elyas74** [jsreport/jsreport#204]
right to left in other languages not work.
original HTML look well, but after converting to pdf right align does not work.
see the full question in StackOverflow 
http://stackoverflow.com/questions/36470119/jsreport-right-to-left-in-none-english-languages

**Comment by elyas74** [comment]
I test it in your online playground and it was correct, but in my local playground I have the same problem. can this be a dependency problem or something like this?

**Comment by pofider** [comment]
This is probably related to this phantom issue https://github.com/ariya/phantomjs/issues/13060

https://playground.jsreport.net runs on windows. If you are on linux you may try to re-install fonts https://github.com/jsreport/docs/blob/master/installation/ubuntu.md#fixing-phantomjs

Please don't cross post you're questions, we are watching for SO, github as well as GG. Choose one and write there.

**Comment by elyas74** [comment]
thank you
I test this module, and work well with phantom and rtl
[https://www.npmjs.com/package/phantom](url)

**Comment by pofider** [comment]
That package uses the newer phantomjs@2. jsreport by default uses phantomjs@1 which is more stable. However you can opt in to the newer version which intentionally fixes your issue. See phantomjs2 in the docs http://jsreport.net/learn/phantom-pdf
