### ISSUE TITLE
JS-Report depending on insecure and/or outdated packages

### ISSUE THREAD

**Issue by postama** [jsreport/jsreport#207]
Following issues reported by snyk. It seems that many of them just require a dependency update

✗ Low severity vulnerability found on hawk@2.3.1
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:hawk:20160119
- from: jsreport@0.13.4 > jsreport-core@0.6.3 > script-manager@0.5.4 > request@2.53.0 > hawk@2.3.1

✗ Low severity vulnerability found on moment@2.10.6
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:moment:20160126
- from: jsreport@0.13.4 > jsreport-core@0.6.3 > moment@2.10.6

✗ Low severity vulnerability found on moment@2.10.6
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:moment:20160126
- from: jsreport@0.13.4 > jsreport-scripts@0.5.2 > moment@2.10.6

✗ Low severity vulnerability found on ms@0.6.2
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:ms:20151024
- from: jsreport@0.13.4 > jsreport-core@0.6.3 > reap@0.1.0 > ms@0.6.2

✗ Low severity vulnerability found on ms@0.6.2
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:ms:20151024
- from: jsreport@0.13.4 > jsreport-fs-store@0.3.1 > socket.io@1.3.7 > debug@2.1.0 > ms@0.6.2

✗ Low severity vulnerability found on ms@0.6.2
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:ms:20151024
- from: jsreport@0.13.4 > jsreport-fs-store@0.3.1 > socket.io@1.3.7 > socket.io-adapter@0.3.1 > debug@1.0.2 > ms@0.6.2

✗ Low severity vulnerability found on ms@0.6.2
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:ms:20151024
- from: jsreport@0.13.4 > jsreport-fs-store@0.3.1 > socket.io@1.3.7 > engine.io@1.5.4 > debug@1.0.3 > ms@0.6.2

✗ Low severity vulnerability found on ms@0.6.2
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:ms:20151024
- from: jsreport@0.13.4 > jsreport-fs-store@0.3.1 > socket.io@1.3.7 > socket.io-client@1.3.7 > engine.io-client@1.5.4 > debug@1.0.4 > ms@0.6.2

✗ Medium severity vulnerability found on request@2.65.0
- desc: Remote Memory Exposure
- info: https://snyk.io/vuln/npm:request:20160119
- from: jsreport@0.13.4 > jsreport-authorization@0.3.0 > request@2.65.0

✗ Medium severity vulnerability found on request@2.65.0
- desc: Remote Memory Exposure
- info: https://snyk.io/vuln/npm:request:20160119
- from: jsreport@0.13.4 > jsreport-xlsx@0.2.0 > request@2.65.0

✗ Medium severity vulnerability found on request@2.53.0
- desc: Remote Memory Exposure
- info: https://snyk.io/vuln/npm:request:20160119
- from: jsreport@0.13.4 > jsreport-core@0.6.3 > script-manager@0.5.4 > request@2.53.0

✗ Low severity vulnerability found on uglify-js@2.4.24
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:uglify-js:20151024
- from: jsreport@0.13.4 > jsreport-handlebars@0.3.1 > handlebars@4.0.4 > uglify-js@2.4.24

✗ High severity vulnerability found on ws@0.8.0
- desc: Remote Memory Exposure
- info: https://snyk.io/vuln/npm:ws:20160104
- from: jsreport@0.13.4 > jsreport-fs-store@0.3.1 > socket.io@1.3.7 > engine.io@1.5.4 > ws@0.8.0

✗ High severity vulnerability found on ws@0.8.0
- desc: Remote Memory Exposure
- info: https://snyk.io/vuln/npm:ws:20160104
- from: jsreport@0.13.4 > jsreport-fs-store@0.3.1 > socket.io@1.3.7 > socket.io-client@1.3.7 > engine.io-client@1.5.4 > ws@0.8.0

**Comment by pofider** [comment]
Thank you for pointing it out. We're gonna update the dependencies as we anyway planned to do. It is just too overwhelming to do it constantly. 

Closing this issue to hide it from the board. Please note that everything related to the security should be rather emailed to the repository maintainer first rather than making it public here. Thank you for understanding.
