### ISSUE TITLE
Allow use of existing SSL/TLS certs outside project directory

### ISSUE THREAD

**Issue by runlevelsix** [jsreport/jsreport#209]
I'm not sure if this is the correct repo to report this issue, jsreport seems to be somewhat modular, and I'm not sure which part handles this issue...

I'm trying to use an existing cert in /etc/ssl/certs, but jsreport cannot find it when I use the path with a leading `/` because it looks for the cert starting from the jsreport directory.

I was able to run jsreport with my SSL cert only after addressing the .key and .crt files by backing out of the current directory first (`../../../../../etc/ssl/certs/certname.crt`).

Could jsreport be updated to allow for absolute paths rather than assuming a relative path? I tried looking for where the config file was read in the code, but didn't find it...

Thanks.

**Comment by pofider** [comment]
Thank you for bug report.

Configuration `certificate` should accept both relative as well as absolute paths. However I found a bug in that logic which I just fixed.

Please update module jsreport-expresss@0.3.2 to get the fix

**Comment by runlevelsix** [comment]
Wow, that was fast! Thanks!

I also just hacked together a fix. I'll look to see if you did it the same way.

I added a key in my `prod.config.json` called `certDirectory` and referenced it in `jsreport-express/lib/reporter.express.js` lines 71 & 72.

**Comment by runlevelsix** [comment]
The fix appears to have the same behavior as before.

One thing I noticed is that I don't have a `rootDirectory` defined in my config, and the check for the existence of the cert appears to require that it is defined (`reporter.express.js:71`)

**Comment by pofider** [comment]
`rootDirectory` has its default. It doesn't matter you don't have it in the config...

This if should be skipped if you have absolute path in the `certificate.cert`
https://github.com/jsreport/jsreport-express/blob/master/lib/reporter.express.js#L71

And it should get here, where it reads the certificate based on the absolute path
https://github.com/jsreport/jsreport-express/blob/master/lib/reporter.express.js#L86

**Comment by runlevelsix** [comment]
Ok, it appears to work now after restarting Chrome. Much thanks!
