### ISSUE TITLE
Start with pm2 [on premise]

### ISSUE THREAD

**Issue by RobertPrediger** [jsreport/jsreport#21]
I have problems starting jsreport on premise with "pm2".
I did install it on an ubuntu server. The client is node with jsreport-client.

After starting with `pm2 start --name jsreport server.js`, when I run a report, the client throws an `Error: connect ECONNREFUSED`.
When I start it with `node server.js`, everything works fine.

Do you know why or have a workaround?

**Comment by rossnorvell** [comment]
For reference as someone who has had the same problem, initially connecting on the https://whatever after a basic install will cause this error. I don't really care so much about ssl so my fix was to change httpsPort to httpPort in prod.config.json   -- sincerely amazing library so far though.

**Comment by pofider** [comment]
Closing this because of long inactivity. Feel free to reopen.
