### ISSUE TITLE
Image not rendering on a certain server installation

### ISSUE THREAD

**Issue by Ackhuman** [jsreport/jsreport#213]
We are having a very strange issue on just one developer's local server instance.

A certain report that he is rendering on his machine fails to display any images.

As an example, [here](https://i.imgsafe.org/27ca7fb.jpg) is what my machine renders, and [here](https://i.imgsafe.org/2751894.jpg) is what his renders.  We are using the same C# code, the same server configuration, the same data, and the same template.

The request is done using a pregenerated HTML string that contains the cached images in a div with display:none as per your recommendations ([here](http://pastebin.com/u5eNYTGp) is the template we use to generate this).  They are using DataUrls, and they are included in this example in the header, again using a pregenerated HTML string for the header.  The footer is having the same issue.

The strangest part of this is that it only seems to be happening on a report that uses Highcharts.  When he generates the same report without including any charts, the images show up.

The other developer tried starting from scratch with his server installation, uninstalling the service, getting a fresh copy of jsreport.exe, installing it, and setting up the configuration again, and is still having the issue.  This started happening yesterday, after he introduced a printDelay into the request through the C# code, but he has since reverted all those changes.

He will be trying to use a test installation of the server late today to make an identical report request to see if it fixes the issue.  I will update this issue with the results.

**Comment by pofider** [comment]
Hmm, interesting. :)

Please try to remove the display:none, does it render at least in the report content?
Check the configuration option for phantom, do you use phantom-server or dedicated-process strategy?

```js
"phantom": {
  "strategy": "phantom-server"
},
```

Since v0.8, the default is dedicated-process.

This is important to know because the phantom-server is caching images over the requests.

**Comment by Ackhuman** [comment]
With the configuration we were using, that did not cause it to render.  We saw additional empty squares where the images would be.  We were not using phantom server, but when we changed to that option, it seemed to be consistently rendering images as expected.  Here is the configuration he used:

```
{
    "certificate": {
        "key": "node_modules/jsreport/certificates/jsreport.net.key",    
        "cert": "node_modules/jsreport/certificates/jsreport.net.cert"
    },
    "connectionString": { "name": "neDB" },
    "httpPort": 2001,
    "blobStorage": "fileSystem",
    "phantom": {
"strategy": "phantom-server",
                "timeout": 180000
    }
}
```

>The above configuration is working.  But with strategy not set, it does not work.   Also, even if we take out the display:none, the images do not appear unless we have the strategy set.  We also tried explicitly the strategy to dedicated-process and the images did not display.

We had been experiencing issues with charts taking too long to render (which is why we were using the printDelay setting); are images rendered before or after charts would be?  Could this be causing the issue?

**Comment by pofider** [comment]
You are on windows, right? Which jsreport version you have?

With phantom-server, I guess if you restart jsreport and try the first render, the images won't display, right?

Does the images display in html?

I've no clue what is rendered first in phantomjs webkit. I is too complex to find out. Did you turn off the animations in highcharts?

**Comment by Ackhuman** [comment]
Yes, we are on windows, using the latest version (0.8.1 I think).

The other dev reported the opposite before, he said he would restart the service and it would work the first time only.

What do you mean by do they display in HTML?  We have tried two methods so far, a Data URL as a CSS background property in a style tag, and an image tag with a Data URL.

Yes, we turned off animations for highcharts.  Everything was working before, he started having this problem only Tuesday.

**Comment by pofider** [comment]
> What do you mean by do they display in HTML?

I meant if there are the same problems with images when using html recipe. This would assure us the problem is in pdf printing and not somewhere else.

In the latest jsreport, there is debug button in the studio which displays the logs from phantomjs. There could be potentially some important messages. It would be worth it to try.
http://jsreport.net/blog/debug-extension

**Comment by Ackhuman** [comment]
The images did show up in HTML.  

The developer did get images to show up correctly in PDFs by changing the server config to use phantom-server rather than dedicated process.  He has switched back and forth between configurations many times now and it seems to consistently work.  For our purposes, this is now resolved, but I would like to help figure out what's actually happening.

If we have time this week, we will try grabbing the debug logs.  Will I be able to use the additional options property in JSReport.Client to request the debug logs with the response?

**Comment by pofider** [comment]
Ok, Thank you for info. I've no other hints or questions now.

Here is the c# code you can use to retrieve the logs

```cs
var rs = new ReportingService("http://localhost:3000");

var res = rs.RenderAsync(new RenderRequest()
    {
        template = new Template()
            {
                content = "foo",
                recipe = "phantom-pdf",
                engine = "jsrender"
            },
        options = new RenderOptions()
            {
                additional = new
                    {
                        debug = new
                            {
                                logsToResponse = true
                            }
                    }
            }

    }).Result;

var logs = new StreamReader(res.Content).ReadToEnd();
```

**Comment by pofider** [comment]
Closing this because of long inactivity. 
However feel free to reopen or add comments when it comes.
