### ISSUE TITLE
Access data without engine?

### ISSUE THREAD

**Issue by ackzell** [jsreport/jsreport#215]
Sorry if this is documented somewhere, but I just can't find it. 

So, let's say I didn't use any rendering engine in jsreport Studio. How can I refer to the data for my report?

Thanks,

**Comment by pofider** [comment]
I'm not sure if I understand. Can you elaborate more?

The templating engines are there to refer data and dynamically build report content.

**Comment by ackzell** [comment]
Thanks for the quick response. I am exploring an idea: I already built an AngularJS (1.x) report output for an app. I was trying to use the directives I already have into jsreport studio.

I am able so far to render a "hello world" into html as well as into a PDF file. 

But I would like to know if there is a way to access the data that you would normally access through handlebars or jsrender in a "vanilla" way to feed it into my AngularJS app.

I realize this is not intended to work this way, but as I said, I already have the report output built in directives and stuff. Ideally I wouldn't want to rewrite everything in one of the given engines.

I hope this makes sense. Thanks again.

**Comment by pofider** [comment]
Oh I see.
I guess this should help http://jsreport.net/blog/using-input-data-in-html-page-inline-javascript
This way you can put the data into vanilla javascript and use it as you like

**Comment by ackzell** [comment]
Thanks a lot, I'm looking into it. :)

**Comment by ackzell** [comment]
Not sure if I'm looking at it the wrong way, but this still needs to have one of the engines to parse the data, right? So, I need the engine to first read the data and then pass it to the inline script tag.

In doing so, I get conflicts with the Angular's way of rendering it's own templates. I believe. So this is why I was asking about not selecting a render engine at all.

**Comment by pofider** [comment]
I didn't know the tags will interfile with angular syntax, sorry.

Another way of doing it is to use custom script. Please check this
https://playground.jsreport.net/studio/workspace/EJLD5rNzZ/3

**Comment by ackzell** [comment]
I think I got it :)

http://stackoverflow.com/questions/25366412/using-express-handlebars-and-angular-js/29292666#29292666

So, basically adding a helper from handlebars, now both can live together.

**Comment by ackzell** [comment]
Although I think I like using the custom script better. Less moving parts I think. 
I am so grateful for jsreport, thanks a lot @pofider. You can close the issue if you want.

**Comment by pofider** [comment]
Great. Thanks for the feedback. Closing.
