### ISSUE TITLE
task.strategy: in-process == string functions don't work in helpers

### ISSUE THREAD

**Issue by jcfergus** [jsreport/jsreport#217]
I recently switched my server to use the in-process rendering strategy.  When that is set, string functions don't work in helpers.  This helper, for example:

function dateString( date ) {
    return date.split('T')[0];
}

which works fine with the default strategy, fails with:

TypeError: date.split is not a function at Object.dateString (evalmachine.:2:17) at wrapped (/app/server/node_modules/jsreport-jsrender/node_modules/jsrender/jsrender-node.js:324:16) at Object.eval [as fn](eval at buildCode %28/app/server/node_modules/jsreport-jsrender/node_modules/jsrender/jsrender-node.js:1768:10%29, :15:28) at renderWithViews (/app/server/node_modules/jsreport-jsrender/node_modules/jsrender/jsrender-node.js:1126:22) at Object.renderContent [as render](/app/server/node_modules/jsreport-jsrender/node_modules/jsrender/jsrender-node.js:995:13) at Tag.$tags.for.render (/app/server/node_modules/jsreport-jsrender/node_modules/jsrender/jsrender-node.js:1939:24) at renderTag (/app/server/node_modules/jsreport-jsrender/node_modules/jsrender/jsrender-node.js:569:26) at Function.eval [as fn](eval at buildCode %28/app/server/node_modules/jsreport-jsrender/node_modules/jsrender/jsrender-node.js:1768:10%29, :7:2) at renderWithViews (/app/server/node_modules/jsreport-jsrender/node_modules/jsrender/jsrender-node.js:1139:18) at Function.renderContent [as render](/app/server/node_modules/jsreport-jsrender/node_modules/jsrender/jsrender-node.js:995:13) From previous event: at /app/server/node_modules/jsreport-core/lib/render/render.js:141:54 at _fulfilled (/app/server/node_modules/listener-collection/node_modules/q/q.js:794:54) at self.promiseDispatch.done (/app/server/node_modules/listener-collection/node_modules/q/q.js:823:30) at Promise.promise.promiseDispatch (/app/server/node_modules/listener-collection/node_modules/q/q.js:756:13) at /app/server/node_modules/listener-collection/node_modules/q/q.js:564:44 at flush (/app/server/node_modules/listener-collection/node_modules/q/q.js:110:17)

when task.strategy is set to in-process.  This is true of any String-type function.  (jsreport 0.13.4)

JF

**Comment by pofider** [comment]
Are you sure the parameter is string? Isn't it rather a date which doesn't have split function?

Can you try to return `typeof  date` ?

For me the in-process strategy works fine.

**Comment by jcfergus** [comment]
Aha.  I see what's happening.  When I'm using the default strategy, it gets serialized into a string somewhere along the line.  When I'm using in-process, I get the date object.

**Comment by pofider** [comment]
Yes, we should probably do something with it and revive dates in the inner cross process communication happening inside jsreport/script-manager.

**Comment by pofider** [comment]
This should be fine in the v3 now.
