### ISSUE TITLE
params from querystring on GET method

### ISSUE THREAD

**Issue by meriturva** [jsreport/jsreport#218]
Hi to all,
i have to integrate jsreport into an existing application (actually is SCADA WinCC application).
I have the only possibility to open just a link to preview report so i have to pass variables from query string.
Any way to take param value from query string and make an interactive query?
Thanks.
Diego

**Comment by pofider** [comment]
I'm afraid we don't  forward query string into the rendering process. In other words, you cannot access these values through templating engine or script now.

However it sounds quite useful, I'll give it some thoughts.

In the meantime, you can for example create tiny proxy/wrapper which converts the link into the correct rendering request. That shouldn't be problem, or am I missing something?

**Comment by meriturva** [comment]
@pofider Thanks for your answer but it is not possible to have a proxy....i could (i guess) build a html page where i could get query string and make a post call to jsreport....but it is really "complicated" process. I think query string params is the best approach.

I think that feature could be really useful and powerful....thinking how many SCADA application could be expanded by a single webviewer component controlled by vbscript/csscript that change url. You could also make a "pseudo realtime" chart.

Thanks again.
Diego

**Comment by pofider** [comment]
I've never got in touch with SCADA and have no clue about the options you have there... 
However, maybe it should work for you also this way:

1. create a template using [html-with-browser-client](https://github.com/jsreport/jsreport-browser-client) recipe. This template should monitor hashchange event and based on the value call render of particular template with particular data

2. Your webview then changes the url like
GET: http://jsreport-host/templates/shortid-of-template#some-aditional-info

3. jsreport based on this request automatically sends back rendered template output, that will contain js which will create the full rendering request based on hash and use [browser-client](https://github.com/jsreport/jsreport-browser-client) to call jsreport server

Maybe this way you get even more control, what you think?

**Comment by pofider** [comment]
Additionally here is the code for extension adding query string into input data

`queryString.js`
```js
module.exports = function (reporter, definition) {
  reporter.beforeRenderListeners.add('queryString', function (req) {
    req.data = req.data || {}
    req.data.$query = req.query
  })
}
```

`jsreport.config.js`
```js
module.exports = {
  'name': 'query-string',
  'main': 'queryString.js'
}
```

Create this files somewhere in the application root, restart jsreport, and you should find query string through templating engine

**Comment by meriturva** [comment]
@pofider Really Really thanks.
It works like a charm! Now on my template i can access to `query` object with all of my querystring params.

But second step it is to filter sql made by a `script` as described on http://jsreport.net/blog/pdf-reports-in-sql-server

Mainly i have to get query string params, call my `script` with mssql query filterd by param and finally render template with correct data.
is it possible?

i have tried to access to `request.template` object from `script` without success as described on http://jsreport.net/learn/scripts

**Comment by pofider** [comment]
Ups, I didn't notice the followup here.

I think your approach is very good. What doesn't work there for you? You should be able to reach the `request.data.$query` and execute your sql statements accordingly.

```js
function beforeRender(done) {
    var param = request.data.$query.someParam
   //... do sql statements
    done();
}
```

Can you share your script?

**Comment by meriturva** [comment]
Perfect it works....mainly i was testing all with a old version of jsreport found on windows single executable on jsreport.net site.
I tested right now with npm v0.13 package and works great!
So thanks!

**Comment by vajnorcan** [comment]
Is this approach still valid for 1.10 as it seems like **jsreport.config.js** is not being picked up as I'm constantly getting undefined for the **$query** object. Thanks

**Comment by ccwalkerjm** [comment]
Is it possible to do the same with the public shared link?   I actually implemented the solution but it doesn't work with the public-templates?access_token=xxxxxx  path;     

Kindly advise.

Courtney
