### ISSUE TITLE
can't download pdf from jsreport online playground

### ISSUE THREAD

**Issue by djangojack** [jsreport/jsreport#222]
I am trying to download a report from the playground, and it isn't working. I hit the run button, and it renders to the right. But then, when I press the download button, and save it as report.pdf, the download fails and says "Failed - No file". Is this the expected behavior?

<img width="220" alt="screen shot 2016-06-16 at 1 30 47 pm" src="https://cloud.githubusercontent.com/assets/12073894/16126526/8d9cdece-33c6-11e6-9472-b0438667b7fa.png">

For example: https://playground.jsreport.net/studio/workspace/e77zeliQO/144

**Comment by pofider** [comment]
Interesting, this looks like a change or bug in chrome.
This stopped to work suddenly also in the older versions of jsreport where it was working a month ago.
It seems to work in firefox.

In every case, there will be soon update in playground adding the download button next to the Run which will work for sure correctly.

Can you try to use firefox or edge if you are on windows?

**Comment by djangojack** [comment]
Just tested safari, which also doesn't work because I can't even find the save button.

When do you expect the new playground to be available?

**Comment by pofider** [comment]
What seems to work for me in chrome is...
Right click on pdf in preview => print => save as pdf

https://github.com/jsreport/jsreport/issues/195

Next week I guess, if you are in kind of urgent need for downloading pdf, try to install another browser.

**Comment by pofider** [comment]
The playground has been updated. You can find the `Download` button in the context menu of `Run` button.

**Comment by robo66** [comment]
I'm getting the same issue with jsreport v 1.4 on Chrome. Works on Firefox.

**Comment by bjrmatos** [comment]
hi @robo66 , have you tried using the "Download Button"?

<img width="685" alt="captura de pantalla 2017-02-02 a las 11 40 49 p m" src="https://cloud.githubusercontent.com/assets/4262050/22579813/1773b8d0-e9a1-11e6-8f89-8bee748b506b.png">

let me know if you have the issue using the download button, download from the pdf viewer is kinda broken in chrome because a limitation

**Comment by robo66** [comment]
Hi, yeah that works okay it's just the download above the pdf that doesn't work.

**Comment by bjrmatos** [comment]
hi @davidbranco, so far there is no workaround, unfortunately browser pdf preview is not able to download pdf that was generated dynamically, the download of pdf preview only works when you opened a static pdf file, not something that was generated dynamically in a request

**Comment by pofider** [comment]
@davidbranco Is there a reason why using [download button in studio](https://github.com/jsreport/jsreport/issues/222#issuecomment-277163466) is not an option for you?

**Comment by davidbranco** [comment]
@bjrmatos @pofider guys, first of all, thanks for the quick reply and congrats for your awesome work. 
My comment was just to know if you guys already did a workaround. The JSReport is in test yet (we will buy it in June). So, my IT TEAM will create all templates and then we will generate the PDF using jsreport-cli. Thanks again.
