### ISSUE TITLE
jsreport online 500 error: REST API + template with script fails

### ISSUE THREAD

**Issue by djangojack** [jsreport/jsreport#223]
I have a template with a predefined script to give me access to handlebars helpers. Whenever I use the rest api with this template, it gives me a 500 error with this message. Everything works fine if I turn the script off OR if I just hit the run button on jsreport online. 

`{"message":"Error during rendering report: Unexpected identifier","stack":"SyntaxError: Unexpected identifier\n    at module.exports (E:\\approot\\node_modules\\toner\\lib\\engineScript.js:99:12)\n    at IncomingMessage.<anonymous> (E:\\approot\\node_modules\\script-manager\\lib\\worker-servers.js:153:57)\n    at IncomingMessage.emit (events.js:92:17)\n    at _stream_readable.js:943:16\nFrom previous event:\n    at Reporter.render (E:\\approot\\node_modules\\jsreport\\lib\\reporter.js:197:53)\n    at E:\\approot\\node_modules\\jsreport\\extension\\express\\lib\\routes.js:142:18\n    at Layer.handle [as handle_request] (E:\\approot\\node_modules\\express\\lib\\router\\layer.js:82:5)\n    at next (E:\\approot\\node_modules\\express\\lib\\router\\route.js:110:13)\n    at Route.dispatch (E:\\approot\\node_modules\\express\\lib\\router\\route.js:91:3)\n    at Layer.handle [as handle_request] (E:\\approot\\node_modules\\express\\lib\\router\\layer.js:82:5)\n    at E:\\approot\\node_modules\\express\\lib\\router\\index.js:267:22\n    at Function.proto.process_params (E:\\approot\\node_modules\\express\\lib\\router\\index.js:321:12)\n    at next (E:\\approot\\node_modules\\express\\lib\\router\\index.js:261:10)\n    at E:\\approot\\node_modules\\jsreport\\extension\\authentication\\lib\\authentication.js:168:20\n    at Layer.handle [as handle_request] (E:\\approot\\node_modules\\express\\lib\\router\\layer.js:82:5)\n    at trim_prefix (E:\\approot\\node_modules\\express\\lib\\router\\index.js:302:13)\n    at E:\\approot\\node_modules\\express\\lib\\router\\index.js:270:7\n    at Function.proto.process_params (E:\\approot\\node_modules\\express\\lib\\router\\index.js:321:12)"}`

**Comment by pofider** [comment]
Please share that custom script.

**Comment by pofider** [comment]
Closing because missing response here
