### ISSUE TITLE
Using --development results in "environment not set" warning

### ISSUE THREAD

**Issue by LykaiosNZ** [jsreport/jsreport#225]
Seems the warning in regards to environment is given even when you specify --development:

```
c:\JSReport>npm start --development

> jsreport-server@ start c:\JSReport
> node server.js

2016-06-29T21:10:27.059Z - warn: Node environment not set - using development configuration. Use options --production or --development to ensure exact configuration.
```

Not a huge deal seeing as it still uses dev.config.json, but a little confusing to be told the environment hasn't been set when it is. Using --production does not produce the warning.

**Comment by pofider** [comment]
Yes, you are right. It seems that npm doesn't set NODE_ENV when running with `--development` flag. I'll remove the warning message. Thank you for pointing it out.

**Comment by bjrmatos** [comment]
@LykaiosNZ the correct command is `npm start -- --development`, the `--` part is necessary to pass args to npm scripts

**Comment by LykaiosNZ** [comment]
@bjrmatos I did try that too and got the same result:

```
c:\JSReport>npm start -- --development

> jsreport-server@ start c:\JSReport
> node server.js "--development"

2016-06-30T19:55:30.931Z - warn: Node environment not set - using development configuration. Use options --production or --development to ensure exact configuration.
```

That said, I'm not particularly familiar with npm/node and how these flags work so not entirely sure what the correct solution is here. It may still be useful to show some sort of warning that it's running in dev mode?

**Comment by pofider** [comment]
I removed the misleading warn message. Thank you for pointing it out.
