### ISSUE TITLE
npm start --production error in mac

### ISSUE THREAD

**Issue by hanselacacia** [jsreport/jsreport#226]
Hi.I hope you can help me. I try to install JSReport in a MAC (Mountain Lion 10.8.5), node v6.2.2 and npm v3.9.5 they were installed  correctly.

But, when I run the command _npm start --production_ I get the following error:

Error occured during reporter init. Error: ENOENT: no such file or directory, stat '/Users/miuser/Library/Containers/com.apple.Preview/Data/Documents/iCharts'

Attach the screenshot:

![error](https://cloud.githubusercontent.com/assets/20403635/16738971/41beb3a4-4755-11e6-8031-15e835b46902.png)

**Comment by pofider** [comment]
This problem is discussed here - http://jsreport.net/blog/jsreport-10-is-here#comment-2758201072

Shortly - please try to install jsreport into dedicated directory

**Comment by pofider** [comment]
@hanselacacia This that help?

**Comment by hanselacacia** [comment]
Hi Jan,

yes, in a dedicated directory jsreport is working now. However, I installed
first brew, link node and then I had to assign permissions to the
node_modules folder. I do not know why.

Thank you very much.

2016-07-13 7:38 GMT-06:00 Jan Blaha <notifications@github.com>:

**Comment by pofider** [comment]
Ok, thank you for the info. Closing this
