### ISSUE TITLE
Save as window can´t detect file type of report

### ISSUE THREAD

**Issue by hanselacacia** [jsreport/jsreport#227]
Hello. I made the report in jsreport Studio, then clic Run/Run to new tab and the report opens in new tab correctly. I click download link in pdf viewer of chrome and Save as window appears with Type textbox recognizing my pdf report and All files options. 

But, when I open a new tab from my application, in the Save as windows only appears All files option ?.

This is my code, can you help me to know that I'm doing wrong:

var xhr = new XMLHttpRequest();
          var data = JSON.stringify({
              template: { shortid: "N12gQsyUb" },
              options: {  "Content-Disposition": "attachment; filename=myreport.pdf" },
              data: {
                  solicitante: "MIKE OSEJO VILLEGAS",
                  docSolicitado: "AVALUO",
                  fechaVisita: "3 de marzo 2016",
                  perito: "Ing. Didier Fonseca",
                  proyecto: "CONDOMINIO RESIDENCIAL BAJAREKE",
                  direccion: "Del Cementerio La Piedad 300 m este, entrada al complejo"
              }
          });

          xhr.open('POST', 'http://localhost:5488/api/report', true);
          xhr.setRequestHeader('Content-type', 'application/json; charset=utf-8');
          xhr.responseType = 'arraybuffer';

          xhr.onload = function (e) {
              console.log("done");
              var uInt8Array = new Uint8Array(this.response);
              var datauri = 'data:application/pdf;base64,' + arrayBufferToBase64(uInt8Array);
              window.open(datauri, "Reporte");
          };

          xhr.send(data);

Testing in Chrome Versión 49.0.2623.110 m
jsreport 1.0.6
Windows 7 Professional

Thank you for the help.

**Comment by pofider** [comment]
Hi,

please consider using jsreport browser client, it provides `download` function you would use. Or take a look at its source how is it done there
http://jsreport.net/learn/browser-client
https://github.com/jsreport/jsreport-browser-client-dist
