### ISSUE TITLE
Unable to enable moment in 1.08

### ISSUE THREAD

**Issue by TrikinCurt** [jsreport/jsreport#228]
Perhaps I am missing an obvious issue, but I tried to put "moment" in allowedModules but that did not work, then I put *.  Did I miss something?  I did see 1.09 came out while i was installing, but i could not see what it changed.

`"tasks": {
        "strategy": "in-process",
        "timeout": 10000,
        "allowedModules": ["*"]
    },
    "scripts": {
        "allowedModules": ["*"],
        "timeout": 60000
    }`

**Comment by pofider** [comment]
The format is
`"allowedModules": "*"`
or
`"allowedModules": ["moment"]`

**Comment by TrikinCurt** [comment]
I have tried that with the same error?  Am I missing something more than npm install moment and making the change to config and restarting?

**Comment by pofider** [comment]
That should be it. npm install, check it is really created in node modules, edit the config and restart server.

Check if the config is really applied. The name of the config file is written in the console when you start the server.

Can you share the error? 

Are you using moment in custom script on in helpers? For helpers you need to set `tasks.allowedModules` and for scripts `scripts.allowedModules`

**Comment by TrikinCurt** [comment]
> Initializing jsreport in development mode using configuration file dev.config.json

`"tasks": {
        "strategy": "dedicated-process",
        "timeout": 10000,
        "allowedModules": "*"
    },
    "scripts": {
        "allowedModules": "*",
        "timeout": 60000
    }`

> drwxr-xr-x 4 root root 4096 Jul 26 13:34 jsreport-embedded-store
drwxr-xr-x 5 root root 4096 Jul 26 13:41 moment
drwxr-xr-x 4 root root 4096 Jul 26 15:57 jsreport

the error is:

> Error occured - Error during rendering report: moment is not defined
Stak - ReferenceError: moment is not defined

Caused by a helper:

`function formatDate(date) {
    
    var foo = moment(date);`

Is there another step I am missing?  This code worked fine in the old (very old) version I was using before.

**Comment by pofider** [comment]
Ah ok, thank you for more details.

 `allowedModules` is there just for security reasons. You need to still require moment:

```js
var moment = require('moment')
var foo = moment(date)
```

**Comment by TrikinCurt** [comment]
Got it!   That is great, thanks for the help.
