### ISSUE TITLE
jsreport express with jsreport core

### ISSUE THREAD

**Issue by yusmarcastro** [jsreport/jsreport#229]
I cannot attach jsreport core to my simple express js app, I'm using the boilerplate in the jsreport-express package doc. When I start my app I'm able to query the main path "http://localhost:3000/" correctly but when I try with "http://localhost:3000/reporting" the browser output "Cannot GET /reporting". Here my demo details:

package.json:
{
  "name": "jsreport-server",
  "version": "1.0.0",
  "description": "JSReportServer",
  "main": "server.js",
  "dependencies": {
    "express": "^4.14.0",
    "jsreport": "^1.0.9",
    "jsreport-core": "^1.0.6",
    "jsreport-express": "^1.0.2",
    "jsreport-jsrender": "^1.0.1",
    "jsreport-phantom-pdf": "^1.0.3",
    "jsreport-templates": "^1.0.1"
  }
}

server.js (app entry point):
var express = require('express');

var app = express();

app.get('/', function (req, res) {
    res.send('Hello from the main application');
});

var reportingApp = express();
app.use('/reporting', reportingApp);

var jsreport = require('jsreport-core')();
jsreport.use(require('jsreport-jsrender')());
jsreport.use(require('jsreport-phantom-pdf')());
jsreport.use(require('jsreport-templates')());
jsreport.use(require('jsreport-express')({ app: reportingApp }));

jsreport.init();
app.listen(3000);

In the jsreport-express package doc says that the only requirement for the package is jsreport-template and as you can see I am including the package in the startup pipeline.

Regards.

**Comment by pofider** [comment]
Since jsreport@1 the express extension adds only the API. If you want to add also the studio, you need to install and use also [jsreport-studio](https://github.com/jsreport/jsreport-studio)
