### ISSUE TITLE
A few things about upgrading to 1.0 from 0.13.x

### ISSUE THREAD

**Issue by jcfergus** [jsreport/jsreport#234]
1.  I had to go into my mongodb, and remove the settings entry for analytics, which was set to a value of "ok", because it was bombing out on startup otherwise.  (Sorry, I don't have the full stack trace anymore, I should have saved it.)  
2. Several of my scheduled jobs wound with next scheduled times sometime in the future.  I had to go disable them and re-enable them to get the next run date to be correct.  
3. Minor UI bug - when changing the cron schedule or enabling/disabling, the Next run time does not auto update in the view.  I have to close the tab for the scheduled task and re-open it in order to see the updated Next run time.   
4.  It would be nice to be able to get a view of all upcoming scheduled jobs, in chronological order.

**Comment by pofider** [comment]
Thanks for your notes. I'll take a look at it.

**Comment by pofider** [comment]
The bug with settings as well as the ui bug in scheduling was fixed. 

The feature request for upcoming jobs have been submitted to scheduling repository
https://github.com/jsreport/jsreport-scheduling/issues/3

Thank you for your notes.
