### ISSUE TITLE
Implement compression for data

### ISSUE THREAD

**Issue by BerendWouters** [jsreport/jsreport#235]
When sending large data, it'd be useful to have some form of compression, to avoid sending too much data and thus reaching the incoming request limit

**Comment by pofider** [comment]
Great, thanks for suggestion. 

It will be probably the best to add the [compression] (https://github.com/expressjs/compression) middle-ware to [jsreport-express](https://github.com/jsreport/jsreport-express) extension. I'll take a look at it.

**Comment by BerendWouters** [comment]
That'd be wonderful, gzip would do a lot of good :)

**Comment by bjrmatos** [comment]
question: gzip applies for all http requests? json requests too? i've only implemented gzip on resources like `.css, .js, images, etc`

**Comment by BerendWouters** [comment]
> question: gzip applies for all http requests? json requests too?
If I'm not mistaken, this indeed is possible for all HTTP-requests. It's an HTTP-header, and the receiving server should be able to work with it. Also look at this blogpost: https://developers.google.com/blogger/docs/3.0/performance

**Comment by pofider** [comment]
I've done some investigations and it turned out that compression is already supported in jsreport and we don't need to implement or configure anything. :) This is because we already use [body-parser middleware](https://github.com/expressjs/body-parser) which automatically decompress the POST body if there is correct header.

See this example in node.js:
```js
zlib.gzip(JSON.stringify({
      template: {
        content: 'xxx',
        recipe: 'html',
        engine: 'none'
      }
    }), (err, buffer) => {
      request.post({
        url: 'http://localhost:5488/api/report',
        gzip: true,
        body: buffer,
        headers: {
          'Content-Encoding': 'gzip',
          'Content-Type': 'application/json'
        }
      }).pipe(res)
    })
```

**Comment by BerendWouters** [comment]
And this is also included in the C#-client?

**Comment by pofider** [comment]
You have to write your own function and make httpclient request with compressed body right now.

I've submitted the feature request to [jsreport net repository](https://github.com/jsreport/net/issues/16) to add this feature.
