### ISSUE TITLE
Slow PDF generation for large reports

### ISSUE THREAD

**Issue by zam6ak** [jsreport/jsreport#237]
I have been trying to speed up PDF report generation, but no matter which recipe/strategy I use it takes considerable amount of time to generate PDF even with simplest layout.

Here is a comparison for a simple, but large report I tried
- Report template used is a 'plain' HTML with no scripts or remote resources loaded. 
  The body is just an HTML table.
  Resulting PDF has 348 pages in Landsccape mode.
- Data is local JSON file  with 8300 rows and 18 columns
- Engine used is 'handlebars'
- Time shown is the fastest time out of 3 runs
- HTML rendering result (# 1) is just here for comparison purpose (PDF would take longer to generate, but the question is how much longer)

![image](https://cloud.githubusercontent.com/assets/838582/18389095/49a8e0d4-7672-11e6-8dec-bb7785260818.png)

So my question is - Is there anything that can be done to achieve faster speeds?
Going from 0.5 second (HTML) to 12+ second PDF response is a pretty large "gap"....

**Comment by pofider** [comment]
Unfortunately there is not much we can do about it. We are doing our best and optimize rendering time with caching handlebars templates or reusing phantomjs instances, but it is not in our power to go deeper to webkit or chromium codebase where the slowdown originates. 

I've also tried rendering pdf without virtual dom and html conversion using apache fop, but it also takes the same amount of time. 

Currently I don't have a solution for this. You gonna have to try different technology or maybe run the rendering of such long pdf reports in a background job?

**Comment by zam6ak** [comment]
Thanks for clarification. 
We currently use Apache FOP based reporting system and were looking to replace it with something faster.

**Comment by zam6ak** [comment]
Just an update, I am evaluating [PDFMake](http://pdfmake.org/) which is based on [PDFkit](http://pdfkit.org/) hoping perhaps I could make a custom recipe...
But it is slow as well when generating table with large number or rows...

**Comment by pofider** [comment]
Sure, custom recipes are easy.... I'm aware of this nice technology, but I think that better is to concentrate on improving the html and webkit based pdf rendering than using proprietary formats. 
Next big goal for jsreport is to fork chromium/webkit and try to optimize it for our needs.

**Comment by zam6ak** [comment]
I agree. 
Its just that this is nice product but I can't get the PDF speed resolved so I was looking at other solutions.
Can you share any timelines as to when we may be able to see increase in speed?

**Comment by pofider** [comment]
> Can you share any timelines as to when we may be able to see increase in speed?
This is long therm plan. I'm gonna take look on the chromium/webkit codebase at the beginning of the next year. I've no idea what I'll find there. :) I'll share plans afterwards.

**Comment by TommyLjung** [comment]
> This is long therm plan. I'm gonna take look on the chromium/webkit codebase at the beginning of the next year. I've no idea what I'll find there. :) I'll share plans afterwards.

Is this fixed now? :)

**Comment by bjrmatos** [comment]
> Is this fixed now? :)

well, we did not have the need to fork chromium yet, so far there is a good progress in performance using [headless chromium](https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md), which is available in jsreport using the [chrome-pdf recipe](https://jsreport.net/learn/chrome-pdf)

**Comment by pofider** [comment]
Today the chrome-pdf recipe is primarily used to generate pdf reports. 
This recipe uses chromium to convert html to pdf.
It can still be slow in some cases, but we don't have enough capacities and knowledge to go inside the code there and optimize it.

However, we introduced [pdf-utils](https://jsreport.net/learn/pdf-utils) extension which can dynamically combine multiple reports/pdfs together. This means that a bigger report can be assembled from multiple parts and the rendering can then run in parallel. This could speed up bigger reports rendering on multi CPUs hardware.

I'm closing this because we aren't planning to do more at this moment.
The html->pdf conversion optimizations can happen inside chromium.
We will concentrate on everything around.
