### ISSUE TITLE
Unable to replace xslt template

### ISSUE THREAD

**Issue by zam6ak** [jsreport/jsreport#238]
I have multiple report templates that use the same xslt template
Currently it is not possible to replace xslt template.

The template needs to be deleted, then re-uploaded.
Then **each report** has to be resaved, because the template changed...

**Comment by pofider** [comment]
Thank you for reporting this.

I've just released hotfix for xlsx which fixes this. You can install it now using
`npm install jsreport-xlsx`

it's gonna be part of the next jsreport hotfix as well.

**Comment by zam6ak** [comment]
Thanks!
