### ISSUE TITLE
npm start is not working

### ISSUE THREAD

**Issue by dineshu07** [jsreport/jsreport#239]
I have installed jsreport. and initialized successfully but not able to start the server. getting log

error: Error occured during reporter init Error: ENOENT, no such file or directory '/home/alethea/.kde/socket-alepc16'
    at Object.fs.statSync (fs.js:689:18)
    at /home/alethea/node_modules/jsreport/node_modules/jsreport-core/lib/util/util.js:51:21
    at Array.forEach (native)
    at Object.exports.walkSync (/home/alethea/node_modules/jsreport/node_modules/jsreport-core/lib/util/util.js:44:10)
    at /home/alethea/node_modules/jsreport/node_modules/jsreport-core/lib/extensions/locationCache.js:50:20
From previous event:
    at /home/alethea/node_modules/jsreport/node_modules/jsreport-core/lib/reporter.js:90:8
From previous event:
    at Reporter.init (/home/alethea/node_modules/jsreport/node_modules/jsreport-core/lib/reporter.js:69:30)
    at Reporter.reporter.init (/home/alethea/node_modules/jsreport/lib/extendInit.js:8:21)
    at Object.<anonymous> (/home/alethea/server.js:3:10)
Error: ENOENT, no such file or directory '/home/alethea/.kde/socket-alepc16'
    at Object.fs.statSync (fs.js:689:18)
    at /home/alethea/node_modules/jsreport/node_modules/jsreport-core/lib/util/util.js:51:21
    at Array.forEach (native)
    at Object.exports.walkSync (/home/alethea/node_modules/jsreport/node_modules/jsreport-core/lib/util/util.js:44:10)
    at /home/alethea/node_modules/jsreport/node_modules/jsreport-core/lib/extensions/locationCache.js:50:20
From previous event:
    at /home/alethea/node_modules/jsreport/node_modules/jsreport-core/lib/reporter.js:90:8
From previous event:
    at Reporter.init (/home/alethea/node_modules/jsreport/node_modules/jsreport-core/lib/reporter.js:69:30)
    at Reporter.reporter.init (/home/alethea/node_modules/jsreport/lib/extendInit.js:8:21)
    at Object.<anonymous> (/home/alethea/server.js:3:10)

please tell me did i miss anything.

**Comment by pofider** [comment]
You gonna need to install jsreport into dedicated directory like /home/alethea/myapp
Then it should work.

The problem here is that jsreport is crawling its parent directory and searching for applicable extensions during the start. There is a bug in this routine which sometimes crashes if you have specific other files/dirs there. 

The fix is already in jsreport-core master and should come with next jsreport hotfix, but please install it now to the own directory as mentioned anyway.

**Comment by dineshu07** [comment]
Sir I tried to install in dedicated directory but no luck. I have cleared npm cache, uninstalled jsreport and created new directory with different name and installed in new directory still not working.

**Comment by pofider** [comment]
Ok, this is how the app should look like after installing
`/home/alethea/myapp/package.json, server.js, dev.config.json`
`/home/alethea/myapp/node_modules/jsreport ....`

I've experienced previously problems with npm installing the package still to the root folder `/home/alethea/node_modules/jsreport` folder even the current directory was different. I solved this by deleting the root `/home/alethea/node_modules` (if there is nothing important) or by creating a separate extra root directory like `/myapp` and installing there.

**Comment by dineshu07** [comment]
Thank you sir. it worked. the problem is  I didn't remove these file from home directory package.json, server.js, dev.config.json. after removing all the files and did fresh installation in dedicated directory. it worked. thank you very much sir.
