### ISSUE TITLE
feature request: be able to set any value for report "shortid"

### ISSUE THREAD

**Issue by herbertpimentel** [jsreport/jsreport#240]
It is not a big deal but we may need keep track of this shortid in our apps and would be nice have the ability to set the shortid by we own.

See that example:

```
POST http://localhost:5488/api/report?shortid=sales_by_seller
```
insteadof

```
// the report with title = sales_by_seller 
POST http://localhost:5488/api/report?shortid=H1EkpMc3
```
the comment in the code will be necessary because we can't see in the UI any place to help us to find the report with shortid "H1EkpMc3" when we got a list with several templates.

**Comment by pofider** [comment]
API also accepts report name.

`POST /api/report: { template: name: 'foo' }, data: ... }` 

Wouldn't this be enough for you?

**Comment by yarongolan** [comment]
How does this work with folders?

**Comment by pofider** [comment]
@yarongolan Check the docs https://jsreport.net/learn/api

> In the most typical case, you will just put your template's shortid or template's name and input data. The template name property needs to be unique template name. In the case you use multiple folders it is recommended to pass instead of the name full path to the template. For example
```
{
  "template": { "name": "/myfolder/mytemplate" }"
  "data": {}
}
```
