### ISSUE TITLE
The export to excel using XLSX did not work

### ISSUE THREAD

**Issue by iergis** [jsreport/jsreport#243]
I tried to export the samplereport aut of installation into xlsx recipe and it gives this error
I used nodejs comand prompt to install server.
Any Ideas what is wrong or I'm doing somthing wrong.
Using latest version 1.0.9

<table style='border-style:solid'>
    <tr>
        <th>Name</th>
        <t...
Stak - Error: Unable to parse xlsx template JSON string (maybe you are missing {{{xlsxPrint}}} at the end?): 
<h2>Book sales</h2>
<table style='border-style:solid'>
    <tr>
        <th>Name</th>
        <t...
    at c:\IndulisReporting\node_modules\jsreport\node_modules\jsreport-xlsx\lib\fallback.js:67:17

**Comment by pofider** [comment]
You cannot simply use xlsx recipe to render html based format. Xlsx recipe requires different xml based format, see docs jsreport.net/learn/xlsx
