### ISSUE TITLE
Multi-column div not rendering in PDF

### ISSUE THREAD

**Issue by Wei-KeatKong** [jsreport/jsreport#245]
I'm having trouble getting multiple columns of data to render in PDF using any of the PDF recipes. 

I'm trying to render a 3-column div across two pages in PDF as follows:
.... content ...
row1 | row 3 | row 5 
row2 | row 4 | row 6
<page break>
row7 | row10 | row13
row8 | row11 | row14
row9 | row12 | row15
... content ...

If i use the HTML recipe, the 3 columns are rendered correctly.

Please see the playground example here:
https://playground.jsreport.net/studio/workspace/r1uNs47bx/19

**Comment by pofider** [comment]
css3 columns are not supported in phantomjs webkit
https://github.com/ariya/phantomjs/issues/11821

I'm afraid you need to implement the column structure in different way. Perhaps using floats or maybe tables.
