### ISSUE TITLE
Error occured - too many parameters

### ISSUE THREAD

**Issue by pcastelo** [jsreport/jsreport#246]
hello guys i am doing a very large POST to generete xml file , with handlebars as procesor and out is a text file 
i am getting the following error could you helpme to solve this? 

Error occured - too many parameters
Stak - PayloadTooLargeError: too many parameters
    at queryparse (/home/jsreport/node_modules/body-parser/lib/types/urlencoded.js:144:13)
    at parse (/home/jsreport/node_modules/body-parser/lib/types/urlencoded.js:75:9)
    at /home/jsreport/node_modules/body-parser/lib/read.js:116:18
    at invokeCallback (/home/jsreport/node_modules/raw-body/index.js:262:16)
    at done (/home/jsreport/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/home/jsreport/node_modules/raw-body/index.js:307:7)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by pofider** [comment]
You get this when running from jsreport studio, right?

Did you try to run this also through API? In this case there is configuration option you may try to set

```js
"express": {
        "inputRequestLimit ": "20mb"
}
```

**Comment by pcastelo** [comment]
yes i try from the studio and the api and the error is the same , 
with this config the error is the same 
is posible change the urlencoded size?

**Comment by pofider** [comment]
I'm quite wondering why it fails in urlencoded. Don't you send your data as JSON?

**Comment by pcastelo** [comment]
yes i am sending the data as json ,
i try to generate a pdf with the same request and its work fine , but when 
but when i use text recipe on response this crash

**Comment by pofider** [comment]
Do you really have correct content type in headers?

`Content-Type:application/json`

It should not get to the code where it is crashing if you have this header.

**Comment by pcastelo** [comment]
i am using http://jsreport.net/learn/browser-client
as you say , i  see it is using Content-Type:application/x-www-form-urlencoded
i go try to change this content type , or you recomend use other way ?

**Comment by pofider** [comment]
Ah ok. You use `render` function to trigger rendering, right?

Try to use `renderAsync` which uses json instead of urlencoded and is more reliable for big data sets.

**Comment by pcastelo** [comment]
its work for me ty!!!
