### ISSUE TITLE
Replace q promises with bluebird

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#247]
There seems to be very significant improvement when using bluebird promises.
The quick test on the fs store shows me 3x better performance for querying data store.

This is very surprising to me and such improvement would have very significant impact.
The q needs to replaced soon.

**Comment by bjrmatos** [comment]
yess!!! finally! 😄 i've been using `bluebird` all the time and i can confirm that it is the best promise library out there!

**Comment by pofider** [comment]
I've verified that the q can be replaced with bluebird step by step. We don't need to do it at once everywhere. It also doesn't produce breaking changes so we don't have to wait for release 2 and start doing it slowly right away. 

I've now released [node-listener-collection](https://github.com/pofider/node-listener-collection) to work with bluebird, the next step is switch in [jsreport-core](https://github.com/jsreport/jsreport-core) and extensions as it comes.

**Comment by pofider** [comment]
This is now reality in jsreport@1.4
