### ISSUE TITLE
How can I do some calculation in the end of each page?

### ISSUE THREAD

**Issue by navid045** [jsreport/jsreport#249]
I am using jsreport with ejs engine. Is it possible to do automatically some calculation in the end of each page. for example sum of a column values and print it in the end of page? I tried with <tfooter> tag but it execute in the end of for loop for all items. I need sum for items in each page. Have any body any solution for it?

**Comment by pofider** [comment]
This is not very much about jsreport but rather about css or phantomjs.

You can try to use thead and tfoot to achieve this. These tags are repeated on each page if the table spawns multiple pages.

**Comment by navid045** [comment]
@pofider Thank you for your response, I am using <tfooter> tag but it shows total of all items not total items of each page. Do you have any idea?
