### ISSUE TITLE
Structuring jsreport entities into folders

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#250]
This have became the most requested feature recently.

The main motivation is that it is hard to work with large numbers of templates in the studio.  It is ok with 30, but some users have already 100 and this is too much. They need to structure them into modules.

- We need a tree in studio
- The current strict grouping by entity type will be removed
- We need to support all store drivers so we need to have new attribute "folder" on each entity and new entity type "folder"
- The `fs-store` should be probably storing the entities in the real directories, but we need to find a way how to distinguish between entity types
- Would be nice if we can specify user permissions to the whole folder

I was thinking a while that the better solution to the problem would be using `lables`. This is more powerful because one template can have multiple labels where it cannot have multiple folders. Also assigning the permission based on the label is technically easier than to the folder. **However it still seems to me that the folders are more natural to the users so we likely do it the folders way.**

Short discussion here - https://github.com/jsreport/jsreport-studio/issues/14

**Comment by bjrmatos** [comment]
both solutions sounds great! can we have both? but i like the label approach more, because it is the easier solution and users can decide if they like to view the resources grouping by entity type (the current one) or by the label. Maybe a organization based on folders sounds more natural but maybe is too much complexity?

**Comment by pofider** [comment]
Everyone wants to have both :) It is true that the labels are very easy to do and folders will likely require breaking changes => should be part of the (spring?) jsreport@2

I've some more plans with folders. I would love to be able to download font-awesome or bootstrap,  and extract it somewhere to data folder. fs-store would automatically recognize these unknown files as assets and the studio would display it in the same folder structure in ui. This would feel more natural and we can switch to the current `config.json` based format when user actually adds some additional properties like permissions or labels.

**Comment by picibirdAdmin** [comment]
+1 for folders definately. We use tags to target report types. We would use folders to structure reports for customers and projects. Tags are better than folders but we would love both options. Keep up the good work.

**Comment by rashmim00** [comment]
+1 for folders.

**Comment by XjeaxaxX** [comment]
+1 for folders!!!!!!

**Comment by sdnetwork** [comment]
+1 for folders

**Comment by ThePolymorph** [comment]
+1 for folders

**Comment by pofider** [comment]
:open_file_folder: :open_file_folder: :open_file_folder:
Folders feature is now ready for use in jsreport [2.3.0](https://github.com/jsreport/jsreport/releases/tag/2.3.0)
