### ISSUE TITLE
query data from postgresql?

### ISSUE THREAD

**Issue by geomapdev** [jsreport/jsreport#251]
There are modules for mssql and mongodb, but is there a way to query report data (not templates) directly from postgresql?

**Comment by pofider** [comment]
Yes, you just need a custom script which use a node.js PostgreSQL client to query data. This one can be good enough
https://github.com/vitaly-t/pg-promise

This technique is deeply described in this article
http://jsreport.net/blog/pdf-reports-in-sql-server
