### ISSUE TITLE
Deleting saved reports from UI didn't delete it from the mongodb 

### ISSUE THREAD

**Issue by ansuman273** [jsreport/jsreport#252]
The current delete functionality present in Jsreport for saved reports doesn't delete it completely from db source or local storage path; It only removes the record in ui level so we won't see that row in the saved report table. I hope going forward this functionality gets added so it will be helpful for space management by completely removing the saved report.

**Comment by pofider** [comment]
Yes, this is missing. 
We will add this.

Thank you for suggestion.

**Comment by ansuman273** [comment]
Great! . I am going to check it out . Everybody will love it
