### ISSUE TITLE
Custom font in PDF header and footer of phantomjs recipe.

### ISSUE THREAD

**Issue by 563203132** [jsreport/jsreport#256]
I know it's possible to style the header and footer with inline css. But is 
it possible to use a custom font via font-face?
I believe it's not possible to include font-face declarations as inline 
css. Would it change anything if the font was installed on the server 
running phantomjs?
Hope someone out there has an idea :)
Thanks!

**Comment by pofider** [comment]
I believe you can do this with base64 encoded font-face in inline css.

See this demo
https://playground.jsreport.net/studio/workspace/Hk8MQRPEe/3

**Comment by 563203132** [comment]
Nice! It's work for me.
Very thankful!
