### ISSUE TITLE
Error running sample report OSX 10.12.1

### ISSUE THREAD

**Issue by stoff3l** [jsreport/jsreport#261]
Hi all,

I've installed jsreport on my local OSX (10.12.1) machine and I'm trying to run the sample report but I get an error.

I installed using NPM 4.1.2 and I used the following commands as described on the site:
sudo npm install jsreport --production
sudo node node_modules/jsreport --init
npm start

Note that after running the 1st install step I get the following warnings, not sure if this might be the problem:
    npm WARN enoent ENOENT: no such file or directory, open      '/Users/tinus/Documents/repos/pm_project/reportserver/package.json'
    npm WARN react-copy-to-clipboard@4.2.3 requires a peer of react@^0.14 || ^15 but none was     installed.
    npm WARN reportserver No description
    npm WARN reportserver No repository field.
    npm WARN reportserver No README data
    npm WARN reportserver No license field.

When I then go to localhost/5488, select the sample template and click on run I get the following output:

    Error occured - Error during rendering report: Command failed:      /Users/tinus/Documents/repos/pm_project/reportserver/node_modules/phantom-html-to- pdf/node_modules/phantomjs/lib/phantom/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any     /Users/tinus/Documents/repos/pm_project/reportserver/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js    /var/folders/5q/sc8m61d55dgdbhwt0fms_wzw0000gn/T/jsreport-temp/1ebce420-eb9c-11e6-9fe8-9d47de51e292settings.html
    Stak - Error: Command failed: /Users/tinus/Documents/repos/pm_project/reportserver/node_modules/phantom-html-to-pdf/node_modules/phantomjs/lib/phantom/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /Users/tinus/Documents/repos/pm_project/reportserver/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js /var/folders/5q/sc8m61d55dgdbhwt0fms_wzw0000gn/T/jsreport-temp/1ebce420-eb9c-11e6-9fe8-  9d47de51e292settings.html

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)	
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

I'm very new to NodeJS so I'm hoping someone can help me figure this out?

Kind regards
Tinus

**Comment by pofider** [comment]
Hi,

the default phantomjs used in jsreport stopped to work with the Mac Siera update. At this moment, you need to additionally run:
`npm install phantomjs-exact-2-1-1 --save`

And then select phantomjs 2.1.1 in the recipe menu (after reload)
![phversion](https://cloud.githubusercontent.com/assets/2041960/22626208/d8f7d96a-eba8-11e6-8137-53eed7825fbb.png)

Alternatively you can configure jsreport to use other phantomjs in this config
```
"phantom": {   
    "defaultPhantomjsVersion": "2.1.1"
  }
```

This is in documentation described here
https://jsreport.net/learn/phantom-pdf#macos-sierra
https://jsreport.net/learn/phantom-pdf#phantomjs2

**Comment by stoff3l** [comment]
Hi,

Thank you for the quick reply, that fixed the issue.

Kind regards
Tinus

**Comment by DimaSavchenko** [comment]
Hi, @pofider! 
I have the same error, but I installed phantomjs-exact-2-1-1 and set request.template.phantom.defaultPhantomjsVersion: "2.1.1". 

After render:
```
jsreport.render(request).then(function (resp) {
        fs.writeFileSync('report.pdf', resp.content)
      });
```
Thanks

**Comment by bjrmatos** [comment]
hi! @DimaSavchenko have you tried using the following in jsreport config file? (without changing request options)

```js
...
"phantom": {   
    "defaultPhantomjsVersion": "2.1.1"
  }
....
```

if you open the jsreport studio, can you see the 2.1.1 version in phantomjs version dropwdown? if you can see it, what happens when you render from studio using that version? does it ends with an error? or does it finish normally?

**Comment by DimaSavchenko** [comment]
@bjrmatos Thanks for the response.

It happens only if I use request options. If I run jsreport-cli and change phantomjs version everything is  OK

**Comment by bjrmatos** [comment]
i see. thanks for the update.

according to [docs](https://jsreport.net/learn/phantom-pdf#phantomjs2) the correct option in request options is:

```
request.template.phantom.phantomjsVersion = "2.1.1"
```

and not `request.template.phantom.defaultPhantomjsVersion`. maybe that was the error in the first place.

**Comment by DimaSavchenko** [comment]
Nice, Everything worked out

@bjrmatos, Thanks very much
