### ISSUE TITLE
Problem with phantom-pdf

### ISSUE THREAD

**Issue by lsmar** [jsreport/jsreport#268]
When I try to run with phantom-pdf as recipe I get this error: 

<img width="1579" alt="captura de tela 2017-02-20 as 21 18 28" src="https://cloud.githubusercontent.com/assets/11711447/23146061/2f469ed6-f7b2-11e6-92cd-dfdddc1fa12a.png">

<img width="665" alt="captura de tela 2017-02-20 as 21 22 20" src="https://cloud.githubusercontent.com/assets/11711447/23146116/b2b0e48e-f7b2-11e6-8270-09b80775cd42.png">

I'm trying to run on:
mac osx 10.12.3
node 7.4.0
npm 4.0.5

Anyone can help me?

**Comment by bjrmatos** [comment]
hi!, unfortunately `phantomjs` v1 (which jsreport uses by default) doesn't work on macOS Sierra, you will need to use `phantomjs` v2 in order to use the `phantom-pdf` recipe.

you can find instructions on [how to use phantomjs v2 here](https://jsreport.net/learn/phantom-pdf)

**Comment by pofider** [comment]
Mac OS Sierra problems are explicitly noted in docs.
https://jsreport.net/learn/phantom-pdf#macos-sierra

Closing now.
