### ISSUE TITLE
Use ArangoDB as a data source

### ISSUE THREAD

**Issue by lobosan** [jsreport/jsreport#270]
Is it possible to connect ArangoDB to JSReport and query a graph or use the REST API to create a dashboard?

**Comment by pofider** [comment]
You can very easily connect to any data source which exposes a http endpoint.

See example here
https://playground.jsreport.net/studio/workspace/r1G-1ULP/3
and you would probably use this rangodb http API
https://docs.arangodb.com/3.0/HTTP/

The next option is to use an arango javascript driver. This seems to be the official one
https://github.com/arangodb/arangojs
you should be able to install it using 
`npm install arangojs`
and then get its instance in jsreport [custom script](https://jsreport.net/learn/scripts) using
`require('arangojs')`

I've never used this db, so take this just as hints.

**Comment by lobosan** [comment]
Thanks @pofider, I'll give it a go
