### ISSUE TITLE
jsreport v2

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#272]
The intention of this ticket is to prepare the list of breaking changes we want to make or discuss for release jsreport@2. 

The list will grow... We will possibly do un-breaking changes as part of release 1. There is no strict plan in feature scope or date for release 2. We continue to develop features into the release 1, this is just for future reference.

1. (DONE) raise minimal supported node.js version from 0.12 to v8
2. (REJECTED) possibly make in-process strategy the default one
3. (DONE) rethink configuration - maybe one shortcut `allowLocalAccess`
4. (REJECTED) possibly allow usage of local files as default and make the "secure" mode as opt in
5. (DONE) switch to chrome instead of phantomjs and make phantomjs optional
6. (DONE) refine logging
7. (DONE) refine rendering request object - currently it is mostly expected a form of express request cloned on many places #262 
8. (DONE)rework default fs store to support cluster mode (the rewrite is ready in jsreport-fs-store@next)
9. (DONE in default recipes) the `Content-Disposition` response header could contain template name instead of always `report.pdf`.
10. (DONE) Refactor underlying document store and blob storage api https://github.com/jsreport/jsreport-core/issues/11
11. (DONE) make `.init` to throw an error if it is being called more than once https://github.com/jsreport/jsreport-core/issues/13
12. (DONE) https://github.com/jsreport/jsreport-xlsx/issues/32 
13. (DONE) jsreport core should resolve data dir and tempdir relatively to the app folder (or cwd?) if the value is relative

**Comment by bjrmatos** [comment]
> check if the phantomjs 2.5 is finally stable enough to be the default one

seems like it will never be stable 😆 [the project doesn't have maintenance right now](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), so i guess that a better plan will be to look at [headless chromium](https://www.chromestatus.com/features/5678767817097216) when it gets stable, and try to make a recipe extension with it

**Comment by pofider** [comment]
12. Use POCO names. Like `electronPdf`, `phantomPdf` instead of the name with dash `phantom-pdf`.  It is hard to integrate such attributes to another language which doesn't support the `-` in property name.

**Comment by bjrmatos** [comment]
13. change month format of cron expressions to match the standard/most used format (scheduling) jsreport/jsreport-scheduling#7

**Comment by pofider** [comment]
I start to develop [here](https://github.com/jsreport/jsreport/blob/2.0.0-beta/v2.md) document describing some aspects of v2.

**Comment by pofider** [comment]
Just to remind, the recipes should use `reporter.tempAutoCleanupDirectory` instead of `reporter.tempDirectory`.

**Comment by pofider** [comment]
Right now we share some configs across the extensions. Like `xlsx` or `phantom`. We should likely split this and duplicate this to make it more clear.

**Comment by pofider** [comment]
The v2 beta is now published - https://jsreport.net/blog/jsreport-v2-beta

We will now give some time to public testing and evaluate if there is something more we would like to push into final v2.

**Comment by bjrmatos** [comment]
> Is there any point that express extension starts by default on a random port? I would rather prefer 5488 I think.

i don't think there is anything special about the random port, so changing the default makes sense

**Comment by pofider** [comment]
The v2 is now released.
https://jsreport.net/blog/jsreport-v2-released
