### ISSUE TITLE
Error occured - Error during rendering report: findDataItem(...).then is not a function

### ISSUE THREAD

**Issue by zeshanhassan** [jsreport/jsreport#275]
I am trying to request report server 1.5.1 (recently installed) its throwing this error.
previously it was working fine for 1.09.
![report](https://cloud.githubusercontent.com/assets/3735174/24396298/1c69e450-13bc-11e7-8e6b-539b49155c9f.png)

**Comment by pofider** [comment]
Thank your filling the issue.

It seems that the server is receiving rendering request in format `{ template: { dataJson: ??, .... } }`
Is it right? What you send to `api/report`?
The dataJson property inside template is not valid. I believe there was a back compatibility hack in this which was removed not long ago.

In every case, you should send data as separate property in request like
`{ template: {...}, data { propA: ... } }`

We need to fix this error message, so I mark this as bug.

**Comment by zeshanhassan** [comment]
Thanks a lot. its working now. Basically we are sending data in template object but in newer version. now data is in siblings level to template

**Comment by bjrmatos** [comment]
fixed in this [commit](https://github.com/jsreport/jsreport-data/commit/2d9ab1cc55fd727745dce341eee269579bdf1ee7)
