### ISSUE TITLE
jsreport init not working

### ISSUE THREAD

**Issue by vinaykharecha** [jsreport/jsreport#276]
OS: Ubuntu xenial
NPM Version: 3.10.8
Node Version: 6.9.0

I simply installed jsreport-cli with command `sudo npm install jsreport-cli -g` after doing that whenever i run `jsreport init` or `sudo jsreport init` it gives me following error

> /usr/bin/env: ‘node\r’: No such file or directory

and this is not case with my machine only; issue can be seen in other machine as well.

**Comment by pofider** [comment]
Thank you
I can replicate this and searching for fix.

Quick workaround is to skip using jsreport cli and install/start in old fashion way
```sh
npm install jsreport
node node_modules/jsreport --init
npm start
```

**Comment by vinaykharecha** [comment]
Thank you @pofider, quick workaround is working.
I appreciate your help.

**Comment by pofider** [comment]
Thank you for pointing it out, many people would hit this soon....

The problem was wrong (windows) line endings in the `jsreport-cli`. 
This is now fixed in the latest package delivered through `npm install jsreport-cli -g`
