### ISSUE TITLE
can't use jsreport in node 0.10.48 and npm2

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#279]
there were some issues when installing jsreport using npm2 (missing dependencies):

- [fix dependencies in studio](https://github.com/jsreport/jsreport-studio/commit/98e16691d4c9377474bedeb14a76c293a436fc6c)
- [fix dependencies in fop-pdf](https://github.com/jsreport/jsreport-fop-pdf/commit/ec00e59135b4d6b9c97e214d19af167a2a7c472d)

and the following prevents using jsreport in node 0.10.48:

- `jsreport-xlsx` is using `file-type` as a dependency, this dependency has dropped support for node <4 in its release `4.x.x`, this problem can be solved downgrading `file-type` to `3.x.x`

i will let the last problem to @pofider (just because him has upgraded that dependency before and maybe there was a reason for that) for the last step to do before a new jsreport release

**Comment by pofider** [comment]
I'm not aware aware of any particular reason. I was likely just updating all dependencies.
Please downgrade it and add travis test which catch this.

**Comment by bjrmatos** [comment]
ok, test added and dependency downgraded, ready for new bug fix release 👍

**Comment by bjrmatos** [comment]
fixed already
