### ISSUE TITLE
Error: Template must contains _id, shortid or content attribute.

### ISSUE THREAD

**Issue by wandiong** [jsreport/jsreport#284]
hi 

I've eccountered this error

> Error: Template must contains _id, shortid or content attribute.

why it happens?

i tried adding shortid as it asked to template

and it returning

> Unable to find specified template or user doesnt have permissions to read it: H1SRTVmRe

anybody know more or less why this happened?

thanks before :)

**Comment by pofider** [comment]
Please share your request body and headers. Do you have authentication enabled in jsreport config?

**Comment by wandiong** [comment]
![capture](https://cloud.githubusercontent.com/assets/16790405/25119562/ec2e377a-2444-11e7-9033-4e43a1a4cdfa.PNG)
hi @pofider , this is what i got after i forced send response . 

is it what you needed?

and I'm not enabling authentication, because i've created same config before in same module. but it works great

thanks for helping :)

**Comment by pofider** [comment]
I see on the image the headers are fine, but I'm missing the request body there.

**Comment by wandiong** [comment]
it appears that re-config it made the document is worked. thank's a lot for helping me` +1 :D

https://jsfiddle.net/j2ocs1uq/

**Comment by pofider** [comment]
Ok, glad it worked in the end.

**Comment by ggoforth** [comment]
I'm getting this error just running the example directly as it is from the home page.  Do I need to add additional config to make the example on the homepage run?  My server just looks like:

```
const http = require('http');
const http = require('http');
const http = require('http');
const jsreport = require('jsreport');

http.createServer((req, res) => {
  jsreport.render("<h1>Hello world</h1>").then((out)  => {
    out.stream.pipe(res);
  }).catch((e) => {
    res.end(e.message);
  });

}).listen(1337, '127.0.0.1');
```

**Comment by bjrmatos** [comment]
@ggoforth can you please update the render call to:

```js
jsreport.render({
      template: {
        content: "<h1>Hello world</h1>",
        engine: 'handlebars',
        recipe: 'chrome-pdf'
      }
    })
```

i think we need to update docs, can you please tell me where did you see that example¿

**Comment by wibobm** [comment]
The example is still bad.  https://jsreport.net/learn/pdf-reports-in-nodejs

**Comment by bjrmatos** [comment]
@wibobm thanks for the [PR](https://github.com/jsreport/docs/pull/23) fixing the docs
