### ISSUE TITLE
I can not add  font-awesome icons

### ISSUE THREAD

**Issue by maikolestevez** [jsreport/jsreport#289]
Thanks to create jsreport is a greate project and helping me a lot.
Im trying to add icons to my project using this link https://jsreport.net/blog/font-awesome-icons-in-reports and using this code

```
<style>

        {#asset font-awesome.css}

        .fa {
           font-family: 'FontAwesome2' !important; 
        }

        @font-face {
          font-family: 'FontAwesome2';
          src: url({#asset fontawesome-webfont.woff @encoding=dataURI});
          format('woff');
        }
    </style>
```
Any icon apear on my report im testing with jsreport studio locally.
I just want you to give me some advice, i have working with it all day

**Comment by pofider** [comment]
Try to render html recipe and inspect the output with browser dev tools to find out what is wrong.

**Comment by maikolestevez** [comment]
This is what im getting from devtool.
![devotools](https://cloud.githubusercontent.com/assets/8959257/25765202/c9fb0c6e-31b9-11e7-8374-9e012c3b70cd.jpg)

**Comment by pofider** [comment]
Where is the js syntax error coming from? You should remove everything from the page and try only the font awesome style and testing element.

**Comment by maikolestevez** [comment]
I create a new template with  this code 
```

<html>

<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
   
    <style>
        {#asset font-awesome.min.css}

        .fa {
           font-family:'fontawesome-webfont'!important; 
        }
        @font-face {
          font-family:'fontawesome-webfont';
          src: url({#asset fontawesome-webfont.woff @encoding=dataURI});
         format('woff');
        }

    </style>
</head>

<body>

<h2><i class="fa fa-user fa-4x"></i>Maikol Estevez</h2>

</body>



</html>
```
i got this "fontawesome-webfont" when  select the button  copy the embeding code to the clipboard on the file .woff. I still cant see the icon.

**Comment by maikolestevez** [comment]
I solved it, my problem was that i was using an old  versio, Font Awesome 3.2.1, I download 4.7 and it works.

Thanks for your help!!!
