### ISSUE TITLE
saving requests logs in settings collection reaches the 16 MB limits of mongodb

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#290]
it seems that when [using mongodb store we are saving request logs constantly until the limit of 16mb per record is reached in mongodb](https://forum.jsreport.net/topic/90/mongodb-write-error-when-i-m-not-writing-anything-to-mongo/2).

we need to inspect how we are saving the request logs when using mongodb to ensure that we are not doing something bad.

detected version of jsreport with the problem: 1.4.0

**Comment by pofider** [comment]
The solution should be likely just to trim the log messages to specific maximum size.

- maximum 5 number of request logs stored (already done)
- maximum 500 number of log lines per request
- trim the text and all the rest log lines if accumulated total request log bytes > 500KB

https://github.com/jsreport/jsreport-studio/blob/master/lib/requestLog.js#L19
