### ISSUE TITLE
creating default express app multiple times when starting

### ISSUE THREAD

**Issue by dan-goodson** [jsreport/jsreport#292]
I've had jsreport up and running a few times, but today when starting it, i'm getting the following.

![image](https://cloud.githubusercontent.com/assets/20187766/25957924/5084bf4e-3667-11e7-8b42-bbb8b1528dba.png)

It tries to start the express app a couple more time before failing. I've tried a different port but have the same trouble.

**Comment by pofider** [comment]
Don't you have `jsreport-express` somehow installed twice in the application folder?
Can you try to search for `jsreport-express` there?

If it is there only once, it could help to delete this folder
`c:\Users\DanGoodson\AppData\Local\Temp\jsreport-temp`

**Comment by dan-goodson** [comment]
Thanks, deleting the jsreport-temp folder worked
