### ISSUE TITLE
[page number] how can I exclude some pages from paging list

### ISSUE THREAD

**Issue by wandiong** [jsreport/jsreport#293]
hi

i have a question

for paging part. i found out that it will page all of the current listed page on PDF (i'm using phantom pdf and handlebars btw)

so. how can i made something like this?

Hello from Page 1 // exclude this

Hello from Page 2 // page 1/1

Hello from Page 3 // exclude this

thanks and much appreciated for helping !! 👍

**Comment by bjrmatos** [comment]
hmm do you mean how to exclude some pages for printing the page number in report, right?

i'm not sure how to make your case work (it seems like it is not possible natively) but i guess that you will need to have a list of pages to ignore and when the time to print the page number comes you will need to check the list and decide it should be printed or not. 

what it is sure is that your case would require a lot of conditions in your side, you just need to prepare some logic, sorry for not being able to help you more on this.

also, try to post questions like this in our official forum https://forum.jsreport.net/
