### ISSUE TITLE
jsreport config shortcuts

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#296]
Some configuration options spawns multiple properties/extensions which makes it complex to set up correctly. 

For example, it is common to allow to jsreport to access local files, however now user needs to edit the phantom-pdf config, assets config, scripts config, tasks config and possibly other places. 

**It could be done with just single root config `allowLocalAccess: true`.**
(I would even like that this is the default in the release 2.)

The next example which requires to be set on multiple places is the strategy we use for the rendering. If you want to run in http server, you need to change tasks, phantom and electron configs.

**It could be done with just single root config `executionStrategy: http-server`**

The last example is if the jsreport should run in "stateless" mode. This requires to change the connectionString, logs and fs store.

**It could be done with just single root config `stateless: true`**

I don't  want to make it even more complicated with new options. I see significant need only for the first one. Maybe we have still time for making this.  Just want to share my thoughts for now.

UPDATE: It would be up to the extensions to respect these shortcuts.

**Comment by saad749** [comment]
The shortcuts make sense. I will prefer to be able to change the executionStrategy in just one place, than in multiple files.

**Comment by pofider** [comment]
So far we introduced global `allowLocalFilesAccess`  config shortcut in v2.
We will wait some time for feedback and reevaluate later others.

**Comment by pofider** [comment]
The `allowLocalFilesAccess ` is great. The `executionStrategy` isn't needed now because jsreport 3 uses just worker threads. The `stateless` seems uncommon. Closing.
