### ISSUE TITLE
Problems with long tables

### ISSUE THREAD

**Issue by samir-kamble** [jsreport/jsreport#297]
Hello,

I am facing 2 problems in generation of pdf reports out of long tables.

1. My rows are getting cut in between hence the data also gets cut in half on 2 pages.

![table row cut](https://cloud.githubusercontent.com/assets/12523579/26587839/204f4ac4-4571-11e7-8277-a01a4914c414.png)

2. I want to repeat table headers on every page for long tables but headers are overlapping rows.

![header overlaps](https://cloud.githubusercontent.com/assets/12523579/26588058/d11aa47a-4571-11e7-95d6-8b0401b3d9a0.png)

Can you please suggest any workaround for the same?

JSReports version : 1.4.0
Phantom : 1.9.8
Handlebars for HTML markup

**Comment by bjrmatos** [comment]
hi! seems like it is a bug in phantomjs, unfortunately we can't do nothing there, but i'm sure there must be some css or markup that you need to apply as a workaround, my best advice would be to try to search for similar problems in phantomjs issues or in stackoverflow

**Comment by pofider** [comment]
Unfortunately there is no unique workaround. You need to try them on your own. 
Start with searching something like "phantomjs table header overlapping"

Maybe this links would help
https://github.com/jsreport/jsreport/issues/93
https://github.com/ariya/phantomjs/issues/14898
https://github.com/ariya/phantomjs/issues/10927

**Comment by pofider** [comment]
Closing as duplicate to https://github.com/jsreport/jsreport/issues/93

**Comment by samir-kamble** [comment]
Well Found a solution finally... Its 
> border-collapse: collapse;
if you have it in css for tables remove it. And watch it working fine.

**Comment by pofider** [comment]
Thank you for sharing your solution.
