### ISSUE TITLE
how to enable Authentication in jsreport

### ISSUE THREAD

**Issue by navneetccna** [jsreport/jsreport#30]
Install latest jsreport 

after that i tried to enable authentication on my local server following instruction given on http://jsreport.net/learn/authentication

but not able to get login screen

my prod.config.json is 

{
    "authentication" : {
        "cookieSession": {
            "secret": "dasd321as56d1sd5s61vdv32",
            "cookie": {
                "domain": "192.168.177.10"
            }
        },
        "admin": {
            "username" : "nav",
            "password": "test123N"
        }
    },
    "cookieSession": {
        "secret": "dasd321as56d1sd5s61vdv32",
        "cookie": { "domain": "192.168.177.10" }
    },
    "certificate": {
        "key": "certificates/jsreport.net.key",    
        "cert": "certificates/jsreport.net.cert"
    },
    "connectionString": { "name": "neDB" },

    "httpPort": 3000,
    "blobStorage": "fileSystem",
    "cluster": {
      "numberOfWorkers": 2,
      "enabled":  false
    },
    "phantom": {
        "numberOfWorkers" : 2,
        "timeout": 180000
    },
    "tasks": {
        "numberOfWorkers" : 2,
        "timeout": 10000
    },
    
    "tempDirectory": "/root/node_modules111/",
    "rootDirectory": "/root/node_modules/",
    
    //"extensions": ["excel-parser", "express", "templates", "html", "phantom-pdf", "scripts", "data", "images", "statistics", "reports", "childTemplates", "sample-template", "authentication"]
}

**Comment by pofider** [comment]
This looks like an orphan. Closing. Feel free to reopen when having issues still.
