### ISSUE TITLE
Docker: jsreport is not running

### ISSUE THREAD

**Issue by myaskevich** [jsreport/jsreport#304]
Hi,

I'm trying to run a jsreport docker image, and the server is not starting.

When running `docker exec jsreport ps aux`, there's not even `node` process running.
Logs from `docker logs -f jsreport` are empty.

The container doesn't exit, nor it is operational.

**Comment by pofider** [comment]
did you run something like this before?

```
docker run -p 80:5488 jsreport/jsreport
```

**Comment by myaskevich** [comment]
Yes, I ran `docker run -d -ti --name jsreport -v /data/jsreport:/jsreport -p 5488:5488 jsreport/jsreport`

**Comment by myaskevich** [comment]
I'm looking into default Dockerfile and it seems to me that it has something to do with permissions.

**Comment by pofider** [comment]
Try it without `-ti`. It works for me then.

**Comment by myaskevich** [comment]
@pofider You're right!
Thanks for the help!
