### ISSUE TITLE
i have error when start npm using jsreport-core

### ISSUE THREAD

**Issue by mahermagdy** [jsreport/jsreport#305]
@pofider  I follow the example in docs also for your info I am using vs code with node js to apply jsreport-core
my books.js   as the follow

var jsreport = require('jsreport-core')({ tasks: { allowedModules: '*' } })
jsreport.use(require('jsreport-phantom-pdf')())
jsreport.use(require('jsreport-jsrender')())
jsreport.use(require('jsreport-templates')())
var fs = require('fs');
var express = require('express');
var router = express.Router();

jsreport.init().then(function() {
    return jsreport.render({
        template: { content: '<h1>Hello {{:foo}}</h1>',
            helpers: "function jquery() {" +
                "var fs = require('fs');" +
                "var path = require('path');" +
                "return fs.readFileSync(path.join(__rootDirectory, 'jquery.js'));" +
                "}",
            engine: 'jsrender',
            recipe: 'phantom-pdf'
        },
        data: {
                foo: "world"
        }
    }).then(function(resp) {
        //prints pdf with headline Hello world
        const pdf = resp.content.toString();
        console.log(pdf);
        fs.writeFileSync(output_fn, pdf);
        console.log("Saved PDF content to " + output_fn);
    });
}).catch(function(e) {
    console.log(e)
})

**app.js   as follow**

var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

var index = require('./routes/index');
var users = require('./routes/users');
var books = require('./routes/books');
var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', index);
app.use('/users', users);
app.use('/books', books);
// catch 404 and forward to error handler
app.use(function(req, res, next) {
    var err = new Error('Not Found');
    err.status = 404;
    next(err);
});

// error handler
app.use(function(err, req, res, next) {
    // set locals, only providing error in development
    res.locals.message = err.message;
    res.locals.error = req.app.get('env') === 'development' ? err : {};

    // render the error page
    res.status(err.status || 500);
    res.render('error');
});

module.exports = app;

**pakage.jsone**
{
  "name": "app",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.17.1",
    "cookie-parser": "~1.4.3",
    "debug": "~2.6.3",
    "express": "~4.15.2",
    "jade": "~1.11.0",
    "jsreport-core": "^1.3.2",
    "jsreport-jsrender": "^1.0.2",
    "jsreport-phantom-pdf": "^1.4.5",
    "jsreport-templates": "^1.1.1",
    "morgan": "~1.8.1",
    "request": "^2.81.0",
    "requier": "0.0.1",
    "serve-favicon": "~2.4.2"
  }
}

# **please help me to complete the example ,when start npm  ihave this error**

G:\jsreport\jsreport-core\app\node_modules\express\lib\router\index.js:458
      throw new TypeError('Router.use() requires middleware function but got a ' + gettype(fn));
      ^

TypeError: Router.use() requires middleware function but got a Object
    at Function.use (G:\jsreport\jsreport-core\app\node_modules\express\lib\router\index.js:458:13)
    at EventEmitter.<anonymous> (G:\jsreport\jsreport-core\app\node_modules\express\lib\application.js:220:21)
    at Array.forEach (native)
    at EventEmitter.use (G:\jsreport\jsreport-core\app\node_modules\express\lib\application.js:217:7)
    at Object.<anonymous> (G:\jsreport\jsreport-core\app\app.js:27:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (G:\jsreport\jsreport-core\app\bin\www:7:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Module.load (module.js:487:32)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (G:\jsreport\jsreport-core\app\bin\www:7:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm ERR! node v6.11.0
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! app@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\jsreport\jsreport-core\app\npm-debug.log

**Comment by pofider** [comment]
You have way too much stuff in your sample. Please make it small as possible so I can look at it. It is not even clear the problem actually comes from jsreport. Also try to use markdown formating in your sample, this is hardly readable.

**Comment by mahermagdy** [comment]
@pofider 
thanks for your reply I am solving the above error its something in my JS code and the example is working fine but I need your feedback if we need to add router.get

router.get('/', function(req, res, next) {
    // res.sendFile(path, "./bin");
    //res.download(path: "./bin", filename: "test.pdf");
   // res.send('hello world');

});

**Comment by pofider** [comment]
Hm. I don't understand what you are actually asking for.

Closing this because the original problem is gone.

**Comment by mahermagdy** [comment]
ok thank you
