### ISSUE TITLE
Error while printing text

### ISSUE THREAD

**Issue by danieloquendo** [jsreport/jsreport#308]
![image](https://user-images.githubusercontent.com/12579110/27929408-760883b4-6258-11e7-9fb7-3910cd68b6fb.png)

Centos
Node v6.10.3

Any idea what could be the issue here?
Thank you.

**Comment by bjrmatos** [comment]
you `Centos` installation is probably missing some packages that phantomjs uses, try running these commands `sudo yum install -y fontconfig` and `sudo yum install -y freetype`, that should be enough to solve your problem, if your problem persist try to search [phantomjs issues](https://github.com/ariya/phantomjs), there you probably will see that there is more people with the same problem and with more detailed instructions.

(similar problem reported before: https://forum.jsreport.net/topic/175/phantom-pdf-renders-only-black-boxes)

**Comment by pofider** [comment]
This could also help
```
sudo yum install bzip2
sudo yum install libXext  libXrender  fontconfig  libfontconfig.so.1
sudo yum install urw-fonts
```
From https://github.com/jsreport/docs/blob/master/installation/centos.md#fixing-pdf-fonts

**Comment by danieloquendo** [comment]
**thanks for your reply,
This also helped me:**

`sudo yum install libXext libXrender xorg-x11-fonts-Type1 xorg-x11-fonts-75dpi`

**Search sources:**
`yum search <font name>`

**thanks !**
