### ISSUE TITLE
How to get the page count with Electron?

### ISSUE THREAD

**Issue by FernandoAiresCastello** [jsreport/jsreport#309]
I've been building a report in jsreport studio using the Electron engine, in which I need to get the total page count as rendered on PDF. I've tried everything I could possibly think of, but nothing seems to work, I even tried to calculate the page count by dividing the entire document height by the total height of the content that fits in one page, but the results are rather inconsistent. Is there any way to get that information without having to resort to using the Phantom engine?

**Comment by bjrmatos** [comment]
we only have the page count available when the rendering of the report has ended (present in a http response header), but not when report is rendering, unfortunately electron does not expose any functionality to get page number or pages count, so this feature is impossible at this moment.

maybe this [post](https://jsreport.net/blog/phantomjs-pdf-watermark) can help you to get the page count result more consistent when using javascript

**Comment by pofider** [comment]
This seems to be quite consistent

https://playground.jsreport.net/studio/workspace/r1iSgRpIW/4
```html
<script>
    var html = document.documentElement

    var height = Math.max(html.clientHeight, html.scrollHeight, html.offsetHeight )
                       
    var pageSize = 1052
    console.log(document.height)
    var numberOfPages = Math.ceil(height / pageSize)
    var pageCount = document.createElement('h1'); 

    pageCount.innerHTML = numberOfPages;   
    pageCount.style.position = 'absolute';
    pageCount.style.top = 0;
    pageCount.style.left = 300;

    document.documentElement.appendChild(pageCount);
</script>
```
