### ISSUE TITLE
Using html-to-xlsx recipe

### ISSUE THREAD

**Issue by egarciadev** [jsreport/jsreport#31]
Hello,
I have been using jsreport for node js, I wish to use the html-to-xlsx recipe but always get this error:
Recipe html-to-xlsx not found, it was added in the config file in extensions property, there  is a folder named html-to-xlsx too, but no success I cant find the way to generate the report.

Please tellme what is wrong here, I have tested it in windows 7 and ubuntu os

**Comment by egarciadev** [comment]
HI;

Is there some way to work with background-image in jsreport? I need a
watermark image for my report, but no success the image does not display,
Is it another way?

2014-12-03 8:49 GMT-05:00 Jan Blaha <notifications@github.com>:

> Hi, please patience with excel. It is brand new and undocumented so there
> will be issues.
>
> I expect you downloaded latest jsreport and added html-to-xlsx to the
> extensions. The issue you may have is that html-to-xlsx is dependent on
> xlsx recipe and will not work without it. Can you make sure you have also
> xlsx recipe enabled?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsreport/jsreport/issues/31#issuecomment-65408723>.
>



-- 
Eduar Garcia
Ingeniero de Desarrollo
Duana & CIA. LTDA

**Comment by pofider** [comment]
You mean in html-to-xslx recipe right?

Unfortunately it is not currently supported there, but you can submit a feature request issue for it.
The list of currently supported css in html-to-xslx is here http://jsreport.net/learn/html-to-xlsx

**Comment by egarciadev** [comment]
Hi Thanks for the support.

The recipe is phantom-pdf, is another way to make it posible? tks

2015-02-23 9:42 GMT-05:00 Jan Blaha <notifications@github.com>:

> You mean in html-to-xslx recipe right?
>
> Unfortunately it is not currently supported there, but you can submit a
> feature request issue for it.
> The list of currently supported css in html-to-xslx is here
> http://jsreport.net/learn/html-to-xlsx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsreport/jsreport/issues/31#issuecomment-75552018>.
>



-- 
Eduar Garcia
Ingeniero de Desarrollo
Duana & CIA. LTDA

**Comment by pofider** [comment]
Please check this https://playground.jsreport.net/#playground/vBzgj0lrr/1

**Comment by egarciadev** [comment]
Thks, I gonna give ti a try

2015-02-23 10:09 GMT-05:00 Jan Blaha <notifications@github.com>:

> Please check this https://playground.jsreport.net/#playground/vBzgj0lrr/1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsreport/jsreport/issues/31#issuecomment-75558765>.
>



-- 
Eduar Garcia
Ingeniero de Desarrollo
Duana & CIA. LTDA

**Comment by egarciadev** [comment]
Hi how are you doing?

I´m facing a weird error when trying to run my app in a centos 6.6 server
there is it:

[image: Imágenes integradas 1]

the error crash my server and just stop, I have used sudo and root but no
success
 may you tell me some advice

tnks

2015-02-23 12:06 GMT-05:00 Eduar Garcia <desarrollo@duanaltda.com>:

> Thks, I gonna give ti a try
>
> 2015-02-23 10:09 GMT-05:00 Jan Blaha <notifications@github.com>:
>
>> Please check this https://playground.jsreport.net/#playground/vBzgj0lrr/1
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jsreport/jsreport/issues/31#issuecomment-75558765>.
>>
>
>
>
> --
> Eduar Garcia
> Ingeniero de Desarrollo
> Duana & CIA. LTDA
>



-- 
Eduar Garcia
Ingeniero de Desarrollo
Duana & CIA. LTDA

**Comment by pofider** [comment]
The image is not displayed...

**Comment by egarciadev** [comment]
Ok, here again

2015-05-27 1:15 GMT-05:00 Jan Blaha <notifications@github.com>:

> The image is not displayed...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsreport/jsreport/issues/31#issuecomment-105771420>.
>



-- 
Eduar Garcia
Ingeniero de Desarrollo
Duana & CIA. LTDA

**Comment by egarciadev** [comment]
Hi:

I have may express server with cluster modulo of node js, when I start up
my server I got this in jsreport


[image: Imágenes integradas 1]

its happening when I run in child workers here:

if (cluster.isMaster) {

    var numCPUs = require('os').cpus().length;

    for (var i = 0; i < numCPUs; i++) {
        cluster.fork();
    }

    cluster.on('exit', function(worker, code, signal) {
        console.log('worker ' + worker.process.pid + ' died');
        //se reemplaza el worker que acaba de caer
        cluster.fork();
    });

} else {


    var app = express();
    var server = app.listen(G.settings.server_port);
    var io = require('socket.io').listen(server);
    var container = intravenous.create();


    /*========================================
     ==========================================*/
    jsreport.bootstrapper({
        logger: {providerName: "console"}
    }).start().then(function(bootstrapper) {
        G.jsreport = bootstrapper;
    });


its no happen when I dont use cluster, do you may help me with some advice?


Tks

2015-05-27 7:40 GMT-05:00 Eduar Garcia <desarrollo@duanaltda.com>:

> Ok, here again
>
> 2015-05-27 1:15 GMT-05:00 Jan Blaha <notifications@github.com>:
>
>> The image is not displayed...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jsreport/jsreport/issues/31#issuecomment-105771420>.
>>
>
>
>
> --
> Eduar Garcia
> Ingeniero de Desarrollo
> Duana & CIA. LTDA
>



-- 
Eduar Garcia
Ingeniero de Desarrollo
Duana & CIA. LTDA

**Comment by pofider** [comment]
You probably need to submit your comments through github.com website otherwise I still don't see the images you are including.

I have tried your code and it seems to work for me. Do you have in jsreport config different port than the express app you are starting? Note that if you want to attach jsreport to the existing express application your bootstrapper's options should look like 

```js
jsreport.bootstrapper({
        logger: {providerName: "console"},
        express: { app: app }
    }).
```

**Comment by egarciadev** [comment]
Allright gonna try that way, tks

2015-06-09 3:08 GMT-05:00 Jan Blaha <notifications@github.com>:

> You probably need to submit your comments through github.com website
> otherwise I still don't see the images you are including.
>
> I have tried your code and it seems to work for me. Do you have in
> jsreport config different port than the express app you are starting? Note
> that if you want to attach jsreport to the existing express application
> your bootstrapper's options should look like
>
> jsreport.bootstrapper({
>         logger: {providerName: "console"},
>         express: { app: app }
>     }).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsreport/jsreport/issues/31#issuecomment-110269011>.
>



-- 
Eduar Garcia
Ingeniero de Desarrollo
Duana & CIA. LTDA
