### ISSUE TITLE
pdf is blank with simple HTML

### ISSUE THREAD

**Issue by shadyyehia** [jsreport/jsreport#311]
What is the problem with this code guys? I can't get a PDF from this simple HTML.

module.exports = function (callback) {
    var jsreport = require('jsreport-Core')();

    jsreport.init().then(function () {
        return jsreport.render({
            template: {
                content: '<h1>Hello </h1>',
                engine: 'jsrender',
                recipe: 'phantom-pdf'
            }
        }).then(function (resp) {
            callback(/* error */ null, resp.content.toJSON().data);
        });
    }).catch(function (e) {
        callback(/* error */ e, null);
    })
};

Thanks  so much for your answers.
Shady

**Comment by pofider** [comment]
This jsreport code is fine, you likely do something wrong with the output
```
callback(/* error */ null, resp.content.toJSON().data);
```

**Comment by bjrmatos** [comment]
closing the issue as it seems like there is no problem.. feel free to post more details if there is a issue.
