### ISSUE TITLE
Making a render request including inline assets through the API

### ISSUE THREAD

**Issue by miqid** [jsreport/jsreport#313]
Hello,

I'm trying to work out if `jsreport` supports making REST-based API render requests that support the inclusion of assets inline (i.e. a CSS file using UTF-8 encoding).

I reviewed the [documentation for assets][1] and tried a few combinations of including an `assets` property into my render requests, but I wasn't able to get the rendered report to pull the data through. For example, I tried the following:

```js
{ data: '...', template: { assets: { css: '...' } } }
{ data: '...', template: { ... }, assets: { css: '...' } }
```
```html
<style>{#asset css @encoding=utf8</style>
```

So, this has left me wondering if requests with inline assets are even supported.

I basically have a stateless `jsreport` server which I'm hitting to render reports, so it's conducive to my current design if I could include assets inline with render requests.

[1]: https://jsreport.net/learn/assets

**Comment by pofider** [comment]
You are right, this is currently not supported. 

Isn't it anyway more straight forward to ignore the assets extension and send the assets' content through data or directly in the template?

```
{ data: { assets: { css: 'foo'} }
```

```
<style>{{{assets.css}}}</style>
```

**Comment by miqid** [comment]
@pofider, thanks for the swift reply. :smiley:

Yes, as you say, shoving assets into the `data` property is an easy solution to making them available when rendering via API requests.

However, given the state of the codebase I'm wrestling with, I think I might just use a pre-processor to transplant CSS and other assets directly into a compiled form of the template to then pass along in my request. Thanks for the suggestion though!

Please feel free to close off this issue if it's no relevant to the `jsreport` road map.

**Comment by pofider** [comment]
Yes, I think you get better control with your pre-processing or you can simply use the data.

The assets extension is not so much useful in "stateless" scenario so we won't add support for loading assets directly from the request. At least not at this moment.
