### ISSUE TITLE
Docker configuration with Kubernetes

### ISSUE THREAD

**Issue by cesartl** [jsreport/jsreport#314]
Kubernetes does not support special characters like `:` or `.` in the environment name variables.

This means environment variable like `connectionString:name` cannot be used.

Would it be possible to have an alternative way of setting these? Ideally `connectionString_name`

**Comment by pofider** [comment]
Yes, this already works.
Both `:` as well as `_` can be used as separators.

**Comment by cesartl** [comment]
if this is the case can we update the documentation for the docker configuration so this is known?

**Comment by pofider** [comment]
Yes. Thank you. 

Now the docker readme is updated.

**Comment by cesartl** [comment]
That was quick!

Thanks a lot
