### ISSUE TITLE
[Guidance] Inserting html and XSS

### ISSUE THREAD

**Issue by cesartl** [jsreport/jsreport#316]
I would like my web application (React.js) to show the output of reports in html.

I can make a call to the reporting engine and get back some html. Now I need to insert this html into my page. In react I found this way:

```
<div dangerouslySetInnerHTML={{ __html: this.state.html }}>
</div>
```

As the name suggests `dangerouslySetInnerHTML` is not really recommended due to risk of XSS attacks.

Do you think this approach is sensible? If the endpoint producing the html is mine then I guess this is fine but I would like to know if this is the way most people tackle this problem.

**Comment by bjrmatos** [comment]
> Do you think this approach is sensible? If the endpoint producing the html is mine then I guess this is fine but I would like to know if this is the way most people tackle this problem.

we are using React a lot (even in jsreport code base), so if you ask me i can recommend that `dangerouslySetInnerHTML` it is the better approach to show html output from jsreport 👍. 

if you need better isolation you can also try to render an iframe in your React component and then get a ref to that iframe node, then on every jsreport render just update the iframe content.

**Comment by cesartl** [comment]
OK thanks for the tips
