### ISSUE TITLE
Docker environment variable set array value

### ISSUE THREAD

**Issue by cesartl** [jsreport/jsreport#318]
With the docker image, how can one set a configuration property that is an array? For example:

```
scripts.allowedModules
````

I tried

```
scripts_allowedModules=['http']
```

```
scripts_allowedModules=http
```

but none of them work. 

In js report I got the error

```
inputs.allowedModules.filter is not a function
```

So I'm guessing I'm replacing the property by a string instead of an array.

Once I know how to do that I can raise  PR to change the documentation and explain how to do that

**Comment by pofider** [comment]
I see, thank you. So far I don't see a solution in the [nconf](https://github.com/indexzero/nconf) which is used for parsing and merging configs.

However don't you anyway want to set `scripts_allowedModules=*`? This is common if you have control over the report templates you run.

**Comment by cesartl** [comment]
yes that's a good idea.

**Comment by bjrmatos** [comment]
if it helps in something i usually do this from the command line when i want array values in config:

```
jsreport start --scripts.allowedModules "" --scripts.allowedModules http
```

(but not sure if docker config take duplicate keys and make values as arrays automatically)

**Comment by pofider** [comment]
This is probably not possible when dealing with environment variables...
But good catch.

**Comment by pofider** [comment]
We now automatically convert configs passed through environment variables into correct data types.
This can now be used with v2
```
extensions_scripts_allowedModules=request,http
```

https://jsreport.net/blog/jsreport-v2-released
