### ISSUE TITLE
Update the docker images

### ISSUE THREAD

**Issue by notatestuser** [jsreport/jsreport#320]
Would you mind updating the images in the Docker Hub? I \*think\* they were built using the old scripts that produced larger images. Thanks!

**Comment by bjrmatos** [comment]
yes, i think the plan is to update the images in docker hub when releasing jsreport v1.8.0, which should be ready in the following days.

**Comment by drmikecrowe** [comment]
@bjrmatos will this include a fix for https://github.com/jsreport/jsreport/issues/312?

**Comment by bjrmatos** [comment]
@drmikecrowe yes, i think so, we have the cause of the bug, so that error should be solved in the next release.

**Comment by pofider** [comment]
Released in 1.8.1
