### ISSUE TITLE
XLSX with beforeRender() script throws an error

### ISSUE THREAD

**Issue by joshplaetzler** [jsreport/jsreport#321]
When Rendering a XLSX recipe with data from mssql I get this error

> Error occured - Error during rendering report: Cannot read property 'xl/worksheets/sheet1.xml' of undefined Stak - TypeError: Cannot read property 'xl/worksheets/sheet1.xml' of undefined at Object.add (evalmachine.:176:42) at Object. (evalmachine.:406:17) at Object.eval (eval at createFunctionContext

I have my linked script set up to load data. example:

```
var sql = require('mssql');
var config = {
    "user": "jsreport",
    "password": "password",
    "server": "janblaha-PC\\SQLEXPRESS",
    "database": "northwind"
}

function beforeRender(done) {
    sql.connect(config).then(function() {
        var req = new sql.Request();
        return req.query('select count(*) as Count, ShipCountry  from Orders group by ShipCountry').then(function(recordset) {
            request.data = { countries: recordset };
            done();
        });
    }).catch(done);
} 
```

I can load data into pdf, html, and even html-xlsx with no error. I tried to use just a basic sheet that I can get to load without the script, shown below.  Wondering if I need to load my data a different way or if what i'm trying to do is not possible. I couldn't find anything about loading data from msql in the documentation for xlsx recipes.

```
{{#xlsxAdd "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row"}}
    <row>
        <c t="inlineStr"><is><t>Hello world</t></is></c>
        <c><v>11</v></c>
    </row>
{{/xlsxAdd}}

{{{xlsxPrint}}}
```
--

**Comment by pofider** [comment]
Could you please try this change?

```js
//old
request.data = { countries: recordset };
//new
Object.assign(request.data, { countries: recordset })
```
The recipe is passing some additional data to the templating engines processing and you are overwriting them.

**Comment by joshplaetzler** [comment]
That did the trick Thank you so much.

**Comment by pofider** [comment]
Please keep this open, just to remind me I need to fix example in mssql readme. I'll close it afterwards.
