### ISSUE TITLE
JS Report timing out.

### ISSUE THREAD

**Issue by NalinSajwan** [jsreport/jsreport#322]
Hi,

I was trying out jsreport for generating xlsx files and followed instructions for installing it in on a remote ubuntu machine by following [these steps](https://jsreport.net/blog/jsreport-behind-nginx-on-ubuntu "Ubuntu installation guide.").

After installation i was able to generate xlsx files out of smaller data-sets and it worked pretty well. But when i increased data-set size to array of json about 57638 in length and around 71 MB file size or more, i started facing this issue (stated below) -

```
Error when processing render request Error during rendering report: Timeout error during executing script Error: Timeout error during executing script
    at null._onTimeout (node_modules/jsreport/node_modules/jsreport-core/node_modules/script-manager/lib/manager-processes.js:24:8)
    at Timer.unrefdHandle (timers.js:318:16) requestId=1
```

I then updated my conf file settings to increase `scripts > timeout` and tried different values of `tasks > strategy` - 

```
"tasks": {
	"strategy": "in-process",
	"timeout": 50000,
	"allowedModules": []
},
"scripts": {
	"allowedModules": [],
	"timeout": 50000
}
```
After trying to change both settings - `scripts > timeout` and `tasks > strategy` i was still stuck at same error. So, i opened up file path -> `jsreport/node_modules/jsreport-core/node_modules/script-manager/lib/manager-processes.js`, error was getting thrown from this section of code - 

```
var timeout = setTimeout(function () {
	worker.kill()
	cb(new Error('Timeout error during executing script'))
}, options.timeout || this.options.timeout)
```
For 2nd parameter of `setTimeout` value was --> `options.timeout || this.options.timeout`, console.log for both values resulted in : `options.timeout -> undefined` and `this.options.timeout -> 10000 (10 seconds)`.

When i set value of  `setTimeout` 2nd parameter to **50000** report started generating and total time it took was about 40000 ms to provide me a document link for -> ms office online.

I didn't had much time to look at why this value of 10000 ms was not getting override by my conf file settings, but because of this short patch i was able to generate excel out of bigger size data.

PS : I will be waiting for a proper fix regarding this issue.

**Comment by pofider** [comment]
Thank for your report. Great that you have spent some time and done your investigation before posting here.

Please check that you edit the correct config file. The name of the config file based on `NODE_ENV` environment variable is printed out in the first lines of the logs. 

I verified that setting the `tasks,timeout` in config is correctly applied. My guess is that you edit the wrong config.

**Comment by NalinSajwan** [comment]
Hi, thanks for the update 👍.

I was initializing it via forever module by using following commands `forever start server.js --production` but setting was still being picked from `dev.config.json` instead of `prod.config.json`.

After changing `tasks.timeout` in `dev.config.json`, setting is now getting picked from correctly and working without my patch.

Command `npm start --production` picks setting correctly from `prod.config.json`. I will see how to run it with forever module.
