### ISSUE TITLE
JSReport header,and footer placing

### ISSUE THREAD

**Issue by vinithios** [jsreport/jsreport#323]
Hi,
   How to provide header, and footer in a pdf with multiple pages.Anybody have an answer?

**Comment by vinithios** [comment]
Where the footer should be placed in the following code?

code:

     <body>
    <h2>{{header}}</h2>
    <h1>Any company description here</h1>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod .</p>
    
    <p style="margin-top: 100px;">At vero eos et accusam et justo duo dolores et ea rebum.</p>
    <div style='page-break-before: always;'>
        <h2>{{header}}</h2>
        <h1>Any company description here</h1>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod.</p>
        <p style="margin-top: 100px;">At vero eos et accusam et justo duo dolores et ea rebum.</p>
    </div>
  </body>

**Comment by pofider** [comment]
![screen](https://user-images.githubusercontent.com/2041960/29401020-c9328330-832f-11e7-8527-df5fd5301475.png)

The default [phantom-pdf](https://jsreport.net/learn/phantom-pdf) recipe lets you to set the header content through the ui.

**Comment by vinithios** [comment]
{#pageNum} and {#numPages}  are not replaced by numbers in jsreport pdf.Should i include anything??

**Comment by pofider** [comment]
These get replaced only in the header or footer. Not in the content. It is unfortunately phantomjs limitation.

**Comment by vinithios** [comment]
Thanks for your reply.

I don't know how to use header , and footer in local code.
This is my code..I don't whether it's correct or not.If it is wrong what should i do to make it correct?
      <body>
    <div style='text-align:center'>{#pageNum}/{#numPages}</div>
    <h1>Any company description here</h1>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod.</p>
    
    <p style="margin-top: 100px;">At vero eos et accusam et justo duo dolores et ea rebum.</p>
    <span id='pageNumber'>{#pageNum}</span>    
 </body>

**Comment by vinithios** [comment]
I got the way that ,  how to use header and footer. But, still i am struggling on image placing on both header and footer.can you please explain how to place image in header
