### ISSUE TITLE
"jsreport installation not found, installing jsreport latest version now...."

### ISSUE THREAD

**Issue by egodasa** [jsreport/jsreport#326]
![jsreport](https://user-images.githubusercontent.com/9961837/29548538-d712d5ae-872b-11e7-9bbc-860041263c55.jpg)

I have a problem with jsreport. It show a message "jsreport installation not found, installing jsreport latest version now" and there's nothing happen.
Last night it works but today it not works. So I remove it and install it again. But it show that message. I'm trying to search on google but can't find this message anymore on the result.
I have ubuntu and archlinux. But they show same message.
And node version is v6.11.0 and NPM is v5.0.3.
Thx :)

**Comment by pofider** [comment]
How long did you wait before killing the `jsreport init`?

I see that installing `jsreport-cli` took you `75s`. That is like 4x more then usual. Maybe you have slow internet connection at the moment. I believe that installing jsreport afterwards can take even more than 5 minutes on your machine.

**Comment by egodasa** [comment]
I'm just do full update to ubuntu and installing new version of nodejs. Now everything ok again. Jsreport can run again
