### ISSUE TITLE
Enterprise Licensing issue

### ISSUE THREAD

**Issue by jferg-riq** [jsreport/jsreport#327]
There -seems- to be an issue with the enterprise licensing code in 1.8.1; it may be specific to my environment and I've worked around it for now, but wanted to mention it.  

It seems like with the enterprise license, it hangs after writing the license json to disk, and the jsreport.init() promise never returns.   The last message I get is 'Storing license verification information to license.json'.   

If license.json already exists, it works OK.  It was a particular problem for me because I'm working in docker and license.json was not in the docker image, so it was having to create it every time I started the image.  I worked around it by just adding license.json to the docker image, so it's fine now, but thought I'd mention it anyway.

**Comment by pofider** [comment]
Thank you for sharing it.

This was hotfixed 4 days ago in release [1.8.2](https://github.com/jsreport/jsreport/releases/tag/1.8.2)

**Comment by jferg-riq** [comment]
Heh.  *sigh*   That could have saved me several hours yesterday.  :-)

**Comment by pofider** [comment]
Oh. I apologize for that bug.
