### ISSUE TITLE
PDF rendering ++

### ISSUE THREAD

**Issue by yoerivdm** [jsreport/jsreport#328]
Hi, currently looking into JSReports to make it our primary reporting server for html and pdf reports.

As for PDF I have a few questions and enhancements in mind ...
Is there a roadmap for getting a Chrome PDF recipe?

I noticed that PDF handles font-sizes differently than html (phantom, electron), i often use a percentage font on my body to get a base 10px font-size in a browser. This is not the case in PDF so I lower it to for instance 40% to get my desired result.

Electron seems to have a problem with font-sizes containing decimal places ... 1.8rem of a 7px font leaves strange text-rendering. 

My thought here is ...  it would be nice to add a css-post(/pre)-processor to the 'pipeline', like postCSS. With a postCSS extension, I can simply replace all rem or em with px and vice versa, get legacy flex instead of flex (phantomJS) etc.

Just my 2c

**Comment by pofider** [comment]
> Is there a roadmap for getting a Chrome PDF recipe?

It is. We keep an eye on headless chrome. However so far it is basically the same as electron. Both are using the same code on the background. So new recipe is not solving anything as far as I see. We'll anyway bring it soon, but don't expect it to be a game changer.

> My thought here is ... it would be nice to add a css-post(/pre)-processor to the 'pipeline', like postCSS. With a postCSS extension, I can simply replace all rem or em with px and vice versa, get legacy flex instead of flex (phantomJS) etc.

How would you do this? You can currently use [custom script](https://jsreport.net/learn/scripts) and `beforeRender` hook to alter the input template. You could use regexp to replace rem to px here, but not sure if this is what you are looking for.

**Comment by yoerivdm** [comment]
PostCSS offers an extension to replace my used css-vars with their values, also an extension to intelligently replace rem by px, not just a replace but replacing with a calculated value without decimals. I also use auto-prefixer extension to add all different prefixes to the properties that need it etc.

Will look into beforeRender but I don't see how i can modify the css assets in that function ... only when a PDF-recipe is used :-)

Thanks for your fast reply and nice product!

**Comment by pofider** [comment]
Ah ok, I didn't know this tool. This topic is likely the same as this one, please check it out
https://github.com/jsreport/jsreport/issues/300

**Comment by yoerivdm** [comment]
Indeed ... except that I am postprocessing my CSS instead of preprocessing :-)

Differs in how to write css. The first offers a dialect which is then processed into valid css, the latter takes valid css as an input and transforms it to fill gaps in browser-compliancy.

**Comment by pofider** [comment]
Yes, I understand. However both ways should be likely part of the deployment, not the jsreport runtime, as it is mentioned in the linked topic.

**Comment by yoerivdm** [comment]
np, i've read the other issue ... looks sufficient to try that kind of a setup

**Comment by pofider** [comment]
Closing as there is no action needed here. Please open new issues if you have further questions or suggestions.
