### ISSUE TITLE
Offline server

### ISSUE THREAD

**Issue by yoerivdm** [jsreport/jsreport#329]
None of our test, staging and production servers are allowed to access internet resources. 
Is there a way to install JSReport on an offline server? 

Why offline? Simple: security, we aren't allowed to use cloud-services either so a cloud instance is not an option due to sensitive information. I work at a banking institution.

Regards
Yoeri

**Comment by pofider** [comment]
Of course! What kind of issue you have there?

You can simply run installation on the same platform and then copy paste the whole applicaiton.

**Comment by yoerivdm** [comment]
Okay, so, I run npm install jsreports on a clean windows-machine and copy over the folder to an offline server?

**Comment by pofider** [comment]
Yes, it is mentioned in faq
https://jsreport.net/learn/faq#deploy-to-production

I forgot to mention that without additional configuration, you wan't be able to use excel online studio preview. However you can always download the excel result from studio and open it in your excel.

**Comment by yoerivdm** [comment]
damn, looked over it ... should add offline server to the faq topic-title ;-)
we'll try it ... thanks a lot!

**Comment by pofider** [comment]
Haha, yes, probably I should.

No problem, closing this now, feel free to add a comment if you have further questions.
