### ISSUE TITLE
Error during rendering report: Timeout - while rendering xlsx through html-to-xlsx recipe for large data

### ISSUE THREAD

**Issue by parthgandhi7** [jsreport/jsreport#330]
We are using jsreport online paid account for rendering our reports. It was working fine till now. Now for huge data (approx. 4000 rows with each row having around 10 fields) i am getting timeout error as
`Error during rendering report: Timeout` while trying to render xlsx through recipe `html-to-xlsx`. Though rendering pdf works fine (through recipe `phantom-pdf`). I am using `jsrender` as our templating engine.
I am making a rest API call to render the report with the following parameters: 
```
   var requestOpts = {
      method: 'POST',
      uri: {{REPORT_URL}},
      encoding: null,
      body: {
        template: { name: 'SALES.REPORT',
  recipe: 'html-to-xlsx',
  engine: 'jsrender' },
        data: {{huge data}},
        options: {
          'Content-Disposition': 'attachment; filename=' + fileName,
          timeout: 180000
        }
      },
      headers: {
        'content-type': 'application/json',
        'accept-charset': null,
        Authorization: 'Basic ' + {{auth params}}
      },
      json: true,
      timeout: 180000,
      resolveWithFullResponse: true
    }; 

```

The logs on the jsreport dashboard are as follows: 

```
Timeout
Error: Timeout at /usr/src/app/node_modules/phantom-workers/lib/phantomManager.js:117:29 at /usr/src/app/node_modules/phantom-workers/lib/phantomWorker.js:103:20 at Socket. (/usr/src/app/node_modules/phantom-workers/lib/checkPortStatus.js:45:9) at emitOne (events.js:96:13) at Socket.emit (events.js:188:7) at TCP._handle.close [as _onclose] (net.js:497:12)
+0 | Starting rendering request 111889
-- | --
+15 | Rendering template {shortid:4J3trsI-W, recipe:html-to-xlsx,engine:jsrender}
+16 | Inline data specified.
+19 | Resources not defined for this template.
+29 | Starting rendering request 111890
+32 | Starting rendering request 111891
+37 | Starting rendering request 111892
+40 | Rendering template {shortid:V1cp8oLWb, recipe:html,engine:none}
+41 | Inline data specified.
+44 | Rendering template {shortid:EkGIroUbb, recipe:html,engine:none}
+45 | Inline data specified.
+47 | Rendering template {shortid:EJqwSsLWZ, recipe:html,engine:none}
+48 | Inline data specified.
+51 | Resources not defined for this template.
+53 | Resources not defined for this template.
+56 | Resources not defined for this template.
+133 | Rendering engine none
+144 | Rendering engine none
+153 | Rendering engine none
+610 | Taking compiled template from engine cache
+811 | Replaced images []
+812 | Executing recipe html
+812 | Skipping storing report.
+812 | Rendering request finished 111890
+818 | Rendering request 111890 finished in 759 ms
+927 | Taking compiled template from engine cache
+931 | Replaced images []
+931 | Executing recipe html
+932 | Skipping storing report.
+932 | Rendering request finished 111892
+938 | Rendering request 111892 finished in 806 ms
+1105 | Taking compiled template from engine cache
+1109 | Replaced images []
+1109 | Executing recipe html
+1110 | Skipping storing report.
+1110 | Rendering request finished 111891
+1120 | Rendering request 111891 finished in 991 ms
+1131 | Rendering engine jsrender
+1423 | Moment Timezone 0.5.5 was already loaded with data from 2016f
+1424 | Taking compiled template from engine cache
+4083 | Replaced images []
+4109 | Executing recipe html-to-xlsx
+4109 | Executing html to xlsx conversion
```

**Comment by pofider** [comment]
Thank you for the issue.

Unfortunately phantomjs has issues with parsing such huge html table, see more info here
https://github.com/pofider/html-to-xlsx/issues/8

We will try to test this directly in jsreportonline and check if the timeout increase would help. We will post here the results.

Note that to get the best performance for excel rendering, you should use [xlsx recipe](https://jsreport.net/learn/xlsx) for now.

**Comment by pofider** [comment]
I've tried increasing timeouts but it doesn't help much. 
Would you consider using the [xlsx recipe](https://jsreport.net/learn/xlsx) instead?

**Comment by parthgandhi7** [comment]
yeah ok. Its a bit time consuming for me now to port all my report templates to xlsx recipe. Anyways if nothing else is possible then i would have to consider xlsx recipe. I would look into it when i get time. Actually i have to export report as html as well as pdf, so i considered building 1 template and use phantom-pdf and html-to-xlsx to render pdf and xlsx respectively. So if any work around is possible then it would be good help for me . Or else i have to make seperate templates for my xlsx export.

**Comment by pofider** [comment]
yes, unfortunately the rendering would take anyway too long or get killed by our hard timeout for user container evaluation. We will potentially try to rewrite the `html-to-xlsx` to use the `headless chrome` instead of `phantomjs`. However we are not quite there yet and there will be likely different issues. For the time being, the best choice is to use `xlsx`recipe for big reports.

Feel free to ping me on gitter or skype if you need help with xlsx recipe, to make the transition easier for you.

**Comment by parthgandhi7** [comment]
Yeah ok np i would start implementing the `xlsx` recipe in some time. Yeah i would definetly ping you if i need any help. Thanks

**Comment by pofider** [comment]
This one is all we have
https://jsreport.net/learn/xlsx

**Comment by parthgandhi7** [comment]
Ok anyways i got my 1st report running online on jsreport with xlsx recipe. Just one more query if you can help me with this. I am querying the jsreport server through API calls from my application. It is working fine with my other reports. But it is giving some error with this new report. Can you please help me with it?
My request params are

```
{ method: 'POST',
  uri: {{report_sever_uri}},
  encoding: null,
  body: 
   { template: { name: 'SALES.CASH_XLSX', recipe: 'xlsx', engine: 'handlebars' },
     data: {{data}},
     options: 
      { 'Content-Disposition': 'attachment; filename=2017-09-27-114707.xlsx',
        timeout: 180000 } },
  headers: 
   { 'content-type': 'application/json',
     'accept-charset': null,
     Authorization: 'Basic {{auth_code}}' },
  json: true,
  timeout: 180000,
  resolveWithFullResponse: true }
```

and the error i am getting is

```
    error: 
     { message: 'Error during rendering report: Unable to find xlsx template with shortid rJ66GeKoZ',
       stack: 'Error: Unable to find xlsx template with shortid rJ66GeKoZ\n    at /usr/src/app/node_modules/jsreport-xlsx/lib/index.js:144:17\n    at _fulfilled (/usr/src/app/node_modules/jsreport-mongodb-store/node_modules/listener-collection/node_modules/q/q.js:794:54)\n    at self.promiseDispatch.done (/usr/src/app/node_modules/jsreport-mongodb-store/node_modules/listener-collection/node_modules/q/q.js:823:30)\n    at Promise.promise.promiseDispatch (/usr/src/app/node_modules/jsreport-mongodb-store/node_modules/listener-collection/node_modules/q/q.js:756:13)\n    at /usr/src/app/node_modules/jsreport-mongodb-store/node_modules/listener-collection/node_modules/q/q.js:564:44\n    at flush (/usr/src/app/node_modules/jsreport-mongodb-store/node_modules/listener-collection/node_modules/q/q.js:110:17)\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)' }
```

I reverified the template name also, its exactly the same.

Can u please help me with this?

**Comment by pofider** [comment]
Hm. This looks ok. Can you please open the template in the studio and associate with it another xlsx template. Hit save. Select there the xlsx template you like and hit save again. Maybe the association is broken there and this could fix it.

![image](https://user-images.githubusercontent.com/2041960/30912844-59a1841a-a38e-11e7-8909-e9082483d8fa.png)

**Comment by parthgandhi7** [comment]
Nope, the error persists.
FYI: It works and renders properly with sample data on the jsreport server . It just gives error with api request call. 
Could this be some kind of permission issue? As my API is querying through a different user other than the root user.

**Comment by pofider** [comment]
Ah ok, good point. You need to add permissions to the xlsx template to that user.
Find the xlsx template in the studio. Open it. And add the particular user in the permissions panel.

**Comment by parthgandhi7** [comment]
clicking on the "read permissions" or "edit permissions" nothing happens.How should i add permissions?

**Comment by pofider** [comment]
![screen](https://user-images.githubusercontent.com/2041960/30913461-977ea572-a390-11e7-9182-733ceb68fb1b.gif)

**Comment by parthgandhi7** [comment]
My read permissions and edit permissions section both are blank.

**Comment by parthgandhi7** [comment]
yes.

**Comment by parthgandhi7** [comment]
Actually i am unable to see any user in the permissions section of any of my working reports also. Still if i create a brand new report and try to access through apis it gives permission denied error. But if i clone any existing report and then edit the report to my requirements , then it works perfectly fine. But i did not have any existing xlsx template so i can't use tha above workaround for this error.

**Comment by pofider** [comment]
Ok, something is wrong there. I'll investigate it and let you know. I assume you use the `storedock` account.

**Comment by parthgandhi7** [comment]
yes

**Comment by pofider** [comment]
Hm, everything looks fine there. Could you please reach me on skype or gitter for a quick chat? 
Search for
@pofider
