### ISSUE TITLE
Single EXE - Phantom2

### ISSUE THREAD

**Issue by yoerivdm** [jsreport/jsreport#331]
Hi, I'm running a jsreport instance on windows via the single-exe.
I added a node_modules folder to it containing electron, wkhtmltopdf and phantom 2-1-1 prebuilt packages. Both electron and wkhtmltopdf are discovered but the phantom recipe is stuck on v1.9.

Am I missing something?

**Comment by pofider** [comment]
True, as far as I see we don't do crawling to discover available phantomjs version in single exe mode
https://github.com/jsreport/jsreport-phantom-pdf/blob/master/lib/phantom.js#L65

Thank you for the issue, we will look into it. I'm afraid you need to use the full installation until we fix that.

**Comment by yoerivdm** [comment]
okay, thanks for the info ... we use the single-exe on dev-machines, will keep 1.9.4 for now ;-)

**Comment by yoerivdm** [comment]
Maybe this can be closed? since phantom is replaced by chrome in v2 ...

**Comment by pofider** [comment]
Yes, the v2 binaries now includes chrome. 
We will see if we will actually release binaries also with phantom. However that is another topic.

Thanks.
