### ISSUE TITLE
Code reformatting in studio breaks our syntax

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#332]
The current lib used for reformatting html and helpers in studio quite often breaks syntax for child templates or assets. This is quite annoying and makes the feature sometimes completely unusable.

We need to find a different formatting lib or try to do something very simple on our own.

**Comment by bjrmatos** [comment]
should be solved in [studio 1.6.1](https://github.com/jsreport/jsreport-studio/releases/tag/1.6.1)
