### ISSUE TITLE
Default fs store rewrite

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#333]
I would like to re implement the default [file system based templates store](https://github.com/jsreport/jsreport-fs-store) from the ground up to achieve the following goals:

## Hierarchy support 
User can create directory hierarchies in the `data` folder and group entities together. Technically a directory will be also an entity which store expose and each entity will have an optional reference to a parent. The API stays flat and this will by design work in other stores without further modifications. Only the studio need to reflect this.
The entities' `config.json` will additionally include `entitySet` property to identify its kind. The directory itself can also contain `config.json` with additional metadata like `tags` or `premission`.

## Easier assets and relative paths
The `data` folder can have at any place a random file like `jquery.js`. Such files will be interpreted as `assets` and visible at the proper place also in the studio UI. Such files won't have metadata like permissions because it won't have a `config.json`.

Referencing such file in html/pdf should be very easy with [base tag extension](https://jsreport.net/learn/base). The developer can simply add
`<script src="myCustomLibs/jquery-1.8.1/jquery.js"></script>` and it should just work.
Or use the `assets` syntax like
`<script>{#asset myCustomLibs/jquery-1.8.1/jquery.js}</script>`

There was a [proposal](https://github.com/jsreport/jsreport-core/issues/15#issuecomment-308331368) to make the paths relative to the particular template being rendered. This means that the base tag would resolve its root based on the template being rendered. This could be configurable in `base` extension options.

This will nicely work for `fs-store`. But the path resolved by base tag won't work in other stores:
`<script src="file:///jsreport-app-path/myCustomLibs/jquery-1.8.1/jquery.js"></script>`
We will likely have to rather serve the assets through a web server links. Until then, the assets syntax should always work, because the assets extension should be able to locate the particular content based on the hierarchy.

## Support for AWS S3 and Azure blob storage
Running mongo or sql is often an overkill for few templates and in the cloud with multiple servers, you currently don't have a better option. I would like to provide bindings also for common AWS S3 and Azure Blob Storage which are basically a 0 cost and gives the very easy maintenance. This would be reached with the following architecture.

The first layer of the templates store would be in the `jsreport-core` and would be just an interface.

The second layer would work just in the memory on arrays and support mongo like queries using one of existing [libs](https://github.com/kofrasa/mingo).

The third layer would differ for file system and AWS S3. The file system would be able to load the entities at the startup and monitor the underlying changes to keep them up to date in the memory from which the second layer servers the queries. The AWS S3 would on the other bind `insert`, `update` and `remove` to the remote S3 storage. The initial start would also load everything and provide in memory representation to the second layer. 

This would be very easy to set up for the cloud. You just need a S3 or Azure Blob Storage endpoint. However if you want to run multiple instances on the same underlying template, you also need to provide an endpoint to AWS Pub/Sub Azure SB service. These would be used to propagate changes between servers.

<hr>
We also received a request to use fully git on the behind for stored templates. I don't take this into consideration at this moment because I think that everyone can store our `data` folder into git repository and maintain commits on its own.
<hr>

I try to make a prototype of this using node 8 and come back here afterwards. However it would be great if some kind of discussion happens here so we go the right track with it.

**Comment by bjrmatos** [comment]
so far i like it, looking forward to play with initial version 😄 

> We also received a request to use fully git on the behind for stored templates. I don't take this into consideration at this moment because I think that everyone can store our `data` folder into git repository and maintain commits on its own.

this is an interesting idea but hard to get it right, i can imagine a world when we have the power of switching between versions of templates, somekind of editing history, diffs, right into the studio. so far it is already possible to do it in user-land, with some extra-work and convention applied by the user, but having something like this by default in jsreport would be really great, the experience will feel excellent.

another thing: in [this issue](https://github.com/jsreport/playground/issues/2) some user asked for the jsreport's playground workspace feature to be available/installable as an extension for jsreport, if something like this happens, do you think it will be something simple to support in fs store? i mean probably the `data` folder would need to have a root folder for each workspace and some logic to differenciate between files of main workspace (the space that you get by default when workspaces are not being used) and files of other workspaces.. but probably you have better ideas and it deserves its own issue, just wanted to mention it 😄

**Comment by pofider** [comment]
> ... but having something like this by default in jsreport would be really great, the experience will feel excellent.
Sure it would be great. The very first version was even tracking the changes in templates. However implementing this correctly in the UI would take a while. Hopefully we get a "time budget" for it afterwards. 

> another thing: in this issue some user asked for the jsreport's playground workspace feature to be available/installable as an extension for jsreport
Hmm. Yes it could work somehow. The extension would add some attributes to the `directory` entity type. Then root directories would be workspaces. The inner would be versions and then the entities. Maybe...

**Comment by pofider** [comment]
The next version of fs store can be found in [next](https://github.com/jsreport/jsreport-fs-store/tree/next) branch and also under `next`  tag in npm.  The new docs can be found here
https://jsreport.net/learn/fs-store

The rewrite is back compatible with the previous. It adds additionally support to Azure Blob Storage and AWS S3 as announced. The implementation of hierarchy and relative links is missing so far. However it is still on the road map.

**Comment by pofider** [comment]
Done in v2 beta. 
https://jsreport.net/blog/jsreport-v2-beta
https://github.com/jsreport/jsreport/releases/tag/2.0.0-beta

The hierarchy is missing, but there is special task for it.
https://github.com/jsreport/jsreport/issues/250
