### ISSUE TITLE
Stop sharing report

### ISSUE THREAD

**Issue by KevinHaisol** [jsreport/jsreport#334]
I created a report and enabled sharing for it.  I want to stop sharing the report, how do you do this?  I want to disable the "Link with read permissions"  and "Link with write permissions".

**Comment by pofider** [comment]
There is no UI button for it. However you can use odata api to set null into template
`readSharingToken` or `writeSharingToken`. You can also edit this manually in your template store. If you use the default one, edit the `data/templates/[yourtemplate]/config.json`.

**Comment by KevinHaisol** [comment]
Ok, that worked, thanks,  How hard would it be to create an extension that would add a button to remove sharing for a report?

**Comment by pofider** [comment]
You don't need to create an extra extension. I would happily accept your PR with such button being add [here](https://github.com/jsreport/jsreport-public-templates/blob/master/studio/ShareModal.js)

**Comment by pofider** [comment]
Done in v2 beta. 
https://jsreport.net/blog/jsreport-v2-beta
https://github.com/jsreport/jsreport/releases/tag/2.0.0-beta
