### ISSUE TITLE
API authentication to report request

### ISSUE THREAD

**Issue by KevinHaisol** [jsreport/jsreport#335]
Is there a way I can pass authentication to jsreport in a web request via api.  This way I can authenticate the user has access to the report, set report variables and return the pdf report.  Is this possible?

**Comment by pofider** [comment]
Yes, see the [API authentication docs section](https://jsreport.net/learn/api#authentication)

You probably need to enable [authentication extension first](https://jsreport.net/learn/api#authentication). This is usually done in jsreport configuration file by changing `authentication.enabled=false`.

**Comment by KevinHaisol** [comment]
Thanks that might work well or be overkill for what I'm looking for.  Is there a way I could create an extension that would allow me to create an end point to the jsreport server:  Example: http://my.jsreport/getAPIReport/sometoken (with some post data)  This would allow me to validate the token passed in and provide a report based on the request? any ideas if this is possible and objects I would need to extend to make this work?

thanks

**Comment by pofider** [comment]
The public templates extension works in the similar way.
https://jsreport.net/learn/public-templates

If you decide to write a custom extension, you can start with docs here
https://jsreport.net/learn/custom-extension

Closing as there is nothing we can do about it. However feel free to post further comments.
