### ISSUE TITLE
Add function in server side extension

### ISSUE THREAD

**Issue by PaulGrimshaw** [jsreport/jsreport#336]
How can I add a function in a server side extension?  I have it all working with static objects, but no functions remain - seems it goes through a JSON.stringify(...) or something:

This works when called in custom script:
```
reporter.beforeRenderListeners.add('connections', function (req) {
       req.data = req.data || {}
       req.data.myThing = "hello"
```

But this doesn't:
```
reporter.beforeRenderListeners.add('connections', function (req) {
       req.data = req.data || {}
       req.data.myFunction = arg => "hello"
```

Any ideas?  I would like to get all my database connections ready to query by lots of different scripts, building a big report.  I know i can do this using a custom global script, but would prefer the server method.

**Comment by bjrmatos** [comment]
hi! 



> I have it all working with static objects, but no functions remain - seems it goes through a JSON.stringify(...) or something:

yes, as you guessed, by default `req.data` is JSON stringified, see my [previous comments about this behaviour and the reason behind that.](https://github.com/jsreport/jsreport/issues/319#issuecomment-318085749). 

the TL;DR: everything in `req.data` is stringified unless when using `in-process` strategy in [`tasks.strategy` config](https://jsreport.net/learn/configuration#script-tasks). if you really need to work with functions change the tasks strategy to `in-process`
