### ISSUE TITLE
Ordering of scripts not working

### ISSUE THREAD

**Issue by PaulGrimshaw** [jsreport/jsreport#337]
We have tried a few simple examples ordering 3 separate scripts, but the order seems very unpredictable.  We know you can order them in the studio, and that this array corresponds to the array within the database, but we have found the rendering process doesn't follow this, and seems to stay the same regardless of the order specified.

A simple experiment with 3 scripts logging to the console, and trying to reorder should recreate this.  Maybe it is to do with our environment... we're using the postgres storage.

Ideally we would be able to order global and extension scripts in combination with specific report scripts. Our basic pattern is to write database queries in a "query script" for each report.  A global generic script  (ideally an extension script) then fetches data from the database as per the query.  We then have a final script sometimes to tailor the data for the report.   This pattern is working great, just stuck with the ordering.

Any thoughts?

**Comment by bjrmatos** [comment]
i see, i've tried a [quick case](https://playground.jsreport.net/studio/workspace/H1dozifsb/13) (just run it with the "Debug" button in studio and then we can see that the log messages of each script are not in the expected order) and indeed the ordering when rendering does not match the expected (the order selected in studio), my first idea would be that ordering is lost when reading from the store (filesystem or database) and we need to ensure that the order always stays the expected. i will try to take a look and see what is hapenning. 

about global scripts ordering we don't have a way to define the order yet, but i agree that it makes sense to add a way to do this, but first i will look into the normal scripts ordering problem.

**Comment by PaulGrimshaw** [comment]
Great.

Re global scripts and extensions, would be great if for each template the order could be specified like the way it is, but also include global and server extensions in the order selection.

**Comment by bjrmatos** [comment]
sorry but you lost me in this part: `but also include  global and server extensions in the order selection.`.. 

what do you mean by ordering of server extensions scripts? do you mean ordering or listeners attached in jsreport instance? like this [one](https://github.com/jsreport/jsreport-scripts/blob/master/lib/scripts.js#L22)? currently there is a way to define a listener that runs before or after others, like this [example](https://github.com/jsreport/jsreport-scripts/blob/master/lib/scripts.js#L19), but listeners are something different than order of script execution so i don't think we will add a way to order those with an UI, because you already have a way to do that with code, something expected for an extension.

about the global scripts we will probably add a new selection UI that lets you decide the order or global scripts in isolation, so the flow would be something like this: 

`[ordered global before render script] -> [ordered normal script before/after render] ->[ordered global after render script]`

but we need to discuss this internally and evaluate tradeoffs, so let's see..

**Comment by PaulGrimshaw** [comment]
Yes meant like those examples.  Sorry i have only been using jsreport for a few days, just starting to get my head round it.

The pattern we have built has a server extension that looks at the current data for special properties (`queries`), and if they are present fetches the relevant data from the database.  This is then added back into the data and the `query` property deleted.

Ideally we would have normal scripts run before and after this, so we can have the script prepare the query then change the data afterwards.

**Comment by PaulGrimshaw** [comment]
This is the `dataLoader` script that needs to run between the normal scripts if that helps:

```const DataApi = require("./src/connections/DataApi”).DataApi
const path = require("path")
const config = require(path.resolve("./config.json"))


function beforeRender(req, res, done) {
    console.log("starting dataLoader")
    req.data = req.data || {}
    req.parameters = req.parameters || {}

    if (req.query) {
        req.parameters = Object.assign(req.parameters, req.query)
    }

    if (req.data.queries) {
        const api = new DataApi(config.dataApiProps)

        for (const query of req.data.queries) {
            if (query.type === “DataApi”) {
                if (query.properties != null && query.properties.query != null) {
                    api.executeQuery({
                        query: query.properties.query,
                        parameters: req.data.parameters
                    })
                    .then(result => {
                        if (query.target) {
                            req.data[query.target] = result.body
                        } else {
                            req.data = Object.assign(req.data, result.body)
                        }
                    })
                    .catch(err => {
                        req.data.err = err
                        console.log("ERROR:", JSON.stringify(err))
                    })
                    
                }
            }
            console.log("done data loader")
            done()

        }
        delete req.data.queries
    }

}```

**Comment by bjrmatos** [comment]
> The pattern we have built has a server extension that looks at the current data for special properties (queries), and if they are present fetches the relevant data from the database. This is then added back into the data and the query property deleted.
> 
> Ideally we would have normal scripts run before and after this, so we can have the script prepare the query then change the data afterwards.

ahh i see, interesting pattern, so basically you would like that your server extension (the one that look for queries and resolve it) runs after each script right? so for example you have a template `foo` that has attached three scripts: `script1`, `script2`, `script3`, each script is adding itw on `req.data.queries`, then your server extensions should resolve the queries, fill the resolved data and the flow should continue in this way with the next scripts, right?

**Comment by PaulGrimshaw** [comment]
Exactly.  So ideally the server execution script is out of sight, so less technical people can still build reports by writing queries and changing the data a bit afterwards with javascript.

**Comment by bjrmatos** [comment]
great, so far until now i did not know that jsreport has `beforeScriptListeners` (jsreport is so powerful that i sometimes forget all the features that it has 😆 ), i think that this listener would help you to solve your case.

you would need to add your listener (server extension) in this way:

```js
// somewhere in your code

// registering your dataLoader extension job
reporter.initializeListeners.add('dataLoader', function () {
// we use `after` option to make sure that this listener runs after `assets` extensions
  reporter.beforeScriptListeners.insert({ after: 'assets' }, 'dataLoader', reporter, function (scriptDef, req, done) {
        // do your dataLoader job here and update `req.data`
  })
})
```

for reference [here is a core extensions that uses the `beforeScriptListeners`](https://github.com/jsreport/jsreport-assets/blob/master/lib/assets.js#L298)

we don't have an `afterScriptListeners` yet (we will probably add it later), but the `beforeScriptListeners` should be enough for your case. let me know how it goes

**Comment by bjrmatos** [comment]
i will check the ordering issue of normal scripts now..

**Comment by bjrmatos** [comment]
i found the issue and now it is fixed, if you need the fix urgently in your project, install the `jsreport-scripts` update in your proyect with: `npm install jsreport-scripts@1.4.3 --save` otherwise the fix will also be present in the next version of jsreport.

i'm closing the issue since the original problem was fixed, but if you want to comment something feel free to do it.

also i'm opening a [new issue](https://github.com/jsreport/jsreport-scripts/issues/10) to keep track about the UI for global scripts execution ordering.

**Comment by PaulGrimshaw** [comment]
Fantastic, thanks for the rapid fix and for the suggested solution.  I will give it a go and let you know.

**Comment by PaulGrimshaw** [comment]
FYI the before script listeners worked a treat. And the ordering is working too now.
