### ISSUE TITLE
Language param from data

### ISSUE THREAD

**Issue by yoerivdm** [jsreport/jsreport#339]
Hi, is there a way to set the language parameter based on input-data?

Only solution i see a this moment is to put all content in a child-template and add the options.language parameter when invoking the child-template.

All document metadata is included in our data, can't pass it via the api at this moment ... 

Tx
Y.

**Comment by bjrmatos** [comment]
hi! i think you can do what you want by using the `beforeRender` hook in a custom script, check this example: https://playground.jsreport.net/studio/workspace/VkLWfMyMb/35 and test how it goes for you.

**Comment by yoerivdm** [comment]
Works like a charm! Thanks!
