### ISSUE TITLE
feature request - jade

### ISSUE THREAD

**Issue by diginfo** [jsreport/jsreport#34]
Any chance that you can provide support for jade templating instead or raw html ?

It would be great if you could !

**Comment by kahwooi** [comment]
you can generate the html first using Jade API before passing it to jsreport to render:

```
var html = jade.renderFile('report.jade', data);
```

**Comment by pofider** [comment]
This is supported through extension now - [jsreport-jade](https://github.com/bjrmatos/jsreport-jade)
Thanks to @bjrmatos
