### ISSUE TITLE
jsreport Heroku deployment

### ISSUE THREAD

**Issue by KevinHaisol** [jsreport/jsreport#340]
I want to deploy jsreport to Heroku.  I'm not an expert on the package.json stuff but know Heroku uses it to build the app.  I use a lot of the jsreport extensions but none of them are listed as dependencies in the package.json file so I don't think they will be deployed to Heroku.  Also, I would like to configure the app to read config information from environment variables.  Can you provide any advice or assistance on this stuff?

Thanks

**Comment by pofider** [comment]
It is enough to have the `jsreport` in the dependencies. 

https://jsreport.net/learn/configuration
> jsreport merges configuration from file, environment variables, command line arguments and also directly from the application code. 

So you can use environment variables to configure jsreport. Just use `_` as separator for the nested configs. Like `connectionString_name=fs`.

**Comment by KevinHaisol** [comment]
Awesome, thanks again

**Comment by fligelmanmeir** [comment]
i have an application that renders jsrepot reports via a restfull api call  uri:'http://localhost:4000/api/report',
now i'v moved my application to heroku and i believe that i have to change things with jsreport.
