### ISSUE TITLE
How to render data from mongodb

### ISSUE THREAD

**Issue by sembrador** [jsreport/jsreport#342]
Can you provide a working sample using mongdb data to render the reports?

Please and Thanks.

**Comment by bjrmatos** [comment]
hi! here is a blog [post](https://jsreport.net/blog/pdf-reports-from-mongodb) showing how to use [jsreport-contrib-mongodb](https://github.com/jsreport/jsreport-contrib-mongodb) extension to query mongodb data inside a jsreport script to finally use it when rendering.

here is the TL;DR:

jsreport `beforeRender` script:

```js
function beforeRender(done) {
	var MongoClient = require('mongodb').MongoClient; 
	MongoClient.connect('mongodb://127.0.0.1:27017/maindb', function(err, db) {
		var collection = db.collection('people').find().toArray(function(err, results) {
		    if (err)
		      return done(err);
		      
			request.data = { people: results };
			done();
		});
	});
}
``` 

make sure to check the relevant [docs](https://github.com/jsreport/jsreport-contrib-mongodb)
