### ISSUE TITLE
Error rendering report: rendering has finished with errors:Error during rendering report: Recipe must be specified

### ISSUE THREAD

**Issue by CoolM1234** [jsreport/jsreport#343]
![capture2](https://user-images.githubusercontent.com/30105375/31117462-7374549e-a85c-11e7-8432-61a682a962d2.PNG)

Refrerence: https://jsreport.net/learn/dotnet-mvc

My Recipe has been specified  but why i m still getting this error??

![capture3](https://user-images.githubusercontent.com/30105375/31117746-828f877c-a85d-11e7-89f2-d01f0c396e40.PNG)

Anyone know how to solve it? pls help 
Thanks

**Comment by pofider** [comment]
The code looks good. Could you please create for me a sample repository where I can replicate this?

I don't want to mix the .net stuff in this repository. I'm closing this now, please open new issue here, when you have the repo ready.
https://github.com/jsreport/jsreport-dotnet
