### ISSUE TITLE
Error during rendering report: Missing helper: "toJSON"

### ISSUE THREAD

**Issue by vishesh1king** [jsreport/jsreport#344]
I am facing the error "missing helpers" when trying to render data from the server.My html script code is, 
```
<script>
      var data = {{{ toJSON this }}};
      console.log('data',data)
      var ctx = document.getElementById('myChart').getContext('2d');
      var myChart = new Chart(ctx, {
          type: 'line',
          data: {
              labels: data.chart.label,
              datasets: [{
                  label: 'Pay slip',
                  data: data.chart.data,
                  steppedLine: true,
                  backgroundColor: "rgba(220,143,143,0.4)",
                  borderColor: ""
              }]
          },
          options: {
              animation: {
                  onComplete: function () {
                      window.JSREPORT_READY_TO_START = true
                  }
              },
              elements: {
                  line: {
                      tension: 0, // disables bezier curves
                  }
              }
          }
      });

  function toJSON (data) {
      return JSON.stringify(data);
  }
  </script>
```

> 
> Error: 2017-10-04T13:15:23.708Z - error: Error when processing render request Error during rendering report: Missing helper: "toJSON" Error: Missing helper: "toJSON"
>     at Object.<anonymous> (/home/ionixx/NetBeansProjects/crossbow/node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19:13)
>     at Object.eval [as main] (eval at createFunctionContext (/home/ionixx/NetBeansProjects/crossbow/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:48:89)
>     at main (/home/ionixx/NetBeansProjects/crossbow/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
>     at ret (/home/ionixx/NetBeansProjects/crossbow/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
>     at ret (/home/ionixx/NetBeansProjects/crossbow/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
>     at /home/ionixx/NetBeansProjects/crossbow/node_modules/jsreport-handlebars/lib/handlebarsEngine.js:25:14
>     at evalmachine.<anonymous>:1:41
>     at ContextifyScript.Script.runInContext (vm.js:32:29)
>     at ContextifyScript.Script.runInNewContext (vm.js:38:15)
>     at Object.runInNewContext (vm.js:91:38) requestId=1

The server file is,

```
jsreport.render({
                    template: {
                        content: fs.readFileSync(baseDir + '/template/report/index.htm', 'utf8'),
                        engine: 'handlebars', // engine: 'jsrender',
                        recipe: 'phantom-pdf',
                        phantom: {
                            "waitForJS": true
                        }
                    },
                    data: data
                });
```

Can anyone have a solution for this?

**Comment by pofider** [comment]
The helpers needs to be set separately, not part of the template inline script. Something like this:

```js
jsreport.render({
                    template: {
                        content: fs.readFileSync(baseDir + '/template/report/index.htm', 'utf8'),
                        helpers: 'function helperA() { return 1 }',
                        engine: 'handlebars',                   
                        recipe: 'phantom-pdf',
                        phantom: {
                            "waitForJS": true
                        }
                    },
                    data: data
                });
```
