### ISSUE TITLE
How to use jsrender

### ISSUE THREAD

**Issue by sembrador** [jsreport/jsreport#345]
I'm trying to make a report using mongodb with jsrender, phantomjs-pdf

This is my template code:

```
<div>
    <table cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th>SOCIO #</th>
                <th>APELLIDO</th>
                <th>NOMBRE</th>
                <th>FECHA DE NACIMIENTO</th>
                <th>CEDULA</th>
                <th>CELULAR</th>
                <th>CAPITULO</th>
                <th>CORREO</th>
            </tr>
        </thead>
        <tbody>
            {{for socios}}
            <tr>
                <td>{{:socio_numero}}</td>
                <td>{{:socio_apellidos}}</td>
                <td>{{:socio_nombres}}</td>
                <td>{{:socio_fch_nac}}</td>
                <td>{{:socio_cedula}}</td>
                <td>{{:socio_telefonos.3.phone}}</td>
                <td>{{:socio_capitulo}}</td>
                <td>{{:socio_email}}</td>
            </tr>
            {{/for}}
        </tbody>
    </table>
</div>

function beforeRender(done) {
    var mongoDb = require('mongodb').MongoClient,
        url = 'mongodb://tester:password!@localhost:27017/pruebas';
    mongoDb.connect(url, function(err, db) {
        var collection = db.collection('info_socios').find({
            "_deleted": {
                $ne: true
            }
        }).toArray(function(err, results) {
            if (err) {
                return done(err);
            } else {
                request.data = {
                    socios: results
                };
                done();
            }
        });
    });
}
```
This is the error I got:

Error occured - Error during rendering report: Syntax error
Compiled template code:

// unnamed/for
var v,ret=""

+"\n            <tr>\n                <td>"
+((v=data.socio_numero)!=null?v:"")
+"</td>\n                <td>"
+((v=data.socio_apellidos)!=null?v:"")
+"</td>\n                <td>"
+((v=data.socio_nombres)!=null?v:"")
+"</td>\n                <td>"
+((v=data.socio_fch_nac)!=null?v:"")
+"</td>\n                <td>"
+((v=data.socio_cedula)!=null?v:"")
+"</td>\n                <td>"
+((v=data.socio_telefonos.3.phone)!=null?v:"")
+"</td>\n                <td>"
+((v=data.socio_capitulo)!=null?v:"")
+"</td>\n                <td>"
+((v=data.socio_email)!=null?v:"")
+"</td>\n            </tr>\n            ";
return ret;
: "Unexpected number"
logs:
+0      Starting rendering request 14
+2      Rendering template {shortid:SkFDILbnZ, recipe:phantom-pdf,engine:jsrender}
+2      Data item not defined for this template.
+28     Resources not defined for this template.
+29     Base url not specified, skipping its injection.
+29     Rendering engine jsrender
Stak - Error
    at /Users/leandrocamano/Public/webapp/meteor/aopweb/reports/node_modules/jsrender/jsrender-node.js:212:27
    at Object.<anonymous> (/Users/leandrocamano/Public/webapp/meteor/aopweb/reports/node_modules/jsrender/jsrender-node.js:2395:2)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/leandrocamano/Public/webapp/meteor/aopweb/reports/node_modules/jsreport-jsrender/lib/jsrenderEngine.js:6:16)

What am I  doing wrong?

Any help will be appreciated.

**Comment by bjrmatos** [comment]
hi! it seems like this syntax `<td>{{:socio_telefonos.3.phone}}</td>` is not valid in jsrender (the problematic part is `.3`, you can't access a specific item in the array in this way. i guess that you can declare a helper that extract a specific item on a array, in this way you would be using the helper instead of `{{:socio_telefonos.3.phone}}` syntax. probably there are other ways but i did not looked in deep into [jsrender docs](https://www.jsviews.com/), maybe you can find something in there that can be helpful for you.

i will close the issue because this is just a problem with jsrender syntax and not with jsreport itself, however feel free to add more comments.

**Comment by sembrador** [comment]
hi! thanks for  your help, I can write a helper to get the array items, but for now I just omit this field <td>{{:socio_telefonos.3.phone}}</td> and now I get just one page with headers. 

Do I need to setup something more?

**Comment by bjrmatos** [comment]
maybe you are not passing the data correctly. can you create [here](https://playground.jsreport.net/) an example for your case? (make sure to attach your data input too) it will help in figure out what could be wrong.
