### ISSUE TITLE
Chart doesn't render correctly. (Auto adding 'undefined' y-axis column)

### ISSUE THREAD

**Issue by CoolM1234** [jsreport/jsreport#346]
(Last data is 2020)
why the chart auto adding 'undefined' (y-axis column) for my chart in phantom-pdf?
![capture](https://user-images.githubusercontent.com/30105375/31331725-1ce8eb62-ad16-11e7-8df1-3130ceebf201.PNG)

but in html page (it's working fine)
![capture2](https://user-images.githubusercontent.com/30105375/31331893-cdc45eb2-ad16-11e7-889f-495d347083a5.PNG)

-----------------------------
2)How to changes chart's width in phatom-pdf ? 
-----------------------------
I have adding "width" to changes chart's width in my css file. 

![capture](https://user-images.githubusercontent.com/30105375/31333334-2b21f3e4-ad1c-11e7-9dfb-83661e5c00d7.PNG)

But the chart's width is only changes in html page doesn't in phantom-pdf. 

please advise
Thanks.

**Comment by pofider** [comment]
Please replicate this issue in playground so we can take a look. Thank you,
https://playground.jsreport.net

**Comment by CoolM1234** [comment]
The problem is fix :smile: 
Thanks :smile:
