### ISSUE TITLE
Handlebars & $localizedResource

### ISSUE THREAD

**Issue by yoerivdm** [jsreport/jsreport#348]
When using a $localizedResource inside a with-clause in handlebars ... the translation doesn't work...
Is this expected behaviour?

I get why this isn't working but this should not interfere ... ;-)

regards
Yoeri

**Comment by pofider** [comment]
The `$localizedResource` is json merged into the root of the input data. So it needs to interfere with `with`. 
You can however easily use `../` to reach the parent context and `$localizedResource`. See this demo

https://playground.jsreport.net/studio/workspace/VkLWfMyMb/40
