### ISSUE TITLE
Docker - wkhtmltopdf doesn't render headers

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#349]
The wkhtmltopdf recipe doesn't render headers after the dockerfile changes introduced in `1.8.0`

The debug message stays
> wkhtmltopdf  --debug-javascript --disable-local-file-access --margin-top 30mm --header-spacing 10 --header-html file:////tmp/jsreport-temp/f5228280-ada8-11e7-98b4-b915cd663418header.html /tmp/jsreport-temp/f5228280-ada8-11e7-98b4-b915cd663418.html /tmp/jsreport-temp/f5228280-ada8-11e7-98b4-b915cd663418.pdf
+484    The switch --header-spacing, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.Loading page (1/2)
`

We should likely use the wkhtmltopdf installed through npm instead from the one from `apt-get`.

**Comment by pofider** [comment]
@notatestuser @bjrmatos Does any of you please remember what was the reason for installing the `wkhtmltopdf` through apt-get instead of the npm in the full docker image? I mean [this line](https://github.com/jsreport/jsreport/blob/master/docker/full/Dockerfile#L19) Merged through this [PR](https://github.com/jsreport/jsreport/pull/310). It seems that the `wkhtmltopdf` installed through `apt-get` doesn't support headers for some reasons.

**Comment by bjrmatos** [comment]
i think there was not a good reason and it was just a mistake, according to the docker file we also install `jsreport-wkhtmltopdf` so i'm not sure why that change, probably just mistake. 

does removing that line makes it work normally again (since it would use the `wkhtmltopdf` of node_modules)?

**Comment by pofider** [comment]
It seems it was really a mistake. Removing `wkhtmltopdf` from `apt-get` makes the header working. Will be part of the next release.

**Comment by notatestuser** [comment]
Please check that it is not being downloaded/installed more than once like that though. That was happening to phantomjs when installed through npm.

**Comment by pofider** [comment]
@notatestuser Thank you for following here. I did check the image size and the new one is smaller. So it should be even better now. The reason for phantomjs were being installed multiple times is because we depend on it in several packages. This is not the case for wkhtmltopdf where there is only one package installing it.

**Comment by notatestuser** [comment]
Great, thanks!
