### ISSUE TITLE
Multi-select issues

### ISSUE THREAD

**Issue by stephentuso** [jsreport/jsreport#350]
Some issues I have with the multi select component used in the properties panel (for scripts, resources, etc.):
 - No way of deselecting something once it has been selected - can be an issue with scripts
 - Selecting a second item deselects the first (if you don't hold down cmd/ctrl) - this can be frustrating sometimes, especially when selecting many items

The second one is more of an opinion though. 

However, seems like a standard checkbox group with a clear all button would be more intuitive.

**Comment by pofider** [comment]
Yes, you are probably right. The list of check boxes would be more intuitive.
We use a common multiselect react component which just works that way:
 - Use CTRL to select multiple items
 - Use CTRL to deselect an item

We will look into a more natural solution as soon we get time for it. Thank you for your suggestion.

**Comment by bjrmatos** [comment]
> However, seems like a standard checkbox group with a clear all button would be more intuitive.

agree, a checkbox next to each option would be a nice addition. let's see 😄

**Comment by stephentuso** [comment]
Ah thanks that helps, I hadn't tried ctrl to deselect

**Comment by MI53RE** [comment]
also if you happen to go with the checkbox, a 'tick/untick all' checkbox would be a nice addition too (I'm thinking about the priviledge part, when you happen to have so many users that when you need to add only the read permission on all of them for a new element it become quite a hurdle ^_^')

**Comment by bjrmatos** [comment]
done, it is part of upcoming v2
