### ISSUE TITLE
handlebars-intl

### ISSUE THREAD

**Issue by yoerivdm** [jsreport/jsreport#351]
how can i change the locale of handlebars-intl when using it in a report?
want to add a custom locale ... :-|

**Comment by bjrmatos** [comment]
according to `handlebars-intl` docs this is the way to go:

```js
{{#intl locales="fr-FR"}}
    /*your content here*/
{{/intl}}
```
([relevant docs](https://formatjs.io/handlebars/#intl))

also just FYI you also can achieve localization by using [localized resources](https://jsreport.net/learn/resources#localization)

**Comment by pofider** [comment]
Closing as there is not activity here.
