### ISSUE TITLE
JS Report Custom Names for Latest Version 1.8.2

### ISSUE THREAD

**Issue by yellareddy-allcloud** [jsreport/jsreport#358]
Hello sir, actually i used  previous version jsreport. now i upgraded, in the previous version i am overriding AddResponseHeader action method to giving  custom names for downloaded reports. i was used in C# like below code which was sent by you  6 months back

public class MyFilterAttribute : JsReportFilterAttribute
{
public MyFilterAttribute(IReportingService reportingService) : base(reportingService)
{
}

    protected override void AddResponseHeaders(ActionExecutedContext context, EnableJsReportAttribute jsreportAttribute, Report output)
    {
        foreach (var httpResponseHeader in output.Response.Headers)
        {
            if (httpResponseHeader.Key.ToLower() == "connection" || httpResponseHeader.Key.ToLower() == "transfer-encoding")
                continue;                

            context.HttpContext.Response.AddHeader(httpResponseHeader.Key,
                                                   string.Join(";", httpResponseHeader.Value));
        }

        foreach (var httpContentHeader in output.Response.Content.Headers)
        {
            if (httpContentHeader.Key.ToLower() == "content-disposition")
            {
                context.HttpContext.Response.AddHeader(httpContentHeader.Key,
                    (string)context.Controller.ViewData["jsreportCustomContentDisposition"]);
            }
            else
            {
                context.HttpContext.Response.AddHeader(httpContentHeader.Key,
                                                       string.Join(";", httpContentHeader.Value));
            }
        }

        context.HttpContext.Response.ContentType = output.ContentType.MediaType;
    }
}

now above code is not working in the latest version 1.8.2, for over riding custom names , can you please ping me the code related to latest version for downloading reports with custom names.

**Comment by pofider** [comment]
This can be found in [the official mvc example](https://github.com/jsreport/jsreport-dotnet-example-webapp). In particular on [this line](https://github.com/jsreport/jsreport-dotnet-example-webapp/blob/master/Controllers/HomeController.cs#L35).

**Comment by yellareddy-allcloud** [comment]
tan q sir, working 5 n.

**Comment by pofider** [comment]
I've realized that the mentioned link is for asp.net core web app example.
Here you can find also full .net framework asp.net MVC example
https://github.com/jsreport/jsreport-dotnet-example-net-webapp
