### ISSUE TITLE
I cannot start the jsreport, always get an error "an error has occurred when trying to initialize jsreport.."

### ISSUE THREAD

**Issue by gauravjagota** [jsreport/jsreport#360]
I cannot start the jsreport. It always throws an error "an error has occurred when trying to initialize jsreport.." on "jsreport start". I am using node.js version 8.9.1, npm version 5.5.1 and there are no issues with installation or initialization of jsreport.

C:\Users\gach>jsreport init
Initialized

C:\Users\gach>jsreport start
An error has occurred when trying to initialize jsreport..

**Comment by bjrmatos** [comment]
hi! can you post the full log messages (including the errors) that you get in console when starting jsreport? if you use `node server.js` instead of using `jsreport start` do you still get this error?

**Comment by gauravjagota** [comment]
Thanks @bjrmatos for reply. I reinstalled it and removed all npm-cache folders. It's up and running :)
