### ISSUE TITLE
template footer, header are not read (handlebars, phantom-pdf)

### ISSUE THREAD

**Issue by krutkowski86** [jsreport/jsreport#361]
After updating jsreport from version 1.70 to 1.9.1 studio doesn't read header and footer despite the fact proper files are available (footer.handlebars, header.handlebars). It occurs after server restart.

**Comment by bjrmatos** [comment]
i can confirm the bug.

steps to reproduce after a fresh install.

- create a template, save it
- edit header or footer save it
- run it, it works
- shutdown server
- start server and try to render the template
- template does not recognize header of footer (even that header/footer.handlebars are present)

**Comment by bjrmatos** [comment]
just as a note, same case works in jsreport@1.8.2, so this is a bug that was recently introduce in 1.9.x releases.

**Comment by pofider** [comment]
Thank you for your bug report.
We've just released critical hotfix 1.9.2 to correct that.
