### ISSUE TITLE
Add white labeling feature

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#362]
Make it easy for integrator to change jsreport studio logo and theme.

Technically the studio extension should have an option specifying which css or image to load.

**Comment by bjrmatos** [comment]
there is new branch in studio https://github.com/jsreport/jsreport-studio/tree/white-labeling with some changes that make possible to customize the theme vars colors in studio dev mode. 

i still need to work on the option to load the user css

**Comment by bjrmatos** [comment]
this was done as part of 2.6.0 🎉
