### ISSUE TITLE
Support returning promises from custom scripts

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#363]
Something like this should work.
```js
function beforeRender(req, res) {
  return fetch('foo').then((res) => req.data = res)
}
```

```js
async function beforeRender(req, res) {
  const data = await fetch('foo')
  req.data = data
}
```

Technically we make script manager working the same way as mocha does. If the function doesn't take `done` param. We expect it to return a promise.

Expected this to be included in v2.

**Comment by rashmim00** [comment]
I am waiting for this one. Thanks for working on it.

**Comment by pofider** [comment]
Done in v2 beta. 
https://jsreport.net/blog/jsreport-v2-beta
https://github.com/jsreport/jsreport/releases/tag/2.0.0-beta

**Comment by bjrmatos** [comment]
> Sorry for digging out this old post, but did this functionality manage to get into 1.10x?

i'm afraid not, it is only supported on jsreport >=2.0.0
