### ISSUE TITLE
Provide query string parameters to the rendering pipeline

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#365]
We already provide to render a template through simple get
 GET `http://localhost:5488/templates/foo`

This should be extend with ability to add parameters to the url and fetch them in templating engines or scripts
 GET `http://localhost:5488/templates/foo?paramA=foo`

**Comment by pofider** [comment]
The relevant code is [here](https://github.com/jsreport/jsreport-templates/blob/master/lib/templates.js#L93).

The idea is to extend the rendering request generated in template link as
```js
{
   template: templateFromUrl,
   data: {
     $req: {
       query: {
         paramA: 'foo'
       } 
     }
   }
```

The problem can be that the sample data associated with the particular template won't be applied afterwards. This would be breaking change, because at this moment the templates rendered through link  have the sample data applied. I would be open to implement it this way and break it in `v2`. The user should anyway expect that the sample data are not applied in the runtime.

There is also a solution to merge in `$req.query`  after the data extension passes. This sounds to me technically strange.

Or another way to pass it through `options` and let the developer use the custom script to set it to data as he needs. The problem here is that it requires two steps from developer.

The last option is to dramatically change the information we send to templating engine. Right now it is just `data`. However perhaps also the `options` or `template` could be useful in templating engine. It would be reachable as `$template` and `$options` on the root context. In this case we could pass the `$req` on options. I'm not sure how much providing `template` and `options` to the engines evaluation would be useful. Nobody did ask for it yet, but perhaps it is just because there is always easy workaround with script. The downside here is of course that it increases the data transfer in cross process strategies.

So far I see the first option as the best. What are your thoughts?

**Comment by bjrmatos** [comment]
> The problem can be that the sample data associated with the particular template won't be applied afterwards. This would be breaking change, because at this moment the templates rendered through link have the sample data applied. I would be open to implement it this way and break it in v2. The user should anyway expect that the sample data are not applied in the runtime.

somehow i like the current behaviour (applying sample data), it was something very natural to discover when using jsreport for the first time, so i'm not sure if i like changing that.

> There is also a solution to merge in $req.query after the data extension passes. This sounds to me technically strange.

sounds strange to me too and not very comfortable with that behaviour

> Or another way to pass it through options and let the developer use the custom script to set it to data as he needs. The problem here is that it requires two steps from developer.

i like this the most, it is the most explicit and expected for me. looks normal that query params will be available in options for the developer to work with them in script, with this developer has the choice if they want those params to be in data, or maybe just use them to fetch data in third party http API without making the query params visible in template data at all. seems to me that the two steps problem can be well justified with this in mind.



> The last option is to dramatically change the information we send to templating engine. Right now it is just data. However perhaps also the options or template could be useful in templating engine. It would be reachable as $template and $options on the root context. In this case we could pass the $req on options. I'm not sure how much providing template and options to the engines evaluation would be useful. Nobody did ask for it yet, but perhaps it is just because there is always easy workaround with script. The downside here is of course that it increases the data transfer in cross process strategies.

i think that data should remain the central input for template engines, easy to reason about. we have scripts as the general place to put logic that transforms the report request somehow, so i think cases like this should be solved in script, we are making the query information already available in the central place of render transformation (script) so it is up to the developer how to use them.

**Comment by pofider** [comment]
> Or another way to pass it through options and let the developer use the custom script to set it to data as he needs. The problem here is that it requires two steps from developer.

> i like this the most, it is the most explicit and expected for me. looks normal that query params will be available in options for the developer to work with them in script, with this developer has the choice if they want those params to be in data, or maybe just use them to fetch data in third party http API without making the query params visible in template data at all. seems to me that the two steps problem can be well justified with this in mind.

Ok, I like your thinking. Lets go with providing it on `options`...

Now I'm not sure what kind of naming I like more. Accessing the query string parameter in script could look like this. The double req unfortunately doesn't look so nice.
```js
function beforeRender(req, res, done) {
  const parA = req.options.req.query.parA
  const headerA = req.options.req.headers['customHeader']
}
```

**Comment by bjrmatos** [comment]
> Now I'm not sure what kind of naming I like more. Accessing the query string parameter in script could look like this. The double req unfortunately doesn't look so nice.

according to [this conversation](https://github.com/jsreport/jsreport/issues/262#issuecomment-300841347) http related things are going to live inside `req.context` so maybe using `req.context.http` looks more natural.

```js
function beforeRender(req, res, done) {
  const parA = req.context.http.query.parA
  const headerA = req.context.http.headers['customHeader']
}
```

**Comment by pofider** [comment]
And the response header would be found on `res.meta.headers`

**Comment by pofider** [comment]
Done in v2 beta. 
https://jsreport.net/blog/jsreport-v2-beta
https://github.com/jsreport/jsreport/releases/tag/2.0.0-beta
