### ISSUE TITLE
query parameters passed to /templates/ break external resources and result in endless loop

### ISSUE THREAD

**Issue by djmurf** [jsreport/jsreport#368]
We have implemented an extension to capture query parameters passed into a report render: 

http://localhost:5488/reporting/templates/B1Hr_bXZG?param1=27465&param2=1111

While this works, whenever a template makes an external asset request: 

<script src="{#asset ../../../static/jquery/dist/jquery.js @encoding=link}"></script>

the module: jsrepoort-assets/lib/assets.js

Does not deal with the query parameters properly.
Line 126: 

`  return base + (req.originalUrl || '/').replace('api/report', '') + 'assets/content/' + assetName
`
Is simply stacking the assetName on the end of req.originalUrl, resulting in a url with a query parameter in the middle. Thus actually ends up calling the report generator again for ever asset defined, resulting an endless loop. 

A simple suggestion would be to strip off all query parameters during the construction of the asset url:

`return base + (req.originalUrl || '/').replace(/\?.*$/, '').replace('api/report', '') + 'assets/content/' + assetName
`

**Comment by pofider** [comment]
Thank you. Makes sense. We will look into it.

**Comment by pofider** [comment]
This should be resolved in `jsreport-assets@0.6.8`. 
Please let us know if it works for you.
