### ISSUE TITLE
Modify JSON provided before render

### ISSUE THREAD

**Issue by samir-kamble** [jsreport/jsreport#370]
Hello,

We recently purchased licensed copy of JSreport and facing a small problem,

We want to modify JSON inputs given to JSreport before execution of Handlebars with help of Javascript.
Can we be able to do it? Please let me know if there is any workaround to this.

Regards,
Sam.

**Comment by pofider** [comment]
You can use scripts extension and write a custom javascript function which alters the input data.
See the documentation and examples here
https://jsreport.net/learn/scripts
