### ISSUE TITLE
Header image is being cut off

### ISSUE THREAD

**Issue by joromeo** [jsreport/jsreport#371]
Hello,

I added the fix to get a header image to display by adding the same image and setting display:none to the body. However the image in the header is being cut off. I have tried adding <br/> tags, padding, and margins in the header file and nothing seems to work. This header is displayed on all pages.

![image](https://user-images.githubusercontent.com/34318257/33890692-f60d66ec-df21-11e7-8cc9-f07836314603.png)

Any ideas?

Thank you.

**Comment by pofider** [comment]
Did you try to increase the header size?
Can you replicate the issue in [playground](https://playground.jsreport.net) so someone can take a look on it?

**Comment by joromeo** [comment]
Hello,

I was trying to increase the height via css styling but that wasn't working. However, while setting up the issue in the playground I noticed that their is a header height option as part of the designer under the phantom pdf properties. After configuring that properly my header is now rendered correctly.

Question to piggy back on this before closing the issue. Can you share the same header and footer files between reports? As in have them in a single folder, 2 files and all reports use a 1file for the header and a 1file for the footer? This way if you have to make a change and you have 10 reports you do not need to change it 10 times?

**Comment by bjrmatos** [comment]
> Question to piggy back on this before closing the issue. Can you share the same header and footer files between reports? As in have them in a single folder, 2 files and all reports use a 1file for the header and a 1file for the footer? This way if you have to make a change and you have 10 reports you do not need to change it 10 times?

you can use [assets](https://jsreport.net/learn/assets) to centralize repetitive content (like repetitive html content), then you just need to add the asset in every header/footer of your reports, when you need to change something you just need to change the asset content without needing to change it 10 times.

**Comment by joromeo** [comment]
Ah ok. I didn't think to add assets to the header and footer.

Thank you.

Closing the issue.
