### ISSUE TITLE
Make one page Landscape and the rest Portrait 

### ISSUE THREAD

**Issue by joshplaetzler** [jsreport/jsreport#372]
I've been trying to figure out if I can turn one page Landscape.   I see how to turn all the pages in a report landscape but not just one.  Not sure this is even possible.  Any help would be appreciated. 
Thanks

**Comment by pofider** [comment]
Unfortunately it is not possible. See more info [here](https://forum.jsreport.net/topic/119/landscape-and-portrait-layout-in-same-report/6).
