### ISSUE TITLE
TaskCanceledException: a task was cancelled while rendering the report

### ISSUE THREAD

**Issue by maikolestevez** [jsreport/jsreport#375]
Good afternoon,

Im trying to render a report that contains too much data and when it takes too long it shows me this message:
TaskCanceledException: a task was cancelled.

If i load less data the report work well.

My question is, there is a way to avoid  TaskCanceledException and let the rendering time take what it has to take to render the report?

The   embeddedReportingServer is already started in WebApiConfig.cs
My Code:
```
   var result = new jsreport.Client.Report();
   var embeddedServer = new EmbeddedReportingServer();

  result = await embeddedServer.ReportingService.RenderAsync(new
                    {
                        template = new
                        {
                            name = "OperacionesDiaria",

                        },

                        data = new
                        {
                          dataCollections:data.ToList()
                          
                        }

                    });
```
                

Thanks

**Comment by pofider** [comment]
I guess you use `jsreport.Client` c# nuget package?

Try to [increase the http timeout](https://jsreport.net/learn/dotnet-client#timeouts)

**Comment by maikolestevez** [comment]
Thanks, i was testing
I add this line of code
   embeddedServer.ReportingService.HttpClientTimeout = TimeSpan.FromMinutes(10);

But now i receive this message:
Unable to render template. Error during rendering report: Timeout when executing in phantom

**Comment by pofider** [comment]
Yes, now you need to increase the default 60s timeout for phantom rendering.

You can do this in c# code if you use `jsreport.Local` by setting [this config prop](https://github.com/jsreport/jsreport-dotnet-types/blob/master/jsreport.Types/Configuration/PhantomConfiguration.cs#L11) 
Or if you use configuration file, you can use [this prop](https://jsreport.net/learn/phantom-pdf#configuration).

**Comment by maikolestevez** [comment]
I add those lines to my config files
 prod.config.json:	
```
	"phantom": {
		"numberOfWorkers": 2,
		"timeout": 180000
	},
	"tasks": {
		"numberOfWorkers": 2,
		"timeout": 180000,
		"strategy": "http-server"
	}
```


dev.config.json
```
    	"phantom": {
    "numberOfWorkers" : 2,
  "timeout": 180000

},
    "tasks": {
        "numberOfWorkers" : 2,
        "timeout": 180000,
        "strategy": "http-server"
    }
```
Im still recieving the same message :
Unable to render template. Error during rendering report: Timeout when executing in phantom.

 is this the right place?

**Comment by pofider** [comment]
yes, are you sure your config files are applied? How do you startup jsreport?

**Comment by maikolestevez** [comment]
I have this
**Helper.cs**
  public static class Helper
    {
        public  static EmbeddedReportingServer embeddedReportingServer = new EmbeddedReportingServer();
    }

 **webApiConfig.cs** 
 ```
            Helper.embeddedReportingServer.StartAsync().Wait();
```
**Controller**
 Helper.embeddedReportingServer.ReportingService.HttpClientTimeout = TimeSpan.FromMinutes(10); 
                    report= await Helper.embeddedReportingServer.ReportingService.RenderAsync(new

I dont know if  is using the config file.
How can i set the server to use it?

**Comment by maikolestevez** [comment]
Thanks to keep helping me,

I add this  befor i start the embedded server 
 ```
Helper.embeddedReportingServer.Configuration = new
            {
  
                phantom = new
                {
                    timeout = 900000,
                    numberOfWorkers = 2
                },


                tasks = new
                {
                    numberOfWorkers = 2,
                    timeout = 900000,


                }

            };
```
Now im getting this error:

"ExceptionMessage":"Unable to render template. Error during rendering report: Command failed: C:\\Api - copia\\App_Data\\jsreport\\app\\node_modules\\phantomjs\\lib\\phantom\\phantomjs.exe --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any C:\\Api - copia\\App_Data\\jsreport\\app\\node_modules\\phantom-html-to-pdf\\lib\\scripts\\standaloneScript.js C:\\Api - copia\\App_Data\\jsreport\\temp\\cce966c0-f08e-11e7-baae-cddbcaa95377settings.html\n","ExceptionType":"jsreport.Client.JsReportException"

**Comment by pofider** [comment]
Hm, it seems that phantomjs fails in the end on its own. Perhaps because reaching memory limits. 
Can you run task manager and check the resource consumption during the process?
After what time it ends exactly?

**Comment by maikolestevez** [comment]
I was testing and this is what i got:

**Phantonjs process         CPU 10% Memory 256MB**
**Time what the process takes to fail is 11 min 30seg**

Im trying to render amchart graphic that has more than 62,689 rows and each row has an object of 8 properties, and it will has more rows.

This report has two more charts but they work well because they doesn't have too many data.

I was thinking to create a single process just with phantomjs that generate an image of the graphic that is giving me problems, and put this image inside of the report after the process finish.

What do you recommend me?

**Comment by maikolestevez** [comment]
I forgot to mention something, the report will be generated in background and is going to be sent to an email address because of that the user wont notice the rendering time.

The PDF just has one page.

The idea is to watch the behavior of  this lines  in the whole day
![nodos](https://user-images.githubusercontent.com/8959257/34525729-55c5c1aa-f076-11e7-99be-012ce43344b0.JPG)

Do you think that making the process individually with phantom could work?

**Comment by pofider** [comment]
Shouldn't you just use some aggregation in the chart? Nobody can see 100 000 points in such chart, or am I wrong?

I think that you end up with the same issue with rendering the chart separately, but you can try it out.

**Comment by maikolestevez** [comment]
I was thinking the same, but i will find some workaround with this.
Congratulations to create this reporter is really helping people.
Thank you, I really appreciate your help.

**Comment by pofider** [comment]
Ok. Thank you for your appreciation. Good luck with workarounds.
