### ISSUE TITLE
Unable to load resource

### ISSUE THREAD

**Issue by DimaSavchenko** [jsreport/jsreport#377]
Hi, guys!
I use jsreport like this: 

```
jsreport.render(request).then(function (resp) {
    fs.writeFileSync('report.pdf', resp.content);
    next(null);
});
```

And not all pictures are rendered. 

![image](https://user-images.githubusercontent.com/11638499/35150985-9abbc674-fd2d-11e7-8cdf-43189a34d191.png)

Logs in a console for each not rendered picture:

 ```
warn: Unable to load resource (#18URL:http://...)
 warn: Error code: 5. Description: Operation canceled 
```

Thanks!

**Comment by pofider** [comment]
Hi, how are the images hosted? It is somewhere on the web? Whats theirs sizes?
Can you try to increase the `template.phantom.resourceTimeout: 10000`?

**Comment by DimaSavchenko** [comment]
Images are hosted on aws. ~7mb.
10000 not enough I set resourceTimeout: 1000000, rendering time is 135801 ms (21 images and all are rendered).
What do you think I can aim a better result without decrease images quality?

**Comment by pofider** [comment]
I would recommend to resize the images on the server where it is hosted before transfer to jsreport server.
Another thing to consider is to use config `phantom.strategy:"phantom-server"`. This would make phantomjs cache the images.
