### ISSUE TITLE
Full docker image - support for phantomJS 2.x

### ISSUE THREAD

**Issue by marekkajda** [jsreport/jsreport#378]
Hi, would it be possible to add phantomJS 2.x version to the full docker image? The current version doesn't support the latest HTML/CSS.

**Comment by pofider** [comment]
Thank you for the suggestion. We will try to include it in the `jsreport@1.9.3` when it comes. You should be able to quickly  build your own image until then.

**Comment by pofider** [comment]
The phantomjs 2 and also chrome-pdf are now part of the full image in the 1.10.
