### ISSUE TITLE
jsreport letter spacing issue on Amazon linux, on Ubuntu it works fine but on Amzon linux letter spacing get disturb.

### ISSUE THREAD

**Issue by awaisayub149** [jsreport/jsreport#379]
Hi I am using jsreport for generate pdf from HTML, i am faicng this issue, jsreport letter spacing on Amazon linux is not good, on Ubuntu it works fine but on Amzon linux letter spacing get disturb.
![selection_039](https://user-images.githubusercontent.com/36033231/35672276-ceeaa780-075f-11e8-9dc8-50cf6cc9270c.png)
this is from Ubuntu

![selection_038](https://user-images.githubusercontent.com/36033231/35672299-e533ad52-075f-11e8-8578-acc2e40ddd3f.png)
and this is from Amzon linux, can any one tell me how fix it?

**Comment by pofider** [comment]
Please try to search [phantomjs issues](https://github.com/ariya/phantomjs/search?q=letter+spacing&type=Issues&utf8=%E2%9C%93) for the solution.

**Comment by pofider** [comment]
Closing as this is not something we can solve. It is a phantomjs topic, so we recommend to search for solution there.
