### ISSUE TITLE
unable to install jsreport

### ISSUE THREAD

**Issue by jagadeesh-vj** [jsreport/jsreport#381]
Hi I am trying out jsreport for the first time. I got it installed by following the instruction.

npm install jsreport-cli -g
jsreport init
jsreport start

Later I uninstalled the jsreport for some reason. The same command used previously to install is not working right now.  I am unable to install jsreport. I have node v8.9.4, NPM 5.6.0 in my machine.

npm install jsreport-cli -g   ---> working correctly
jsreport init    -----> fails.

I get the following error. Please help.

jsreport installation not found, installing jsreport latest version now, wait a moment...
{ Error: Command failed: npm i -S jsreport
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated npmconf@2.0.9: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
invalid config loglevel="notice"
Error making request.
Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)

Please report this full log at https://github.com/Medium/phantomjs
invalid config loglevel="notice"
Error making request.
Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN rollback Rolling back delayed-stream@0.0.5 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\JAGADEESAN\R&D
npm WARN rollback Rolling back hoek@0.9.1 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\JAGADEESAN\R&D\NPM\node_
npm WARN rollback Rolling back readable-stream@2.2.9 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\JAGADEESAN\R&
npm WARN rollback Rolling back node-pre-gyp@0.6.39 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\JAGADEESAN\R&D\
npm WARN rollback Rolling back tar-pack@3.4.0 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\JAGADEESAN\R&D\NPM\n
npm WARN react-copy-to-clipboard@4.3.0 requires a peer of react@^0.14 || ^15 but none is installed. You must install peer dependencies yourself.
npm WARN jsreport-server@ No description
npm WARN jsreport-server@ No repository field.
npm WARN jsreport-server@ No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: phantomjs@1.9.15 (node_modules\phantom-workers\node_modules\phantomjs):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: phantomjs@1.9.15 install: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@1.9.17 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jagadeesan_vadivelu\AppData\Roaming\npm-cache\_logs\2018-02-13T11_31_58_994Z-debug.log

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5) killed: false, code: 1, signal: null, cmd: 'npm i -S jsreport' }
undefined
Error: Unexpected error happened
    at C:\Users\jagadeesan_vadivelu\AppData\Roaming\npm\node_modules\jsreport-cli\lib\commands\_initializeApp.js:19:25
    at C:\Users\jagadeesan_vadivelu\AppData\Roaming\npm\node_modules\jsreport-cli\lib\commands\_initializeApp.js:141:16
    at C:\Users\jagadeesan_vadivelu\AppData\Roaming\npm\node_modules\jsreport-cli\node_modules\npm-install-package\index.js:30:21
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5) {"originalError":{"killed":false,"code":1,"signal":null,"cmd":"npm
(Original) Error: Command failed: npm i -S jsreport
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated npmconf@2.0.9: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
invalid config loglevel="notice"
Error making request.
Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)

Please report this full log at https://github.com/Medium/phantomjs
invalid config loglevel="notice"
Error making request.
Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN rollback Rolling back delayed-stream@0.0.5 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\JAGADEESAN\R&D
npm WARN rollback Rolling back hoek@0.9.1 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\JAGADEESAN\R&D\NPM\node_
npm WARN rollback Rolling back readable-stream@2.2.9 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\JAGADEESAN\R&
npm WARN rollback Rolling back node-pre-gyp@0.6.39 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\JAGADEESAN\R&D\
npm WARN rollback Rolling back tar-pack@3.4.0 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\JAGADEESAN\R&D\NPM\n
npm WARN react-copy-to-clipboard@4.3.0 requires a peer of react@^0.14 || ^15 but none is installed. You must install peer dependencies yourself.
npm WARN jsreport-server@ No description
npm WARN jsreport-server@ No repository field.
npm WARN jsreport-server@ No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: phantomjs@1.9.15 (node_modules\phantom-workers\node_modules\phantomjs):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: phantomjs@1.9.15 install: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@1.9.17 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jagadeesan_vadivelu\AppData\Roaming\npm-cache\_logs\2018-02-13T11_31_58_994Z-debug.log

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5) {"killed":false,"code":1,"signal":null,"cmd":"npm i -S jsreport"}

**Comment by bjrmatos** [comment]
seems like it was just a download error when trying to install phantomjs, can you try again in a fresh directory?

**Comment by jagadeesh-vj** [comment]
Thanks for your reply.

Looks like the proxy setting blocked the installation in windows environment.

**In Linux, the issue got resolved with the help from the below link.**
https://github.com/jsreport/docs/blob/master/installation/ubuntu.md#fixing-phantomjs

**Fixing phantomjs**
Official ubuntu distribution is missing some fonts jsreport needs to be able to render pdf reports. Use following to include them.

**sudo apt-get install build-essential chrpath git-core libssl-dev libfontconfig1-dev**
