### ISSUE TITLE
Dynamic Data Sources

### ISSUE THREAD

**Issue by jsheely** [jsreport/jsreport#382]
I see that you can provide a JSON preview data source. But is there a way to create a data sources that a user could include in their template?

These data sources could be a simple API or a schema to include specific data sources which could then be joined in some way. 

Such as Customers and Products. and you could optionally choose to join them as CustomerProducts

**Comment by pofider** [comment]
You can find [here demo](https://jsreport.net/blog/pdf-reports-in-sql-server) which shows how to create data source from sql. This is done using [server evaluated scripts](https://jsreport.net/learn/scripts).

However there is no visual tool that would let user click through tables and define data source,
