### ISSUE TITLE
better handling of errors caused by trying to initialize jsreport multiple times 

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#384]
original issue here: https://stackoverflow.com/questions/48840565/jsreport-hello-world/48855112

and problem description here: https://stackoverflow.com/a/48855112/4111743

TL;DR: when some code is calling initialize multiple times, jsreport just exit the process with no error message. we should show an error at least or add some code that just process the first initialize call and let the others wait until jsreport is actually initialized.

**Comment by pofider** [comment]
Done. Will be released in v2.

**Comment by pofider** [comment]
Done in v2 beta. 
https://jsreport.net/blog/jsreport-v2-beta
https://github.com/jsreport/jsreport/releases/tag/2.0.0-beta
