### ISSUE TITLE
Downloaded jsreport-win.zip | Executed the jsreport.exe nothing happened | How to use "jsreport-win.zip"

### ISSUE THREAD

**Issue by alexgitub** [jsreport/jsreport#387]
Hi I downloaded the following "jsreport-win.zip"
![image](https://user-images.githubusercontent.com/14552411/36719713-d919370e-1be0-11e8-882e-c79bccede6be.png)
After executing the following "jsreport.exe" nothing happens how do i use this.

Can i use this as a standalone without installe via node.js

**Comment by pofider** [comment]
Please look into docs how to use the "jsreport.exe".
https://jsreport.net/learn/cli

**Comment by bjrmatos** [comment]
more info here: https://jsreport.net/learn/single-file-executable
