### ISSUE TITLE
v2 migration utility

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#388]
I'm planning the following cmd utility to help with migration...
User npm installs jsreport-migration and initiate it through command line.
This utility will boot up v1 jsreport in the current folder and guide user with the following steps guide.

1. Please backup your jsreport app and data
2. Please update to the latest jsreport 1.x the first
3. You seems to have stored images. jsreport v2 doesn't support images extension and rather encourage to use assets instead. Should we migrate images to assets and try to update existing templates to use assets?
4. You seems to have scripts that doesn't follow the correct syntax, you will need to update them manually.
5. You use phantom-pdf recipe which is not part of the jsreport v2. The v2 by default uses chrome-pdf instead. These two technologies produces different output sizes and we cannot automatically convert templates for you. Please choose if you want to keep using phantom-pdf recipe with jsreport v2 or you plan to migrate templates manually to chrome.
6. You use fop recipe. Should we additionally install this recipe to the future v2 instance?
7. Logging TODO
8. You have stored schedules with CRON expression which evaluation is changed to follow standard in v2. You will need to update... TODO
9.  Should we install jsreport v2 now?

**Comment by pofider** [comment]
More technical details about implementation... Important to note that this utility will be useful just in the mainstream jsreport application. This means in application that was installed by the basic steps described in page download. The custom node application as well as single exe users needs to read the upgrade guide. There will be no automation. 

I think we should be pragmatic in the implementation and cover only main cases. The other cases can be quickly covered when we see users having issues.

The flow should be.
The user will install `jsreport-migration` and run it. The utility require jsreport from the cwd and init it. This jsreport instance will be used to check the config values. The `jsreport.documentStore` will be used to migrate images to assets for example.

**Comment by bjrmatos** [comment]
all the migration steps listed are implemented and ready for checks [here](https://github.com/jsreport/jsreport-migration)

**Comment by pofider** [comment]
This is done. We just need to add some notes to the final v2 release.
