### ISSUE TITLE
Header repeating /dynamic naming

### ISSUE THREAD

**Issue by BreeeeAd** [jsreport/jsreport#393]
When I look through the example of "Orders with data fetch script" https://playground.jsreport.net/studio/workspace/SkDFywLpe/3
I saw that the table header keep repeating on every page header. I can't see the CSS file, can you explain how to do that?
Also, I want to know is there any function of customer naming for the pdf file (instead of "report(1)","report(2)")?

**Comment by pofider** [comment]
The `thead` tag is responsible for repeating table header on each page.

Check docs for specifying output report name
https://jsreport.net/learn/api#content-disposition-and-report-name
