### ISSUE TITLE
load custom fonts in linux not working

### ISSUE THREAD

**Issue by elgreatly** [jsreport/jsreport#394]
i read [this](https://forum.jsreport.net/topic/199/phantom-pdf-and-custom-fonts-problem/3) discussion and @pofider said "Unfortunately I was not able to find a solution for this",
is there a solution for this issue or will fix it in the upcoming versions?

it's very useful module to download PDF but i'm using a linux server and need to add custom font to the pdf 

any help will be appreciated
Thanks

**Comment by pofider** [comment]
There won't be new releases of phantomjs. It is being archived.
The problem with fonts you have is not in jsreport but somewhere between os and phantomjs. 
Unfortunately I don't know how to help with it.

Do you have the same problem with [chrome-pdf](https://jsreport.net/learn/chrome-pdf)? It is anyway the new default in the v2 release.

**Comment by pofider** [comment]
The v2 is released, you can try it out with chrome-pdf.

Closing for longer inactivity, but don't hesitate to add more comments. We still monitor this.
