### ISSUE TITLE
ECONNRESET Issues

### ISSUE THREAD

**Issue by yoerivdm** [jsreport/jsreport#396]
Hi, we are testing JSReports and experience some errors (occasionally).

This is what I see from the error:
**read ECONNRESET
Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TCP.onread (net.js:568:26)**

We call JSReports from C#.
Our test-version is 1.8.1, it is hosted on a Windows box and runs the node serveras a service  (non-iis).

Any help/guidance on where to search for a solution would be appreciated.

**Comment by pofider** [comment]
Please try to share more information:

- jsreport logs
- jsreport configuration
- how long the rendering takes for you
- how is the memory consumption for node/phantomjs process during the rendering

**Comment by yoerivdm** [comment]
Can't get logs right now, when the next time the problem occurs, i'll get you all the info.
We'll be updating to v1.10 (including licence) in the coming week.

**Comment by pofider** [comment]
Closing for longer inactivity. Feel free to add more info when you have it. We still monitor this issue.
