### ISSUE TITLE
Validate node version on startup

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#399]
Initial report [here](https://forum.jsreport.net/topic/463/jsreport-v2-beta-released-asking-for-a-feedback/3).

We should validate the minimal node version in jsreport as well as in cli and report back proper message.

**Comment by bjrmatos** [comment]
done.

jsreport -> https://github.com/jsreport/jsreport/commit/47395adf12a296e4600e8ade7bd65433d62a3d57

jsreport-cli -> https://github.com/jsreport/jsreport-cli/commit/3604f4ef6a14fee48bc5768e7f33bcf87d365afc

jsreport-migration -> https://github.com/jsreport/jsreport-migration/commit/957aca8c426e8c74a8f69ea61b63735bb882c14e

**Comment by pofider** [comment]
Thanks.
