### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by johnbester** [jsreport/jsreport#402]
I have embedded jsreport into another app and on startup the following error is logged:
"Error when loading extension TypeError: Cannot read property 'toLowerCase' of undefined".
(I have attached an error log as well as the code for embedding jsreport)

Possible solution:

I have avoided the exception by changing a line in lib/jsreport-fs-store/main.js (line 5). Basically I have added a check to see if the connectionString.name exists before calling toLowerCase() on it.
was:
`if (reporter.options.connectionString && reporter.options.connectionString.name.toLowerCase() !== 'fs')`
changed to:
`if (reporter.options.connectionString && reporter.options.connectionString.name && reporter.options.connectionString.name.toLowerCase() !== 'fs')`

Embedding jsreport code:
>var jsroptions = { phantom: { strategy: 'phantom-server' }, 
>    tasks: { strategy: 'in-process' }, 
>    scripts: { allowedModules: '*' } };
>var jsrdata = { dataDirectory: 'someFolder',  syncModifications: true };
>var jsreport = require('jsreport')( jsroptions );
>jsreport.use(require('jsreport-handlebars'));
>jsreport.use(require('jsreport-phantom-pdf'));
>jsreport.use(require('jsreport-fs-store')( jsrdata ));

Error log:
> - error: Error when loading extension TypeError: Cannot read property 'toLowerCase' of undefined
>TypeError: Cannot read property 'toLowerCase' of undefined
>    at module.exports (/data/projects/nodejs/administrator-nodejs/node_modules/jsreport-fs-store/lib/main.js:5:83)
>    at /data/projects/nodejs/administrator-nodejs/node_modules/jsreport-core/lib/extensions/extensionsManager.js:118:31
>    at tryCatcher (/data/projects/nodejs/administrator-nodejs/node_modules/bluebird/js/release/util.js:16:23)
>    at Promise._settlePromiseFromHandler (/data/projects/nodejs/administrator-nodejs/node_modules/bluebird/js/release/promise.js:512:31)
>    at Promise._settlePromise (/data/projects/nodejs/administrator-nodejs/node_modules/bluebird/js/release/promise.js:569:18)
>    at Promise._settlePromiseCtx (/data/projects/nodejs/administrator-nodejs/node_modules/bluebird/js/release/promise.js:606:10)
>    at Async._drainQueue (/data/projects/nodejs/administrator-nodejs/node_modules/bluebird/js/release/async.js:138:12)
>    at Async._drainQueues (/data/projects/nodejs/administrator-nodejs/node_modules/bluebird/js/release/async.js:143:10)
>    at Immediate.Async.drainQueues [as _onImmediate] (/data/projects/nodejs/administrator-nodejs/node_modules/bluebird/js/release/async.js:17:14)
>    at runCallback (timers.js:763:18)
>    at tryOnImmediate (timers.js:734:5)
>    at processImmediate (timers.js:716:5)

**Comment by bjrmatos** [comment]
to solve this easily without needing you to change something inside jsreport you can pass the `connectionString` in your options:

```js
var jsroptions = { connectionString: { name: 'fs' }, phantom: { strategy: 'phantom-server' },
tasks: { strategy: 'in-process' },
scripts: { allowedModules: '*' } };
```
