### ISSUE TITLE
docs: page-breaks Phantom & Chrome

### ISSUE THREAD

**Issue by yoerivdm** [jsreport/jsreport#403]
Not really an issue but something worth nothing in the docs.
Phantom 2.1.1 and Chrome PDF are capable of using the page-break-inside property in CSS.

https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-inside

It' a nice addition to the page-break props in the docs about PhantomPDF. Tested with JSReport Phantom 2.1.1 and Chrome PDF. 

See: https://playground.jsreport.net/studio/workspace/SyUrRILTg/9398

**Comment by bjrmatos** [comment]
thanks for the recommendation and link to playground, we will make sure to add more info about this in docs. 👍

**Comment by yoerivdm** [comment]
Maybe worth mentioning, self-closing DIV tags (non-standard) for creating pagebreaks are performance-killers in chrome.

With self-closing div's: 
 https://playground.jsreport.net/studio/workspace/ry46PHlTG/2

Non-self closing:
https://playground.jsreport.net/studio/workspace/ry46PHlTG/3

**Comment by pofider** [comment]
Both topics are now noted in the v2 docs. We will merge it to master and make it online soon. Likely the next week.
