### ISSUE TITLE
When outputting to html, ignore pdfutils

### ISSUE THREAD

**Issue by yarongolan** [jsreport/jsreport#406]
HTML output is very useful for CSS debugging. However, if you've configured pdfutils (say for chrome-pdf) when you switch to html it will fail on "Invalid PDF structure"

**Comment by bjrmatos** [comment]
yes, this is default chrome behaviour so you just have to workaround it with some tweaks in the template of your header/footer.

using the following i think i get what you are looking for:

content: 

```html
content
```

header:

```html
<html>
    <head>
        <style>
            html, body {
                margin: 0;
                font-size: 14px;
            }
        </style>
    </head>
    <body>
        <div style="margin-top: -17px">
            header
        </div>
    </body>
</html>
```

footer:

```html
<html>
    <head>
        <style>
            html, body {
                margin: 0;
                font-size: 14px;
            }
        </style>
    </head>
    <body>
        <div style="margin-bottom: -17px">
            footer
        </div>
    </body>
</html>
```

output:

<img width="1581" alt="captura de pantalla 2018-05-14 a las 9 26 16 a m" src="https://user-images.githubusercontent.com/4262050/40003457-fe86aac2-5758-11e8-83ac-4da4cd43f5fb.png">

**Comment by pofider** [comment]
Ok, makes sense. We will skip the pdf utils when template is rendered with non-pdf recipe.
Thank you for suggestion.

**Comment by yarongolan** [comment]
Thanks for the new version!
