### ISSUE TITLE
API call vs Studio call

### ISSUE THREAD

**Issue by ychhajed** [jsreport/jsreport#412]
We upgraded from 1.31. to 2.0 as mentioned in https://github.com/jsreport/jsreport/issues/411

Now when we are trying to call the report VIA API then it fails with some javascript error. Which tells us that the JSON data passed from the API is not read correctly by jsreport . When we run the same in the studio it runs fine. (There is no change in any of the code which generated the API call and also nothing in the JSreport templates.)

What might be the cause for this ? 

Thanks

**Comment by pofider** [comment]
Could you please partially share the request structure? Also the full javascript error could help us to identify if the problem is really in the incoming request.

**Comment by ychhajed** [comment]
The request JSON is same what we have in the studio.
Request structure 
{"template":{"shortid":"rk2wAis2-"},"data":[{}]}

Error returned:
`{
    "message": "Cannot read property 'split' of undefined",
    "stack": "Error: Cannot read property 'split' of undefined\n    at module.exports (/var/app/current/node_modules/jsreport-core/lib/util/createError.js:4:17)\n    at Reporter.createError (/var/app/current/node_modules/jsreport-core/lib/reporter.js:256:12)\n    at Reporter.executeScript (/var/app/current/node_modules/jsreport-core/lib/reporter.js:267:18)\n    at <anonymous>\ncaused by: Error: Cannot read property 'split' of undefined\n    at Array.toHourSec (vm.js:162:19)\n    at eval (eval at createFunctionContext (/var/app/current/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:27:76)\n    at prog (/var/app/current/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)\n    at execIteration (/var/app/current/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)\n    at Object.<anonymous> (/var/app/current/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:73:15)\n    at Object.eval [as main] (eval at createFunctionContext (/var/app/current/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:31)\n    at main (/var/app/current/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)\n    at ret (/var/app/current/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)\n    at ret (/var/app/current/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)\n    at /var/app/current/node_modules/jsreport-handlebars/lib/handlebarsEngine.js:25:14\nFrom previous event:\n    at Reporter.executeScript (/var/app/current/node_modules/jsreport-core/lib/reporter.js:264:47)\n    at invokeRender (/var/app/current/node_modules/jsreport-core/lib/render/render.js:49:36)\n    at module.exports (/var/app/current/node_modules/jsreport-core/lib/render/render.js:122:11)\n    at <anonymous>"
}`

**Comment by pofider** [comment]
The error comes from handlebars helper function. Can you share helpers from template `rk2wAis2-`? The error the most likely comes from line 162.

**Comment by ychhajed** [comment]
Just to let you know: The error represents that the data passed to the function does not have a value, which makes use think that the data passed in JSON is not picked up. Same JSON data works fine in the studio when we run it.
 
Here is the function on line 162 
line 159 : `function toHourSec(data) {

	if(data !== null) {
		var elem = data.split(':');
		var days = 0;
		var hours = elem[0];
		if(hours.indexOf('.') != -1) {
			var array = hours.split('.');
			days = parseInt(array[0]);
			hours = parseInt(array[1]) + (days * 24);
		}
		var mins = elem[1];
		return hours + ":" + mins;
	}
}
`
