### ISSUE TITLE
Attach to existing express app failed in 2.0.0

### ISSUE THREAD

**Issue by samilywang** [jsreport/jsreport#416]
Hi. I try to follow this page's(https://jsreport.net/learn/adapting-jsreport) guide to attach jsreport to an express app. But it doesn't work. Then I downgrade jsreport to 1.10.0, the example code works.

So, any breaking upgrade to attaching to express app? Could someone give a new example?

**Comment by pofider** [comment]
Thank you for your issue. I've just updated article with v2 configuration changes.

See the change highlight...
```js
const jsreport = require('jsreport')({
  extensions: {
	  express: { app: reportingApp, server: server },
  },
  appPath: "/reporting"
});
```
