### ISSUE TITLE
Should be empty: []

### ISSUE THREAD

**Issue by kahwooi** [jsreport/jsreport#42]
After installing jsreport, I found out the app take longer to load, and it give me this message on the console:

```
Should be empty: []
```

Anything to do with the configuration?

**Comment by pofider** [comment]
Should be empty: [] is just a harmless message coming from one of the libraries.

I plan to replace the library in the future but please ignore the message for now.

**Comment by pofider** [comment]
Fixed in the 0.3.0 release
