### ISSUE TITLE
licensing for excel pivot table

### ISSUE THREAD

**Issue by arisliang** [jsreport/jsreport#424]
In the playground, there's excel pivot table (https://playground.jsreport.net/studio/workspace/HyQH-eKv/115). It looks like embedding an online-excel document. Does it require excel license from Microsoft if the page with embedded excel is served on the internet?

**Comment by pofider** [comment]
Hm. That is rather question for another place.

I haven't found an answer after quick search.
I would guess that the online version is free as express limited edition and MS gets the money from full desktop app. However please try some public forums to get valid answer.
