### ISSUE TITLE
External editor - no refresh

### ISSUE THREAD

**Issue by yoerivdm** [jsreport/jsreport#426]
Hi, I just installed a new machine (osx), loaded it with jsreports (1.10) and vscode.
I normally work split-screen, on the one side my browser with a rendered report, other side vscode pointing to the data folder.

Since my reinstall, jsreports does not automatically refresh when editing a file. With some files (eg data), I don't see my changes at all, not even in jsreports editor after saving in vscode. Looks like refreshes are screwed by some kind of cache?

Any pointers on how to fix this? I'm used to this workflow which is very productive (for me) ...

Kind regards
Yoeri

**Comment by pofider** [comment]
Glad you like this feature. I like it as well.

The modifications syncing is disabled when the env variable NODE_ENV is equal `production`. Maybe you have it set?
In every case you can force syncing by changing the configuration file with

```js
"connectionString": {
    "name": "fs",
    "syncModifications": true
  }
````

**Comment by yoerivdm** [comment]
Can't get it to work :-(
I installed watchman on osx ... but after installing jsreports, maybe that's the issue?

**Comment by pofider** [comment]
@bjrmatos Can you try it on your osx? It seems to work for me on win.

**Comment by bjrmatos** [comment]
watch mode still works for me in OSX (El Capitan) with 1.10.

@yoerivdm not sure if watchman is causing you that problem but maybe you can try to open this [file](https://github.com/jsreport/jsreport-fs-store/blob/1.2.4/lib/persistence.js#L65) in your `node_modules` and change some [options](https://github.com/paulmillr/chokidar/tree/1.6.1) there, maybe you can pass `usePolling: true` to the options of `.watch` and see if it changes something for you.

**Comment by yoerivdm** [comment]
thanks, i'll try this today ... sorry for the late answer

**Comment by yoerivdm** [comment]
@bjrmatos It works by adding the autoPolling option! 👍 
productivity++  ;-)

**Comment by bjrmatos** [comment]
nicee, we don't have plans to add an option to control `usePolling` for watch files in v1, but in v2 `usePolling: true` is the default and we are adding new option there to disable it if needed. so you will have control over this when you migrate to v2 👍

**Comment by yoerivdm** [comment]
Thanks, we’ll look into upgrading soon :-)
