### ISSUE TITLE
Using recipe 'chrome-pdf' i cannot render the background for the Header Footer templates 

### ISSUE THREAD

**Issue by HgsTGitHub** [jsreport/jsreport#427]
Using 'chrome-pdf' as recipe I cannot seem to render the header and footer templates with the correct css classes. 

In the chrome options i set displayHeaderFooter=true and printBackground= true , but the css only works when rendering the main template not the header/footer templates.

**Comment by pofider** [comment]
Can you replicate your issue here? Thank you
https://playground.jsreport.net/

**Comment by HgsTGitHub** [comment]
Hi, I tried but the online version is incomplete, if you choose 'chrome-pdf' you don't even have the options of adding a header or footer, but if you use the version that you install 2.1.0 it does have the options.

**Comment by pofider** [comment]
Ah ok, there is an older version. We are currently working on updated.
Sorry.

Please let me know how do you add css to the header? Through link?
I am not sure this will work there. I think you need to add the styles inline.

**Comment by HgsTGitHub** [comment]
Each Header and Footer template uses its own css, but the background is not printing, which is the problem.

**Comment by pofider** [comment]
How about you export your templates using "right toolbar settings/export" and share it so I can take a look? In case you have no sensitive information there. Thank you

**Comment by pofider** [comment]
Here I see the problem mentioned
https://github.com/GoogleChrome/puppeteer/issues/2182

with solution using css
```css
-webkit-print-color-adjust: exact
```

Could you please try it out?

**Comment by HgsTGitHub** [comment]
I used the line in my css and it worked, for now I believe it is the solution, thank you very much.

**Comment by pofider** [comment]
I updated docs to include the workaround for this chrome bug

https://jsreport.net/learn/chrome-pdf
