### ISSUE TITLE
Incorrect handling of DPI scaling in PhantomPDF

### ISSUE THREAD

**Issue by orobert91** [jsreport/jsreport#428]
We have developers that use 4k monitors on their development machines so Windows scaling is set to 400%. Problem is PhantomPDF incorrectly handles Windows DPI scaling and renders everything 400% smaller.

Is there a solution to this or I need to wait the official transition from messy/buggy PhantomPDF to Headless Chrome to be completed?

Putting global CSS scale is a messy workaround I prefer not to use, because we have to change the code when switching development environments/workstations.

Report render with Windows scaling set to 400%:

![image](https://user-images.githubusercontent.com/6403705/41886289-bc867aac-78c9-11e8-80ef-863367177521.png)

Report render with Windows scaling set to 100%:

![image](https://user-images.githubusercontent.com/6403705/41886340-eee0b2ce-78c9-11e8-8cd4-80694b1c6357.png)

**Comment by pofider** [comment]
Is there something blocking you from switching to chrome?
The phantomjs scaling issue is big pain without a clear solution I am afraid.

**Comment by orobert91** [comment]
Yes, unless I am mistaken headless Chrome recipe is not available on .NET (it isn't even available in the recipe enumeration). What is the expected release date for .NET?

**Comment by pofider** [comment]
I shipped pre-release of the nugets for v2. Unfortunately nuget is stuck in some validation. I ping here when it is ready.

**Comment by pofider** [comment]
The pre-release nugets are availible and include chrome recipe by default. Please give it a try.

**Comment by orobert91** [comment]
I have given it a try and encountered some issues: 

- https://github.com/jsreport/jsreport-chrome-pdf/issues/15
- https://github.com/jsreport/jsreport-chrome-pdf/issues/16
