### ISSUE TITLE
Pdf report not working with forever

### ISSUE THREAD

**Issue by kahwooi** [jsreport/jsreport#43]
I try to deploy it to production using forever, and the PDF report does not load at all:

I have a default prod.config.json:

```
{
    "certificate": {
        "key": "certificates/jsreport.net.key",    
        "cert": "certificates/jsreport.net.cert"
    },
    "connectionString": { "name": "neDB" },
    "httpsPort": 443,
    "blobStorage": "fileSystem",
    "cluster": {
      "numberOfWorkers": 2,
      "enabled":  false
    },
    "phantom": {
        "numberOfWorkers" : 2,
        "timeout": 180000
    },
    "tasks": {
        "numberOfWorkers" : 2,
        "timeout": 10000
    }
}
```

**Comment by pofider** [comment]
I have just tried to install jsreport on ubuntu machine and run it with 
`sudo forever -m 5 server.js` and I was able to render a pdf in the designer. 

It is just an issue of pdf and html works?
phantomjs maybe missing some fonts, on ubuntu you need to install them using
`sudo apt-get install build-essential chrpath git-core libssl-dev libfontconfig1-dev`

Does it work without forever?

**Comment by kahwooi** [comment]
Yes it works without forever.

**Comment by kahwooi** [comment]
I am using Windows for development, maybe i will take some time to test it on Linux.

Basically this is what did, it is very simple, most of the time will stuck at report.render({:

```
var html = jade.renderFile(path.resolve(__dirname + '/..') + '/views/report/report.jade',  JSON.parse(data));

                report.render({
                    template:{
                        content: html,
                        phantom: {
                            footer: "<div style='text-align:center'>{#pageNum}/{#numPages}</div>"
                        }
                    }
                }).then(function (out) {
                    out.result.pipe(res);
                });
```

**Comment by pofider** [comment]
What is the code for initializing jsreport, the instance of `report` in your snipped?

Btw I have just fixed freezing during debugging what may help you, I will release it soon also into npm.
https://github.com/jsreport/jsreport/commit/bba36532e78c67f54060481694cf9835758b5027

**Comment by kahwooi** [comment]
I just declare it globally:

```
var report = require('jsreport');
```

**Comment by pofider** [comment]
That should be ok, following works for me on ubuntu with forever:

```js
var http = require('http');
var report = require("jsreport");

http.createServer(function (req, res) {
    console.log("rendering");
    report.render({
        template: {
            content: "<h1>Hello World</h1>",
            phantom: {
                footer: "<div style='text-align:center'>{#pageNum}/{#numPages}</div>"
            }
        }
    }).then(function (out) {
        console.log("done");
        out.result.pipe(res);
    }).fail(function (e) {
        console.log(e);
    });
}).listen(80);

```

**Comment by pofider** [comment]
Closing this because of long inactivity. Feel free to reopen.
