### ISSUE TITLE
HTTP headers is missing within req.context.http

### ISSUE THREAD

**Issue by AlsonVamp** [jsreport/jsreport#434]
Hi. I'm trying to get http headers of request inside beforeRender() function, but there is no such object and `req.context.http`  structure is `{ baseUrl: 'http://localhost:5488', query: {} }`.  I'm using jsreport/jsreport:2.1.1 docker image.

**Comment by pofider** [comment]
This seems to work for me. Can you share more details, how the script looks like, how the request looks like...

![image](https://user-images.githubusercontent.com/2041960/43064468-4cafb850-8e5f-11e8-8ac6-203d3af8fb90.png)

**Comment by AlsonVamp** [comment]
Sure. Thank you very much for the fast response. My goal is to take the authorization header from POST request to jsreport api and propagate it to secured endpoint of my data server. 

With jsreport v1 I'm able to fetch the headers like that: 
![jsreport_v1](https://user-images.githubusercontent.com/670416/43102272-51d25558-8ed3-11e8-9cce-bb99096cf8d3.png)

But jsreport v2 request object has no http `headers` within :
![jsreport_v2](https://user-images.githubusercontent.com/670416/43102753-a7f72a3e-8ed4-11e8-9030-d1004a2bdb6c.png)

**Comment by AlsonVamp** [comment]
Got it, thank you @pofider !

**Comment by bjrmatos** [comment]
done, we just need to update `jsreport-core` and `jsreport-express` deps of jsreport in order to land this.
