### ISSUE TITLE
Best practices for team development on jsreport?

### ISSUE THREAD

**Issue by jLouzado** [jsreport/jsreport#439]
Hello,

Just gotten my team onto jsreport for building our reports and it's amazing, but now I'm running into a small problem.

Basically I'm trying to bring the entire jsreport app under git version control, so that a dev just has to run `npm install && npm start` and they'll have a jsreport server running locally.

The problem though, is that it's putting the `authentication` configuration into the repo; basically the admin username and password.

How do i bring the project under source control without exposing my configuration keys?

**Comment by bjrmatos** [comment]
> How do i bring the project under source control without exposing my configuration keys?

there are [multiple ways to specify configuration](https://jsreport.net/learn/configuration#configuration-sources), one that could help you with sensitive values is specifying it using [env vars](https://jsreport.net/learn/configuration#environment-variables), you can remove the admin username and password from your config file and just ensure that when jsreport is started env vars like `extensions_authentication_admin_username` and `extensions_authentication_admin_password` are defined, with that will be up to the developer to start jsreport with the correct env vars set, for example they can use this command to do it `extensions_authentication_admin_username=admin extensions_authentication_admin_password=xxx npm start`.

of course you can even automate this by storing this sensitive values in a `.env` file and ignore this file in git, then you just need to add some logic to the entry point of your app (`server.js` in case of jsreport project) that loads this file at startup and set `process.env` before jsreport starts.

and remember, what i have described is just one possible solution, you can try many other options, the sky is the limit, it just depends how your team is more comfortable working
