### ISSUE TITLE
2.1.1 problems with the new Commit menu item

### ISSUE THREAD

**Issue by MolallaComm** [jsreport/jsreport#440]
I've been playing around with the new version of jsreports to see how hard it will be to upgrade and also thinking how best to organize our growing number of reports.  I really like the versioning feature - however - a few things I notice:

1. Sometimes the uncomitted changes screen won't show anything (even when there are lots of changes) until I manually reload the whole page - i.e. do a shift reload on http://localhost:5488.

2. There seems to be quite a few bugs where if you rename objects - Commit gets confused - sometimes reloading will help - but at the moment I seem to have gotten it into a state where on the uncomitted changes page it is still showing the old names and will not get rid of them (oddly if i click on each item it shows 0 changes probably because the file no longer exists).  If I restart the server everything sorts itself out so it isn't a huge issue.

3.  This is just using the builtin version control module - not the git - although I suspect it may have similar problems - i may play with it next and if I find problems will update the issue.

**Comment by pofider** [comment]
Thank you for the issue.

Would you be able to describe a pattern when this happens? I would love to be able to replicate it and solve it. If you are not able to replicate it consistently, could you open F12 tools and check console for errors when the page gets stuck?

**Comment by pofider** [comment]
We fixed several bug fixes in the version control in the latest [2.3.0](https://github.com/jsreport/jsreport/releases/tag/2.3.0) release.
Please open a new bug if update doesn't help.
