### ISSUE TITLE
Studio ability to fetch data on tab focus

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#441]
Some tabs (use cases) like version control commit history should fetch the data on tab focus, not just the first time. this feature replaces the need for "refresh" button in tabs. There are also other use cases like "Startup" page which would benefit with this new feature. 

There should be an ability for tab/editor to run fetch on tab focus.

**Comment by bjrmatos** [comment]
tab focus = when the tab is active (tab is the one visible of the rest of tabs)

(just a note for my future-self 😃)
