### ISSUE TITLE
JSReport Server goes down without any Error

### ISSUE THREAD

**Issue by cvvm** [jsreport/jsreport#445]
We have installed a licensed version of JSReport in production environment. The JSReport server goes down without any error messages in the log files. 
We are not sure how to proceed

**Comment by pofider** [comment]
It would help to provide more information for the start.
What os do you run on? Do you run a "tool" to run jsreport? Like a windows service, forever or pm2?
Are you able to replicate the crash?

Did you check windows events logs in case of windows or system logs an dmesg in case of windows?

**Comment by pofider** [comment]
Closing because of missing response.
