### ISSUE TITLE
Confused with license and options

### ISSUE THREAD

**Issue by skayablars** [jsreport/jsreport#449]
Sorry for the question but I'm confused with the licencese is there a way that I can use jsreport for commercial use with my own servers? 

And the 5max template is this only for the template studio provided with the web jsreport or all template studios included those that are on my own server?

**Comment by pofider** [comment]
The free plan can be used in commercial projects with only one limitation. You can store maximum 5 templates in the jsreport store. The template entities are typically created and persisted to store using jsreport studio UI. The templates sent to the jsreport render API with full specification doesn't count to this. In other words the requests which includes in the body `template.content` are not using stored template. To be sure you can always open jsreport studio and verify how many templates are visible there.

The studio also warns in the modal dialog that the maximum number of templates was reached and one month trial in which you can use infinite templates started.
