### ISSUE TITLE
Missing values in phantom-pdf export

### ISSUE THREAD

**Issue by thekalinga** [jsreport/jsreport#45]
When I try to export the Charts drill down from playground, I see that the bars are missing from the pdf output. This chart can be seen properly if we use html option.

Can u please verify whether this is a bug/not.

This issue can be verified at https://playground.jsreport.net/#/playground/Z1EmF0bOt

This is from the phantom-pdf export

![image](https://cloud.githubusercontent.com/assets/452518/6131524/9f98bdd2-b172-11e4-812e-3bd8b79c9e55.png)

This however is from html recipe

![image](https://cloud.githubusercontent.com/assets/452518/6131581/048ae404-b173-11e4-8a9d-aa6b2f795cbf.png)

**Comment by pofider** [comment]
This is probably caused by the highchart animation. To solve it you can set up **print delay* in the phantom menu or remove the animations from in the highchart options (https://playground.jsreport.net/#playground/e77zeliQO/2)

**Comment by thekalinga** [comment]
Thanks..

After setting animation to false, the chart is being exported properly.

PS: The link you shared is not working. If I try with html recipe, it throws *Uncaught ReferenceError: $ is not defined*

**Comment by pofider** [comment]
True, just remove "http:" from the script references and it will work.

**Comment by thekalinga** [comment]
Thanks..
