### ISSUE TITLE
Add Values to particular column/row in EXCEL

### ISSUE THREAD

**Issue by A-Pradeep** [jsreport/jsreport#453]
Hello, i wanted to add JSON /value to a particular column and row of the excel.
I'm using the following demo code 
```
    {{xlsxRemove "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row" 1}}
{{#xlsxAdd "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row"}}
<row>
    <c t="inlineStr"><is><t>Hello</t></is></c>
<code to B4> Name:
    
</row>
{{/xlsxAdd}}
{{{xlsxPrint}}}
```
Since i'm new i need to know how can i insert  the `Name` to the B4 of the excel . and even for B5 or C8 something like this.
What is the code to insert to a specific row and column of the excel

Thank You

**Comment by bjrmatos** [comment]
you can try something like this: https://playground.jsreport.net/w/bjrmatos/eNM0J4nH

if the row already exists you should use `xlsxReplace` helper, if not then you should add the row with `xlsxAdd` and put there all the cells

**Comment by A-Pradeep** [comment]
Hey, thanks for the reply and link , but i'm still no understanding  how can i put the values at single cell or target the single cell. As in the link you have provided , what will be the code if i want only `D2` to be at the `D column` and `5th row`, is it possible to do this way , and i'm sorry to say , i'm also confused with this `row already exists` and  `row doesn't exists` in what reference this row is related to . is it refer to the excel , because if it does , it doesn't make any sense !
Help me out

**Comment by A-Pradeep** [comment]
> you can try something like this: https://playground.jsreport.net/w/bjrmatos/eNM0J4nH
> 
> if the row already exists you should use `xlsxReplace` helper, if not then you should add the row with `xlsxAdd` and put there all the cells

Hey, thanks for the reply and link , but i'm still no understanding how can i put the values at single cell or target the single cell. As in the link you have provided , what will be the code if i want only D2 to be at the D column and 5th row, is it possible to do this way , and i'm sorry to say , i'm also confused with this row already exists and row doesn't exists in what reference this row is related to . is it refer to the excel , because if it does , it doesn't make any sense !
Help me out

**Comment by bjrmatos** [comment]
>what will be the code if i want the value only D2 to be at the D column and 5th row

it will be 

```html
{{#xlsxReplace "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row[4].c[3]"}}
    <c t="inlineStr"><is><t>{{row1.a}}</t></is></c>
{{/xlsxReplace}}
```

pay attention at this part: `worksheet.sheetData[0].row[4].c[3]`, here our target is row with index `4` (5th row) and cell with index `3` (`A` is equal to `0` so `D` will be `3`)

>i'm also confused with this row already exists and row doesn't exists in what reference this row is related to . is it refer to the excel , because if it does , it doesn't make any sense !

it refers to excel, it does not matter that when you open excel in Office you see infinite rows, the reality is that rows are just created in demand.. when you add some content at that row, at least that is the case when using an excel editor. so if your xlsx template file constains some rows pre-created you can replace its value with the `xlsxReplace` helper given a specific row index or row index + cell index, but when there was no row pre-created you will need to use `xlsxAdd` helper to create the row in the end. you will know when to use `xlsxReplace` or `xlsxAdd` depending on the contents of your xlsx template file, when a row does not exists at certain position and you try to use `xlsxReplace` then you will see an error.

**Comment by AsharDweedar** [comment]
is there any way to keep the styles of the original cell and replace only the text?

**Comment by AsharDweedar** [comment]
Never Mind, I just replaced the `<is />`:
```
        {{#xlsxReplace "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row[15].c[9].is"}}
            <is><t>{{ name }}</t></is>
        {{/xlsxReplace}}

```
