### ISSUE TITLE
Concurrent request performance

### ISSUE THREAD

**Issue by alj1s** [jsreport/jsreport#457]
I'm seeing some degradation in performance when jsreport is servicing concurrent requests.

When running jsreports on a virtual machine it takes on average (mean) 2120ms to render a single pdf of 32 pages. 90% of requests are rendered within 2385ms. For our requirements, this is just about acceptable given the hardware.

These results were obtained running on a VM running on AMD Opteron(tm) Processor 6278 (16 core 2.4GHz, with a single core assigned to the VM) with 4GB of RAM. The chrome-pdf recipe was used.

However, if I run 4 browsers and submit the same template to be rendered to pdf then each request takes over 6000ms. As I'm looking at using this in an app which may have 400 concurrent requests I'm concerned that jsreports would not be suitable for my use-case. Further this performance seems unexpected based on the figures quoted here: https://jsreport.net/blog/pdf-reporting-performance

The template html is static html generated from an angular app dashboard and it consists of 10 svg charts generated from visualization created using d3.js and sections of descriptive text. Removing all svg the pdf is rendered in around 1500ms just rendering the html (with svg but using the html recipe) takes around 100ms

Are these figures expected?

**Comment by ximenean** [comment]
@pofider thanks for your response.

Sorry I wasn't clear. I'm not planning to use a single VM for production use, I'm evaluating jsreport currently and I'm using a single VM for that evaluation.

If I run jsreport on a Macbook Pro with a 2.7GHz i7 (quad core) then I can render the chosen report with the following performance:

1 request - 1.6s
2 concurrent requests - 2s
4 concurrent requests - 3s
8 concurrent requests - 4.2s

Based on the performance on the VM I wanted to get a rough idea of what setup we'd need in production to support 400 concurrent requests (max). I don't think we'd be able to support spinning something like 100 instances. We're looking to be able to submit the request and render pdf in the browser in around 2s.

I would be interested to try out reusing chrome instances. Let me know what I need to do.

**Comment by pofider** [comment]
Update your `jsreport-chrome-pdf` extension using

```
npm i jsreport-chrome-pdf@1.2.0
```

Then alter config with

```js
{
  "templatingEngines": {
    "timeout": 60000,
    "strategy": "http-server",
    "numberOfWorkers": 4
  },
  "chrome": {
    "timeout": 40000,
    "strategy": "chrome-pool",
    "numberOfWorkers": 4
  }
}
```

This will configure jsreport to spin up several node and chrome process workers which are reused over multiple requests. Try to play with `numberOfRequests` to get the best results.
