### ISSUE TITLE
Couldn't Open workbook - Excel Error  & Chrome-pdf error

### ISSUE THREAD

**Issue by A-Pradeep** [jsreport/jsreport#459]
Hi, im using the JSReport on the server CentOS 6.10, and i've noticed that some of the excel files are not working in the JSReport. For example i have demo Excel file . Which has some calculations and other chart stuff.
If i upload this demo excel inside the JSReport and hit run i'll get the error that

```
Couldn't Open workbook
We're sorry, we couldn't open your workbook. It's possibly corrupt or using a file 
format that's not supported.
```
But the same excel file is running fine in the Excel Online also . Even the file is stored with xlsx extension inside jsreport server.
Even after uploading correct (error free ) excel and download the excel  result in the `corrupted excel` , but same excel template , is uploaded in the online excel and i won't face any error while uploading , downloading or working with it. Below link , i've uploaded the online excel template (from Office 365). 

[Excel in playground](https://playground.jsreport.net/w/A-Pradeep/P7YQXJmz
)
The template linked is the general excel template from the office , even this also not working.

**Chrome-PDF**  
when it comes to the chrome-pdf , im facing the unusual error,
```
Error: Failed to launch chrome!
/ht/jsreportapp/node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
```
i'm running it on the CentOS 6.10 , and even reinstalled it twice ,but in the website its given for the centos 7

Any ways i can solve these both problems

**Comment by pofider** [comment]
Regarding chrome... Did you follow our installation instructions for CentOS
https://jsreport.net/learn/centos

**Comment by pofider** [comment]
Can't you upgrade to centos 7? We have tested the installation instructions on it.
Here is a troubleshooting thread for  centos, perhaps you will be able to figure it out from it
https://github.com/GoogleChrome/puppeteer/issues/391

**Comment by pofider** [comment]
Yes I have the excel problem investigation in my tasks queue. Unfortunately I am on the road now with limited time and without excel license on the laptop. I will take a look during the weekend. Hope it is enough for you.

**Comment by A-Pradeep** [comment]
Thank you and looking for your response.

**Comment by A-Pradeep** [comment]
@pofider  Hi , any updates on the Excel issue ?

**Comment by pofider** [comment]
I've spent with it half day but so far no solution.
The problem originates in the sax parsing library we use. 
It will take me some more time to figure it out.

**Comment by pofider** [comment]
Please update jsreport-xlsx and try again.

```js
npm i jsreport-xlsx@2.0.3 --save --save-exact
```

It took me a while to track the bug in thirdparty coffee script implemented library.
Now it should be fixed.

**Comment by A-Pradeep** [comment]
That's great news ! 
I'll test it out surely.
