### ISSUE TITLE
jsreport as a npm package is vulnerable

### ISSUE THREAD

**Issue by massimilianorango** [jsreport/jsreport#462]
Running `npm audit` when installing the latest version of jsreport will report some vulnerabilities, 7 High and 1 Low. 
The High ones are caused by the subdependecy `request`: https://nodesecurity.io/advisories/720
The Low one is caused by the subdependency `compression`: https://nodesecurity.io/advisories/534

I think that updating the dependencies to the latest stable versions should do the job.

**Comment by pofider** [comment]
Hi,
we update dependencies regularly. No need to open a specific issue for it.
Please see this comment for details
https://github.com/jsreport/jsreport/issues/354#issuecomment-377030562
