### ISSUE TITLE
ESET kills jsreport.exe which tries to call Win32/NSSM.D

### ISSUE THREAD

**Issue by GrigoryDev** [jsreport/jsreport#463]
Hi,

I'm trying to implement JSReport in my project but ESET Antivirus kills jsreport.exe which tries to call "Win32/NSSM.D". I get "Potentially unsafe application removed" error.

Why it happens and what's your suggestions on that?

**Comment by bjrmatos** [comment]
hi! about the why it happens, it is probably because ESET somehow thinks that jsreport is a unknown app and blocks it by default, so one thing you can try is to mark jsreport as a safe application or exclude it for antivirus scans.

**Comment by GrigoryDev** [comment]
The problem is that it blocks jsreport.exe file which is located at the temprorary path such as
C:/Users/UserName/AppData/Local/Temp/jsreport/dotnet/binary-default-2.2.0.0/jsreport.exe
That way I can't add any exclusion to ESET. More problems come if the folder will be changed according to the new package version.

**Comment by pofider** [comment]
Hm. I don't know why esset doesn't like it. 
Maybe it is an option for you to exclude the whole folder `C:/Users/UserName/AppData/Local/Temp/jsreport`

Or run your app through docker.

Or run full standalone jsreport and just connect to it using `jsreport.Client` from your .net application.

I know, probably not something you would like to hear, however it takes time to find out what in particular ESET doesn't like about our binary.

**Comment by GrigoryDev** [comment]
I've excluded the whole folder, and it seems to work fine now but this ESET behavior is pretty odd. Please kindly update this issue in case you resolve this issue some day. Anyways, thanks for your time!
