### ISSUE TITLE
add `resolveEntityFromPath` to jsreport-proxy (scripts) and expose `resolveEntityPath`, `resolveFolderFromPath `

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#468]
with the addition of folders to jsreport, we allow entities with the same name to exists as long as they are in different hierarchies, because of that queries inside scripts that does something like this

```js
await jsreportProxy.documentStore.collection('assets').findOne({ name: 'base.pdf' })
```

will probably return something not expected when there are more than one entity with the same name, the solution for this will be to add the `folder` property to the query and use that if you want to search for an entity at a specific folder

```js
await jsreportProxy.documentStore.collection('assets').findOne({ 
  name: 'base.pdf',
  folder: { shortid: '<shortid of parent folder>' }
})
```

however to do that you must know the `shortid` of the parent folder, which is not something intuitive to remember when working on these queries.

a solution for this will be to use a helper function like `resolveEntityFromPath` (which the implementation will be done in core and exposed in proxy) which would be used like this:

```js
const entity = await jsreportProxy.folders.resolveEntityFromPath('/path/to/entity')
```

**Comment by bjrmatos** [comment]
additionally it would be nice if we expose the current `reporter.folders. resolveEntityPath` and `reporter.folders.resolveFolderFromPath`

**Comment by pofider** [comment]
This is on proxy already since v3 at least.
