### ISSUE TITLE
import into folder should generate entities with new _id, shortid and updated references

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#471]
it will be nice to support importing entities inside a specific folder, it will give you a new namespace to import, which won't have conflicts, so you will be able to have all entities that an specific import was contained

**Comment by bjrmatos** [comment]
for now when import into folder mode is on, we will throw error when we found entity with duplicated _id. 

the goal of this feature was that it will always insert all the entities of zip into a folder, for that we need to resolve #473 first and then generate new _id, shortid and update references when importing into folder. until then this feature works as long there is no duplicate between the local entities and the entities from zip.

**Comment by pofider** [comment]
solved in 2.9.0
