### ISSUE TITLE
have a single way to know which property contains the name of an entity

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#472]
we should have just one way to get the name property of an entitySet, right now in studio we use the [nameAttribute](https://github.com/jsreport/jsreport-studio/blob/07522969d15992d841a7ce1208cdc8aafd079e69/src/Studio.js#L71) specified when `addEntitySet` in called in client-side part of extensions. on the server we get this information from `model.entitySets[<set name>].entityTypePublicKey`. 

we should probably just use the information defined from the entity set (server) in both contexts (client, server) and avoid having two sources

**Comment by pofider** [comment]
I hope we will in v3 migrate to entity sets with strict conventional attributes: _id, name, shortid, modificationDate
So this shouldn't be needed.
