### ISSUE TITLE
add some metadata to entity type to be able to recognize that property is a reference to another entity

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#473]
we should be able to find which properties of an entity contain references, this will allow us to implement more reliable migrations in the future, and will let us see how entities are linked between them, probably enabling us to make some updates to this references automatically.

**Comment by bjrmatos** [comment]
implementing this will help with more complex cases of import, for example we would like that the import into folder feature #471 to be able to import all the entities of zip into target folder. 

in this case when entities with same _id exists we want that the entity of the zip to be inserted (not updated) on the store, for that we need to generate new id for the entity, when we do this we need to also generate new shortid because if we don't do that we will end with entities with duplicated shortid in store, the problem with generating shortid if that we will break references to scripts, data, etc so in this case we need a way to update all the references because of the new shortid, in this case the metadata in entity type will help to recognize which properties hold this references to other entities.

**Comment by pofider** [comment]
solved in 2.9.0
