### ISSUE TITLE
chrome based recipe printing images

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#478]
We could use [puppeteer screenshot](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagescreenshotoptions) function to print images instead of pdfs.

This time the `jsreport-chrome-pdf` repository should host all code and push two recipes to the jsreport.
`chrome-pdf`
`chrome-image`

**Comment by bjrmatos** [comment]
done in https://github.com/jsreport/jsreport-chrome-pdf/commit/6d236c7453c04e6338568656369999b46c313262
