### ISSUE TITLE
PCI SCAN issues

### ISSUE THREAD

**Issue by pranavstark** [jsreport/jsreport#479]
Hi,

I ran a PCI Scan using Qualys on my jsreport server which has authentication enabled (using jsreport's built-in authentication module).

Issues found in scan -
1. Web Server Uses Plain-Text Form Based Authentication
2. Session Cookie Does Not Contain the "Secure" Attribute
3. AutoComplete Attribute Not Disabled for Password in Form Based Authentication
4. Sensitive form field has not disabled autocomplete

Are these issues already logged, If so what are the timelines. If you think these issues fixes can be done in couple of hours can you please guide me how to fix these issues.

**Comment by pofider** [comment]
Thank you. We will take a look at what we can do with it.

**Comment by bjrmatos** [comment]
> 1. Web Server Uses Plain-Text Form Based Authentication

this just means that the login form is being exposed in page that does not use https/ssl, to fix this you just need to use jsreport with https, either by using configuration `httpsPort`, and `certification` in the [webserver configuration part of configuration file](https://jsreport.net/learn/configuration#web-server-configuration) or by using some kind of proxy (like nginx) in front of jsreport.



> 2\. Session Cookie Does Not Contain the "Secure" Attribute

*this needed [a change in one of our extensions](https://github.com/jsreport/jsreport-express/commit/386a3ffbcaf1702b65e24686f4a896fb570d6914) to make it work, so please wait until we do the release of it before trying it, after the release you can follow the instructions bellow to try it.*


you can set the `Secure` attribute of the session cookie that jsreport uses by adding this to your configuration:

```js
{
  "extensions": {
	"authentication" : {
	    "cookieSession": {
	        "secret": "<your secret here>",
		    "cookie": { "secure": true }       
	    }
	}
  }
}
```

the import part is `"cookie": { "secure": true }` which configures the session cookie to be secure, but keep in mind that when you do this change you need to have your server running over https, so it needs that you resolve the security issue nº 1 first



> 3\. AutoComplete Attribute Not Disabled for Password in Form Based Authentication

we had updated the login form fields to disable autocomplete, so this will be part of new release

>4\. Sensitive form field has not disabled autocomplete

we had updated some fields that we think that are sensitive, however the issue description is too general to we can't know for sure if there is some other field that needs to be updated, so if after the release you have more description or maybe the exact list of fields that needs to be updated according to Qualys then it will help that you let us know.
