### ISSUE TITLE
jsreport-server installation undefined port

### ISSUE THREAD

**Issue by Condor2708** [jsreport/jsreport#48]
After I run the command "node server.js --install" i received the following command
2015-02-18T16:01:52.633Z 
- info: reporter initialized
service jsreport-server is running. go to https://localhost:undefined

Also there is a possibility to run jsreport under http protocol and choose another port?
For example http://127.0.0.1:5535 ?

Thanks at all!!

**Comment by pofider** [comment]
Maybe it is just a bug in the cmd message. Can you check if the jsreport is not actually running on https://localhost:443 ?

Also did you run 
`node node_modules/jsreport --init`
before? 

There should be prod.config.json in the application directory afterwards. There you can modify httpsPort attribute with another port number. Or replace httpsPort with httpPort to run without ssl.

**Comment by Condor2708** [comment]
Hi Jan, Thanks for the quick answer.
Yes I have ran the node node_modules/jsreport --init and it was initialized correctly.
I changed the prod.config to use it without ssl and everything works fine. There is a documentation repository for the prod.config.json file?

**Comment by pofider** [comment]
The basic stuff is here:
https://github.com/jsreport/jsreport/blob/master/config.md

Then every extension configuration is the described separately in the `Configuration` section in docs.
http://jsreport.net/learn/scheduling

**Comment by pofider** [comment]
Added global configuration to the official docs http://jsreport.net/learn/configuration
