### ISSUE TITLE
Orchestrate pdf utils using jsreport script

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#490]
The static pdf utils operations configuration is too limited for some cases.
Like when you want to run the append or merge operation only in some cases.
It could be based on the input data or even based on the items/texts produced by the previous operation.

The most powerful API to the report developers would be through jsreport custom script which would orchestrate the operations.
This could be eventually too complex to support technically, however here is the idea how it could look.

```js
const jsreport = require('jsreport-proxy')

async function afterRender(req, res) {
  const $pdf = await jsreport.pdfUtils.parse(res.content)
  if ($pdf.pages[0].text.include('') || $pdf.pages[0].group === '') {
    const appendRes = await jsreport.render({
      template: { 
        name: 'my-append-template'
      },
      data: { 
          ...req.data,
         $pdf 
      }
    }
    res.content = await jsreport.pdfUtils.append(appendRes.content) 
  }
}
```

```

**Comment by pofider** [comment]
The next case when the dynamic pdf utils orchestration could be very useful is optimizing using parallel processing.

The problem is that long reports are typically built from repeated sections but the chrome rendering is not parallelized and uses just single CPU. The developer could run the rendering from script in parallel and in the end use pdf utils append to make one big final report.

```js
const jsreport = require('jsreport-proxy')
const Promise = require('bluebird')

async function afterRender(req, res) {
    const renderPromises = []
    for (let i = 0; i < req.data.subreports.length; i++) {
        renderPromises.push( jsreport.render({
             template: { 
                name: 'subreport'
             },
            data: req.data.subreports[i]
       }))
    }

   const results = await Promise.all(renderPromises)

   for (let subreport of results) { 
    res.content = await jsreport.pdfUtils.append(res.content, subreport.content) 
   }  
}
```

**Comment by pofider** [comment]
I believe this can be nice.
The scripts extension needs to expose an api so pdf-utils can extend the `jsreport-proxy` and then it is just about naming and some technical implementation.

**Comment by bjrmatos** [comment]
this is now possible in jsreport `2.5.0`, see the [docs](http://jsreport.net/learn/pdf-utils#usage-in-script)
