### ISSUE TITLE
Docker example with authentication doesn't work

### ISSUE THREAD

**Issue by bloodybeet** [jsreport/jsreport#491]
When I take the docker command with authentication as per verbatim from the documentation:

`docker run -e "extensions_authentication_admin_username=admin" -e "extensions_authentication_admin_password=xxx" -e "extensions_authentication_cookieSession_secret=yyylong" -p 80:5488 jsreport/jsreport`

I will not be able to log in using username "admin" and password "xxx". Looks like something is wrong? After entering username and password, I'll just be redirected to the login screen again - no error messages.

![image](https://user-images.githubusercontent.com/12112860/52778420-47aee900-3046-11e9-920c-47689d507ba8.png)

**Comment by bjrmatos** [comment]
i just tried and it works for me, i see that your docker command expose the jsreport container to port 80 (`-p 80:5488`), but the network tab on your screenshoot point to 8001? looks like you are not loading the right port, try with `http://localhost:80` or try another port if for some reason you can not open on port 80

**Comment by bloodybeet** [comment]
Oh, yes 80 is unavailable, I'm running at 8001, and I can access the site
there fine. So there seems to be a bug in the redirecturl nog picking up
the custom port?

**Comment by bjrmatos** [comment]
>I'm running at 8001, and I can access the site there fine

so are you running now with exposed port 8001 and you still get the same bug? `docker run -e "extensions_authentication_admin_username=admin" -e "extensions_authentication_admin_password=xxx" -e "extensions_authentication_cookieSession_secret=yyylong" -p 8001:5488 jsreport/jsreport:2.3.0`

i use the same and it works for me, not sure what can be the problem for you, i don't see any redirect when using the right credentials `admin` and `xxx`. 

do you use docker on linux, windows, or OSX?

**Comment by bloodybeet** [comment]
Yes that is the exact command I used. This is on Docker for Windows, so
Linux container inside a MobyVM which gets bridged (-ish)

**Comment by pofider** [comment]
I ran that command on docker for windows and the authentication works properly for me.

Can you try it from another a different browser? There can be some permanent redirect from the other application stored in your browser's cache

**Comment by pofider** [comment]
Closing as there is no response here.
However feel free to comment, we still monitor it.
