### ISSUE TITLE
Consider ensuring temp folder exists before writes

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#492]
Deleting the `/tmp` shouldn't probably cause jsreport crash.

We could expose some functions like
```
reporter.writeTempFile()
reporter.readTempFile()
```

that would ensure temp exists and also generate those uids.

**Comment by msageryd** [comment]
Hi once more..
Just wanted to let you know that I got jsreport up and running at AWS. I.e. please disregard my previous emails.

I simply started over and created a new service. This time I omitted any port exposure and service discovery. I suppose that I made some error with these parameters. Now that I know that I can get jsreport running in a container I can start tinkering with service discovery so I can reach jsreport from my other servers.

//Michael

On 19 Feb 2019, 15:36 +0100, Jan Blaha <notifications@github.com>, wrote:

Deleting the /tmp shouldn't probably cause jsreport crash.

We could expose some functions like

reporter.writeTempFile()
reporter.readTempFile()


that would ensure temp exists and also generate those uids.

**Comment by bjrmatos** [comment]
done
