### ISSUE TITLE
Problem with link to generated pdfs from Jsreport API response 

### ISSUE THREAD

**Issue by Pepukayi** [jsreport/jsreport#493]
I am trying to use the JSReport API response to get the link of a generated pdf. This was working perfectly till we upgraded to v2.3.0. The response from the API call now looks like below: 

"https://servername:5489/reports/Async rendering in progress. Use Location response header to check the current status. Check it <a href='https://servername:5489/reports/zujUSbLoo6WjwMnT/status'>here</a>.pdf"

The link to the file generated in this case should be: "https://servername:5489/reports/zujUSbLoo6WjwMnT/content". The actual pdfs are being stored in https://servername:5489/jsreportapp/data/storage

How can I get the API response from my jsreport server to be the actual link to the document?

**Comment by pofider** [comment]
Thank you. It looks like a bug. We will take a look and come back to you.

**Comment by pofider** [comment]
The response looks good form our side.

From what version did you update to jsreport 2.3.0.
How does your rendering request look like?

You seem to use `async` rendering, is this your intention?
https://jsreport.net/learn/reports

**Comment by Pepukayi** [comment]
> Thank you. It looks like a bug. We will take a look and come back to you.

The rendering request looks like below:

var jsreportLocation = "https://servername:5489/report";

var jsreportAPIoptions = {
	"template": {"shortid": ShortId},
	"options": {
     	"reports": {"async": true}
     }
};

var jsreportAPIheaders = {
	"CURLOPT_HTTPHEADER": [
			"Content-Type: application/json",
			"Authorization: " + jsreportAuthenticationApplicationLetter
	]
};
platform.api.post(jsreportLocation, JSON.stringify(jsreportAPIoptions), jsreportAPIheaders);

You seem to use `async` rendering, is this your intention?
The intention is to use async so that the link to the generated letter is returned immediately regardless of whether the letter has been fully rendered.

**Comment by Pepukayi** [comment]
Hi Jan...Any pointers for me re the above issue.

**Comment by pofider** [comment]
I don't see there would be a 1.8.6 jsreport release.

Currently it seems to behave exactly how it is documented
https://jsreport.net/learn/reports

>  If you want to start the rendering process asynchronously and receive the responds immediately you should set options.reports.async = true.
In this case you receive response with Location header containing url to the rendering status page. It will be something like http://jsreport-host/reports/id/status. You can then ping the status page to check if the rendering is done. In that case the response status will be 201 and the location header will contain address to the stored report.

I don't this behavior was changed in some of our recent versions.

**Comment by Pepukayi** [comment]
Hi Jan...Visiting the status page returned is give the error:

Report is pending. Wait until 201 response status code. 

I am also a bit lost as to how to ping the status page to return the report location. Can you point me to a Javascript example if possible.

**Comment by Pepukayi** [comment]
I am getting the below error in the logs: 

Async reports extension render failed Error
    at /opt/jsreportapp/node_modules/jsrender/jsrender-node.js:215:27
    at Object.<anonymous> (/opt/jsreportapp/node_modules/jsrender/jsrender-node.js:2452:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/jsreportapp/node_modules/jsreport-jsrender/lib/jsrenderEngine.js:6:16)

**Comment by pofider** [comment]
With `async:true` you get back `Location` response header which contains url you can use to check when the rendering is finished. If you are not interested when this is finished, you can just string replace the path in url.

The `Location` response header typically includes something like this
`http://localhost:5488/reports/vkDFIvyrhZXAKgml/status`

you can just change `/status` to `/content` and you get url where the report can be later downloaded
`http://localhost:5488/reports/vkDFIvyrhZXAKgml/content`

I am closing this as it seems this is working the same like before and like documented.
