### ISSUE TITLE
Click on template in studio startup page causes js error

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#494]
Run template rendering
Open startup page
Click template name at the "last requests" section

![image](https://user-images.githubusercontent.com/2041960/53427452-3fad5c80-39e9-11e9-91fa-5760c54a39af.png)

**Comment by pofider** [comment]
This bug is probably fixed in the latest master studio.
We will just retest it before releasing the 2.4.0

**Comment by bjrmatos** [comment]
i have confirmed that this is fixed in 2.4.0
