### ISSUE TITLE
pdf content is blank

### ISSUE THREAD

**Issue by BrandonCopley** [jsreport/jsreport#496]
I'm having an issue with the PDF content being blank when running on a production server. I am currently running this system using Docker and my docker image locally runs just fine and prints a beautiful pdf, however when running on an AWS ECS instance with agent 1.25.3 the pdf being printed is completely blank. I don't know where to begin diagnosing this because the docker image prints the pdf just fine locally, it's only when the image is being run on an aws ecs instance that the pdf that prints is blank.

**Comment by BrandonCopley** [comment]
We are using cloudflare in the middle, this may factor in, but this was working last week without a problem.

Our code is the following:

`fs.readFile(`${PROJECT_ROOT}/Layouts/order.html`, 'utf8', async (err, html) => {
      if(err) {
        return res.status(500).send(err)
      }

      await jsReport.init()

      try {
        const out = await jsReport.render({
          template: {
            content: html,
            engine: 'handlebars',
            recipe: 'chrome-pdf',
            chrome: {
              format: 'Letter',
              printBackground: true,
              marginTop: '0.25in',
              marginRight: '0.5in',
              marginBottom: '0.25in',
              marginLeft: '0.5in'
            }
          },
          options: {
            'Content-Disposition': `inline; filename=PDFReport-${order_number}.pdf`
          },
          data: {
            storeIcon: storeIcon,
            store: store,
            order: order,
            customer: order.customer_idUser,
          }
        })

        return out.stream.pipe(res)
      } catch (err) {
        console.log('report render err:', err)
        return res.status(500).send(err)
      }
    })`

**Comment by pofider** [comment]
Hm. I would guess the problem is somewhere in the middle and not in jsreport itself. It could be client or some proxy stuff on the way. The docker should kind of guarantee it works the same.

**Comment by BrandonCopley** [comment]
I think you're right. I have connected directly to our EC2 instances and the pdf is still blank, so it's not Cloudflare, but may be something to do with Amazon ECS perhaps? Our service is sitting on:

Docker on EC2 and the pdf content is just blank, the logs show there is content, but the file being streamed is always blank. Do I need a license key perhaps? Any other issues known when running docker containers on EC2? both res.send(content) and out.stream.pipe(res) send blank pdf's The server also runs cleanly with pdf's on heroku, seems very odd that EC2 is having these issues.

**Comment by pofider** [comment]
We didn't experience such issues with EC2 and docker.
I would recommend trying other recipes? Do they work?
How the content of the blank pdf looks like if you open it in some kind of notepad?

**Comment by BrandonCopley** [comment]
Smart idea:

```
%PDF-1.4
%”ÎÈ·
1 0 obj
<</Creator (Chromium)
/Producer (Skia/PDF m72)
/CreationDate (D:20190305220441+00'00')
/ModDate (D:20190305220441+00'00')>>
endobj
2 0 obj
<</Filter /FlateDecode
/Length 102>> stream
xúML9Ä0€Û
œHî$•*}3,<H¿ˇ%BÀ@<ƒñß>Âj˜ì1)ÊùNí`"@’æó69Û;\MÛΩ
π_ÿó∑Æ‡≈ÿ£êk£¶gl7Ω·®aŒK+
Ü”qL
endstream
endobj
3 0 obj
<</Type /Catalog
/Pages 4 0 R>>
endobj
4 0 obj
<</Type /Pages
/Count 1
/Kids [5 0 R]
/Resources <</ProcSet [/PDF /Text /ImageB /ImageC /ImageI]>>>>
endobj
5 0 obj
<</Type /Page
/Resources <</ExtGState <</G0 6 0 R>>>>
/MediaBox [0 0 612 792]
/Contents 2 0 R
/StructParents 0
/Parent 4 0 R>>
endobj
6 0 obj
<</ca 1
/BM /Normal>>
endobj
xref
0 7
0000000000 65535 f 
0000000015 00000 n 
0000000154 00000 n 
0000000326 00000 n 
0000000373 00000 n 
0000000489 00000 n 
0000000631 00000 n 
trailer
<</Size 7
/Root 3 0 R
/Info 1 0 R>>
startxref
668
%%EOF
```

**Comment by BrandonCopley** [comment]
The correct pdf does look very different. I'm going to try and activate logging and see what errors are being thrown because the output content looks very similar with the first few bytes it displays.

**Comment by BrandonCopley** [comment]
Even if I simplify the code to the following, the pdf is still blank on Amazon ECS instances, however in localhost and on Heroku and in the docker container I can see the Hello World just fine.

```
const jsReport = require('jsreport-core')()
jsReport.use(require('jsreport-chrome-pdf')({
  launchOptions: {
    executablePath: (process.platform==='linux')?'/usr/bin/chromium-browser':null,
    args: ['--no-sandbox', '--disable-dev-shm-usage']
  }
}))
jsReport.use(require('jsreport-handlebars')())
jsReport.use(require('jsreport-pdf-utils')())

jsReport.init().then(() => {
          return jsReport.render({
              template: {
                  content: '<h1>Hello {{foo}}</h1>',
                  engine: 'handlebars',
                  recipe: 'chrome-pdf'
              },
              data: {
                  foo: "world"
              }
          }).then((resp) => {
           	// prints pdf with headline Hello world
            return resp.stream.pipe(res)
       	});
      }).catch((e) => {
          console.error(e)
      })
```

**Comment by BrandonCopley** [comment]
After upgrading my packages, it appears this is now running fine. Thanks for your help with this.

I'm not sure what changed, but to recap:
locally everything ran fine
local docker instance ran fine
remote docker instance on ec2 problematic.

upgrade all jsreport related packages

Everything runs. Thanks again!
