### ISSUE TITLE
Move template in studio - 400 Bad request

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#507]
1. Create folder
2. Create template inside it
3. Move template to the root to be the the sibling of the folder
=> Error 400 Bad request. That is correct, because of the name validation. However the error is not displayed. Just empty modal pops up.

**Comment by bjrmatos** [comment]
just for reference, the changes on studio also depends on some changes done in [core](https://github.com/jsreport/jsreport-core/commit/a4c881b7d905bc35659452dcf2177b9944fd8f05)
