### ISSUE TITLE
Upgrade 2.0.0 to 2.3.0 PostgreSQL Database

### ISSUE THREAD

**Issue by josearaujo** [jsreport/jsreport#509]
Where can I get the datatable changes? I update my jsreport instance from 2.0.0 to 2.3.0

**Comment by pofider** [comment]
We don't ship the database changes along with the releases.

We recommend to backup your database. 
Export the templates into zip.
Drop the database.
Start jsreport with the updated version and let it recreate the schema from scratch.
Import the zip.
