### ISSUE TITLE
Allow references to assets that share the same name when using folders.

### ISSUE THREAD

**Issue by kyledevans** [jsreport/jsreport#511]
I'm trying to use the new folders feature introduced in JSReport 2.3.  I get an error when multiple assets share the same name, even if they are in different folders.

My usecase is that I would like to have multiple reports, each stored in its own folder.  And within each folder they would have basically the same template, asset, and script naming conventions.  This would make it easier for another developer to open up the studio and browse around our reports store and understand how each report is built.

So for example this would be the asset layout I may use:
```
/Client Orders
    main.html
    main.pdf
    data-queries.js
    charting.js
    style.css
/Cutest Kitten Memes
    main.html
    main.pdf
    data-queries.js
    charting.js
    style.css
```

I see in the [folder feature announcement blog](https://jsreport.net/blog/introducing-folders) that it does say that asset names must be unique, so technically this probably isn't a bug.  It would be a really nice feature in my opinion if it's not too much trouble.

**Comment by pofider** [comment]
Hm. Maybe this already works. Can you take a look at this example and break it to the case when it doesn't work for you?

https://playground.jsreport.net/w/anon/a~hvTsdq

**Comment by kyledevans** [comment]
Ok it looks like there actually is a bug here.  I reproduced it by renaming the `b` directory to `b b`.  It looks like what is triggering the error is a directory with a space in it.

**Comment by pofider** [comment]
Thank you for pointing it out. I have just fixed in in [jsreport-core](https://github.com/jsreport/jsreport-core/) repository. The fix will be included in the next release.
