### ISSUE TITLE
2 JSReport instances on one Server

### ISSUE THREAD

**Issue by samir-kamble** [jsreport/jsreport#513]
Hello All,

We hold a licensed copy of JSreport with us. And want to raise one small query. Can I run JSReport 1.7 and JSReport 2.0 on same server.

If yes then please let me know how?

Regards,
Samir

**Comment by pofider** [comment]
I think you just need to set different temp directory, otherwise, both would use by default /tmp/jsreport.
And of course, use a different port. 
```
{
   "tempDirectory": "mytemp",
   "httpPort": 2000
```
