### ISSUE TITLE
Change docker timeout

### ISSUE THREAD

**Issue by oniramarf** [jsreport/jsreport#517]
I am experiencing a timeout issue when processing some requests.

```
Error when processing render request Timeout error during executing script Error: Timeout error during executing script
    at listOnTimeout (timers.js:324:15)
    at Timeout._onTimeout (/app/node_modules/script-manager/lib/manager-servers.js:152:23)
    at processTimers (timers.js:268:5)
```

I am using jsreport:2.3.0 docker image.
I've also tried to set the `task_timeout` environment variable to extend the timeout, but didn't have any effect.

**Comment by pofider** [comment]
It should be `templatingEngines_timeout`
https://jsreport.net/learn/configuration#templating-engines-configuration
