### ISSUE TITLE
Remote deployment using jsreport cli

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#518]
It seems quite some many people are asking how to call the import-export api because their deployment process includes uploading stored templates from some git repository.
We could make their life simpler and provide this in the cli likely as a part of the import-export extension. Something like

```
# get the export from the local instance
jsreport.exe export deployment.zip
# upload the export to the remote instance
jsreport.exe import --host http://jsreport.com deployment.zip
```

This would be probably a good fit to the CI pipelines.

**Comment by bjrmatos** [comment]
this is part of new release of jsreport-import-export, available in jsreport 2.6.0
