### ISSUE TITLE
Page numbers missing when adding header & footer in pdf-utils TOC

### ISSUE THREAD

**Issue by yarongolan** [jsreport/jsreport#519]
When running the playground example (https://playground.jsreport.net/w/admin/akYBA4rS, linked from https://jsreport.net/learn/pdf-utils) and clicking on "display header/footer" page numbers disappear

**Comment by pofider** [comment]
Thanks.
You shouldn't combine the native chrome headers with pdf utils.
If you want a custom header, use pdf utils merge for that.

**Comment by yarongolan** [comment]
Hey Jan. The problem with that is if you have a very LARGE report (100 pages, etc.), the header and footer run for each page, which is simply overkill.

**Comment by pofider** [comment]
Check merge whole document flag
https://jsreport.net/learn/pdf-utils#merge

This makes the headers rendering just once

**Comment by yarongolan** [comment]
You are just simply awesome. Thanks!
