### ISSUE TITLE
How to send an Excel file to an email using nodemailer module

### ISSUE THREAD

**Issue by cccabdalla** [jsreport/jsreport#522]
`function sendEmailWithAttachments(recipientEmailId, subject, content, next) {

    var ormMailerInfo = getORMMailerInfo();
    var transporter = nodemailer.createTransport(smtpTransport({
        host: ormMailerInfo.orm_mailer_host,
        secure: ormMailerInfo.orm_mailer_secure,
        port: ormMailerInfo.orm_mailer_port,
        auth: {
            user: ormMailerInfo.orm_mailer_user,
            pass: ormMailerInfo.orm_mailer_pass
        }
    }));
    transporter.sendMail({
        from: ormMailerInfo.orm_mailer_user,
        to: recipientEmailId,
        subject: subject,
        attachments: [
            {
                filename: subject + '.xlsx',
                content: content
            }
            ]
    }, next);
}`

**Comment by bjrmatos** [comment]
hi! i believe this is more a nodemailer usage question than a jsreport one. so far the code looks good, i don't see something where it should not work, however it depends on the values that you are passing for the attachments, which i don't know from where they are coming from or what they contain

**Comment by pofider** [comment]
Maybe you can check this tutorial
https://jsreport.net/learn/periodical-report-sending-through-email#send-output-in-mail

I am closing this as this is not so much about jsreport but rather about sending emails in general.
