### ISSUE TITLE
deploing to heroku

### ISSUE THREAD

**Issue by fligelmanmeir** [jsreport/jsreport#524]
i deploided a web node-adonis application that also serves the user by some pdf reports wich i designed 2 phantom js templates in a local install enpermise of jsreport.  the reports are render through  api post request to the local jsreport uri. i thougt to create another application in heroku by git pushing the jsreportapp directory to heroku and then to change only the api uri to the jsreport application, is this is the way to deploy the reports part of my application?. anyway the jsreport hroku application doesnt run .

**Comment by pofider** [comment]
Can you describe the issues you have with deploying jsreport to heroku?
What errors you get?
Have you tried deploying to heroku using docker?

It is very long time since I used heroku, but perhaps I get an idea what could be wrong if you share more details.

**Comment by fligelmanmeir** [comment]
Dear jana only today i found the simple solusion of signing up to jsreport cloud server i wasnt aware to this and the documantatin dosent explain it enouph

נשלח מה-iPhone שלי

‫ב-3 באפר׳ 2019, בשעה 18:24, ‏‏Jan Blaha ‏<notifications@github.com> כתב/ה:‬

**Comment by fligelmanmeir** [comment]
Dear jan i mean to say that jsreport from my perspective doesnt need to be deployed its already there in the cloud where i going to copy past my templates and calling the remote jsreport server maby needing to install the client dependency also after that ill dive into that docer thing wich i dont understand now

נשלח מה-iPhone שלי

‫ב-3 באפר׳ 2019, בשעה 18:24, ‏‏Jan Blaha ‏<notifications@github.com> כתב/ה:‬

**Comment by pofider** [comment]
Is there still something open we can help with?
Or we can close this?

**Comment by fligelmanmeir** [comment]
Hi dear jan, you can close it thanks a lot 

נשלח מה-iPhone שלי

‫ב-16 באפר׳ 2019, בשעה 22:21, ‏‏Jan Blaha ‏<notifications@github.com> כתב/ה:‬

**Comment by fligelmanmeir** [comment]
Can close thanks

נשלח מה-iPhone שלי

‫ב-16 באפר׳ 2019, בשעה 22:21, ‏‏Jan Blaha ‏<notifications@github.com> כתב/ה:‬
