### ISSUE TITLE
Highcharts legend text with jsreport v2.4

### ISSUE THREAD

**Issue by bpfau79** [jsreport/jsreport#526]
I ran JSReport v2.4 and I am using highcharts (doesn't matter which version of high charts)....when run a report....the legend text does not show up and occasionally just shows a '|' 

The legend symbol does appear along with the main chart content. I believe the highchart is rendered via SVG. 

When I run with JSReport v2.3, it works as expected (legend text appears). This behavior happened with both the stand-alone executable and the .NET wrappers. 

![No Legend Text](https://user-images.githubusercontent.com/36340017/55856320-2db1f400-5b27-11e9-81f7-c2fa51e9a995.PNG)

![Legend Text](https://user-images.githubusercontent.com/36340017/55856469-9f8a3d80-5b27-11e9-8814-134e5501e437.PNG)

**Comment by pofider** [comment]
This likely caused by different chromium version present in 2.3 and 2.4.
Could you share a playground demo so we can try to find a workaround?
https://playground.jsreport.net/

**Comment by bpfau79** [comment]
Well, apparently the playground version works fine....however when I use nuget and use the jsreport.binary v2.4 (Visual Studio 2017) the issue still exists using the same exact template markup that I specified in the playground sample

Is the playground version "newer" than v2.4 jsreport.local from nuget?

https://playground.jsreport.net/w/anon/Shb2yiQK

**Comment by pofider** [comment]
Ok thanks, yes. The playground has a bit newer chrome then the current jsreport.
We will update the chrome in the next jsreport release 2.5.0, although I'm not sure when this will ship.

Maybe there is some kind of workaround for current chrome. Maybe a different version of highcharts would work. Don't know, unfortunately.

**Comment by pofider** [comment]
jsreport 2.5.0 now uses Chromium 76.0.3803.0 (r662092)
