### ISSUE TITLE
JSreport fails to start on CentOS 7.6

### ISSUE THREAD

**Issue by yami12376** [jsreport/jsreport#538]
I am doing steps from: https://jsreport.net/learn/centos
but i get an error:

# jsreport start

> An error has occurred when trying to initialize jsreport (2). Error when loading extension chrome-pdf
> Error: Cannot find module 'puppeteer'

**Then again while trying additional step:**

# npm -v
5.6.0

# npm install puppeteer jsreport-chrome-pdf

> puppeteer@1.14.0 install /opt/jsreportapp/node_modules/puppeteer
> node install.js

sh: node: command not found
npm WARN jsreport-server@ No description
npm WARN jsreport-server@ No repository field.
npm WARN jsreport-server@ No license field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! puppeteer@1.14.0 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the puppeteer@1.14.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-19T14_10_25_149Z-debug.log

**Comment by bjrmatos** [comment]
hi! according to the error message this looks like some permission error maybe or maybe for some reason the node executable is not visible to other processes. probably your node installation was done in a way that it requires admin permissions (`sudo` usage), you can try to run `sudo npm install puppeteer jsreport-chrome-pdf` and if it works then you have a problems with the permissions. to fix the npm permissions issues you can follow some guide like [this](https://www.competa.com/blog/how-to-run-npm-without-sudo/).

**Comment by yami12376** [comment]
sudo npm install puppeteer jsreport-chrome-pdf
[sudo] password for user:
sudo: npm: command not found


 npm install puppeteer jsreport-chrome-pdf

> 
> npm ERR! path /opt/playbooks/jsReport/node_modules/abbrev
> npm ERR! code EACCES
> npm ERR! errno -13
> npm ERR! syscall access
> npm ERR! Error: EACCES: permission denied, access '/opt/playbooks/jsReport/node_modules/abbrev'
> npm ERR!  { Error: EACCES: permission denied, access '/opt/playbooks/jsReport/node_modules/abbrev'
> npm ERR!   stack: 'Error: EACCES: permission denied, access \'/opt/playbooks/jsReport/node_modules/abbrev\'',
> npm ERR!   errno: -13,
> npm ERR!   code: 'EACCES',
> npm ERR!   syscall: 'access',
> npm ERR!   path: '/opt/playbooks/jsReport/node_modules/abbrev' }
> npm ERR!
> npm ERR! Please try running this command again as root/Administrator.
>

**Comment by pofider** [comment]
It seems you have solved it in the end.
Closing.
