### ISSUE TITLE
Aborting rendering request

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#544]
There is currently no way to cancel rendering request.
It could make sense to be able to react on incoming http request events and abort the rendering request when the request is closed by the caller. This means for example kill chrome or node process doing the work.

**Comment by bjrmatos** [comment]
hmm i can't remember the use case for this. i mean, what kind of flow should this feature enable the user to do? or is this more about ensuring we don't leak or have opened processes when the request somehow fails or break?

**Comment by pofider** [comment]
The scenario:
The client makes a call to generate a report. The user or systems decides it is taking too long and cancels the request. We get the closed even on the request in jsreport. But we continue processing.

**Comment by pofider** [comment]
This should work with the worker threads. We should be able to just to worker.terminate the thread.

**Comment by pofider** [comment]
Implemented ready for v3
