### ISSUE TITLE
JSReport 2.4.0 Windows executable Template location

### ISSUE THREAD

**Issue by samir-kamble** [jsreport/jsreport#548]
Hello,

I have deployed latest JSReport version on Offline Windows server. Ran it with "jsreport.exe start"

It started well. I created couple of templates in the same. But I am not able to locate them in the location from where I am running JSReport.  In older version I used to locate them inside "data" folder.

Can you please help me locating those templates.

Regards,
Sam

**Comment by pofider** [comment]
Run `jsreport configure` the first. This will prepare for you configuration file telling jsreport to persist templates in the `data` folder.

**Comment by samir-kamble** [comment]
Thanks for quick revert got it working
