### ISSUE TITLE
Chrome pdf default printing background

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#553]
Not sure if removing default for printing background in [this](https://github.com/jsreport/jsreport-chrome-pdf/commit/8abc595b7daf8a576021c01875e8bb21ab8e7b20) commit was the best idea.

It seems confusing as we can see [here](https://github.com/jsreport/jsreport-dotnet/issues/34).

I guess we wanted to be 1:1 with puppeteer, however, I think you just always want the background.
And the inconsistency now is a bigger pain than inconsistency with puppeteer default options.

I would vote for putting the default printBackground on the server back. I wouldn't even consider this as a breaking change, because I haven't seen a usage when someone would actually disable printing background.

**Comment by bjrmatos** [comment]
> I would vote for putting the default printBackground on the server back. I wouldn't even consider this as a breaking change, because I haven't seen a usage when someone would actually disable printing background.

i agree with this, actually i remember that i was in favor of doing it but we revert it because we did not want to broke some people that does raw requests in jo. even if that is the case we don't know exactly if there are people doing this and expecting not printing the background by default

**Comment by pofider** [comment]
ok, let's do it, we will justify this partially breaking change.
