### ISSUE TITLE
Error while executing templating engine. Missing helper: "for"

### ISSUE THREAD

**Issue by DIMITA** [jsreport/jsreport#555]
I am new with jsreport and I do not know very well how its template engine works and here is the error that I encounter with this code
```js
<table>
    {{for students}}
    <tr>
        <td>{{:id}}</td>
        <td>{{:name}}</td>
    </tr>
    {{endfor}}
</table>
```

 I wonder if someone can help me
this is my data JSON source

`{
    "students" : [ {"id": 1, "name": "dimi"}, {"id": 2, "name": "dimi2"} ]
}`

**Comment by pofider** [comment]
You seem to be missing the basic information. Please check the tutorials we have
https://jsreport.net/learn/get-started
https://playground.jsreport.net/w/admin/hBfqC7af

and the other playground examples...
https://playground.jsreport.net/

**Comment by DIMITA** [comment]
thank i understood
