### ISSUE TITLE
chrome-pdf: First element top margin not respected on 2nd page onward

### ISSUE THREAD

**Issue by diakonos** [jsreport/jsreport#556]
The PDF generated by `chrome-pdf` doesn't seem to respect the top margin of the first element on each page, except on the first page.

I created a demo here: https://playground.jsreport.net/w/anon/A7A~T4_E

I expect to see a 50px top margin for the `h1` on each page, but I only see it on the first page's.

I was curious whether it was only an issue with a page-break div, but in the demo you will see that it happens whether the content naturally pushes an element to the next page or not.

I'm aware that this could possibly be a puppeteer issue rather than jsreport, but I couldn't find any documentation or issues surrounding this. If anyone can help me understand or point me in the right direction, I'd greatly appreciate it.

**Comment by pofider** [comment]
This is how the puppeteer chrome works. The margin isn't page based.
You can set page based margins using chrome settings in the left properties menu.
Check also more complex showcases on playrgound
https://playground.jsreport.net/w/admin/dI2_fUqZ
