### ISSUE TITLE
API jsonData request problem/question

### ISSUE THREAD

**Issue by noclue119** [jsreport/jsreport#56]
Hi, there, I am still learning JSReport so please bare with me. The question/issue I have might be due to a lack of understanding of how the jsreport server work. I am not totally sure.

Basically I am trying to make an API request to a report and passing the data via the jsonDATA . I assumed that you either use the JSONDATA or supply a shortid in Data section to denote which data set you want to use.

So here is my report:
![report](https://cloud.githubusercontent.com/assets/11889956/7093531/22cf4c50-df88-11e4-96f5-4b9e40e90e3d.png)

Here is what the API says:
![report-api](https://cloud.githubusercontent.com/assets/11889956/7093461/734339d6-df87-11e4-82de-d64f2667bee9.png)

Here is a working API request when I reference shortID of the saved Data
![request-working](https://cloud.githubusercontent.com/assets/11889956/7093469/868e4da0-df87-11e4-910f-4a9cf6e3a39b.png)

But when I switch over to using JSONData, it stops working
![request-notworking2](https://cloud.githubusercontent.com/assets/11889956/7093476/975e961c-df87-11e4-9a28-f6bc450d809b.png)

Am I doing something wrong?

Thanks
Ying

**Comment by pofider** [comment]
Hi,

I think you need to use double quotes in JSON, so it would work like this
```js
{
  "template": { "shortid": "EJGZXk2l", "data": {"dataJson": "{\"myTable\": \"atest\" }" } } 
}
```

However, when using API, you should send data separately like this:
```js
{
  "template": { "shortid": "EJGZXk2l" },
 "data": {
   "myTable": "atest"
 } 
}
```

Sending it in `template.data.dataJson` would also work, but it is dedicated to the purpose of data extension and design time, where sending it as a separate property in the request object is core part of jsreport dedicated to be used by API.

I will stress this out in the dialog, sorry for confusion and thanks pointing this out.

**Comment by noclue119** [comment]
Thanks for your quick reply. I am going to give it a try once I get back from much and let you know.

**Comment by noclue119** [comment]
Thank you so much both methods of posting the JSON works!! You rock.


Just a note for other people who might run into this issue:
If you plan on using dataJSON that is template.data.dataJSON
```
{
    "template": {
        "shortid": "EJGZXk2l",
        "data": {
            "dataJson": "{\"myTable\": \"atest\" }"
        }
    }
}
```
while post method 2 data and template are both top level.
```
{
    "template": {
        "shortid": "EJGZXk2l"
    },
    "data": {
        "myTable": "atest"
    }
}
```

I choose method 2 because my posting/streaming back is done via java. The code for the JSON object is much cleaner.
