### ISSUE TITLE
A few exceptions and a question about jsreport local 

### ISSUE THREAD

**Issue by Centrox** [jsreport/jsreport#562]
Hi all,

so here we were, using the free jsreport local version embedded in our application. For a time it worked great.
Until we went on our test environment which ran multiple instances of our application.
We first got an exception that told us that the executable was not a valid executable for this OS.
A bit of a surprise to us because it was working for another instance on our test server.
After discovering jsreport had an http port, we configured each instance to have it's own port.
Now the exception about the OS was gone, but a new exception was logged.
This time jsreport logged that there was something undefined in the model en that we could not forEach on an undefined object. Made sense at first, until we verified what was send as request model data to jsreport.
This was all correct, so we could not figure out why it gave us this exception. It worked locally.
Then we discovered jsreport copies itself to a windows temp directory.
So we gave every instance it's own temp directory, and now the forEach problem went away.

Then finally we had again a new exception. This time it complained about a file being in use from C:windows\temp\jsreport\chrome something.
Now we don't know what to do about this, cause we already configured the temp folder to be in our applications folder\temp
We see the files being created there, but why also still files in windows\temp is what we don't understand.

Is there a way to configure the temp folder for chrome?
We deleted the windows/temp/jsreport directory and now we can render the template again.

Also, we noticed that when jsreport goes into trial mode, and we bring back the number of templates to five, the forEach error returned. If we begin with an empty temp dir, and also stay on the five templates, then it works again.

We now have the yearly enterprise license, and we hope anyone could shed some light on the chrome temp files and why they are not being put in our configured temp folder?

Cheers, and best regards,

Casper Blokzijl
Diract-IT

**Comment by pofider** [comment]
Closing as duplicate
https://forum.jsreport.net/topic/1060/a-bunch-of-exceptions-jsreport-local
