### ISSUE TITLE
pdf utils timeout and rendering cycle control

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#563]
The default timeout for pdf utils operation evaluation seems to be taken from templatingEngines.timeout. This is by default 10s which is not enough quite often.
We should use the timeout in this case in this order

pdf-utils.timeout, scripts.timeout, templatingEngines.timeout

The error should also tell what timeout to increase. The same can be applied perhaps also in the script and templating engine timeout errors.

**Comment by bjrmatos** [comment]
we evaluated this a bit and we think that the best so far seems to allow the pdf utils script to run with no timeout. the reason for this is that pdf utils execution is composed of many operations and each one of them have timeout controls (chrome timeout, template engine timeout, script timeout), so in theory there should be no extra timeout control for the whole pdf utils execution. 

except that there is one case in which not having a timeout will result in endless execution, that case is when you have a `main` template that references an `extra` template in pdf utils operation, but the `extra` template have pdf utils operation that references the `main` template causing a loop. we will need to implement a control that prevent this to happen, probably similar to the control that we have in `proxy.render` that prevents cycles 

references #564

**Comment by pofider** [comment]
The cycle control should be implemented in jsreport-core in a general way. Then we don't need to implement the same in pdf utils, child templates and scripts.

**Comment by pofider** [comment]
The general loop was implemented here https://github.com/jsreport/jsreport-templates/commit/4e86708087bd07e771a06d5a213e00923be77969

The prevention from very long execution of pdf utils should be taken care through  https://github.com/jsreport/jsreport/issues/567

What is missing here is running the pdf utils with 0 timeout. I believe this requires to be https://github.com/jsreport/jsreport/issues/564 done first

**Comment by pofider** [comment]
This is done in 2.6.0
