### ISSUE TITLE
Too many timeouts

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#567]
This is just to think about...
The timeouts for the rendering are too granular. A developer typically wants just a single timeout option. Setting extra templating engine, script, pdf utils, chrome timeout is quite too much. The developer never knows which timeouts will burn in the production.

From the perspective of jsreport user, I would like to set just a single timeout for rendering. 
From the perspective of jsreport developer, there are technical difficulties to support this.
However, maybe we can solve this.

We know the start time of the rendering request, we could have timeouts dynamic in the pipeline. Like in chrome or sandbox we use timeout (now - startTime + generaltimeout)

**Comment by pofider** [comment]
@bjrmatos  What you think?

**Comment by bjrmatos** [comment]
the single timeout will be the best, as you said it looks like we can solve it technically, but i guess that this single timeout should be higher by default, right? it should be ok when rendering things with pdf-utils, etc which usually compose other renders.

i think that this single timeout will be useful to set it per request too, and not just from static configuration.

**Comment by bjrmatos** [comment]
closed in https://github.com/jsreport/jsreport-core/commit/0c27e3f0d6f368c268c227cfdb2e0245fd43b0c8

**Comment by pofider** [comment]
It seems it gonna be useful to have request specific timeout in the jsreportonline so we can implement it also to the core.

So the timeout would be set in the `req.options.timeout`.
This would by default through unless it is configured.

The naming could be as this
```js
reportTimeout
enableUserSpecificReportTimeout
```
