### ISSUE TITLE
Docker Image Libraries

### ISSUE THREAD

**Issue by Css-IanM** [jsreport/jsreport#568]
Is there any persistent way to include third party libraries in the docker image without cloning your own and hosting another docker image? I know there is the allow modules config, of which can be declared with an environment variable but this doesn't add the package and install it does it? I can issue the commands but that doesn't persist on restarts. Common packages like lodash, moment etc. Are very handy in the helpers and in globally available script files.

**Comment by pofider** [comment]
Unfortunately, you can't. That is how docker works. You need to create your own image and inherit from the jsreport one.

Note that the common packages like moment or lodash are typically already part of the official image. However, if you need something that is not there, you need to create your own image. Also I don't encourage you to rely on this as it may change through the versions and better to install exact versions you want to use.
