### ISSUE TITLE
Analyse executable compilation using pkg

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#571]
I found a new library that is doing the nodejs application packaging.
https://github.com/zeit/pkg

I didn't dig very deep, just made a quick prototype for jsreport.

1. npm i pkg -g
2. put to jsreport repo package.json 
```js
"pkg": {
    "assets": [
      "node_modules/vm2/lib/sandbox.js",
      "node_modules/vm2/lib/contextify.js"
    ]
  }
```
3. modify server.js with this
```js
const fs = require('fs')
const path = require('path')

if (!fs.existsSync('chrome')) {
  fs.mkdirSync('chrome')
  fs.mkdirSync('chrome/locales')
  fs.writeFileSync(path.join('chrome', 'v8_context_snapshot.bin'), fs.readFileSync(path.join(__dirname, 'node_modules/puppeteer/.local-chromium/win64-662092/chrome-win/v8_context_snapshot.bin')))
  fs.writeFileSync(path.join('chrome', 'resources.pak'), fs.readFileSync(path.join(__dirname, 'node_modules/puppeteer/.local-chromium/win64-662092/chrome-win/resources.pak')))
  fs.writeFileSync(path.join('chrome', 'notification_helper.exe'), fs.readFileSync(path.join(__dirname, 'node_modules/puppeteer/.local-chromium/win64-662092/chrome-win/notification_helper.exe')))
  fs.writeFileSync(path.join('chrome', 'natives_blob.bin'), fs.readFileSync(path.join(__dirname, 'node_modules/puppeteer/.local-chromium/win64-662092/chrome-win/natives_blob.bin')))
  fs.writeFileSync(path.join('chrome', 'icudtl.dat'), fs.readFileSync(path.join(__dirname, 'node_modules/puppeteer/.local-chromium/win64-662092/chrome-win/icudtl.dat')))
  fs.writeFileSync(path.join('chrome', 'chrome_elf.dll'), fs.readFileSync(path.join(__dirname, 'node_modules/puppeteer/.local-chromium/win64-662092/chrome-win/chrome_elf.dll')))
  fs.writeFileSync(path.join('chrome', 'chrome_child.dll'), fs.readFileSync(path.join(__dirname, 'node_modules/puppeteer/.local-chromium/win64-662092/chrome-win/chrome_child.dll')))
  fs.writeFileSync(path.join('chrome', 'chrome.exe'), fs.readFileSync(path.join(__dirname, 'node_modules/puppeteer/.local-chromium/win64-662092/chrome-win/chrome.exe')))
  fs.writeFileSync(path.join('chrome', 'chrome.dll'), fs.readFileSync(path.join(__dirname, 'node_modules/puppeteer/.local-chromium/win64-662092/chrome-win/chrome.dll')))
  fs.writeFileSync(path.join('chrome', '76.0.3803.0.manifest'), fs.readFileSync(path.join(__dirname, 'node_modules/puppeteer/.local-chromium/win64-662092/chrome-win/76.0.3803.0.manifest')))
  fs.writeFileSync(path.join('chrome', 'locales/en-US.pak'), fs.readFileSync(path.join(__dirname, 'node_modules/puppeteer/.local-chromium/win64-662092/chrome-win/locales/en-US.pak')))
}

const jsreport = require('./')({
  rootDirectory: __dirname,
  extensionsList: ['templates', 'express', 'studio', 'data', 'chrome-pdf', 'handlebars'],
  chrome: {
    launchOptions: {
      executablePath: 'chrome/chrome.exe'
    }
  }
})

if (process.env.JSREPORT_CLI) {
  module.exports = jsreport
} else {
  jsreport.init().then(() => {
  }).catch((e) => {
    console.trace(e)
    process.exit(1)
  })
}
```
4. run pkg server.js --target node8-win-x64

And you can run the output. It is somehow running and you can render pdf reports.
I do exclude some extensions, there is one that is breaking the sandbox with adding some string to helpers that is not bundled.
By naming files of chrome I make sure they are packaged as assets in the exe. It could work just with pkg config, but somehow it was freezing for me during the run.

How to proceed...

Evaluate if the pkg is actually better for us. 
I have a feeling that it works differently than nexe. 
It doesn't bundle things into one big js like nexe.
It seems it is rather putting all required files to the binary and virtualize fs and require so it can be reached.
I see this as a big benefit for a faster start. V8 doesn't need to compile one giant js bundle at the start. Maybe we should check this if it is true.

If we think this is a better approach...

- We should decrease the exe size - compress chrome before it is attached (50mb) and remove some bigger files like js maps (30mb). Maybe something else...
- Make sure all extensions are working.
- Make sure we read config file, for now it is always searching for it inside the binary.
- Make sure it can load custom extensions
- Make sure cli is working
- Check if keep alive still works - we probably don't need winrun anymore

**Comment by pofider** [comment]
Thanks to @bjrmatos, the prototype is ready. Some notes I created during the performance testing.

- use templatingEngine.strategy=in-process
- Use nodejs 12 instead of 8. The node 8 has turned off snapshots for the native modules and its startup time is multiple times slower... gain 100ms 
(the scheduling has an issue with node 12, needs to be fixed)
- Keep optimized runtime.js...  100ms
- Don't use jsreport-client but make a simple http call using native module... 100ms
- require and create Execution.js only when needed.... 20ms

In the end, I have amazing **230ms** for keepalive HTML render compared to 880ms with current 2.5.0 version.

I didn't push my code and keep it up to @bjrmatos to do the last step.

**Comment by bjrmatos** [comment]
> * Use nodejs 12 instead of 8. The node 8 has turned off snapshots for the native modules and its startup time is multiple times slower... gain 100ms
>   (the scheduling has an issue with node 12, needs to be fixed)

i see that the snapshots thing is available from node 12.5.0 but pkg can only compile until 12.2.0, so probably there will be better numbers when node 12.5.0 is available on pkg

**Comment by pofider** [comment]
Two more things....

- Check if it is possible to put to the exe process custom name. Because at this moment it looks as node.js in the taskmgr. It would be nice there is an icon and correct name. If the pkg can't do it, we should rais e an issue.

- Find out how to sign the exe. We will likely need to purchase a certificate for it, but that is a small amount of money that could help customers with firewall and defender fights.

**Comment by bjrmatos** [comment]
>Check if it is possible to put to the exe process custom name. Because at this moment it looks as node.js in the taskmgr. It would be nice there is an icon and correct name. If the pkg can't do it, we should rais e an issue.

i checked and for OSX it seems to have the correct process name (with the old and new executable) 

<img width="1642" alt="Captura de pantalla 2019-08-23 a la(s) 3 11 35 p  m" src="https://user-images.githubusercontent.com/4262050/63621963-00884e80-c5bb-11e9-9019-1af222af891c.png">

if this is not the case for windows or linux, then we can try this changing [process.title](https://nodejs.org/dist/latest-v10.x/docs/api/process.html#process_process_title), i did a test on OSX and changing the process.title works, but not 100% sure about the support of this in other OS.

>Find out how to sign the exe. We will likely need to purchase a certificate for it, but that is a small amount of money that could help customers with firewall and defender fights.

so far the most clear post about signing an exe that i could found is in the [electron docs](https://electronjs.org/docs/tutorial/code-signing). it looks like those steps are general for any app (not matter if we have created the exe with electron or not). one thing about the signing in windows is that it seems that [it needs an EV certificate](https://blogs.msdn.microsoft.com/ie/2012/08/14/microsoft-smartscreen-extended-validation-ev-code-signing-certificates/) for better trust and reputation, and that kind of certificate is a bit expensive (i think it is like $2xx/year 😅) ([related to windows](https://github.com/zeit/pkg/issues/617)) ... and the last thing is that it seems that there is problem signing an executable created with pkg on OSX (issues here [1](https://github.com/zeit/pkg/issues/128),[2](https://github.com/zeit/pkg/issues/66)), it seems that there is a hack to make the code sign to pass on OSX (it is mentioned on the issues), but i'm just mentioning to have this in mind.

**Comment by bjrmatos** [comment]
> * Use nodejs 12 instead of 8. The node 8 has turned off snapshots for the native modules and its startup time is multiple times slower... gain 100ms
>   (the scheduling has an issue with node 12, needs to be fixed)

in the end after some tests we found that using node 12 with pkg has some bugs related to random [`Maximum call stack size exceeded`](https://github.com/zeit/pkg/issues/681) errors. more exactly the error was happening on listeners execution (`node_modules/listener-collection/lib/listenerCollection`).. for the record this was only happening on the first render with keep alive `/jsreport render --template.content=test.html --template.engine=none --template.recipe=html --keepAlive -o output.pdf`, next renders were fine. however we were not sure if any other bugs will appear, because there was even a more random error related to winston logs but i was not able to find a good way to replicate it.

we decided to compile with node 10 instead because of these problem with pkg and node 12. hopefully they can be fixed sometime later

**Comment by bjrmatos** [comment]
we did it!, the [new 2.6.0 release](https://github.com/jsreport/jsreport/releases/tag/2.6.0) contains the new exe based on pkg

**Comment by saurabh-deep** [comment]
Hey @pofider / @bjrmatos - Which Node version you ended up finally with `pkg` - was it Node 10 or Node 12? And were you able to sign the binary created with `pkg` for OS X successfully?

**Comment by pofider** [comment]
We use node 12, but haven't been able to sign osx binary.
