### ISSUE TITLE
login/logout POST link does not take serverUrl into account

### ISSUE THREAD

**Issue by zheffie** [jsreport/jsreport#58]
login/logout POST link does not take serverUrl into account

**Comment by pofider** [comment]
Ok, I will fix it. Thanks for the bug report.

**Comment by zheffie** [comment]
There are some other links in the studio's top navigation panel that are missing the reference to serverUrl

**Comment by pofider** [comment]
I have done some fixes to improve this "serverUrl" feature but it is very messy to code and support it.

Could you please just let me know in what scenario do you use it, so I have an idea about it?

**Comment by zheffie** [comment]
We only make ports 80 and 443 available to the outside world, and there is another website running already on "/"

**Comment by pofider** [comment]
OK, thanks. Have you considered running jsreport on a subdomain like `jsreport.yourapp.com`? Or maybe even different path would be enough `yourpath.com/jsreport`?

I just want to make a picture what leads you into this....

Is it a way for you to provide your own authentication or other things? Or is it just about exposing jsreport on the same port as your application what could be achieved by different domain or path? Thank you.

**Comment by zheffie** [comment]
Well, we do use a different path. eg. ```domain.com/reports```
Problem is that many links are still using leading slash.

Perhaps a quick fix is to use a configurable base tag in your head definition
```
<head>
<base href="http:/domain.com/reports/">
</head>
```

**Comment by pofider** [comment]
Perfect, that is what I need. 

I will check if it would be a problem to have all links without `/` or think about adding configurable base tag.

**Comment by pofider** [comment]
Running jsreport on specific subpath like http://app.com/reports should be possible in jsreport 0.5.0

You only need to set `appPath` to for example `/reports` in configuration.

**Comment by zheffie** [comment]
work perfectly :)
