### ISSUE TITLE
content of file "users" disappeared

### ISSUE THREAD

**Issue by darrug** [jsreport/jsreport#580]
Hello,
this issue happened randomly many times during this month and every time there is an unexpected server shutdown. I have a predefined user created using the interface inside the file, after the issue happens the content of "users" is empty and I not able to login anymore unless I use the admin user. 
If I stop jsreport and add the content to the "users" file when jsreport starts again it empties again the file.

**Comment by pofider** [comment]
What is your jsreport version? Does it happen on the latest one?
Could you email me that file after it gets corrupted by the shutdown and before cleaned by jsreport start?

**Comment by darrug** [comment]
I'm using version 2.4. I'm going to send you the files by mail

**Comment by pofider** [comment]
Please try to update at least `jsreport-fs-store` to the latest one. There are some fixes that could help.

```
npm i jsreport-fs-store@2.4.1
```
Backup first of course...

**Comment by darrug** [comment]
I tried stopping jsreport and restoring the previous content in "users" but it's cleared at the next startup.

**Comment by darrug** [comment]
You can replicate the issue using the empty file I sent you and restoring the content

**Comment by pofider** [comment]
Are you able to replicate the same with the latest jsreport?
Does this happen just for users, all the other entities are persisted?

I'm not able to replicate this. I start jsreport 2.4.0 or 2.5.0.
With the users file you've sent. With a user inside.
I see it exists in studio. I restart several time and the user is still there.

**Comment by darrug** [comment]
> You can replicate the issue using the empty file I sent you and restoring the content

This was a my mistake, If I stop and substitute the users file the file is not corrupted.

I upgraded as you suggested to 
```
jsreport-fs-store@2.4.1
```
At the moment I don't know if this resolve the issue due our customer server shutdown are unexpected and I can't replicate. During the container startup I inserted a check on users file in order to trace  the issue, I'll let you know if it happens again.

**Comment by darrug** [comment]
I noticed that if a run multiple instances using the same data folder and I add a new user on one instance the other instances will delete the user because every instance writes his own cached values - persistence.js persistFlatCacheToFiles.
(underlying changes synchronization disabled)

This could be a problem if I have one instance with a corrupted file because can overwrite the right file. This can happen during rolling updates when multiple instances are running.

Could be possible to have a setting to disable filesystem checks or to increase the "stale" timeout?

**Comment by pofider** [comment]
This is true. 
I have pushed a new option to disable the flat files compaction that could help.
It will be part of the next release but you can try it already
```
npm i jsreport/jsreport-fs-store --save
```
```js
{ 
  "extensions": {
    "fs-store" {
       "compactionEnabled": false
    }
  }
}
```

**Comment by pofider** [comment]
Closing, the option for disabling compaction is available for some time.
