### ISSUE TITLE
Jsreport Keeps Refreshing

### ISSUE THREAD

**Issue by Pepukayi** [jsreport/jsreport#581]
Good day, 

I have an issue that after a restart to a server with my jsreport installation, it now keeps refreshing after a few seconds and I loose all the edits I would have done to my templates. I tried checking the settings but I can't seem to find where to fix this. Could you please point me to where I can change this. 

Regards
Pep

**Comment by pofider** [comment]
This is the same as [here](https://forum.jsreport.net/topic/1102/automatically-reloading).
There is a workaround, but **PLEASE** provide us more information I am asking for.
> This is a new regression on 2.5.0 and it was fine for you before?
The rendering and reloading should happen only if you modify the template file on the background from another process.
Don't you have another process modifying the data files?
Don't you have some kind of slow disk? In this case jsreport can assume it was an external modification even it was not.
Does this happen on your local pc or on a slower environment?

**Comment by Pepukayi** [comment]
Hi,

I am on 2.3.0. No, they are no other background processes modifying the templates. The server has enough processing speed. I made the change to my config file as suggested on the link and all is well now. Thanks

**Comment by pofider** [comment]
I believe you had multiple instances of jsreport running using the same data folder.
There was a bug caused preview loop in this situation.
It is now fixed in fs store. It will be part of the next release. 
Closing.
