### ISSUE TITLE
add some button in studio that shows how the JSON definition for specific template looks like

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#584]
i think it is very common that people ask how i can specify "x" when doing http requests to the API, i think we need a button (or modify the exisiting "API" button) to display how the JSON request looks like for the current template selected in studio. i think this has the potential to make the user understand better how the json body request looks like when you want to replicate something you have done in studio.

**Comment by pofider** [comment]
Probably this makes sense. And maybe even other options are useless then.
I don't like to overwhelm users with information and that is exactly what is the current dialog doing.

**Comment by pofider** [comment]
Leaving just a note...
The new async render "execution visualization" will cover how the inputs looks like, so we won't need anything special regarding this.

Additionally, an idea is to put to the entity right-click context menu buttons "show entity in json", which would pop up modal with json values and json schema

**Comment by pofider** [comment]
The v3 profiles solves this.
