### ISSUE TITLE
Protect office xlsx/docx/pptx documents with password

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#588]

**Comment by pofider** [comment]
Fortunately it is very easy to do and it works for all office outputs.
```js
const Encryptor = require('xlsx-populate/lib/Encryptor')
const fs = require('fs')

function protect(buffer, password) {
    const encryptor = new Encryptor()
    return encryptor.encrypt(buffer, password)    
}

const protectedBuffer = protect(fs.readFileSync('slides.pptx'), 'password')
fs.writeFileSync('protected.pptx', protectedBuffer)
```

So I think we start with custom extension `jsreport-office-password` that will cover this.

@bjrmatos Let me know if you are ok with it. It would be a task for you to finish this.

**Comment by bjrmatos** [comment]
yes, i'm ok with it. let's do it

**Comment by pofider** [comment]
Implemented in new extension
https://jsreport.net/learn/office-password
