### ISSUE TITLE
Bugs in the 0.4.0 release

### ISSUE THREAD

**Issue by noclue119** [jsreport/jsreport#59]
We built a new server with the 0.4.0 release. The HTML-To-XLSX rendering is creating a non-valid XLSX doc. The Phantom PDF generation was still fine. We also tried the 0.3.0 release and noticed that the server was crashing on any render. Our code is the same as https://github.com/jsreport/jsreport/issues/56

We ended up reverting to the 0.2.10 release in order to get both Phantom PDF and XLSX generation to work properly.

**Comment by pofider** [comment]
html-to-xlsx will be fixed in the patch, thanks for the bug report

Unfortunately I have messed up 0.3 version by releasing one of the dependency which was not back compatible with it. Hopefully people will upgrade to 0.4

**Comment by pofider** [comment]
html to xlsx should be fixed in patch 0.4.1 
https://github.com/jsreport/jsreport/releases
