### ISSUE TITLE
preview:true doesn't result in preview

### ISSUE THREAD

**Issue by forvy** [jsreport/jsreport#590]
I was trying to use the `API` from jsreport to a server-side like call by following: https://www.youtube.com/watch?v=11ZStDn87pk

But for some reason my API calling the excel was unable to be previewed, it always straight downloads

I've tried [adding the helper](https://forum.jsreport.net/topic/393/excel-recipe-to-show-in-browser-via-hosted-api/3):
```
function beforeRender (req, res, done) {
  req.options.preview = true
  done()
}
```

add the [option preview:true](https://github.com/jsreport/jsreport-html-to-xlsx/issues/5):

```
router.get('/', function (req, res, next) {
    var data = {
        template: { "shortid": "rkl5pxK_JH" },
        option: {
            preview: true
        }
    }
    var options = {
        uri: 'http://localhost:5477/api/report',
        method: 'POST',
        json: data
    }
    request(options).pipe(res);
});
```
Note: When calling pdf type it was able to previewed.
Was using Windows 10 Home, Chrome Version 75.0.3770.100 (Official Build) (64-bit), NPM 6.4.1, express 4.16.4

Any idea what I'm doing wrong here?

Edit: Not sure if this would help when I call the api to show in front-end side using Angular I was able to download/show PDF type(chrome-pdf), but I wasn't able to show xlsx type (html-xlsx) but was able to download.

From my console:

> Blob {size: 14151, type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}

**Comment by pofider** [comment]
There is a typo, this should work I think

```js
router.get('/', function (req, res, next) {
    var data = {
        template: { "shortid": "rkl5pxK_JH" },
        options: {
            preview: true
        }
    }
    var options = {
        uri: 'http://localhost:5477/api/report',
        method: 'POST',
        json: data
    }
    request(options).pipe(res);
});
```

**Comment by forvy** [comment]
> There is a typo, this should work I think
> 
> ```js
> router.get('/', function (req, res, next) {
>     var data = {
>         template: { "shortid": "rkl5pxK_JH" },
>         options: {
>             preview: true
>         }
>     }
>     var options = {
>         uri: 'http://localhost:5477/api/report',
>         method: 'POST',
>         json: data
>     }
>     request(options).pipe(res);
> });
> ```

ahhhhhh! thanks a lot. I just noticed that the option was missing the `s` I've been wrecking my brain and searching why it wasn't working.

**Comment by forvy** [comment]
Slightly related:

I was able to generate the preview on my back-end but the front-end call to the `<iframe>` was resulting straight download, even though the jsreport receive preview:true correctly.

.html
```
<div style="height:90vh;padding-bottom:10px;">
  <iframe width="100%" height="100%" style="overflow: auto;"></iframe>
</div>
```

.ts used to show file:
```
  showFile() {
    this.fileService.showFile(this.shortid).subscribe((res) => {
      var file = window.URL.createObjectURL(this.utilService.show(res, 'vnd.openxmlformats-officedocument.spreadsheetml.sheet'));
      document.querySelector("iframe").src = file;
    }, (err) => {
      console.error(err);
    });
  }
```

**Comment by pofider** [comment]
Check how the response looks like when you use preview:true using F12 tools.
The response is html which you should read as text and display in iframe for example,
It will load excel app from office online services.

It seems like you are operating with some `vnd.openxmlformats-officedocument.spreadsheetml.sheet` which is wrong.

**Comment by forvy** [comment]
> Check how the response looks like when you use preview:true using F12 tools.
> The response is html which you should read as text and display in iframe for example,
> It will load excel app from office online services.
> 
> It seems like you are operating with some `vnd.openxmlformats-officedocument.spreadsheetml.sheet` which is wrong.

I was able to take the response `<iframe src>` and used it for the preview in angular html. Thanks a lot for the help.

For those who's wondering how:
fileService.ts
```
// I ended up splitting the way to fetch xls and pdf:
showFilePdf(shortid) {
    return this.http.get('http://localhost:8001/test?shortid=' + shortid + '&preview=true', { responseType: 'blob' });
  }
  
  showFileXls(shortid) {
    return this.http.get('http://localhost:8001/test?shortid=' + shortid + '&preview=true', { responseType: 'text' });
  }
```
app.ts:
```
  showxlsx() {
    this.fileService.showFileXls(this.shortid).subscribe((res) => {
      var ele = document.createElement('div');
      ele.innerHTML = res;
      ele.querySelector('iframe').innerHTML = '';
      var file = ele.querySelector('iframe').src;
      document.querySelector("iframe").src = file;
    }, (err) => {
      console.error(err);
    });
  }

  showpdf() {
    this.fileService.showFilePdf(this.shortid).subscribe((res) => {
      var file = window.URL.createObjectURL(this.utilService.show(res, 'pdf'));
      document.querySelector("iframe").src = file;
    }, (err) => {
      console.error(err);
    });
  }
```
