### ISSUE TITLE
inputRequestLimit duplication in templatingEngines

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#595]
Right now we have noedjs express inputRequestLimit in jsreport-express.
However, we have this middleware also in the script-manager and templatingEngines evaluation.

Maybe there should be no limit in the script-manager because we already validate it upfront.
another option is that the jsreport-express sets templatingEngines.inputRequestLimit if it has user defined value in the options.
And the last option is that we just put a better error when templatingEngines.inputRequest limit is being hit so users know what config to change.

https://forum.jsreport.net/topic/1150/issue-about-inputrequestlimit

**Comment by pofider** [comment]
@bjrmatos  What you think?

**Comment by bjrmatos** [comment]
>And the last option is that we just put a better error when templatingEngines.inputRequest limit is being hit so users know what config to change.

i think this looks like the best.

i don't like modifying some general config when some other option from extension is present

this looks like we need some global option "inputRequestLimit" at the root of config that configures these two options.. it just feels weird that express option sets the templatingEngines.inputRequestLimit, more natural is that express limit is modified by the presence of some other option.

**Comment by pofider** [comment]
We decided to set infinite to inputRequestLimit in the jsreport-core.scriptsManager which is used by templating engines, scripts, pdf utils... The reason is that there is no benefit to having validation internally when we already validate the size in the express.
