### ISSUE TITLE
Any way to let the xlsx auto fit over-width / over-height columns/rows?

### ISSUE THREAD

**Issue by forvy** [jsreport/jsreport#597]
https://playground.jsreport.net/w/anon/j4G2n0Jk

By using style.xml you can modify template styling:

```
{{#xlsxReplace "xl/styles.xml"}}
    {#asset style.xml}}
{{/xlsxReplace}} 
```

But then is there any way to let the xlsx auto fit over-width / over-height columns/rows?

**Comment by pofider** [comment]
Unfortunately, office XML doesn't know "autofit".
The excel on double click just calculates the real height and put a number to the style.

I think it is not possible for us to magically calculate the real width/height as the excel does.
