### ISSUE TITLE
Report generation aborted for unsupported asset file extension

### ISSUE THREAD

**Issue by holocentric-bmsnext** [jsreport/jsreport#599]
Hi,
We are getting this exception when trying to generate a report that contains images with other extensions using chrome-pdf recipe, with handlebars engine. 

One or more errors occurred. (Unable to render template.  Asset encoded as dataURI needs to have file extension 
jpeg|jpg|gif|png|svg|woff|tff|otf|woff2|eot) 

Instead of aborting the report generation, we would like the report engine to just log the errors but allow the report to be generated.

Thanks,
Kathy

**Comment by pofider** [comment]
Thank you for the feature request.

I will wait for @bjrmatos opinion, but It seems to me it is better to fail than to silently ignore the problem. So I would keep it as it is. 

Maybe if you describe more your situation, we will be able to recommend you steps how to remove the invalid assets from your template. Maybe using a custom script.

**Comment by bjrmatos** [comment]
i think that it is better to fail than just a warning.. of course i don't know the exact use case that makes you get into the situation of asset without file extension, maybe if you can explain a little more we can understand if there is some limitation.

**Comment by holocentric-bmsnext** [comment]
We have some content that is dynamically created by the users, and it can contain any kind of images in some item's description. The application then dynamically generate the report assets, and use a template to render a report. We would like to just strip out the images instead of failing the generation since we would like to keep the images in the description.

Alternatively we can do some pre-processing to strip out all these images from the item descriptions prior to generating the report assets, but this is a bit over-killed.

**Comment by pofider** [comment]
It sounds to me you should strip or replace the "invalid" images when creating assets.

**Comment by bjrmatos** [comment]
closing as inactive
