### ISSUE TITLE
jsreport on the OpenShift PaaS

### ISSUE THREAD

**Issue by araczkowski** [jsreport/jsreport#60]
Hi,
I would like to run jsreport on OpenShift

For those I suppose I will need to add some additional code and adapt the jsreport. 
I'm guessing that: 
1. possibility to pass the server IP to jsreport should be add
2. ???
any ideas what else?
Did anybody was able to run jsreport on OpenShift?

PS
I will start the repo on github when I find a time
the first version of the server.js will be like below

Thanks and regards
Andrzej

``` javascript
#!/bin/env node

var servHost = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1';
var servPort = process.env.OPENSHIFT_NODEJS_PORT || 5000;
var jsreport = require('jsreport');


try {
    jsreport.bootstrapper({
        httpPort: servPort,
        httpIp: servHost
    }).start();
    console.log('Started jsreport on IP: ' + servHost + ' port: ' + servPort);

} catch (err) {
    console.log('Error: ' + err);
}
```

**Comment by araczkowski** [comment]
the repo for the jsreportOpenShift 
https://github.com/araczkowski/jsreportOpenShift

of course so far no luck on OpenShift - see the log below 

any ideas how to provide the host ip to the jsreport server?


``` shel
Wed Apr 15 2015 17:35:10 GMT-0400 (EDT): Node server stopped.
DEBUG: Running node-supervisor with
DEBUG:   program 'server.js'
DEBUG:   --watch '/var/lib/openshift/552ed312fcf93339ca000208/app-root/data/.nodewatch'
DEBUG:   --ignore 'undefined'
DEBUG:   --extensions 'node|js|coffee'
DEBUG:   --exec 'node'
DEBUG: Starting child process with 'node server.js'
DEBUG: Watching directory '/var/lib/openshift/552ed312fcf93339ca000208/app-root/data/.nodewatch' for changes.
Started jsreport on IP: 127.13.159.1 port: 8080
DEBUG: Program node server.js exited with code 1
DEBUG: Starting child process with 'node server.js'
Started jsreport on IP: 127.13.159.1 port: 8080
DEBUG: Program node server.js exited with code 1
DEBUG: Starting child process with 'node server.js'
```

**Comment by pofider** [comment]
You can workaround starting on dedicated ip address using following code.

```js
var servHost = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1';
var servPort = process.env.OPENSHIFT_NODEJS_PORT || 5000;
var jsreport = require('jsreport');

var  app = require('express')();
require("jsreport").bootstrapper({
    express : { 
        app : app
    }
}).start().then(function() {
    app.listen(servPort, servHost);
}).catch(function(e) {
   console.log('Error: ' + err);
});
```

Note that bootstrapper.start returns a promise, see how it is logging error in my snipped.

**Comment by araczkowski** [comment]
Thank you Jan for quick and detailed reply, your tip works OK on my local box - It's nice that jsreport can be attached to the existing express app.
I hope that now I'm step further with the jsreport on the OpenShift, but looks like the servHost should be bind in some other place too...

Please find the error stack info from error.log below. Any ideas? 
Thanks, Andrzej


``` shel
015-04-16T20:16:49.867Z - error: uncaughtException: listen EACCES date=Thu Apr 16 2015 16:16:49 GMT-0400 (EDT), pid=503611, uid=6072, gid=6072, cwd=/var/lib/openshift/552fdadee0b8cd8a0d0000df/app-root/runtime/repo, execPath=/opt/rh/nodejs010/root/usr/bin/node, version=v0.10.25, argv=[node, /var/lib/openshift/552fdadee0b8cd8a0d0000df/app-root/runtime/repo/server.js], rss=42344448, heapTotal=34235136, heapUsed=20860392, loadavg=[6.951171875, 5.05078125, 3.59521484375], uptime=1342349.118445875, trace=[column=11, file=net.js, function=errnoException, line=901, method=null, native=false, column=19, file=net.js, function=Server._listen2, line=1020, method=_listen2, native=false, column=10, file=net.js, function=listen, line=1061, method=null, native=false, column=5, file=net.js, function=Server.listen, line=1135, method=listen, native=false, column=40, file=/var/lib/openshift/552fdadee0b8cd8a0d0000df/app-root/runtime/repo/node_modules/jsreport/node_modules/net-cluster/lib/net-cluster.js, function=Server.listen, line=50, method=listen, native=false, column=61, 
file=/var/lib/openshift/552fdadee0b8cd8a0d0000df/app-root/runtime/repo/node_modules/jsreport/node_modules/net-cluster/lib/net-cluster.js, function=Server.listen, line=3, method=listen, native=false, column=12, 
file=/var/lib/openshift/552fdadee0b8cd8a0d0000df/app-root/runtime/repo/node_modules/jsreport/node_modules/script-manager/lib/manager.js, function=findFreePort, line=38, method=null, native=false, column=5, 
file=/var/lib/openshift/552fdadee0b8cd8a0d0000df/app-root/runtime/repo/node_modules/jsreport/node_modules/script-manager/lib/manager.js, function=ScriptsManager.start, line=44, method=start, native=false, column=10, 
file=/var/lib/openshift/552fdadee0b8cd8a0d0000df/app-root/runtime/repo/node_modules/jsreport/node_modules/script-manager/lib/manager.js, function=ScriptsManager.ensureStarted, line=118, method=ensureStarted, native=false, column=36, 
file=/var/lib/openshift/552fdadee0b8cd8a0d0000df/app-root/runtime/repo/node_modules/jsreport/node_modules/q/q.js, function=Promise.post, line=1103, method=post, native=false], 
stack=[Error: listen EACCES,     
at errnoException (net.js:901:11),     
at Server._listen2 (net.js:1020:19),     
at listen (net.js:1061:10),     
at Server.listen (net.js:1135:5),    
at Server.listen (/var/lib/openshift/552fdadee0b8cd8a0d0000df/app-root/runtime/repo/node_modules/jsreport/node_modules/net-cluster/lib/net-cluster.js:50:40),     
at Server.listen (/var/lib/openshift/552fdadee0b8cd8a0d0000df/app-root/runtime/repo/node_modules/jsreport/node_modules/net-cluster/lib/net-cluster.js:3:61),     
at findFreePort (/var/lib/openshift/552fdadee0b8cd8a0d0000df/app-root/runtime/repo/node_modules/jsreport/node_modules/script-manager/lib/manager.js:38:12),     
at ScriptsManager.start (/var/lib/openshift/552fdadee0b8cd8a0d0000df/app-root/runtime/repo/node_modules/jsreport/node_modules/script-manager/lib/manager.js:44:5),     
at ScriptsManager.ensureStarted (/var/lib/openshift/552fdadee0b8cd8a0d0000df/app-root/runtime/repo/node_modules/jsreport/node_modules/script-manager/lib/manager.js:118:10),     
at Promise.post (/var/lib/openshift/552fdadee0b8cd8a0d0000df/app-root/runtime/repo/node_modules/jsreport/node_modules/q/q.js:1103:36)]
```

**Comment by pofider** [comment]
Ouch... You really can't start any http server on openshift with custom port? jsreport is starting internally other web servers to optimize performance and provide a kind of a container for bad reports which could block the system.

I am willing to add an option to start whole rendering "in process" to avoid this, but it is probably the best you fork jsreport and make a prototype, then I can make needed changes to jsreport core when the concept is proven.

You particularly need to "ignore" script manager dependency.
- comment out starting script-manager here
https://github.com/jsreport/jsreport/blob/master/lib/reporter.js#L79
- bypass script manager rendering here
https://github.com/jsreport/jsreport/blob/master/lib/render/render.js#L22
with something like response.result = request.template.content

phantom-pdf rendering is starting also an internal web server, so it won't work as well, but you can get at least some kind of a html rendering to work

**Comment by araczkowski** [comment]
Hi Jan, thanks for detailed instructions - there is a progress :)
http://jsreportopenshift-cwms.rhcloud.com/

concerning the **custom ports on OpenShift** - maybe this can be useful for us?:
"It is possible to bind to the internal IP with **port range: 15000 - 35530**. All other ports are reserved for specific processes to avoid conflicts. "
https://help.openshift.com/hc/en-us/articles/202185874

**the first version of a prototype** for openshift is on fork 
https://github.com/araczkowski/jsreport/commit/b839512e94c3b1823c19743ce09185c9576eca0b
should I do a pull request or first we can try to make this more useful? - if it will be possible to do at least full html rendering?

**Comment by pofider** [comment]
Hmm, that is interesting. Please try the port from that range if it really works. Script manager is searching for the port here
https://github.com/pofider/node-script-manager/blob/master/lib/manager.js#L29
Then we can make the port configurable and we are almost done for html. The same thing can be done then for pdf.

Too early for the pull request, lets make it working first.

**Comment by araczkowski** [comment]
Hi again,
I checked the ports on the internal IP - this approach works OK
so I did a script-manager fork, added a portscanner to the dependencies and implement this in code:
https://github.com/pofider/node-script-manager/compare/master...araczkowski:master

now the html template works OK http://jsreportopenshift-cwms.rhcloud.com/

2 questions:
1. can you merge this (possibility to take port from range and assign the server host) into script-manager
2. how can we do this same for phantom-pdf - could you please give me some clue?
thanks and regards

**Comment by pofider** [comment]
Ok, perfect so one more thing to prove is pdf, then I will merge it. It is completely enough you just verify it is working for fixed port value...

Here write something like OPENSHIFT_NODEJS_IP + ":20000" instead of just a port
https://github.com/pofider/phantom-workers/blob/master/lib/phantomWorker.js#L50

Replace ip with OPENSHIFT_NODEJS_IP
https://github.com/pofider/phantom-workers/blob/master/lib/phantomWorker.js#L89

Replace ip with OPENSHIFT_NODEJS_IP
https://github.com/pofider/phantom-workers/blob/master/lib/checkPortStatus.js#L6

The port variable here should contain ip with port, so remove the ip from string
https://github.com/pofider/phantom-html-to-pdf/blob/master/lib/phantomScript.js#L16

Thank you very much. Let me know when it is working and then I can do the rest to make jsreport ready for OpenShift.

**Comment by araczkowski** [comment]
Hi Jan,
thanks - I had some time today, so I was able to figure out this :)
We have jsreport with pdfs on OpenShift!

Since I more understand this now ... I cleaned up a little bit my previous code and it is here:
phantom-workers
https://github.com/pofider/phantom-workers/compare/master...araczkowski:master
phantom-html-to-pdf
https://github.com/pofider/phantom-html-to-pdf/compare/master...araczkowski:master
node-script-manager
https://github.com/pofider/node-script-manager/compare/master...araczkowski:master

this was tested on OpenShift - it works OK: http://jsreportopenshift-cwms.rhcloud.com/

The pull requests are on the way 

Thanks you

PS
maybe it will be a good idea to add a port ranges and host to options... somehow
of course is up to you how you will merge this


PS2
I will work on some special case - report with SVG and HTML soon
if the solution based in jsreport will work better then our current approach I'm going to write a article/presentation about this
then I'm going to recommend this solution to my client

so we should be in touch :)

**Comment by pofider** [comment]
I have just released jsreport 0.5.0 with changes required for running jsreport on OpenShift.

Could you please verify these instructions are correct?
https://github.com/jsreport/docs/blob/master/installation/OpenShift.md

Thank you.

**Comment by araczkowski** [comment]
Hi Jan,

OK - I forked  docs and I'm working on "Starting with jsreport on OpenShift (step by step instruction)"
https://github.com/araczkowski/docs/blob/master/installation/OpenShift.md

but something is wrong:
1. when the app  is run with options in server.js there is a problem
``` shel
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:471:13)
    at /home/andrzej/Projects/SVIETE/doc_jsreportopenshift/node_modules/jsreport/lib/bootstrapper.js:48:71
```
looks like self.config.rootDirectory is undefined

2. I added the options to the prod.config.json file - now it works on localhost 

``` javascript
{
    "connectionString": {
        "name": "neDB"
    },
    "blobStorage": "inMemory",
    "tasks": {
        "host": "127.9.11.129",
        "portLeftBoundary": 15000,
        "portRightBoundary": 35530
    },
    "phantom": {
        "host": "127.9.11.129",
        "portLeftBoundary": 15000,
        "portRightBoundary": 35530
    }
}

```

but on OpenShift there is a error

``` shel
Error: bind EACCES
    at errnoException (net.js:901:11)
    at net.js:1069:30
    at Object.39:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at Pipe.channel.onread (child_process.js:345:11)
```

I will try to figure what is going on later (when I will have more time)

Reagards 
Andrzej

**Comment by pofider** [comment]
To the path error.....

You should not nest `options` in the bootstrapper param, it should be like this:
```js
require('jsreport').bootstrapper({
    express: {
        app: app
    },
    tasks: {
            host: servHost,
            portLeftBoundary: 15000,
            portRightBoundary: 35530
    },
    phantom: {
            host: servHost,
            portLeftBoundary: 15000,
            portRightBoundary: 35530
    }    
})
```

To the EACCES...
Maybe you can try to set the port ranges exclusive for the `tasks` and `phantom`. Like:
```js
 tasks: {
            host: servHost,
            portLeftBoundary: 15000,
            portRightBoundary: 16000
    },
    phantom: {
            host: servHost,
            portLeftBoundary: 17000,
            portRightBoundary: 18000
    }    
```
That is just a shot, the problem is probably somewhere else, I will give it some thoughts...

**Comment by pofider** [comment]
I forgot to add that the docs you are creating looks very good. I appreciate it. Thanks a lot.

**Comment by araczkowski** [comment]
Hi,

1. path error
you are right - I went too far with the  "options inception" ;)

but still looks like the configuration file is mandatory - maybe it's OK - I don't know?
In case not - below detail description:

I have the server.js with all the options I need, like below:
``` javascript
#!/bin/env node
//  OpenShift jsreport Node application

var servHost = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1';
var servPort = process.env.OPENSHIFT_NODEJS_PORT || 5000;
var jsreport = require('jsreport');
var app = require('express')();
var options = {
    express: {
        app: app
    },
    tasks: {
        host: servHost,
        portLeftBoundary: 15000,
        portRightBoundary: 35530
    },
    phantom: {
        host: servHost,
        portLeftBoundary: 15000,
        portRightBoundary: 35530
    },
    connectionString: {
        name: "neDB"
    },
    blobStorage: "inMemory"
};

jsreport.bootstrapper(options).start().then(function() {
    app.listen(servPort, servHost);
});
```
now if I'm going to start this (node server.js) without a configuration file and I will have a error:
``` shel
error when bootstrapping jsreport
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at /home/andrzej/Projects/SVIETE/jsreports/doc_jsreportopenshift/node_modules/jsreport/lib/bootstrapper.js:45:71
From previous event:
    at Bootstrapper.start (/home/andrzej/Projects/SVIETE/jsreports/doc_jsreportopenshift/node_modules/jsreport/lib/bootstrapper.js:39:16)
```
simply add a prod.config.json file (even with the empty object {}) and it :sparkles: works OK

**Comment by araczkowski** [comment]
2. EACCES...
looks like it wasn't all - sometimes in the node-script-manager/lib/worker.js the host was undefined
I corrected this, the pull request:  https://github.com/pofider/node-script-manager/pull/5
with this fix it works for me on OpenShift

**Comment by araczkowski** [comment]
#### docs for OpenShift 
I'm glad the you like it :smile: 
here is the pull request with a first version: https://github.com/jsreport/docs/pull/1

soon I'm going to describe (add to this doc) how to use a OpenShift's Mongodb cartridge (to store the jsreport data)

Regards
Andrzej

**Comment by pofider** [comment]
Great!

I see now that error with `path.join...` is actually a bug. The original idea is to precreate config in bootstrapper when it is not found. This doesn't seem to me be very bright now, it should rather work without the config file. I will probably change this behavior.

Thanks for the detailed docs. I will try to follow your instructions on my own to see OpenShift in action.

**Comment by pofider** [comment]
I just released new jsreport package and tested it with updated installation instructions for OpenShift. It is working great now. 

Thank you very much for your cooperation on this.

**Comment by araczkowski** [comment]
Hi,

you are welcome :)
thanks for your cooperation on this and for the very interesting project!


PS
I did a presentation for my Client - comparing the typical XSL-FO workflow vs modern HTML & CSS workflow (based on Oracle BI Publisher vs jsreports).
The conclusions are:
1. HTML&CSS solutuin used in jsreport in some cases can be better for us 
2. solution based on HTML&CSS can solve some of our current problems :)

Currently I'm working on plugin for integration the jsreport with the application framework used by my Client (Oracle APEX).
So I hope that I will be able to extend and continue my contribution to the jsreport project.

Have a nice day!
Andrzej
