### ISSUE TITLE
Get headers from browser client response

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#609]
It seems there is no way to get headers from `jsreport.renderAsync`.
We are returning just ArrayBuffer with some shortcut functions.

![image](https://user-images.githubusercontent.com/2041960/62522904-eddbee80-b832-11e9-9da5-372fd94f8052.png)

For now, I would propose to attach to the ArrayBuffer also property `xhr` that could be used to get the response headers. So just something like this [here](https://github.com/jsreport/jsreport-browser-client-dist/blob/master/src/jsreport.js#L178)

```
response.xhr = xhr
```

**Comment by bjrmatos** [comment]
ah yes, i agree with this idea, i think this is common to see on some libraries that wrap xhr requests, so this solution looks the best.

**Comment by pofider** [comment]
This is done in browser client dist 1.3.0.
However, it will start to work when we release the next jsreport because it needs some cors related changes in the express extension.
