### ISSUE TITLE
modular reports

### ISSUE THREAD

**Issue by zheffie** [jsreport/jsreport#61]
Is the following use case possible in the existing platform?
Create a configurable report based on a combination of re-usable modules.

eg: a main report template
```
{#child moduleTable}
{#child moduleGraph}
```
where moduleTable and moduleGraph are independent templates with their own scripts to load data using ajax

**Comment by pofider** [comment]
Scripts are not evaluated for the child templates right now. However I think there was just a technical reason for this, It makes sense to me that if there is a script on the child template, it should be evaluated.

So I should probably do it.

**Comment by pofider** [comment]
This should be now supported in jsreport 0.5.0
