### ISSUE TITLE
chart.js renders faulty  charts  when using chrome-pdf recipe

### ISSUE THREAD

**Issue by NazmiAltun** [jsreport/jsreport#610]
There seems to be a problem with  chrome-pdf recipe , when I use chart.js to render a simple horizontal bar chart. However, same template works with **html** and **html-with-browser-client** recipes.

Here is the playground url : [https://playground.jsreport.net/w/NazmiAltun/Co41j7SM](https://playground.jsreport.net/w/NazmiAltun/Co41j7SM)

Html recipe output :
![html](https://user-images.githubusercontent.com/22505205/62571369-dc79fd00-b899-11e9-8335-88ca6532fa33.PNG)
chrome-pdf recipe output:
![chromepdf](https://user-images.githubusercontent.com/22505205/62571383-e4d23800-b899-11e9-9ab7-d12abb6d79a4.PNG)

Any idea?

**Comment by NazmiAltun** [comment]
oh snap,  setting  **wait for network iddle**   flag to true fixed the issue.  I am closing this.

**Comment by GiorgosBetsos** [comment]
@NazmiAltun I have the exact same issue, but I do not understand what you mean by setting wait for network iddle flag to true. Where am I supposed to set this flag?

**Comment by GiorgosBetsos** [comment]
Well, it was something simple:

   ```
    HttpContext.JsReportFeature()
                .Recipe(Recipe.ChromePdf)
                .Configure(req => req.Template.Chrome = new Chrome
                {                    
                    WaitForNetworkIddle = true  
                }); 
```

**Comment by Tiagochicoo** [comment]
@GiorgosBetsos  where do you add this code? Thanks

**Comment by d093w1z** [comment]
You can delay the printing by setting the 'wait for printing trigger' or 'wait for network idle' in jsreport studio.

Reference:
[jsreport chrome-pdf#printing-triggers](https://jsreport.net/learn/chrome-pdf#printing-triggers)
