### ISSUE TITLE
Passing evaluated data adds an extra space to last argument

### ISSUE THREAD

**Issue by OlivierKamers** [jsreport/jsreport#611]
Using a child template with data like this, containing another interpolated value:
`{#child name @data.foo={{anotherHelper bar}} }` actually passes the data `{ "foo": "bar "}` instead of the expected `{ "foo": "bar"}` (assuming the helper `anotherHelper` just returns the its argument). 

The space before the closing `}` is needed to make it valid handlebars syntax (`{#child name @data.foo={{anotherHelper bar}}}` gives a syntax error) but the regexp used for parsing the call to child template includes it in the data: https://github.com/jsreport/jsreport-child-templates/blob/master/lib/childTemplates.js#L110

It looks like it's the same issue as in this StackOverflow post with a suggested workaround: https://stackoverflow.com/a/50840208
However, I was wondering if it's maybe possible to adapt the regex to handle this case? I'm hoping it's possible to check for an optional space at the end of the expression.

**Comment by pofider** [comment]
@bjrmatos Thank you, great work. I've done also a performance test on giant html and the speed is ~identical to the previous implementation. 

@OlivierKamers This will be released in jsreport 2.6.0 which will the most likely come to life the next week.

**Comment by OlivierKamers** [comment]
Great news, thanks for the very quick response! 👍
