### ISSUE TITLE
Pdf utils significantly increases file size

### ISSUE THREAD

**Issue by holocentric-bmsnext** [jsreport/jsreport#613]
We have been using jsreport to generate some pdfs and the files that are getting outputted are unreasonable large for their contents. After some trial and error we have found out pdfutils to be one of the main causes. We applied a blank template merge operation on an existing template and the file size increased from 800kb to 5200kb.

We are using jsreport version 2.5 and chrome to pdf.

Thanks,

Thomas

**Comment by pofider** [comment]
Would you be able to share that original pdf you are merging into?

I've tried merging into the invoice sample and the size difference is 64kb -> 81kb. And it is caused by the introduction of xobject (merge operation). Additional there are some white spaces that causes also the increase, but not sure if it is the case making it such increase for you. I would like to try it out with your template.

**Comment by holocentric-bmsnext** [comment]
[export.zip](https://github.com/jsreport/jsreport/files/3538929/export.zip)

Hi Jan,

I have attached a minimum repro zip to be imported into jsreport.

I am using these settings:
- engine: handlebars
- recipe: chrome-pdf

When merging whole document with the header footer, the pdf generated is 611 KB. When not merging, the pdf generated is 68 KB in size.

Thanks,


Thomas

**Comment by pofider** [comment]
Thank you.
I see the problem now. It is likely caused by the duplication of fonts on every page.
I will try to find time to optimize it. Unfortunately, it is bit complicated, so it won't be part of the upcoming release I am afraid.

**Comment by pofider** [comment]
I hope I was able to fix the main problem which was duplicating fonts.
You can try the updated pdf utils after
```
npm i jsreport/jsreport-pdf-utils
```

Note the fix is relevant just for the "merge whole document" option.

**Comment by holocentric-bmsnext** [comment]
Hey Jan,

Thank you, it seems that your fix has improved performance. I was wondering how I would be able to get this in my docker container, as the docker image seems yet to have this fix in.

Thanks,


Thomas

**Comment by pofider** [comment]
We have a quick tutorial for extending jsreport default image here
https://jsreport.net/learn/customize-docker-image

You just need to install pdf utils extension from git dep in your dockerfile.
```
RUN npm i jsreport/jsreport-pdf-utils --save
```

**Comment by pofider** [comment]
The updated pdf utils are now part of the jsreport@2.7.0
