### ISSUE TITLE
PDF not showing proper borders on tables

### ISSUE THREAD

**Issue by aslamkhan669** [jsreport/jsreport#615]
I am generating a pdf but its not applying style to the table rows. 
![image](https://user-images.githubusercontent.com/2170474/63446083-31e80980-c457-11e9-90d1-784fa71bd827.png)
```
 <tr style="border-top:2px solid black;font-weight: 500">
                        <td colspan="6">Amount In words</td>
                        
                        <td colspan="2">Total Invoice Value(A+B+C)</td>
                </tr>	
                <tr style="border-bottom:2px solid black;font-weight: 600;color:black">
                        <td colspan="6">Rupees <%=words%> only.</td>
                        
                        <td colspan="2" id="totalInvoiceAmount"> &#8377; <%=invoiceAmount %></td>
                </tr>
```	
this is the styling i am applying it works ok if I generate pdf from chrome browser.

**Comment by bjrmatos** [comment]
hi! it will be good if you can replicate the problem [here](https://playground.jsreport.net/), save it, and share the link back. i would like to check it, maybe it is just the default behaviour of the chrome headless and you need to apply the style differently, but i would like to confirm it with an example

**Comment by aslamkhan669** [comment]
https://playground.jsreport.net/w/aslamkhan669/4eKp0LsR

**Comment by aslamkhan669** [comment]
I was applyiing broders on rows so there its not working but it works if I apply it on td would be good if I can do tr instead

**Comment by bjrmatos** [comment]
i checked and it seems that row border can't be applied by default in browser too (i used the same html do you have in browser)

however i you add this css to the table, it works. ([see this](https://stackoverflow.com/a/10040881))

```css
#yourTable {
  border-collapse: collapse;
}
```
