### ISSUE TITLE
Use API to create entity to specific folder

### ISSUE THREAD

**Issue by ericmvu** [jsreport/jsreport#619]
It would be nice if we could specify a folder in which the new entity is created to. Right now it puts the new entity to the root folder. This is inconvenient when working with a folder structure through the UI.

**Comment by bjrmatos** [comment]
hi!

when using the http API you can create an entity at specific folder by sending the folder parent information in the request body.

```js
{
  //...rest of template properties
  folder: {
    shortid: '<shortid of parent folder folder here>'
  }
  //...rest of template properties 
}
```
