### ISSUE TITLE
pdf utils append fails with PDF downloaded from remote url

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#621]
the pdf utils append fails in this specific case, replicated in the followed zip.

more specifically it fails [here](https://github.com/jsreport/jsreport-pdf-utils/blob/master/lib/utils/addPages.js#L5) when trying to parse the pdf buffer of the remote pdf

[export.zip](https://github.com/jsreport/jsreport/files/3584977/export.zip)

**Comment by pofider** [comment]
The trouble is that the linked pdf is linearized. The library we use to parse pdf doesn't support linearized pdfs. It would be a lot of effort to implement this support.

The current workaround would be to "delinearize" pdf with another tool before using in jsreport. However not sure if such a tool exists.

**Comment by pofider** [comment]
The linearization support has specific task here
https://github.com/jsreport/jsreport/issues/857
