### ISSUE TITLE
templateHelpers not working in pug engine

### ISSUE THREAD

**Issue by rajusubramaniam** [jsreport/jsreport#627]
> I have this code in NodeJS.

```
jsreport.render({
   template: {
		content: 'h1 Hello #{templateHelpers.foo()}',
		helpers: { foo: () => { return 'world' } },
		engine: 'pug',
		recipe: 'chrome-pdf'
	},
	data: {
					},
}).then((out) => {
	out.stream.pipe(res);
}).catch((e) => {
	res.end(e.message);
});
```

I tried various combinations and could not get visibility of the helper method 'foo'. Am I missing something?

`Error while executing templating engine. templateHelpers.foo is not a function on line 1`

**Comment by pofider** [comment]
It by default expects a string like:

```
helpers: "function foo () { return 'hello world' }"
```

You need to switch to the in-process templating strategy if you want to pass object with functions. This can be done in the config:

```
{ "templatingEngines": { "strategy": "in-process" } ... }
```
