### ISSUE TITLE
Replace value from merge cells

### ISSUE THREAD

**Issue by maykoestevez** [jsreport/jsreport#633]
Hello, I want to change the value of merge cells, an example I would like to replace the value of the B1:F1 cells

<img width="622" alt="Screen Shot 2019-09-23 at 5 12 14 AM" src="https://user-images.githubusercontent.com/8959257/65414561-0348b000-ddc2-11e9-89a4-ff9a90c1ec62.png">

So far I have  this 
```
{{#xlsxReplace "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row[0].c[0]"}}
<c t="inlineStr"><is><t>change name</t></is></c>
{{/xlsxReplace}}
{{{xlsxPrint}}} 
```
These lines will help to replace the value on a specific cell but I don't know how to point to the merge ones.

**Comment by pofider** [comment]
Shouldn't just this tiny change make it work?
```
{{#xlsxReplace "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row[0].c[1]"}}
<c t="inlineStr"><is><t>change name</t></is></c>
{{/xlsxReplace}}
```

**Comment by maykoestevez** [comment]
I already tried this and I don't get any change with that approach, with the code that I published The A1 cell get the text, but when I point to cell[1] nothing happened.

**Comment by pofider** [comment]
It does for me...
Please share a simple playground demo just with one merged cell and that code so I can take a look.
https://playground.jsreport.net/

**Comment by maykoestevez** [comment]
I created I new file and replace the value correctly seems like the file has something that does not allow me to replace the value, I will keep trying.

In another hand, I notice that when I replace the value, it lose all the previous format, is there a way to keep the format while replacing or applying those formats when replacing the value

**Comment by pofider** [comment]
Use xlsxMerge instead.

```
{{#xlsxMerge "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row[0].c[1]"}}
    <c t="inlineStr"><is><t>change name</t></is></c>
{{/xlsxMerge}}
```

Closing this as there seems to be no issue. Feel free to comment further.

**Comment by maykoestevez** [comment]
Thanks, it works.
