### ISSUE TITLE
Moving entities between folders without jsreport studio

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#636]
Currently, entities store the folder.shortid in the `config.json`.
This prevents users to manually move entities between folders without jsreport studio.

There should be no folder.shortid persisted in the `config.json` and it should be automatically computed from the parent folder. 
The permission distributions should be evaluated if this doesn't break it.

**Comment by bjrmatos** [comment]
done in https://github.com/jsreport/jsreport-fs-store/commit/bc67c49cca89d65a0ded92f1316a3587e3da9549
