### ISSUE TITLE
Trying to move Windows to CentOs

### ISSUE THREAD

**Issue by samir-kamble** [jsreport/jsreport#638]
Hello I am moving Windows installation of JSReport 1.7.0 to CentOs. 

I am getting phantomJS errors. I even installed PhantomJS 1.9.5 Linux version. Server also got started on 5488 but When I try to generate PDF it abruptly closes down the server and am not able to understand where it is going wrong. 

I am attaching NPM log for your reference. Please help me in this regards.
[npm-debug.log](https://github.com/jsreport/jsreport/files/3647815/npm-debug.log)
Sam.

**Comment by pofider** [comment]
You can try something like this
```
sudo yum install bzip2	
sudo yum install libXext  libXrender  fontconfig  libfontconfig.so.1	
sudo yum install urw-fonts
```

And try to search phantomjs centos issues
https://github.com/ariya/phantomjs/search?q=centos&type=Issues

I am afraid we can't help you further. We concentrate mainly on chrome-pdf now and run phantomjs just on ubuntu docker images.
