### ISSUE TITLE
long tables and html-to-xlsx

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#639]
when trying to produce an xlsx file with thousands of rows (like for example using json file of 24mb) the chrome/phantom conversion hangs. i've saw that phantom just crashes after a while, and that chrome can load the page after some time but then it crash on the js part that reads all the tr elements of the DOM and i could not avoid thinking that we can somehow parallelize this to avoid the chrome crash, for example that somehow user is able to define tables that can be we can parallelize internally, each of these table will handle a different piece of data, and in the end we will merge all the rows in single xlsx file, similar to what we do with pdf-utils merge but in this case with html-to-xlsx conversion.

**Comment by bjrmatos** [comment]
for myself: in case we have some progress with this idea i have a test case in my local called "jsreport-html-to-xlsx-timeout-issue" that we can use for testing.

**Comment by pofider** [comment]
I guess it will be always too slow to render 100 000 table cells using a browser and then evaluate it.
I would like to test how the browserless solution would work
https://github.com/cheeriojs/cheerio

**Comment by pofider** [comment]
https://jsreport.net/learn/html-to-xlsx#cheerio-html-engine
