### ISSUE TITLE
Access data in script tags

### ISSUE THREAD

**Issue by CuReSoft** [jsreport/jsreport#64]
Hi guys,

how can i access the jsreport.template.data Objects in a phantom-pdf report.

Im fetching data this way.

 $.get(serviceurl''+jsreport.template.data.e._id,function(data){......

In the wrapper-html its just working fine but when i switch to phontom pdf it seems the jsreport var is not set.

How can i get the data pushed to jsreport.template.data in a script tag?

Thanks in advance, 
Max

**Comment by pofider** [comment]
Hi,

jsreport.template object is provided just by wrapped-html recipe.

In phantom-pdf you can use standard approach with templating engines, so for example with handlebars it could be 
$.get(serviceurl{{e._id}},function(data){......

**Comment by CuReSoft** [comment]
YOU MADE MY DAY. Thx a lot.
