### ISSUE TITLE
Timeout error during tests using Jest

### ISSUE THREAD

**Issue by Bubomir** [jsreport/jsreport#640]
Hi I try to test my code but jsreport always throw timeout error. I try to increase timeout but no progress. If i run normal server and try render pdf file it's work fine

    
![image](https://user-images.githubusercontent.com/9303146/65788736-047c3300-e15c-11e9-830d-0adbce450817.png)

debug log

![image](https://user-images.githubusercontent.com/9303146/65788762-15c53f80-e15c-11e9-8037-0e40a442d303.png)

ENV
    WIN 10: 1903, build 18362.356
    node: "10.15.0"
    jsreport-chrome-pdf: "1.6.1",
    jsreport-core: "2.6.1",
    jsreport-ejs: "2.2.0"

example code

    import jsreport from 'jsreport-core'

    const jsreportEjs = require('jsreport-ejs')
    const jsreportChrome = require('jsreport-chrome-pdf')

    describe('test render', () => {
	    it('test', async () => {
		    const jsreportInstance = await jsreport()
			    .use(jsreportChrome())
			    .use(jsreportEjs())
			    .init()
		    const result = await jsreportInstance.render({
			    template: {
				content: '<div>Hello world</div>',
				engine: 'ejs',
				recipe: 'chrome-pdf'
			}
		})
		expect(result).toBe('To be someting')
	    })
    })

Thaks for help

**Comment by pofider** [comment]
Not familiar with jest. It works with mocha
https://github.com/jsreport/jsreport-ejs/blob/master/test/ejs.js#L43

Let us know if you find out what is the issue with jest here.
Maybe it has an issue with spawning a new process with templating engine evaluation. 
You can try this

```js
const jsreportInstance = jsreport({
templatingEngines: {
strategy: "in-process"
})
```

**Comment by Bubomir** [comment]
Thank you so much your solution works fine
