### ISSUE TITLE
Default docker env values - templatingEngines.strategy

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#643]
https://forum.jsreport.net/topic/1276/bad-request/15

We set in dockerfile some default values through Dockerfile env
https://github.com/jsreport/jsreport/blob/master/docker/default/Dockerfile#L41

This makes it impossible to change through normal config file.

**Comment by pofider** [comment]
We have two options:

1. Use the [editConfig.js](https://github.com/jsreport/jsreport/blob/master/docker/default/editConfig.js) to write the templatingEngines.strategy to our `jsreport.config.json` which gets replaced by the mounted user config.

2. Simply don't use extra strategy there and stay with default.

I would be probably for the second option and be consistent with the normal jsreport. The small performance decrease can be easily fixed by customers config.

**Comment by bjrmatos** [comment]
i like more the second option too 👍

**Comment by pofider** [comment]
Ok. We will pass it in the 2.7.0, and do it after we release 2.6.1 hotfix.

**Comment by bjrmatos** [comment]
done in https://github.com/jsreport/jsreport/commit/8b1e61aaafa54b552ebc79a92de153be3f2837d6
