### ISSUE TITLE
Data propagation to the nested  requests

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#645]
jsreport merges the parent request data into the child requests
https://github.com/jsreport/jsreport-core/blob/master/lib/render/request.js#L22

The sample data extension loads linked entity only if the input data are empty
https://github.com/jsreport/jsreport-data/blob/master/lib/data.js#L35

The sample data extension also "guarantees" there is an empty object on the request.
https://github.com/jsreport/jsreport-data/blob/master/lib/data.js#L40

These three aspects cause jsreport to skip loading sample data for child template even when it is linked and no data provided on the input request.
https://playground.jsreport.net/w/felipebossolani/SOKRsubw

The solution could be maybe this.
It will be the jsreport-core responsibility to guarantee the `req.data` is not null.
The core would write to the `req.contex.originalInputDataIsNull=true`.
The sample data extension would load the linked entity in case `req.contex.originalInputDataIsNull`.
The data propagation to the child requests would work as it is.

**Comment by bjrmatos** [comment]
ok, got it. i like the solution, especially that we move the default of `req.data` to core. i would probably just use the word `Empty` instead of `Null`

**Comment by bjrmatos** [comment]
fixed:

https://github.com/jsreport/jsreport-data/commit/fd09cfd3be895e2df7d86d2e76035065bc90a881

https://github.com/jsreport/jsreport-core/commit/c6492f06a5231962270e7b240cd11b5d11d439be
