### ISSUE TITLE
Chrome-PDF table background-color

### ISSUE THREAD

**Issue by clintnetwork** [jsreport/jsreport#646]
Hi,

I make an export using C# and chrome-pdf recipe, the body contains a watermark, but the `table` shown over the page is not transparent, how to remove the `table` background-color ?

Example:
![image](https://user-images.githubusercontent.com/5221349/66356990-6b27fa80-e96d-11e9-8d22-48ecd2599ec9.png)

Thank you

**Comment by pofider** [comment]
Please share a minimal playground demo replicating the problem.
https://playground.jsreport.net

**Comment by clintnetwork** [comment]
Sure @pofider 

https://playground.jsreport.net/w/anon/rZR~gYbL

**Comment by pofider** [comment]
https://jsreport.net/learn/chrome-pdf#css-media-type-and-bootstrap

> Chrome by default uses print CSS media query when printing pdf. This impacts CSS frameworks like Bootstrap which usually produces different results for print media type. The pdf in this case applies different styles then html. You can adapt/unite this by changing media type settings from print to screen in the template's chrome settings.

So you need to change the mentioned settings.

**Comment by clintnetwork** [comment]
Oh nice, I use jsreport C# library, what is the action to do? I'm not sure

**Comment by clintnetwork** [comment]
It's fixed, you need to use:

```css
@media print {
    .table td, .table th {
        background-color: rgba(255, 255, 255, 0.7) !important; 
        border-top: 0 !important;
    }
}
```

PS: replace `rgba(255, 255, 255, 0.7)` by the color of your choice you can also use `transparent`!
