### ISSUE TITLE
Exit jsreport script with custom statusCode

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#653]
https://forum.jsreport.net/topic/1343/how-to-send-204-instead-of-empty-report

Something like this should be possible
```js
function beforeRender(req, res) {
  const error = new Error('My error message')
  error.statusCode = 202
  throw error
}
```
and...
```js
function beforeRender(req, res) {
  req.cancel({
    message: 'Not ready'
   statusCode: 202
  }
}
```

**Comment by bjrmatos** [comment]
i like the idea of cancellable renders, i guess it is also related to [this](https://github.com/jsreport/jsreport/issues/544), right? it describes a different case of cancelling but i think it is related, anyway i just came here to link that issue to this :)

**Comment by pofider** [comment]
> i like the idea of cancellable renders, i guess it is also related to this, right?

I think these things are fully separated. This was just about jsreport scripts.
Actually we already support canceling script using `req.cancel` but we don't allow to set a custom response status code. This issue is about it.

**Comment by Offbeatmammal** [comment]
this would be very helpful ... I've got a similar issue where depending on the combination of parameters sent via the API it's very easy to get an empty (or meaningless) report back, so being able to deliver a specific response code and message would be a huge help for integration

**Comment by bjrmatos** [comment]
> ```js
> function beforeRender(req, res) {
>   const error = new Error('My error message')
>   error.statusCode = 202
>   throw error
> }
> ```

hmm i think i'm a bit against this way of cancel the script, i like the fact of being explicit (user calling `.cancel`) instead. it can also help prevent potential issues by some libraries used in the script that can throw errors using the same property, in that case, we will get a hidden behaviour and the rendering request will end with unwanted status code. i think it is easy for users to be explicit about this and we prevent getting in such potential confusion.
