### ISSUE TITLE
Using jsreport as a lambda layer

### ISSUE THREAD

**Issue by pdashford** [jsreport/jsreport#654]
Hi. I have jsReport set as a lambda as per the documentation which works fine. However to reduce the upload size I put the jsReport files in a lambda layer. But when running the function I get the following errors. Has anyone else been able to separate out the modules into an aws lambda layer?

`"{"errorMessage":"EROFS: read-only file system, rename '/opt/nodejs/node_modules/jsreport-studio/static/dist/1.client.js' -> '/opt/nodejs/node_modules/jsreport-studio/static/dist/extensions.client.js'","errorType":"Error","stackTrace":["Object.fs.renameSync (fs.js:766:18)","Reporter.reporter.on (/opt/nodejs/node_modules/jsreport-studio/lib/studio.js:87:12)","emitOne (events.js:121:20)","Reporter.emit (events.js:211:7)","configureExpressApp (/opt/nodejs/node_modules/jsreport-express/lib/reporter.express.js:189:12)","Object.reporter.initializeListeners.add (/opt/nodejs/node_modules/jsreport-express/lib/reporter.express.js:301:21)","/opt/nodejs/node_modules/listener-collection/lib/listenerCollection.js:171:33","/opt/nodejs/node_modules/listener-collection/lib/listenerCollection.js:151:16","tryCatcher (/opt/nodejs/node_modules/listener-collection/node_modules/bluebird/js/release/util.js:16:23)","Promise._settlePromiseFromHandler (/opt/nodejs/node_modules/listener-collection/node_modules/bluebird/js/release/promis...`

**Comment by pofider** [comment]
Have you followed this tutorial?
https://jsreport.net/learn/aws-lambda-serverless

If you would follow it correctly the studio extension would be disabled in the lambda env
https://github.com/jsreport/jsreport-aws-lambda-starter-kit/blob/master/prod.config.json#L56
It seems you have it enabled based on your error.

**Comment by pdashford** [comment]
Yes thats the tutorial I followed. I have that in the prod config file. It works if I include the node_modules in the lambda but I want these to be as a lambda layer

**Comment by pofider** [comment]
It seems your prod.config.json isn't applied then. 
It should be if there is properly set NODE_ENV=production environment variable.
It should based on [this line](https://github.com/jsreport/jsreport-aws-lambda-starter-kit/blob/master/index.js#L6)

Please share the jsreport boot logs from lambda.
I don't see a reason why lambda layer should make a difference.

**Comment by pdashford** [comment]
That line is in the code, I'll place that on the lambda function as well and check.

**Comment by pdashford** [comment]
I get the following error message.
`Initializing jsreport@2.4.0 in production mode using configuration file: none`
The prod.config file is in the lambda folder, so I am guessing its trying to get the config file from within the lambda layer and not the function?

**Comment by pdashford** [comment]
Found that if I pass in the config on the require statement then it works.
`const jsreport = require('jsreport')({
    "httpPort": 5488,
    "allowLocalFilesAccess": true,
    "store": {
        "provider": "fs"
    },`

**Comment by pdashford** [comment]
So my final config, which works is

`const config = require('prod.config.json')
const jsreport = require('jsreport')(config)`

**Comment by pofider** [comment]
So the layer with node_modules and jsreport cannot reach the file `prod.config.json` in another layer but can reach `data` also in the different a layer? Strange. If you ever find an explanation, please share it here for others.

**Comment by pofider** [comment]
The config file can be also specified using the config param
```js
require('jsreport')({
  configFile: path.join(__dirname, 'prod.config.json')
})
```

FYI I updated the starter kit to reflect this and also use the layers.
https://github.com/jsreport/jsreport-aws-lambda-starter-kit
