### ISSUE TITLE
"iddle" should be "idle"

### ISSUE THREAD

**Issue by Offbeatmammal** [jsreport/jsreport#656]
In the chrome-pdf and chrome-image code and docs, there is reference to networkIddle... should this be networkIdle? https://github.com/search?q=org%3Ajsreport+iddle&type=Code

**Comment by bjrmatos** [comment]
yes, it should be just `idle`, but this is going to be a breaking change so we will do it on future major version release (v3). thanks

**Comment by pofider** [comment]
Its now ready in the v3
