### ISSUE TITLE
JsReport on docker in Windows 10 using volume does not store data in it

### ISSUE THREAD

**Issue by yami12376** [jsreport/jsreport#662]
I start JsReport on Windows 10 (Windows for docker) with command:

`docker run --name jsreport -d -p 5488:5488 -v C:\jsreport:/jsreport jsreport/jsreport:2.6.1`

I checked option to use example templates when i first visited JsReport page.
Unfortunately i see that directory located in C:\jsreport is empty.

I want that all templates are saved in this mounted directory.
Like said here: https://hub.docker.com/r/jsreport/jsreport/

I see that files are stored inside containre, restarting container, removing and making new one does not erase all the data.

> Persist templates
> The templates are by default persisted inside the container. You may rather want to store them in a mounted directory or in an external database.

**Comment by yami12376** [comment]
Ok, when i start:

`docker run --name jsreport -d -p 5488:5488 -v C:/jsreport:/jsreport jsreport/jsreport:2.6.1`

it is ok. The path needs to be that way. Another way the data is probably saving somewhere inside the container.

**Comment by pofider** [comment]
It is more a docker for windows thing than jsreport, however, I add the note to our docker readme so future readers won't fall into the same.

Thank you for sharing. Closing.

**Comment by alb3ric** [comment]
Hello,

I got the same issue, except I'm setting my volume correctly with /
I can see the data folder been created in my mounted volume when I first start jsreport, if i go in the container and i create a file in /jsreport it is created in my mounted folder, but if I create new template they are not created in the mounted folder.
+ if I put a jsreport.config.json file in the mounted folder, it is not taken into account (eg: changed the port) but I can open it from the container and read it (vi).

Am I missing something ?

Thanks in advance for your help

Regards

**Comment by alb3ric** [comment]
Hello,

My bad...after a reboot of my computer it is working.
