### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by suhaimim** [jsreport/jsreport#671]
An unhandled exception occurred while processing the request.
JsReportBinaryException: Error rendering report: rendering has finished with errors:A critical error occurred while trying to execute the render command (2). connect EHOSTUNREACH 172.16.1.10:8080 (1). caused by error (2):-> stackError: at onCriticalError (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:302:19) at exports.handler (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:198:14) at process._tickCallback (internal/process/next_tick.js:68:7)caused by error (1):-> meta = {"errno":"EHOSTUNREACH","code":"EHOSTUNREACH","syscall":"connect","address":"172.16.1.10","port":8080}-> stackError: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
jsreport.Local.Internal.LocalUtilityReportingService.RenderAsync(string requestString, CancellationToken ct)

**Comment by suhaimim** [comment]
After disable proxy


An unhandled exception occurred while processing the request.
JsReportBinaryException: Error rendering report: rendering has finished with errors:A critical error occurred while trying to execute the render command (2). connect ETIMEDOUT 172.16.1.10:8080 (1). caused by error (2):-> stackError: at onCriticalError (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:302:19) at exports.handler (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:198:14) at process._tickCallback (internal/process/next_tick.js:68:7)caused by error (1):-> meta = {"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"172.16.1.10","port":8080}-> stackError: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
jsreport.Local.Internal.LocalUtilityReportingService.RenderAsync(string requestString, CancellationToken ct)

**Comment by pofider** [comment]
Thank you for the submitted issue.

Let's keep the conversation at a single place here
https://github.com/jsreport/jsreport-dotnet/issues/43
