### ISSUE TITLE
jsreport docker container creates a settings file with root owner

### ISSUE THREAD

**Issue by teebszet** [jsreport/jsreport#677]
jsreport docker container creates a settings file within the mounted volume with root owner.

I can't find any documentation on this, but not sure why this is happening?

**Comment by pofider** [comment]
Thank you for the issue report. We weren't aware that node process in our docker images is running as root. We will fix this in the upcoming 2.7.0 release.

**Comment by pofider** [comment]
This is now fixed in the 2.7.0 images
