### ISSUE TITLE
Language param from data

### ISSUE THREAD

**Issue by yoerivdm** [jsreport/jsreport#679]
Hi, since we upgraded jsreports (1.10 to latest version), our beforeRender script to set the report language is broken.

See this issue for a sample (not working anymore):
[Issue 339](https://github.com/jsreport/jsreport/issues/339#issue-260214390)

**Comment by pofider** [comment]
Thank you for the regression issue.
We will need to make sure the resources extension runs after scripts execution. Now it runs before.
We will try to check it until the next release.

I lately don't think the resources extension was a good idea from me and users should do the same fully using scripts instead. You should be able to replace resources extension usage as a workaround and maybe even as a better solution for the future.,

```js
const jsreport = require('jsreport-proxy')
async function beforeRender(req, res) {
        const localizedResource = await jsreport.documentStore.collection('data').findOne({ name: req.options.language + '-data' })
        Object.assign(req.data, {
            $localizedResource: JSON.parse(localizedResource.dataJson)
        })    
}
```
You see that this way you have full control.

**Comment by yoerivdm** [comment]
Hi, thanks for the fast reply (as always) ... the workaround fixes my issue, thanks!
