### ISSUE TITLE
Font color rendering

### ISSUE THREAD

**Issue by michelre** [jsreport/jsreport#68]
Hi guys

I'm very fond of jsreport and it's very useful to me. So, congratulations, you did a very great job.

My question is pretty simple. I have a report and I'd like to set the color of my titles. So I use something like:  `<h2 style='color: #009530;'>...</h2>` in my template. Everything looks fine when I convert the report into HTML. But the color does not render correctly when I export it into PDF with phantom-pdf. Is there a solution? Do I have to use fop and write my own recipe?

**Comment by pofider** [comment]
Hi,

this should just work. Are you able to simulate this behavior in the playground? Here is working example of font color:
https://playground.jsreport.net/#playground/-JQrphV41e/2

**Comment by michelre** [comment]
Ok, I think I understood what I did wrong. In fact I was using Bootstrap to edit my style and that was not a good idea. Here is an example: https://playground.jsreport.net/#playground/ZJRPjD2EJg/1

Thank you for your help!

**Comment by pofider** [comment]
Ah, seems that phantom has a trouble with applying correct style when the color is inherited in bootstrap. You may need to add !important to apply the color.
https://playground.jsreport.net/#playground/ZJRPjD2EJg/2

**Comment by michelre** [comment]
Yes, that what I did. In fact, I wonder if Bootstrap is really useful because apparently the grid system cannot be use with phantom.

**Comment by pofider** [comment]
Yes, bootstrap is probably not very useful here.
