### ISSUE TITLE
Docx support charts embedding

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#684]
The inspiration can be found here
https://github.com/prog666/docxtemplater-chart-module

**Comment by bjrmatos** [comment]
the initial implementation with support for the basic charts was finished, for now it just supports updating the data in the chart, no styles or other options to modify the chart are implemented yet 

https://github.com/jsreport/jsreport-docx/commit/6e2aa072424df7600a1bd8d019e2c0f7c643fba7
