### ISSUE TITLE
Docker default image build fails

### ISSUE THREAD

**Issue by cxubrix** [jsreport/jsreport#687]
After cloning repository a simple docker build fails. While the chrome version is locked, all other dependencies are off in edge repos. (sample below from tag:2.6.1)
 
`Docker build -t jsreport:jsreport .` 

fails with 

```
$ docker build -t jsreport:jsreport-local .
Sending build context to Docker daemon  10.75kB
Step 1/18 : FROM node:alpine
 ---> 8880b18e5207
Step 2/18 : EXPOSE 5488
 ---> Using cache
 ---> 8db455ce92a2
Step 3/18 : RUN addgroup -S jsreport && adduser -S -G jsreport jsreport
 ---> Using cache
 ---> 92fa755d763d
Step 4/18 : RUN apk update --no-cache && apk upgrade --no-cache  &&   echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories &&   echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories &&   apk add --no-cache     chromium@edge=76.0.3809.132-r0     nss@edge     freetype@edge     harfbuzz@edge     ttf-freefont@edge     git     bash   && rm -rf /var/cache/apk/* /tmp/*
 ---> Running in 9dc49ef1f132
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
v3.9.4-294-ge657e0093e [http://dl-cdn.alpinelinux.org/alpine/v3.9/main]
v3.9.5-3-gfaabae9a55 [http://dl-cdn.alpinelinux.org/alpine/v3.9/community]
OK: 9776 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/2) Upgrading libcrypto1.1 (1.1.1b-r1 -> 1.1.1d-r2)
(2/2) Upgrading libssl1.1 (1.1.1b-r1 -> 1.1.1d-r2)
OK: 7 MiB in 16 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  chromium-72.0.3626.121-r0:
    breaks: world[chromium=76.0.3809.132-r0]
The command '/bin/sh -c apk update --no-cache && apk upgrade --no-cache  &&   echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories &&   echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories &&   apk add --no-cache     chromium@edge=76.0.3809.132-r0     nss@edge     freetype@edge     harfbuzz@edge     ttf-freefont@edge     git     bash   && rm -rf /var/cache/apk/* /tmp/*' returned a non-zero code: 1

```

**Comment by pofider** [comment]
We always update the chrome deps during the release.
We will soon release 2.7.0 and we make sure the docker uses the same chrome as the normal npm installation.

At this moment, you better inherit from the previous docker image and do what you need.

```
FROM jsreport/jsreport:2.6.1
....
```

or specify available chromium.

**Comment by cxubrix** [comment]
> We always update the chrome deps during the release.
> We will soon release 2.7.0 and we make sure the docker uses the same chrome as the normal npm installation.
> 
> At this moment, you better inherit from the previous docker image and do what you need.
> 
> ```
> FROM jsreport/jsreport:2.6.1
> ....
> ```
> 
> or specify available chromium.

The issue is that I am customizing docker file from jsreport and inheriting is not sufficient. I am running it on env. with no root user and read only file system, so the ability to create image from repo clone is quite important. Is there a possibility for you to provide a file with locked dependencies(per release)?

**Comment by pofider** [comment]
We provide releases with locked dependencies from npm. This produces consistent installs.
https://github.com/jsreport/jsreport/tree/2.6.1

Unfortunately, docker requires an extra chromium build and for some reason, google removes the old releases from the public alpine repository. That is why you get that error.

**Comment by pofider** [comment]
I believe the latest available chromium in repo is 79.0.3945.130-r0, so maybe you can just update it [here](https://github.com/jsreport/jsreport/blob/master/docker/default/Dockerfile#L10)

**Comment by cxubrix** [comment]
Thanks, that actually was the reson for creating this issue, I suspect that puppeteer version is not compatible with @edge chromium anymore. 

Once I updated docker file to 79.0.3945.130-r0 then the image is build successfully, but any API reqests fail to start chromium

```
error: Error when processing render request Failed to launch chrome!
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZNSt19_Sp_make_shared_tag5_S_eqERKSt9type_info: symbol not found


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
 Error: Failed to launch chrome!
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZNSt19_Sp_make_shared_tag5_S_eqERKSt9type_info: symbol not found


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.<anonymous> (/app/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:214:15)
    at Interface.close (readline.js:403:8)
    at Socket.onend (readline.js:180:10)
    at Socket.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

```

**Comment by pofider** [comment]
Hm. Can't tell at this moment. It is always a bit of pain to get this matching and working. We will take a look likely this week. When releasing the 2.7.0

I think I didn't get what was the problem with inheriting from the previous docker image when building yours. You aren't able to do customizations you need when inheriting? Can you please elaborate more on this?

**Comment by cxubrix** [comment]
> Hm. Can't tell at this moment. It is always a bit of pain to get this matching and working. We will take a look likely this week. When releasing the 2.7.0
> 
> I think I didn't get what was the problem with inheriting from the previous docker image when building yours. You aren't able to do customizations you need when inheriting? Can you please elaborate more on this?

It is quite a lot of customization of original to get it working on previously mentioned conditions- no root(just 1001 user) and read only file system with rare exceptions for /tmp and logs. Once I will be done with it, I hope there will be something to contribute back to this project.

**Comment by pofider** [comment]
Would you be able to share just in a comment your investigations?
We are currently looking especially on how to avoid running node process without root. 
We are getting error `2020-02-04T16:12:22.456Z - error: Error occured during reporter init Error: EACCES: permission denied, mkdir '/tmp/jsreport/autocleanup'`
Have you experience it and was able to fix it?

Just that we don't reinvent the wheel here if you were already able to solve it.
