### ISSUE TITLE
PDFUtils causes significant duplication of assets and makes PDF huge

### ISSUE THREAD

**Issue by yarongolan** [jsreport/jsreport#689]
See example at https://playground.jsreport.net/w/anon/kIcxf40x, called TestDuplication. 1.4MB with the header & footer and TOC (using PDFUtils), 350K without.

**Comment by yarongolan** [comment]
By the way, adding 4 more sections (that have nearly any content) brings it up to 2.7MB

**Comment by pofider** [comment]
This is duplicated of https://github.com/jsreport/jsreport/issues/613
See the last comment, you can get the fix from git dep at this moment,, it will be part of the next release.
