### ISSUE TITLE
Temp 'reports' file name clash with "Reports" folder

### ISSUE THREAD

**Issue by yoerivdm** [jsreport/jsreport#692]
Just had a great issue today ... in an effort to get some structure in our reports-forrest, a reports folder was created in data. Since the creation we are experiencing crashes when trying to (re)start jsreports.

When starting jsreports, it creates a ~reports file in the data folder and then it tries to rename it to reports. Since we already have a folder with the same name, we get an exception resulting in a start fail :-)

A "block" in the UI to create files/folders with such "reserved" names would be nice ... or a warning or just don't create a reports temp file with a common name...

**Comment by pofider** [comment]
What jsreport version do you use? There is such block in 2.6.1
![image](https://user-images.githubusercontent.com/2041960/74231511-0687fe00-4cc7-11ea-8061-b1334acc9bec.png)

Didn't you have reports extension disabled when creating that folder and enabled the extension afterward?

**Comment by yoerivdm** [comment]
Yes ... but it's the case sensitiveness that poses a problem.
We create a "Reports" folder on windows through the UI ... without problems. "reports" gives the correct blocking message.

**Comment by pofider** [comment]
Ups. Thank you. We will fix the validation.

**Comment by bjrmatos** [comment]
the validation was fixed, it will part of next jsreport release
