### ISSUE TITLE
How to build a jsreport server in cluster or distributed?

### ISSUE THREAD

**Issue by Jackclarify** [jsreport/jsreport#696]
How to build jsreport server in cluster or distributed, is there a ready-made solution or guidance? Any prompt will be appreciated. Thanks  @pofider @bjrmatos

**Comment by pofider** [comment]
You can run jsreport in a cluster just like any other service.
I am not sure what exactly you are asking for.
Could you elaborate more?

**Comment by Jackclarify** [comment]
Oh , thanks @pofider , I've achieve it by [running-in-cluster](https://jsreport.net/learn/fs-store#running-in-cluster) , and fixed the error 
`src\tcp_wrap.cc:146: Assertion `args[0]->IsInt32()' failed.
 1: node::DecodeWrite
 2: v8::internal::compiler::Type::Negative31
 3: v8::internal::wasm::SignatureMap::Find
 4: v8::internal::Builtins::CallableFor
 5: v8::internal::Builtins::CallableFor
 6: v8::internal::Builtins::CallableFor
 7: 000002C58A1043C1
2020-02-29 17:28:01.48 - error: workerId=5 (pid=9208) died - replacing with new workerId=7 (pid=16328) workerId=0`
with this [answer](https://github.com/nodejs/node/issues/18389#issuecomment-360925262)
Finally my configuration is like below:
`        'fs-store': {
            'dataDirectory': path.join(rootDirectory, 'reportserver/data'),
            'compactionInterval': 60000
        },
        'phantom-pdf': {
            'strategy': 'dedicated-process',
            'defaultPhantomjsVersion': '2.1.1',
            'allowLocalFilesAccess': true,
            'numberOfWorkers': 4,
            'timeout': 450000
        },`

Thank you!
