### ISSUE TITLE
Drag drop to the entity tree

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#697]
Studio nice to have 
- drop zip to the entity tree opens import dialog and process import...
- drop a file to the entity tree uploads an asset

**Comment by bjrmatos** [comment]
done in

- https://github.com/jsreport/jsreport-studio/commit/9088daa8ba6ee1eb0f5d86f2aad148a2445095b0
- https://github.com/jsreport/jsreport-assets/commit/905d89c6804ead2faee452cbc1b56d6b4bca3aee
- https://github.com/jsreport/jsreport-import-export/commit/24fc054cc2469fccdd5738cfaa85d610739f389a
