### ISSUE TITLE
Image resizing

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#698]
A common problem we have for ages:
Phantom or Chrome fails OOM because it is printing original images and ignoring the width/height.
Our recommendation is to resize images upfront, but we should be able to propose an easier solution and do the job in jsreport.

**Solution 1**

New extension jsreport-image-resize
```
<img src='{#imageResize url=xxx width=yyy height=zzz}' />
```

The afterTemplatingEngine will process these jsreport tags and does the resize.

---
**Solution 2**

Use chrome page evaluation and inspect images on the page and do the resizing.
This is an implicit solution, devs don't need to do anything, but it has some risks.

**Comment by bjrmatos** [comment]
hmm so is this about taking the image from url and resize it serve-side on the fly? won't this a have a negative performance cost to resize the image per request? i guess this scenario applies mostly in cases where the image is truly dynamic and can not be resize it up-front, right? (and store it as asset for example)

i like better the option 1, so it is clear that something it is happening with the image at runtime.

**Comment by pofider** [comment]
Imagine you are pdf printing a table of students where data contains links to the student profile pictures. These are big and you don't want to create extra service to resize them. You also do it upfront, you don't know all the pictures.

Pictures compression won't be such a killer compared to pdf print I think. And in the future, it has an easy solution with a cache.

**Comment by bjrmatos** [comment]
we decided to try a different approach to this problem. we decide to add async helpers support, with this we are able to put the resize logic in just a helper and use any npm image resize module out there to resolve the problem.

with this in mind i've prepared a test case which uses [a popular image resize javascript implementation](https://github.com/oliver-moran/jimp), to test on local make sure to use the jsreport-core version from github.

**Comment by pofider** [comment]
This is now part of the docs
https://jsreport.net/learn/templating-engines#asynchronous-helpers
