### ISSUE TITLE
jsreport with read only fs

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#699]
Assure jsreport can run on the read-only file systems and write docs how this can be achieved.

**Comment by bjrmatos** [comment]
is the goal here to better support cases like aws lambda? i don't have so much experience with those but i guess they will have some kind of tmp volume, right? i mean, that not everythig is 100% read-only but just one volume supports writes and the rest of the system is read-only. basically my doubt is that if the docs that are going to be written assume a 100% read only fs (even for tmp files) or that it is expected that there is some kind of volatile volume that allows writing for tmp files.

**Comment by pofider** [comment]
There is always some tmp volume with writes, or I assume that. We want to make it easy to start jsreport with just linked tmp fs.

One part is that jsreport-studio is writing some files to the app folder and breaking the read-only container. No extensions should write to the app folder.
The other problem is that we create a log directory in app folder, [here](https://github.com/jsreport/jsreport-aws-lambda-starter-kit/blob/master/prod.config.json#L16) I have a hack to prevent it.
Then we create some symlinks when you mount a data directory that breaks read-only container, this should be analyzed.

The idea is that you start jsreport with linked tmp fs, something copies the data there and with proper config, it will just run with read-only app volume

**Comment by pofider** [comment]
This is now described in the docs
https://jsreport.net/learn/docker#readonly-containers
