### ISSUE TITLE
Integreate pdf meta, password protect and signature to the pdf-utils

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#704]
We are too granular here.
All these extensions are about the same, using the same lib, no need to have it in extra extensions. 
We will have everything in the pdf utils.

**Comment by bjrmatos** [comment]
[pdf-sign](https://github.com/jsreport/jsreport-pdf-utils/commit/17d696d19f2d23697592616f843a566ed337e585) and [pdf-meta](https://github.com/jsreport/jsreport-pdf-utils/commit/f149489fb6fdbedf188da9779a2a90a0f6cf64c0) added to the backend

**Comment by bjrmatos** [comment]
closed here https://github.com/jsreport/jsreport-pdf-utils/commit/535ccdf4f5dc45f8c715987171b1bf8c7a44e93a
