### ISSUE TITLE
PDF/A support

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#715]
The pdf utils could be able to produce [PDF/A](https://en.wikipedia.org/wiki/PDF/A) format. It seems the chrome is producing already something almost compliant. Maybe just a minor tweak is missing.

**Comment by pofider** [comment]
Adding v3 mark as its getting more requested. It could be released even soon as a standalone.

**Comment by pofider** [comment]
Some results from the quick analysis. 

A good tool for pdf/a validation https://verapdf.org/software/
On simple pdf it throws several problems on pdf produced by the chrome. Like missing Id. Metadata, XMP. These are likely trivial to solve. Then there is a complain about colors. [Details](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-623-2). Don't get this so much.
The stock report additionally errors on XObjects [One problem](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-64-2)[Second problem](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-64-3).

Fortunately, there is a tool we can use to convert pdf -> pdf/a and then compare the difference to be able to reach the valid pdf/a. Unfortunately its closed/source https://pdf.online/pdf-to-pdfa

I tried an [external tool using Ghostscript](https://github.com/matteosecli/pdf2archive) but it doesn't work with hyperlinks and annotations in the pdf.
I tried libreoffice conversion, but it also breaks links and some layouts in stock report.
There are some java implementations based on the pdfbox, but haven't tried it yet.

It looks the best way will be to try to remove the validation errors and see how it goes. Unfortunately reaching the valid pdf/a isn't assured and the work can be time-consuming.

**Comment by salloggio** [comment]
Hi Jan, I'm interested in the solution of this issue because we have legislative constraints to which we must adapt. Do you have any predictions?

**Comment by pofider** [comment]
I'm afraid we won't have time for this for at least the next 4 months.
We are busy now with v3 and new features like this one will coma after we release and stabilize it.

**Comment by adrian-kuhn** [comment]
Hi Jan. I appreciate your work and the brilliant jsreport tool.
I'm also interested in a PDF/A support. Do you have any plans to include this feature in one of the next releases?

**Comment by pofider** [comment]
We have a beta of this feature implemented, it will be released in the next days/weeks.

**Comment by pofider** [comment]
It's now live.
https://jsreport.net/blog/release-380

**Comment by adrian-kuhn** [comment]
Hi Jan. Thank you very much. It works like a charm!
