### ISSUE TITLE
Issue with FOP

### ISSUE THREAD

**Issue by michelre** [jsreport/jsreport#72]
Hi guys,

I was trying to use FOP-PDF and I encountered an issue. 
My server is on Debian and Jsreport runs on it. The problem comes from the configuration of the extension: https://github.com/jsreport/jsreport/blob/master/extension/fop-pdf/lib/fop.js

In fact we try to execute 'fop.bat': 
```javascript
childProcess.execFile("fop.bat", childArgs, function(error, stdout, stderr) {
                            reporter.logger.info("Rastering pdf child process end.");
```

So I had to change this to execute 'fop' and it's working fine now! ;)

**Comment by pofider** [comment]
Thanks. `fop.bat` is required just for Windows. Fixed.
