### ISSUE TITLE
upgrade winston to fix node 14 warning

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#723]
the following warning is shown in node 14 when starting jsreport

```
(node:38332) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
```

we should upgrade winston to the next major to fix this

**Comment by pofider** [comment]
And use always the new custom logger instance instead of the one bound to the Winston loggers collection.
https://github.com/jsreport/jsreport-core/issues/35

**Comment by pofider** [comment]
implemented in v3 - beta
