### ISSUE TITLE
location cache duration in aws environment

### ISSUE THREAD

**Issue by apareek-sudo** [jsreport/jsreport#735]
Hi Team, as per my understand when jsreport starts it does a crawling for available extensions and stores it. 
Due to this the 1st request to lambda takes some time but subsequent requests are always fast. 

My query is if there is any duration till which the location cache is maintained? 
This is important to me to understand the time requests will take. I am good if such crawling only happen once at time of instantiation of jsreport which means only 1 request will ever take longer time.

Thanks in advance!

**Comment by pofider** [comment]
Hi, the cache has infinite duration.
It is invalidated when the modification date of node_modules folder is changed.

I believe if you initialize jsreport just once like we do [here in the AWS lambda starter kit](https://github.com/jsreport/jsreport-aws-lambda-starter-kit/blob/master/index.js) you don't have to worry about the crawling, it will be done also just once.

**Comment by apareek-sudo** [comment]
thanks @pofider
