### ISSUE TITLE
use .jsreport extension for export file

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#736]
we should use ".jsreport" extension for the file produced after export, this will make it more clear that the format of the file is designed specifically for the import/export flow, and it is not mean to be consumed or extracted as a normal zip file.

this will require other changes in the messages, logs, cli args, modify the file extensions for drag and drop

**Comment by bjrmatos** [comment]
we have decided that the file extensions we are going to use will contain the ".jsr" prefix, so the extension for this case should be now ".jsrexport"

**Comment by pofider** [comment]
Implemented in jsreport 3 beta
