### ISSUE TITLE
Docker fix permissions during init as root

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#743]
Current docker images are switching to limited user `jsreport:jsreport` before running the initialization script `run.sh`. 
This is a problem because we need to fix permissions for the linked volumes there, which fails with `operation not permitted` error.

The solution here is to run the initialization as root and then switch to the limited `jsreport:jsreport` only for the end `node` process.
Based on the study of the other dockerfiles this is typically done using [gosu](https://github.com/tianon/gosu) utility.

We should..
- put a `USER root` at the beginning of the docker file and remove `USER jsreport`
- install gosu https://github.com/tianon/gosu/blob/master/INSTALL.md
- use chown to put everything to the `jsreport:/jsreport` user
- run the app at the end using `gosu jsreport/jsreport node "app/server.js"

**Comment by pofider** [comment]
implemented in v3 - beta

**Comment by WonderPanda** [comment]
@pofider Do you have any recommendations for how to work around this issue for version 2.x without having to make the switch over to the new beta version?

**Comment by pofider** [comment]
You can try to make your own docker image based on our [new dockerfile](https://github.com/jsreport/jsreport/blob/master/packages/jsreport/docker/default/Dockerfile) and install jsreport 2.x
