### ISSUE TITLE
JSReport show HTML JSON response to a text in pdf

### ISSUE THREAD

**Issue by pzanwar03** [jsreport/jsreport#745]
I want to show only text instead of HTML. I am using node js. I've attached two images and codes. Please help to get the solutions.

Table: 

![image](https://user-images.githubusercontent.com/25006760/89334153-e8b8b600-d6b7-11ea-9c73-8aab14ad0880.png)

Function:

![image](https://user-images.githubusercontent.com/25006760/89334177-efdfc400-d6b7-11ea-8ad0-803418881bbf.png)

Table template:

`<table class="table table-bordered">
                {{#detailsRecord records ''}}
                    {{#isEmpty value}}
                    <tr>
                        <th class="thbg" colspan="2">{{index}}</th>
                    </tr>
                    {{else}}                
                    <tr>
                        <td class="first-col">{{index}}</td>
                        <td>{{value}}</td>
                    </tr>
                    {{/isEmpty}}
                {{/detailsRecord}}
            </table>`

Function:

`function detailsRecord(records, resp, opts) {
    records = Object.entries(records);
    for (const [index, value] of records) {
        if ((typeof index === 'string') && ((typeof value !== 'number') && (typeof value !== 'string'))) {
            data = []
            data['index'] = index
            resp += opts.fn(data)
            if (value) {
               resp =   Handlebars.helpers.detailsRecord(value, resp, opts);
            }
        } else {
            data = []
            data['index'] = index
            data['value'] = value
            resp += opts.fn(data)
        }
    }
    
    return resp;
}`

**Comment by pofider** [comment]
Handlebars are escaping html when using double brackets `{{foo}}`.
You want to use triple brackets to avoid escaping. `{{{foo}}}`.

**Comment by pzanwar03** [comment]
Thanks @pofider it's working.
