### ISSUE TITLE
Stack - TypeError: Cannot call method 'toString' of undefined

### ISSUE THREAD

**Issue by maheshkaranjkar** [jsreport/jsreport#75]
Hi Team,

Thanks for this wonderful stuff. I very new to Jsreport. I have installed Jsreport using manual method and able to install successfully. But when Ia m trying to preview sample report of "Book sales" its giving follwing errors.

<code>
   
2015-05-14T07:34:13.362Z - error: TypeError: Cannot read property 'error' of undefined
    at Request._callback (D:\Globe\node_modules\jsreport\node_modules\script-manager\lib\manager.js:185:17)
    at Request.self.callback (D:\Globe\node_modules\jsreport\node_modules\script-manager\node_modules\request\request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Globe\node_modules\jsreport\node_modules\script-manager\node_modules\request\request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (D:\Globe\node_modules\jsreport\node_modules\script-manager\node_modules\request\request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)
error!! TypeError: Cannot read property 'error' of undefined

</code>

and 

<code>
2015-05-14T07:16:09.138Z - warn: Error when processing render request Error during rendering report: Cannot call method 'toString' of undefined TypeError: Cannot call method 'toString' of undefined
    at Images.handleAfterTemplatingEnginesExecuted (D:\Globe\node_modules\jsreport\extension\images\lib\images.js:70:51)
    at D:\Globe\node_modules\jsreport\lib\util\listenerCollection.js:142:41
    at D:\Globe\node_modules\jsreport\lib\util\listenerCollection.js:121:24
</code>

After this errors server gets restart.

Kindly help me in resolving this error, 

Regards
Mahesh

**Comment by pofider** [comment]
Thanks for the bug report, but I can't figure it out. 

It could help if you would put something like `console.log(httpResponse);` into the `D:\Globe\node_modules\jsreport\node_modules\script-manager\lib\manager.js` line 184 and check what it prints.

Or if you have any hints you can give me?

- have you done any configuration change
- have you installed latest jsreport from npm
- any suspicion what could be irregular on your pc
- node.js version
- which windows
- does it work when you create just a plain template with "hello world"
- do you start node process as an admin

**Comment by maheshkaranjkar** [comment]
Hi pofider,

Thank for your reply.
 And your suggestion is really helped me till some extend. I believe the problem might be  because of port in 

_header: 'POST http://127.0.0.1:50868/

Can you please help me how to change port.

Regards
Mahesh

**Comment by maheshkaranjkar** [comment]
Hi pofider,

Thanks for your reply,
When I tried to put loggers 
console.log(body); 
Its giving "body" as undefined.
Answers to your questions.
yes i have done configuration changes changed port in prod.config.json (my environment is dev)
port no 8080 and https instead of https

<code>
 },
    "connectionString": { "name": "neDB" },
    "httpPort": 8080,
    "blobStorage": "fileSystem",
    "cluster": {
</code>

2 . yes I am using latest Jsreport 
3. I am working behind corporate proxy, but js report is using same proxy configuration  which git is using.
4. Node. js version v0.10.36
5. windows 7 32 bit (Installed Jsreport manually 64 bit installer was not working)
7. Its failing on hello world example.
8 I have administrator right on machine (Hope this is what expected :) )


Thanks and Regards
Mahesh

Regards
Mahesh

**Comment by pofider** [comment]
Hi thanks for the details...

I knew that `body` is null from the exception, I was wondering what is in `console.log(httpResponse);`

jsreport is starting internally web servers on free ports to load balance and safely execute users' scripts. The communication between the main jsreport process and these internal servers is somehow crashing in your case. You should notice that there are 4 node.exe processes after start where 3 of them are dedicated for this internal stuff. Is it correct?

I have heard about jsreport running on 32bit, so I have a rather suspicion on some kind of a company policy on your machine which blocking the jsreport internal servers.

**Comment by maheshkaranjkar** [comment]
Hi Thanks for your reply,

Yes you are the problem is proxy issue.

Is there any proxy settings available in jsreport configuration.


Thanks and Regards
Mahesh Karanjkar

**Comment by maheshkaranjkar** [comment]
Hi Pofider,

Thanks a lot for your help. We really appreciate your help. 

Regards
Mahesh

**Comment by pofider** [comment]
Can you share with us what was the final solution which works for you?

**Comment by maheshkaranjkar** [comment]
Hi Pofider,

Sorry for late reply, I removed Http:proxy and Https_proxy from environment variable.

I know this is not right solution, I believe there might me clean solution to handle proxy.
Regards
Mahesh

**Comment by houldsg** [comment]
Thanks. This helps. I removed http_proxy environment variable and added the proxy setting to the npm global config (.npmrc) and it works.

**Comment by maheshkaranjkar** [comment]
@houldsg Glad that it helped you.
