### ISSUE TITLE
consider adding `minimalJsreportVersion` into configuration of jsreport extensions

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#751]
basically some field that will help core to throw an exception when an extension is used in an unsupported jsreport installation, this can happen usually when user install latest version of an external extension that was adapted for a new major version of jsreport. for example this was true when we were preparing the v2 release, we were adapting and publishing extensions to support the v2 release, but in this short time users that were installing extensions with `npm install jsreport-chrome-pdf` were getting the v2 changes of jsreport-chrome in an unsupported jsreport installation (v1).

something to consider about this field is that it should work good when an extension is used just with `jsreport-core` or as part of `jsreport` so the check against the version of this field should not be specific (should not test against 2.1.1 for example) and probably just check major part (`major.minor.patch`) of version

**Comment by pofider** [comment]
We decided that every extension will have in the manifest the minimal core and studio version.
This should be enough for now.

```js
module.exports = {
    'name': 'chrome-pdf',
    'main': 'lib/chrome.js',
    'optionsSchema': {
      chrome: { ...chromeSchema },
      extensions: {
        'chrome-pdf': { ...chromeSchema }
      }
    },
    'dependencies': [ 'templates' ],
    'requires': {
        'core': '2.1.x’,
       'studio': '2.3.x'
    }
}
```

**Comment by pofider** [comment]
Ready for v3
