### ISSUE TITLE
pdf utils digital signature form field

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#754]
https://forum.jsreport.net/topic/1704/pdfformelement-digital-signature-type

**Comment by pofider** [comment]
Big thank you to @umbe77 for contribution.
This will be released in jsreport@2.10.0

**Comment by fedebona** [comment]
Hi @pofider , any plans about 2.10.0 release date?

**Comment by pofider** [comment]
Maybe the next week, it is really hard to say now. We are finishing the last tasks now.

If you want the change immediately with 2.9.0, you need to fork the pdf utils, switch to the 1.9.0 tag, and copy your changes.
The current master depends on the master of jsreport-core, so it won't work otherwise.
