### ISSUE TITLE
Blob storage memory behaviour

### ISSUE THREAD

**Issue by yperfanov** [jsreport/jsreport#755]
Hi,
Currently the application I work on doesn't need to keep the generated reports. So the blob storage is set to _memory_. How jsreport manages the memory with that option? Are blob objects cleaned from the memory at some point? Do I have to handle it explicitly with code?

**Comment by pofider** [comment]
When the report entity is deleted, the blob is deleted as well from the memory.
You can configure the reports automatic clean up and you should be fine.
https://jsreport.net/learn/reports#cleanup
