### ISSUE TITLE
jsreport in azure function

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#758]
It seems it is finally supported to run chrome in azure functions.
https://anthonychu.ca/post/azure-functions-headless-chromium-puppeteer-playwright/
We should try it with jsreport and document it.

**Comment by pofider** [comment]
There is a tutorial now.
https://jsreport.net/learn/azure-functions-serverless

**Comment by Samerkassem** [comment]
@pofider  Hi podifer, I didn't realize that its support in azure functions is that new, I am facing a problem with it, i poste it in the jsreprot forums.
