### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by mike-dnb** [jsreport/jsreport#76]
Hey,

We see the following error when trying to render a PDF:

```
Error:  { [Error: Error during rendering report: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

Here's how we use `jsreport`:
```
require("jsreport").render({
    template: {
        content: output,
        phantom: {
            width: '1200px'
        }
    }
}).then(function(out) {
    out.result.pipe(res); // "res" is our node.js response
}).catch(function(e) {
    console.log('Error: ', e);
});
```

The config file:
```
{
    "certificate": {
        "key": "certificates/jsreport.net.key",    
        "cert": "certificates/jsreport.net.cert"
    },
    "connectionString": { "name": "neDB" },
    "httpsPort": 443,
    "blobStorage": "fileSystem",
    "cluster": {
      "numberOfWorkers": 2,
      "enabled":  false
    },
    "phantom": {
        "numberOfWorkers" : 2,
        "timeout": 180000
    },
    "tasks": {
        "numberOfWorkers" : 2,
        "timeout": 10000
    }
}
```

Has anyone seen that and knows how to fix it?

Thanks,

Mike

**Comment by pofider** [comment]
Hi, 
I would start by adding a console logger:
require('jsreport').renderDefaults.logger.providerName = "console";

The config file is not used when using `require("jsreport").render" and it should not start any external web server by default so I guess the error comes from the communication with jsreport inetrnal web server which is used to compile javascript templating engines. This internal web server is a real pain right now because it is quite often blocked by a proxy or cloud environment rules... I am working on changing the approach on this for the next version, but for now please try to add the logger if there will be something....

**Comment by mike-dnb** [comment]
Thanks for your feedback Jan. I ended up starting `jsreport` as a standalone service and use the remote client in my code to connect with the service. That turns out to be a better architectural design anyway as it allows us to scale both our code and the `jsreport` service independently.

Looking forward to your next release!

**Comment by jfreak53** [comment]
I have this exact same problem. It works perfectly fine on my localhost machine. The second I upload it to my VPS and run it there I get this problem.

I have checked the VPS and the VPS does "not" have IPTables even running, let alone any ports blocked.

This is the debug output:

```
# node index.js
info Initializing embedded storage at /root/reportdev/node_modules/jsreport/data
info Searching for available extensions in /root/reportdev/node_modules/jsreport
info Found 23 extensions
info Using extension html
info Using extension templates
info Using extension data
info Using extension phantom-pdf
info Extensions loaded.
info Initializing embedded storage at /root/reportdev/node_modules/jsreport/data
info reporter initialized
info Starting rendering request 1 (user: null)
debug Inline data specified.
debug Pdf recipe start.
error Error when processing render request Error during rendering report: connect ECONNREFUSED Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
From previous event:
    at Reporter.render (/root/reportdev/node_modules/jsreport/lib/reporter.js:147:8)
    at /root/reportdev/node_modules/jsreport/index.js:84:38
```

Here is the config file:

```
{
    "certificate": {
        "key": "certificates/jsreport.net.key",
        "cert": "certificates/jsreport.net.cert"
    },
    "connectionString": { "name": "neDB" },
    "httpPort": 8088,
    "blobStorage": "fileSystem",
    "cluster": {
      "numberOfWorkers": 2,
      "enabled":  false
    },
    "phantom": {
        "numberOfWorkers" : 2,
        "strategy": "dedicated-process",
        "timeout": 180000
    },
    "tasks": {
        "numberOfWorkers" : 2,
        "strategy": "dedicated-process",
        "timeout": 10000
    }
}
```

I've tried with and without the `strategy` param. I've also tried different `httpPort`'s. I know for positive that 8088 is not blocked, as if I start up apache on that port it works fine.

I cannot setup as a standalone server and connect to it, so I really need to figure out why it's doing this please.

Node version on the server is 0.12.7 and on my localhost is 0.12.4.
