### ISSUE TITLE
Jsreport server side

### ISSUE THREAD

**Issue by mariem11** [jsreport/jsreport#762]
Hello,
i need help reguarding the use of jsreport server side.
what i mean is i want to execute the programm and download the template directly on server, without using web browser (graphic interface).
i created a jsreport project and put it on linux server. when i put 
"jsreport render --template.name=main --out=main.pdf" , 
it shows an error : "chromium revision is not downloaded .run npm install or yarn install"
it always shows this error even after runing npm install

**Comment by pofider** [comment]
Please delete the node_modules folder and hit `npm install` again.
