### ISSUE TITLE
pdf attachements

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#763]
Pdf utils could be able to add attachments to the pdf.

Requested here:
https://forum.jsreport.net/topic/1727/can-jsreport-generate-pdf-with-attachments

**Comment by pittam** [comment]
Hi , Can you please let me know if this feature is available today ?

**Comment by pofider** [comment]
Maybe you can use some external tool that does this and post-process the jsreport pdf output. Although I didn't search in this area yet.

**Comment by pofider** [comment]
Implemented in jsreport 3.5.0
