### ISSUE TITLE
Full import seems to overwrite users (2.10.0)

### ISSUE THREAD

**Issue by newtonion** [jsreport/jsreport#764]
Hello,

We've just updated from various versions (2.7.2, 2.9) to 2.10.0 and are now having a problem with deploying our reports.

Our deployment process makes use of multiple JSReport instances (dev/test). Developers will make changes to dev and then export those changes into a staging folder. These changes are then pushed through the API (api/import?fullImport=true) to our test environment.

This has been working well for a while, but after this latest update the user that we use to run reports on test is getting removed via the import (has read-only permissions) - is this now expected behavior?

This does not affect the reportadmin user (password doesn't change).

**Comment by bjrmatos** [comment]
hi! the full import always removes all the entities you have stored and inserts the entities on the zip, so basically it is a replacement, it discards everything on store replacing it with the entities on zip, this means that a user can end removed if that user is not part of the entities on the zip.

was the user you are mentioning included as part of the export zip? if it was not then it is expected that it ends removed after the full import.

if the user was included on the export zip and still you don't see the user after full import then yes it is a bug

**Comment by newtonion** [comment]
Thanks! That sounds about right - the user does not exist in the place we are creating the export zip from, it must have just been coincidence that this worked until this last update.

Thanks again for the quick response - will amend our process accordingly.
