### ISSUE TITLE
Vulnerability updates

### ISSUE THREAD

**Issue by reitzmichnicht** [jsreport/jsreport#768]
Hi we did a vulnerability scan with snyk on jsreport and it would be great if some vulnerable packages could be updated:
Lodash needs to be at least 4.17.20 https://app.snyk.io/vuln/npm:lodash 

node-forge used by jsreport-pdf-utils need to be at least 0.10.0 https://app.snyk.io/vuln/npm:node-forge
pdfjs-dist used by jsreport-pdf-utils need to be at least 2.0.943 https://app.snyk.io/vuln/npm:pdfjs-dist

ajv needs to be at least 6.12.3 https://app.snyk.io/vuln/npm:ajv

Kind regards,
Michael

**Comment by bjrmatos** [comment]
thanks, we will make sure to update the packages for the next release.

**Comment by pofider** [comment]
I updated the readme with notes explaining how we handle vulnerabilities.
https://github.com/jsreport/jsreport#vulnerabilities
