### ISSUE TITLE
Async helpers improvements

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#769]
1. Helper function's parameters should be converted to real promises when the value is "async mock string" created by another async helper call
https://playground.jsreport.net/w/anon/Z_siglvZ

2. Helpers block will run as an async function. This means user can initialize a library that requires an async call inside the helper's block and use it in the helper's functions.

```js
await mylib.init()

function a () {
  return mylib.performSomething()
}
```

**Comment by msageryd** [comment]
Looking at your sample code it seems like I can declare a global (global to all helpers) variable and await it's initialisation in one place?

At the moment I'm awaiting the initialisation in each place I intend to use the variable, like this:

```
//mylib is declared in a global helper
const mylib;

//everywhere mylib should be used I need to await it to ensure it's initialised
function makeUseOfMylib () {
  await mylib.init()
  return mylib.performSomething()
}

function onotherUseOfMylib () {
  await mylib.init()
  return mylib.performSomething()
}
```

Will your proposed improvement let me replace all of my await calls with one global await, i.e. a "top level await" in the scope of helpers? In that case, it would be awesome!

**Comment by bjrmatos** [comment]
> Will your proposed improvement let me replace all of my await calls with one global await, i.e. a "top level await" in the scope of helpers? In that case, it would be awesome!

yes, that is the plan, await once on the top level, so any lib that is used in helpers that needs some kind of initialization can be executed just at the top level.

**Comment by pofider** [comment]
The implementation is ready. We will retest deeply before the v3 release.
