### ISSUE TITLE
HTML header and footer doens't work with phantom-pdf - jsreport 0.3.0

### ISSUE THREAD

**Issue by walter-psjr** [jsreport/jsreport#77]
The option to insert HTML header and footer with #phantomHeader and #phantomFooter selector is not working. Below is a link to an example using the default parameter header and footer phantomjs and another using HTML.

PhantomJS default parameters:
https://playground.jsreport.net/#playground/vWQhW-7N6m/2

HTML option:
https://playground.jsreport.net/#playground/GWKbkOBQ6I/1

This feature is important for the use of variables and the number of pages.

**Comment by pofider** [comment]
Thanks for the bug report.

Do you need a hotfix for the standalone full jsreport or for the .net embedded one?

**Comment by walter-psjr** [comment]
Yes, I need. We have a system in production with embedded version and after the update for version 0.3.0 this feature stopped work.

**Comment by pofider** [comment]
I have just fixed this in jsreport.Embedded 0.3.0.1. Can you try it?
https://www.nuget.org/packages/jsreport.Embedded/0.3.0.1

**Comment by walter-psjr** [comment]
Perfect! It worked. Thank you for quick return.
