### ISSUE TITLE
Html-to-xlsx timeout values not reflected

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#770]
It seems that we don't pass proper timeout values to the html-to-xlsx.

It always runs with the default 10s here
https://github.com/pofider/html-to-xlsx/blob/master/lib/conversion.js#L17

This means that bigger tables timeouts on chrome-page-eval after 10s

**Comment by bjrmatos** [comment]
this is now fixed in [`jsreport-html-to-xlsx@2.8.1`](https://github.com/jsreport/jsreport-html-to-xlsx/releases/tag/2.8.1)
