### ISSUE TITLE
Different data for different template using API

### ISSUE THREAD

**Issue by lichutin-st** [jsreport/jsreport#775]
Hello!

As I can see, jsreport studio allows to pass different data objects to different PDF document and then merge rendered documents.
![image](https://user-images.githubusercontent.com/68215827/99512311-586a5c80-299a-11eb-9f83-a0afce5951a7.png)

Can we do the same thing using API or one of API clients?

Looks like we can pass only one `data` parameter to the whole rendering request.

Link to the c# api client: https://github.com/jsreport/jsreport-dotnet-types/blob/master/jsreport.Types/Request/RenderRequest.cs#L19

**Comment by pofider** [comment]
I think you need to pass the data in the main request for example in an extra property and then reach it from inside the merged template.

```js
{ template: { name: 'foo'... }, data: { someData: 'xxx', dataIWantToReachInMergedTemplate: {} }
````

then in the merged template

```js
{{dataIWantToReachInMergedTemplate.xxx}}
```

**Comment by pofider** [comment]
I am closing this, but feel free to add comments.

**Comment by lichutin-st** [comment]
The idea was to group and render multiple documents from templates which require the same data fields, so it would be nice to isolate data for different templates (you can't modify existing templates in that situation).

Anyway, I've implement a solution on my side, but it doesn't cover all cases.

**Comment by pofider** [comment]
Sorry for the delay... So far we think this can be done using a custom jsreport script which would call pdf utils methods dynamically.
https://jsreport.net/learn/pdf-utils#usage-in-script

This means you wouldn't send the template operations in `template.pdfOperations` but somewhere in your data and let the script do the work. This way you have full control on what data you send to your templates.
```js
const jsreport = require('jsreport-proxy')
async function afterRender(req, res) {    
    for (const op of req.data.myOperations) {
        const opRes = await jsreport.render({
            template: {
                name: op.template
            },
            data: op.data
        })
        res.content = await jsreport.pdfUtils.append(res.content, opRes.content)
    }
```
I prepared a very simplified demo here. 
https://playground.jsreport.net/w/anon/pd3hAmlw

Let me know if this doesn't fill fully your needs.
We will still consider if the operation data shouldn't be supported as you requested and I keep this open.

**Comment by lichutin-st** [comment]
Thanks, looks good and interesting. I've never thought about such usage of jsreport utils :)

**Comment by carlcontinusys** [comment]
Hello, how can we recalculate the page number for all merged templates? so we can page on all merged pages rather than separate page number per template
