### ISSUE TITLE
pdf content is blank

### ISSUE THREAD

**Issue by pzanwar03** [jsreport/jsreport#778]
My code is:

`await axios.post('http://localhost:3000/reporting/api/report', {

        template: { shortid: 'BkeiI9trWP' } ,
        options: { 'Content-Disposition': 'Attachment;},
        data: {"rows": genStatsJSON[0].jsonlistb }
        }, {
        'headers': {
          'Content-Type': 'application/json'
        }
      }).then(resp => {
        try {
          var writerStream = fs.createWriteStream('output.pdf');
           writerStream.write(resp.data, 'utf8');
        } catch (e) {
          console.log(e);
        }
      }).catch(err => {
        // Handle Error Here
        console.error(err);
      });
`

PDF content does not show

**Comment by pofider** [comment]
Please check our nodejs client. Let me know if it doesn't help.
https://jsreport.net/learn/nodejs-client

**Comment by pzanwar03** [comment]
Thanks @pofider, I need to get pdf using API.
