### ISSUE TITLE
Oracle database template store

### ISSUE THREAD

**Issue by jorisdebock** [jsreport/jsreport#779]
We would like to use our oracle database as template store, if I am correct there is no implementation yet.

I am assuming it is more or less the same as the jsreport-mssql-store extension? I will try and make an extension for oracle database.

**Comment by pofider** [comment]
Yes, it should be similar to jsreport-mssql-store. 
Let me know if you need any advice when you hit problems.

Maybe you will need to add specific types also here, not sure if oracle database types will match.
https://github.com/pofider/node-odata-to-sql/tree/master/lib/types

**Comment by wazowsk1** [comment]
@pofider is it possible to create a repository under jsreport for jsreport-oracle-store? 

note: only oracle database version 12+ is supported by odata to sql library

**Comment by pofider** [comment]
I prepared the repo and invited you to get access writes
https://github.com/jsreport/jsreport-oracle-store

However, if you decide to have the repository and package in your user's area and get some open source credits from it, go ahead. It is fully up to you to decide if you want the code to be in your area or you rather want to push it to us and let us to maintain it in the future.

**Comment by jorisdebock** [comment]
@pofider thanks, sorry for the late response our scheduled was pushed back a bit. 

I will soon be finishing the branch and create a pr.
https://github.com/jsreport/jsreport-oracle-store/tree/add-oracle-store

I would like to push it and have you guys maintain it in the future.

**Comment by pofider** [comment]
Thank you for the work on the oracle store.

The new store implementation was announced here https://jsreport.net/blog/oracle-store
The implementation was also adapted for the next v3.
