### ISSUE TITLE
pdf utils - adding pages groups

### ISSUE THREAD

**Issue by MarioSchrattenecker** [jsreport/jsreport#784]
Using {{{pdfCreatePagesGroup}}} to pass information to another template used with pdf utils yields an array with the correct number of groups in the pages array but it seems like the last object passed in via the function replaces previously added ones.

Using:
`{{{pdfCreatePagesGroup name=@root.name customer=@root.customer orderId=@root.id supplier=supplier finish=finish product=product}}}`

to create groups from following context:
1. `{
  finish: 'Natural Anodised',
  supplier: 'Anodising - AAA',
  product: 'OW080 Series',
  uom: 'SQM',
  wall: 'Wall 1'
}`

2. `{
  finish: 'Pearl White 1114G',
  supplier: 'Powder Coating - ADM',
  product: 'OW080 Series',
  uom: 'LM',
  wall: 'Wall 1'
}`

Debbuging reveals:
1. `Pdf utils adding group field, value: {"product":"OW080 Series","finish":"Natural Anodised","supplier":"Anodising - AAA","orderId":"O-00000052","customer":{"$type":"Eos.Models.EF.Sales.Contacts.Contact, Eos.Models","customerNumber":null,"prefix":null,"suffix":null,"firstName":null,"lastName":null,"companyName":null,"telephone":null,"mobile":null,"fax":null,"eMail":null,"billingAddress":{"$type":"Eos.Models.EF.Sales.Contacts.Address, Eos.Models","street":null,"zipCode":null,"state":null,"city":null,"country":null},"shippingAddress":{"$type":"Eos.Models.EF.Sales.Contacts.Address, Eos.Models","street":null,"zipCode":null,"state":null,"city":null,"country":null}},"name":"57626-Wall 1 -Koo Wee Rup Netball Pavilion-VIC","index":0}`

2. `Pdf utils adding group field, value: {"product":"OW080 Series","finish":"Pearl White 1114G","supplier":"Powder Coating - ADM","orderId":"O-00000052","customer":{"$type":"Eos.Models.EF.Sales.Contacts.Contact, Eos.Models","customerNumber":null,"prefix":null,"suffix":null,"firstName":null,"lastName":null,"companyName":null,"telephone":null,"mobile":null,"fax":null,"eMail":null,"billingAddress":{"$type":"Eos.Models.EF.Sales.Contacts.Address, Eos.Models","street":null,"zipCode":null,"state":null,"city":null,"country":null},"shippingAddress":{"$type":"Eos.Models.EF.Sales.Contacts.Address, Eos.Models","street":null,"zipCode":null,"state":null,"city":null,"country":null}},"name":"57626-Wall 1 -Koo Wee Rup Netball Pavilion-VIC","index":1}`

This is correct so far, the issue arrises when I debug what actually reaches the template called via pdf utils:
`[
  {
    group: {
      product: 'OW080 Series',
      finish: 'Pearl White 1114G',
      supplier: 'Powder Coating - ADM',
      orderId: 'O-00000052',
      customer: [Object],
      name: '57626-Wall 1 -Koo Wee Rup Netball Pavilion-VIC'
    },
    items: []
  },
  {
    group: {
      product: 'OW080 Series',
      finish: 'Pearl White 1114G',
      supplier: 'Powder Coating - ADM',
      orderId: 'O-00000052',
      customer: [Object],
      name: '57626-Wall 1 -Koo Wee Rup Netball Pavilion-VIC'
    },
    items: []
  }
]`

This shows that apparently the second entry is added, but for some reason I could not identify, it also seems to replace the first group.

**Comment by pofider** [comment]
This looks correct. Every page can be part of only one group. If there are two groups on the same page, the page gets the last one.
https://jsreport.net/learn/pdf-utils#grouping-pages

If I am missing something, could you please create a minimal workspace describing the problem here? Thank you.
https://playground.jsreport.net/

**Comment by MarioSchrattenecker** [comment]
https://playground.jsreport.net/w/anon/_sTY0tBR

Here I created the same structure that I basically have in my report, just simpler data.
In the playgroud it performs exactly like I would expect it to, though it does for some reason not on our server.

**Comment by MarioSchrattenecker** [comment]
You mentioning that a page can only be part of one group let me discover the basically simple solution for all of this.

I just missed out on moving the {{{pdfCreatePagesGroup}}} after the pagebreak and that was the cause.
Thank you for your time.
