### ISSUE TITLE
Docker image runs locally but when I upload image to AWS get error

### ISSUE THREAD

**Issue by weisisheng** [jsreport/jsreport#785]
Would appreciate any perspective here...

I would have assumed a Dockerfile setup is the same whether running locally or remotely.  When I try a token example on AWS Lambda console (docker image placed on their ECR service which then makes the lambda available in the console), I get the error, "{
  "errorMessage": "RequestId: foo-foo-foo-foo Error: Couldn't find valid bootstrap(s): [bash]",
  "errorType": "Runtime.InvalidEntrypoint"
}"

*** the build runs without errors and the API is responding to some other "hello-world" functions.

Trying to go the container route as I could not get lambda + api gateway to identify the sample invoice template no matter what I tried.

Thanks in advance.

**Comment by pofider** [comment]
I haven't tried the ECR or API gateway yet.

For lambda we have a dedicated tutorial [here](https://jsreport.net/learn/aws-lambda-serverless), however, that is without docker.

The AWS lambda [troubleshooting docs](https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-images.html) mentions you are missing the proper `ENTRYPOINT` or `CMD` in your dockerfile. Maybe that could be the problem?

**Comment by weisisheng** [comment]
I will check those out.  Thanks for the timely response.

**Comment by weisisheng** [comment]
Hmm, those were correct.  I'll report back if anything else surfaces.
