### ISSUE TITLE
Using #child with static-pdf results in pdf junk data

### ISSUE THREAD

**Issue by WrightLiam** [jsreport/jsreport#790]
So to give the full map;

- Parent template is running handlebars and chrome-pdf, #child template call is done through function that returns '{#child templatename @template.recipe=html}' (I've also tried it without the template.recipe modifier and it makes no apparent difference, and placing the return value directly into the template without the function results in a lexical error)
- Child template is running handlebars with static-pdf as the recipe, it references an asset named filename.pdf, it runs without issue on it's own.
- When you call templatename it renders the rest of the content without issue, but it looks like the encoding changes to base64 which results in everything getting sort of squished(I only say this because the way it acts only occurs when I tried adding an asset using base64 encoding previously), and the PDF's raw data is just dumped into several pages. (Screenshot below)

I am uncertain if I am using this incorrectly or if this is a proper issue. Basically the end goal is to add static pdfs into the report based on conditional report logic.

![image](https://user-images.githubusercontent.com/16748284/110573396-305d5f80-8129-11eb-891d-851d98a1af8d.png)

**Comment by pofider** [comment]
Child templates are just replacing text, it can't replace in pdf or docx.
https://jsreport.net/learn/child-templates

You can give it a try to pdf-utils merge operation to embed another pdf in your parent report
https://jsreport.net/learn/pdf-utils
However, I need to warn that it is primarily designed to work with pdf's produced by jsreport and it may not work on your external static pdf if it is using linearization for example.
