### ISSUE TITLE
html-embedded-in-docx margin and size issue

### ISSUE THREAD

**Issue by konerunaveena** [jsreport/jsreport#801]
how do we set the size and margin in html-embedded-in-docx recipe ? please help me as i need to format the docx with "a3" size.

**Comment by pofider** [comment]
This recipe is using third-party library, which, I am afraid, doesn't support setting explicit size.
https://github.com/evidenceprime/html-docx-js#usage-and-demo

However, it allows you to set the margin at least. 
We can add the margin if you are interested in this.
