### ISSUE TITLE
Base 64 image not displaying in 'Chrome-pdf' and 'Html-to-embedded-docx'

### ISSUE THREAD

**Issue by konerunaveena** [jsreport/jsreport#804]
Hi,
I want to display my base64 image in jsreport,but i'm unable to get the image when trying from recipe 'chrome-pdf' and 'html-to-embedded-docx'.

sample base64 format :
<img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />

**Comment by bjrmatos** [comment]
hi!

can you please share a demo of what you are trying to do? you can share it in the [playground](https://playground.jsreport.net/), save it and then share the generated link here again

**Comment by pofider** [comment]
Closing due inactivity.
