### ISSUE TITLE
Pdf is blank

### ISSUE THREAD

**Issue by konerunaveena** [jsreport/jsreport#809]
Hi,

On click of a button, I'm doing a node API call in which i'm calling the JSREPORTS API  call too.
I'm passing the response whichever i'm getting from the JSREPORTS API but when the file is downloaded I'm getting pdf as blank but in the network tab I was able to see the preview with arraybuffer.
Could anyone suggest

Below is my code on clcik of button
```js
const pdfNodeApi = async() => {

    const requestOptions = {
      method: 'GET',
      headers: { 'Content-Type': 'application/json' ,Authorization: `Bearer ${localStorage.getItem('myToken')}`},
    };
    await fetch("http://localhost:9000/downloadPDF",requestOptions)
    FileSaver.saveAs(await jsReportReponse.blob(), 'Report.pdf');   
}
```

Below is my node api call
```js
app.get("/downloadPDF", async (req, res) => {
const headers = {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Methods': 'GET, POST',
      Authorization: req.headers.authorization,
      Cookie: 'render-complete=true',
    }
    const data = JSON.stringify({
      template: {
        shortid: 'l1DbOPsN5',
        recipe: 'chrome-pdf',
        engine: 'handlebars',
        chrome: {
          width: '210mm',
          height: '297mm',
        },
        content: "<html><body><h1>Coming</h1></body></html>",
      }
    });
  const resp = await axios.post('myazureAPi', data, {
    headers: headers
  });
  res.contentType("application/pdf")
  return res.send(resp.data);
});
```

**Comment by pofider** [comment]
Try to open the downloaded file with a notepad and explore the content. What is inside? Can you share the first few lines?

**Comment by konerunaveena** [comment]
> Try to open the downloaded file with a notepad and explore the content. What is inside? Can you share the first few lines?

please check below

%PDF-1.4
%����
1 0 obj
<</Creator (Chromium)
/Producer (Skia/PDF m79)
/CreationDate (D:20210526083244+00'00')
/ModDate (D:20210526083244+00'00')>>
endobj
3 0 obj
<</ca 1
/BM /Normal>>
endobj
5 0 obj
<</Filter /FlateDecode
/Length 158>> stream
x�U��
�@E������d
���]+~�hA�`�03�h.!��!΋�@2����rU�&xC����qJ%��Iq��u�/s�c��%4��dƪˀK3��
�㧑�
2{��G�P�.�Y��S@�XFj�2�(�"����$�p��Vw[,O88���a.�
endstream
endobj
2 0 obj
<</Type /Page
/Resources <</ProcSet [/PDF /Text /ImageB /ImageC /ImageI]
/ExtGState <</G3 3 0 R>>
/Font <</F4 4 0 R>>>>
/MediaBox [0 0 594.95996 840.95996]
/Contents 5 0 R
/StructParents 0
/Parent 6 0 R>>
endobj
6 0 obj
<</Type /Pages
/Count 1
/Kids [2 0 R]>>
endobj
7 0 obj
<</Type /Catalog
/Pages 6 0 R>>
endobj
8 0 obj
<</Length1 7316
/Filter /FlateDecode
/Length 4687>> stream
x��YpSי��s��,�-��^��F�S~��`Y�l�m� ��X²���rXܤ
톄��}�d�M�4MI�&ׄ
��MhB��Nٰ�l�mB��Lg:�'�鶔���+�<��Ng;�{�s������?�{d�	� ��������	�F5�����3_=� Z�
�	O�*h$� ���Ӓw��/� 3�N��}SV�� ��]��$d@"@�)�7��=3���7 ��66�����3��&y�)� ���7�g���D��'�����a˥u���9���>0�_c�9@�o�������U�� dgP�ɉ��R��6��'�F&���o5O���G?����}%'�o���uς��.����V�&��X+<�,
��%F��	:�����ԃ�DE�b#��V�N��K?�y�o� �'��z������\KKZ%��(d�Y��ϛ
�z
�$�+���s�m�ꭱ�oJ���4������Fwc:@&�n�E��ڨ`�>�|/E��{E+�q5y��>��ݏU�/�7�A�#�<�q����a�|p�m���q�_�Ǩ���q�}�!�����{�0<�/� �l�O��B�9��(�`��}d���k?�ĥ_���.�p]��j}I���ݶc��t��c�;hЧ"� ��?���ӽ��������9���o���yk7o�Q>ᩮ��(-).*tmp���d�U�d��M)�����N�Ѻ�rcHR�!Ug��B��a�7 !U"��fU
ij�͚^��E����h�Y���B��%�|�,���� �G�~I]��v���5f51V+YH~�X��bH���f���7��T/׏$�`.)��d��
��n،�6�?1� a5�V���ڵ%�oȱZ�]�j�ܠ��^s��U��R��i�uv��y3�9WE�Hx{P�d;+�gg�WS�j�ܠ|�=�|Du�
~�ɽ�v���z�KT��fY��h8���p1�?N6Rzgge�q64�_:�S����ܪU��~�0t�j~��Gr���Ush?lcw���e[Pe���X������kj��Nן%��A9�Z����{a'1��-�/�Μ��-v��,�%g�%�}\rpY�b�i6[{���.�9"�)�G������n�S!�Ք��X�ٴT�Sܯ�JUsd\R�vJY�h@+��̚5&己f!�:���I��p?~����YȁT�R����Uo�p|��s%�d��7hӧ˓j��[�O��'����Ԍz�^�q+����{�����Xܗ�%x�K��ʥ��P�
\9��֕�?���b('B;mT
�XUo?Mp����2Tp���j=���7��#�nV��	�;]��7r0'憖���� Y��O�f�F"d_
=Uc~U3%\C�R��HÁem
C-��#
q=���TϗS}`ٛ���>�c���J���X�wL	<��e��O'a��hϥ��y)(����z��|l<=Z����r��ޛ��Ei+���L�љscr�&�_a������l���3˝�q�@�7�����:5G��|?ˍa�Ĵ���<;���<Ʒ�����{�5�6� ���$�+
Z���W���7'��-s^<�3<c������I��>���#Y��D�

e� g$�pO��$h�9g� 5�N4~xA��1��y���#Lü�͒e�rL�_�����l6���8dQF�*ʛ);��9d�Uj�<�S�e�k9^�
7���,,t}r��?��^�]G���C9�����2��|c�]ݔ�}햇�����#O
�j>1v�z���r�x��'<�`&݄�=�_��W#�>����kNu�P6gпSsR`D�a=�O
x��$rܝjMͷ�Z�������}W�٠;O=D����6p�]��]k�@&�$�h�񀀻�a8�д=%ź��6f+��,���l3�E=ӧ=bBS��V��Y�Ѻ�ʬ� j܃Tj݃X<�08�����w�Bi��r��򊰢<�2�]���.;�P���̌��]VY�n!E��Y���p�4&>s��a�@n�c[ǟ���L~m׾gJ�m睇����;�	��-X�����M����~�PSM�;�ϥ��N�V.�Wt9PM��>X�~�Y�3%���\W�KHr�u�����̐��a�ukt:� q-b2bO˩6�Z:i�4��Ԟ�a^Sz�X;�Qj/ig]��#yV���W3�m�m�����p?Q�Ek��Jg��lq��`���"�����e
YY���j�w�vu͔�څT��(i��e��l�ս0X�/-�$�"��|޼0HB�ސ��A�W�o���g�U�������d��a\/(X�c�W�**��.[S06��UVb3dfd!����ʰ��~.O�b�_��-Z0Cr�}��'K�~|��]�9%u��R��N�6-�VP�Q���j�/���Z���q[�O�f�7���I�훷�ջѨo3�f�<��ӣ^��˵��șe��
���d}KAvQ^69g��ht�z�>�����DX��--]I'�I�d�Yt��FDh�YA/���E��%�������(�*�/�B�X+�q
[�cCG�	�B&�A��A���o*5�C��l�=��~k��:?;�ZQ�ꨰb<��9�S��FC����l��������-���~g�a�F���/�* �����#X�mUeMe������;f��p¸}�Ϊ�{�.8���G^U^S�0�=�Ͳ�S�Y3Y,�S[ͣ��f�<�tٻ��:��8j�o���%�D�iÆ
K�'
�Y�,+]�+�F�d��A�_(xFy]aO+�x��u�U�D�@�(¿+�W�9_Rp\�QU��ܰ@iV�ו_*�;
>���|@��UУ��ۯQ�?�R��<� �ݧ<�0*���}���g�ݡࠂ�ZX��^�~_a�����{"�y<NўS�S�#���K�p���yhث�O�r�w	u
�R�)o)�~�c;5�]�T�����>��+?R�Gyd$�(ӊШuO�c�ɵ�k�/�aݧEl��1���#�+�DAJK�R��,-��.��xВ֠`e<-���_ĳ
>��R�CܼA��>PT����<�
QxK�V�K�T*���UL��&�0W���P����Z:�M%dKzEG~�;3�;a���M[j��׽P�K�v����cd��~�Liehjj���o�Ą�E7�1��:U���s7�CO:�v����g�I�|�,���K�mF����M|���zRl龭�cz�Գ-����۱X�[���s��12�=�b����G0ۥLO]�3ϲ�w{�G�j���wGvzfi�u6+�����Ǻ^��|�$,]�K4My&�L��"�2Rtɘ�ܤ3g��Zڝg��I�f�-φ�l��eؘg�v���-��ˆ��浱.[Ȧ�.�>��ENڞ �MWl��5
t~Av�s��^����M���܎��)�+�\�p}�˴���t�p���m�s��ĉ��[3,��v��&_[�MY�9_����A���$�'��o�f�
�'�au�,�tiiyiBrZ�C��q�!Ԟs��`�֋�M�z7np.;����:B������:0�ɛԕt!IH��4����,����s:i�4`m���I�ox%��җ�뷓�L8Yz�7�O<9^Vv�ף��e��URu��r]RҺJWa��
�>0��:�����w{����v����\x��#ee��kd0Z�p["[<��P���u��]�w��E���_�pc�T�y��F��,T�T:���`7��$�i噡�GŒ�
���;��A�a�F0��4.�i$<�u���qZ)�l�6@>��ҫK$�,�(N#�/�iFw��� ^��u��f?F�!6�iQ m0;a� �DO�]�Ə�(e�G�n����kHP
EPB�R���/Ҋ�:�0L�^��T��?�~���,�	����c�#�h����2��G.A7�G�
h^\D5��a�D�t���ƍP�{ٯ�i�7S\~�VGk�:i�Hd���T��(�x�P;w6���O��6�sd*<=>��gdj|��7�;�ud*J�TZTRUT~]C�T$�R���
����z��~brfj|�ش�a�@*+)���G"R <풚�Iu�wK�BT���L��Im�>w]osg�4����T82�'<u�41z�}�T���)\����^�/�/����N_�Ů�/�uQ�{G�'�ġ7��u�������W?��v6iuc�+�W&_^n�(�<�:}���/��O�ū�_eW�ʼWq���tJ<�&N��b�K/
�?�M'�9�^8��'����K�K����K���_��"��C���NQ�C�C��C��_�g�5�)�ɦCKbthI���'��mZ׸-}F��g�D��E�Ƴ;�rCC��ي׊�=~Mx����H\�x��c��.lp������L�twZ��R�#�&Aj�NaB8&zZ�b��踧�X���$�-M�h
�7�ljl��LMb�
���լ/M}f����>tC_�i��L�!�=&���f�������u޸�ݪ���xX���O��pX���m�9ć�=
�u�jYOP
��oU#Dx9q��,��G��N�`��vU玨�G��$n::
Ng4��P%f�'4�E{�;�bt�Q����Nv'�榖���o���
endstream
endobj
9 0 obj
<</Type /FontDescriptor
/FontName /LiberationSerif-Bold
/Flags 4
/Ascent 891.11328
/Descent -216.30859
/StemV 83.984375
/CapHeight 654.78516
/ItalicAngle 0
/FontBBox [-182.12891 -303.22266 1084.96094 1007.8125]
/FontFile2 8 0 R>>
endobj
10 0 obj
<</Type /Font
/FontDescriptor 9 0 R
/BaseFont /LiberationSerif-Bold
/Subtype /CIDFontType2
/CIDToGIDMap /Identity
/CIDSystemInfo <</Registry (Adobe)
/Ordering (Identity)
/Supplement 0>>
/W [0 [365.23438] 38 [722.16797] 74 [500 0 277.83203 0 0 0 833.00781 556.15234 500]]
/DW 0>>
endobj
11 0 obj
<</Filter /FlateDecode
/Length 255>> stream
x�]P�j�0��+���l�Q
�>�-u���v�$d�࿯�]�`��ݝ�usm�t@߭�-:�'=[��� ���ş�����29�kR� �ó���.Bw�D�h�`�U���1�8�r������tg敍4����t��{���A("��6\��h�����
ʛ�����Cru=0��٫��x�:^":?'T'�;�����6�E٩H��N|X!�j��gk}�xϘ)��
��m�+�R�2
endstream
endobj
4 0 obj
<</Type /Font
/Subtype /Type0
/BaseFont /LiberationSerif-Bold
/Encoding /Identity-H
/DescendantFonts [10 0 R]
/ToUnicode 11 0 R>>
endobj
xref
0 12
0000000000 65535 f 
0000000015 00000 n 
0000000419 00000 n 
0000000154 00000 n 
0000006379 00000 n 
0000000191 00000 n 
0000000639 00000 n 
0000000694 00000 n 
0000000741 00000 n 
0000005513 00000 n 
0000005758 00000 n 
0000006053 00000 n 
trailer
<</Size 12
/Root 7 0 R
/Info 1 0 R>>
startxref
6524
%%EOF

**Comment by pofider** [comment]
That looks correct, could you upload that file somewhere so I can inspect it?

What if you remove the `shortid` from the template specification. Maybe your template modifies the content.
```
{
      template: { 
        recipe: 'chrome-pdf',
        engine: 'handlebars',     
        content: "<html><body><h1>Coming</h1></body></html>",
      }
}
```

**Comment by konerunaveena** [comment]
[Report.pdf](https://github.com/jsreport/jsreport/files/6545236/Report.pdf)

I tried to download after removing shortid but I'm getting the blank pdf only

**Comment by pofider** [comment]
Thank you, there is a problem with encoding... The best approach is problem isolation.
I tried to write your axios response to the file, and see the pdf is still blank. So first problem to solve is this part.

[To download binary data in axios, you need to add an extra configuration](https://stackoverflow.com/a/44058739/1660996).
To fix your server code, do this.
```js
 const resp = await axios.post('myazureAPi', data, {
    headers: headers,
    responseType: 'arraybuffer'
  });
```

**Comment by konerunaveena** [comment]
Thanks a ton. It's working.
