### ISSUE TITLE
xlsx is not running in jsreport studio for windows

### ISSUE THREAD

**Issue by satish2010** [jsreport/jsreport#81]
Hello Team,

xlsx is not running in jsreport studio for windows. Can you please help in the issue.

Thanks,
Satish

**Comment by pofider** [comment]
Can you be more specific? Any error details are there? Did you try simple template from here http://jsreport.net/learn/xlsx ?

It is running for me on windows.

**Comment by imolinelli** [comment]
I'm trying to run html-to-xlsx from https://playground.jsreport.net/#/playground/Y3BG0fnPa but not works (neither on my own installation):

![capture](https://cloud.githubusercontent.com/assets/9979212/8200971/371be1f4-14cc-11e5-9b26-205862ded402.jpg)

**Comment by imolinelli** [comment]
Now it works! maybe a problem with excel online?

**Comment by pofider** [comment]
Yes, the error came from excel online service.
