### ISSUE TITLE
security issues

### ISSUE THREAD

**Issue by jauniuseitmantis** [jsreport/jsreport#810]
When running `npm audit` for `jsreport` many high level vulnerabilities are detected. Also 2 vulnerabilities of critical level.

![image](https://user-images.githubusercontent.com/73338602/122956355-36e2b080-d381-11eb-9d40-ad8667c9aabf.png)

![image](https://user-images.githubusercontent.com/73338602/122956565-685b7c00-d381-11eb-8f01-7437b8cb3065.png)

Vulnerable packages should be patched to latest versions. At least critical ones should be patched asap.

**Comment by pofider** [comment]
Thank you for the created issue.

Please see our vulnerabilities notes here
https://github.com/jsreport/jsreport#vulnerabilities

We will soon ship jsreport v3 with everything updated.
