### ISSUE TITLE
Ship ejs (and pug) with single file executale

### ISSUE THREAD

**Issue by Prinzhorn** [jsreport/jsreport#818]
I don't think this would increase the binary much but would make quick start easier for us.

We have a report solution based on AWS Lambda, Chromium and ejs. We are evaluating moving to jsreport and having ejs support in the executable would make it much smoother for our team to play with it without needing a Node.js/npm setup on every machine.

**Comment by pofider** [comment]
Thank you for the idea.

We will discuss it with the team.  However, it isn't just about the size. We can't do breaking changes to the extension when it becomes part of the default installation without doing a major release of the whole jsreport. Also, we need to keep an eye also on the vulnerability reports.

**Comment by pofider** [comment]
We decided to continue including in the binary just the extensions part of the default jsreport distribution.
However, we documented how the custom binary with custom extensions can be compiled so everyone can prepare the binary to desired needs.
