### ISSUE TITLE
Support ESM import

### ISSUE THREAD

**Issue by Smoovsky** [jsreport/jsreport#820]
I'm wondering is the support of importing ES module on the roadmap? It seems we can only use CommonJS to require packages at the moment, but more packages are turning into ESM-only nowadays.

Thanks.

**Comment by bjrmatos** [comment]
we just added some [changes](https://github.com/jsreport/jsreport/commit/6e62a185e430447114efffcef47bdc5d4c801a6c) in the be able to work normally in ESM land. that should be enough but if you are doing some tests with the v3 and find more problem with the ESM just let us know.

thanks

**Comment by Smoovsky** [comment]
> 

Hi, 
We recently tried to use ES import in jsreport 3.x, but it was giving out this error:
```'import' and 'export' may only appear at the top level```
which makes sense.

Would you enlighten me where would the proper place to use import statement?
Thanks.
