### ISSUE TITLE
Incorrect url formation when polling for status (completed)

### ISSUE THREAD

**Issue by mlatasa** [jsreport/jsreport#822]
![image](https://user-images.githubusercontent.com/6143861/134482256-78e00f8f-90ea-4786-90c8-80e250e4732d.png)

I guess you want to access req.headers.host value, it seems you are not getting the value but mistyped it like a String.

**Comment by pofider** [comment]
I didn't find this problem so far.
What version of jsreport do you use?
After what request did you get this response header?
Thank you

**Comment by bjrmatos** [comment]
the issue was there, but [i fixed it](https://github.com/jsreport/jsreport/commit/db2ef44f4fe6eebe4c8b419bf4315fe84ff00772) a week ago (not released yet), so that is probably @pofider can not reproduce it now. i think this can be closed

**Comment by pofider** [comment]
I see, great. Yes, it's fixed now in the master, we should release another beta hotfix soon, likely the next week.

Thank you for reporting the issue,
