### ISSUE TITLE
Include handlebars helpers

### ISSUE THREAD

**Issue by smehrbrodt** [jsreport/jsreport#83]
I would like to make some handlebars helpers available to all reports, like `formatDate`. Is it possible to include a library like http://formatjs.io/handlebars/ and have the helpers available in jsreport?

**Comment by pofider** [comment]
You could solve this by custom script
https://playground.jsreport.net/#playground/Y3wqTR_oem/4
The script could also download the helpers from the web and add it to the template.

or write your own custom extension which would add it.

Somehow I was not yet able to make the formatjs running....

...I am thinking about adding a flag to script saying it should run globally for all the templates. This would be more elegant solution.

**Comment by smehrbrodt** [comment]
Oh I forgot to say: I do all this from the [nodejs backend](https://github.com/digitaldeacon/memberhive/blob/master/common/models/report.js#L12): I wonder whether I can just load the js file as string and include it in the `helpers` property.

**Comment by pofider** [comment]
Ah, ok.

You can just add `helpers` property to the template
```js
require("jsreport").render({
   template: { 
     content: "foo",
     helpers: "function xxx() { return... }"
  }
});
```

**Comment by smehrbrodt** [comment]
Thanks. I fixed this by compiling the Handlebars template manually before calling jsreport.render.
