### ISSUE TITLE
add more style to studio profiler logs 🌈

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#832]
now that we have the profiler working we should add some colors to the UI

<img width="598" alt="Captura de pantalla 2021-10-28 a la(s) 4 10 00 p  m" src="https://user-images.githubusercontent.com/4262050/139336174-2c2a54f0-e154-4b45-a895-e2da303d146d.png">
 

the base idea will be to just add color to the log level `debug`, `info`, etc, (maybe also to the time part `+172`?) but new ideas are welcome.

maybe full timestamp with logs (like we have in server console logs) will be useful too, maybe show them in hover or with some toggle

**Comment by pofider** [comment]
Implemented. Will be in 3.1.0
