### ISSUE TITLE
Problem with http to https redirection [crash server]

### ISSUE THREAD

**Issue by UxorialRook** [jsreport/jsreport#835]
Hello,

**JSReport docker version**: jsreport/jsreport:2.11.0-full-patch1
**Environnement:** Jelastic in docker with a dedicated public IP
**Fail since:** 3 days
**Time between failure:** 2-3 hours

We recently installed a new instance of JSReport with both HTTP & HTTPS ports configured. Sometimes, randomly after 2 or 3 hours, the server crash with the following error:

> 2021-11-12T14:16:32.836Z - [31merror[39m: uncaughtException: Cannot read property 'split' of undefined date=Fri Nov 12 2021 14:16:32 GMT+0000 (Coordinated Universal Time), pid=862, uid=1000, gid=1000, cwd=/app, execPath=/home/jsreport/.nvm/versions/node/v12.16.1/bin/node, version=v12.16.1, argv=[/home/jsreport/.nvm/versions/node/v12.16.1/bin/node, /app/server.js], rss=107913216, heapTotal=67473408, heapUsed=64493464, external=19860485, loadavg=[0.0029296875, 0.0146484375, 0.01611328125], uptime=18156522

If we open the app/server.js, the problem seems to come from the following line:
`        res.writeHead(302, {
          'Location': 'https://' + req.headers.host.split(':')[0] + ':' + config.httpsPort + req.url
        })`

From my understanding of the error, the header host seems to be undefined for whatever reason. I don't know exactly which kind of request provoke the crash because even in the middle of the night when nobody is (normally) using the instance, a crash can append.

Temporarily, we have decided to disable the HTTPS which fixes the problem. However, we would be glad if a solution could be found with the HTTPS enabled.

Thank you in advance for your time and answer.

**Comment by pofider** [comment]
Thank you for reporting the bug.
You are right, it can easily happen some client (typically some robot) doesn't add the `host` header causing the node to crash.
I've pushed the fix to avoid the crash. It will be part of the next v3 hotfix.
You can also manually patch your code, it is a single line.
