### ISSUE TITLE
Issue in creating pdf report

### ISSUE THREAD

**Issue by navneetccna** [jsreport/jsreport#84]
when i generate a report and download pdf i found this in pdf

{"message":"request entity too large","stack":"Error: request entity too large\n    at makeError (/home/ubuntu/node_modules/jsreport/node_modules/body-parser/node_modules/raw-body/index.js:142:15)\n    at /home/ubuntu/node_modules/jsreport/node_modules/body-parser/node_modules/raw-body/index.js:38:17\n    at process._tickDomainCallback (node.js:463:13)"}

**Comment by pofider** [comment]
What is the size of a data set you are sending to jsreport?

Currently there is a limit for 20Mb.
https://github.com/pofider/node-script-manager/issues/4

**Comment by navneetccna** [comment]
well i am using very old version 0.1.17 not able to find this setting in this version where i can find this ?

**Comment by pofider** [comment]
It seems to be hard coded.  You can try to set it here
https://github.com/jsreport/jsreport/blob/0.1.17/extension/express/lib/reporter.express.js#L103

**Comment by navneetccna** [comment]
thank you i tried and let you know asap.

**Comment by pofider** [comment]
You may need to set it up also here
https://github.com/jsreport/jsreport/blob/0.1.17/lib/tasks/workersCluster.js#L75

**Comment by navneetccna** [comment]
I have to make changes in both files and restart jsreport server and it is working

Thank you very much

**Comment by carlblanchard** [comment]
Hi is this configurable in JSReport.exe ? I need to up the limit as working with big data files.

**Comment by pofider** [comment]
@carlblanchard Yes, see [configuration docs](https://jsreport.net/learn/configuration) for details. You can pass `express.inputRequestLimit` config using env variable or config file/

**Comment by carlblanchard** [comment]
I tried that. I generated a new config and then edited it, adding this property but nothing happened. Can you confirm the location of the config file you speak of.

**Comment by pofider** [comment]
`jsreport.config.json` at the same dir as jsreport.exe. Please create a dedicated issue with more description if needed.

**Comment by carlblanchard** [comment]
I have done, I have tried all and still no luck. 
https://forum.jsreport.net/topic/422/data-file-too-large
