### ISSUE TITLE
childTemplate (subreport) in docx (docxtemplater?)

### ISSUE THREAD

**Issue by fedoranvar** [jsreport/jsreport#846]
Good day to you!

Currently, I'm able to `childTemplate` text in `docx` template.

Is it possible to do more powerful `childTemplat`ion (with images, tables etc.) ?

Thank you!

**Comment by pofider** [comment]
Unfortunately, this isn't possible now with the [docx recipe](https://jsreport.net/learn/docx)
We will try to analyze this if it is something we can support in the future.
