### ISSUE TITLE
Example of grouped data and per-group header/footer with aggregate output

### ISSUE THREAD

**Issue by dlong500** [jsreport/jsreport#85]
I'm new to jsreport, and given that most other reporting tools heavily focus on the concept of grouping data (and per group header/footer sections with aggregate capabilities), I'd like to see an example if possible of how this would be approached using jsreport.

Right now none of the examples in the playground have any groups of data or any per-group aggregate output.  Would it be possible to add an example or at least give a basic explanation of how this would be accomplished using a template?  I see the invoice example uses a function to pull in the aggregate data for the entire invoice, but how would a per-group aggregate output work?

Maybe it is simpler than I'm making it out to be in my head, but a detailed example that shows a complex dataset with groups (and even sub-groups) would go a long way to showing how someone with a background in Crystal Reports or Jasper Reports could leverage the power of jsreport.

**Comment by pofider** [comment]
Thanks for the suggestion/question. Don't you have an screenshot of something particular you are looking for? Are you looking for a static pdf report or rather active html/js one?

For the static pdf report you can use just html table and templating engines together with helpers to compute the grouped values. For active html/js report is best to use some existing datagrid js component which solves most of it for you.

The playground examples should be updated with some more complex table based reports. I will try to get to it soon.

**Comment by dlong500** [comment]
I don't have a screenshot at the moment, but here's a simple example of what I'm looking for:

I'm not looking for an interactive report, just a static PDF.  I'll use an invoice as an example since you already have one in the playground.  Let's say you have categories of line items such as labor and materials.  The idea would be to have the labor and material line items grouped together in their own sections with aggregate data for each section (in addition to the overall invoice total).

So it might look like the following:

    | Labor                        | Hours | Rate          | Amount |
    |---------------------------------------------------------------|
    | Set up and configure website | 3     | $80 per hour  | $240   |
    | Graphic Design               | 2     | $100 per hour | $200   |
    |---------------------------------------------------------------|
                                               Labor Total | $440   |

    | Materials                    | Qty   | Cost          | Amount |
    |---------------------------------------------------------------|
    | Desktop computer             | 1     | $1000         | $1000  |
    | iPad                         | 2     | $500          | $1000  |
    |---------------------------------------------------------------|
                                           Materials Total | $2000  |

    |---------------------------------------------------------------|
    |                                        Invoice Total | $2440  |
    |---------------------------------------------------------------|

A lot of reporting engines have built-in support for defining groupings (and even nested groups) with per-group aggregate functions so that the data passed to the report template will be grouped according to the defined groupings (see https://github.com/Nathanaela/fluentreports for a basic reference).  It may be that the power of the templates is such that it will be easy to make groups without special support for them in the engine, but I'm not clear on how to do that without it seeming very inefficient and clunky.  For example, as you suggested I could manually create aggregate functions for each category of line items (similar to the total functions in your existing invoice example), but that doesn't account for the possibility of having many categories that might not be known ahead of time.  It would be awesome to have the template be able to take the data (that has already been ordered by category) be able to dynamically generate the different category sections and subtotals.  Any suggestions would be appreciated.

**Comment by pofider** [comment]
Ok. I get it....

The beauty of jsreport is that you are not limited to any predefined component or grouping mechanism. You can quickly implement anything you want just with javascript. This is the main idea. It's is maybe slower when you want just quickly a simple table in pdf but it pays you back every cent in a long term when you get into more complicated scenarios.

In your case it looks you only need to write function which groups an array of invoice items by specific column and summarizes totals. Look at this snipped and let me know if you get the idea.
https://playground.jsreport.net/#playground/-yvHJJzj-x/11

**Comment by dlong500** [comment]
Thanks for the example.  I see how it wouldn't be too hard to just manually write functions to do my own grouping, but one thing that still escapes me is how to deal with page boundary detection to either show subtotals per page or for smaller groups of data to force a new page if the whole group won't fit on the existing page.

For an example a scenario with subtotals per page, it would be nice if you have a group of items that spans 3 pages to be able to have a subtotal of only the items displayed on each page and then also an overall group total.

For an example of a scenario where forcing a new page would be nice, let's say you are starting a group near the bottom of the first page.  The group contains 10 lines but there is only enough space for 3 lines.  In that scenario it would be nice to have the option of starting the group on the next page without showing anything on the first page.

Maybe there are some existing features that could help, but I'm so new to jsreport that I'm not sure where to start looking.  Is there some kind of context you can access in a javascript function that holds information about the state of the PDF at that point in the render (such as the page height/width in pixels and where you currently are on the page in the render process)?

**Comment by pofider** [comment]
You can use standard html `tfoot` to make the summary row always visible at the end of the page.
https://playground.jsreport.net/#playground/-yvHJJzj-x/12

Unfortunately the conditional behavior for paging is a big pain because lack of support for it in underlying technologies phantomjs/qt. I was thinking many times to fork these libraries and add some kind of a context you mentioned, but it would be very time consuming since I am not familiar with the huge codebase. So right now it is not in the short plan.

**Comment by dlong500** [comment]
Ok.  Yeah, it would definitely be nice to have some context.  What might be really cool would be to borrow a page from frameworks like React and render the report to a virtual DOM first and then go back with a second pass to fix up any paging issues.

I did however, discover some type of bug.  If I modify your example invoice example by adding enough line items to span multiple pages then the third and subsequent pages don't leave room for the header so the line item data overwrites the header data.  See here: https://playground.jsreport.net/#playground/l1DbOPsN5/771

**Comment by pofider** [comment]
This is the same bug as here. http://stackoverflow.com/questions/28167297/flot-jsrender-phantom-bar-label-axis/28178967#28178967

Possible fix is to add an empty header in the phantom-pdf menu
https://playground.jsreport.net/#playground/l1DbOPsN5/774

**Comment by dlong500** [comment]
Ok, thanks for the workaround.  Last question (at least for a while): Is there a way to make it so that if a group of data spans a page that a "continued on next page" message is shown instead of the summary row on every page?

**Comment by pofider** [comment]
The solution would be just to hide the last summary row, but nothing I tried seems to work :(

**Comment by Siafu** [comment]
What about if you have several nested groups ? I'm trying to repeat the header for each level. Very painful.

**Comment by pofider** [comment]
Closing this conversation, but feel free to open new specific questions.
