### ISSUE TITLE
Drag & Drop feature

### ISSUE THREAD

**Issue by best-lucky1030** [jsreport/jsreport#853]
I'd like to integrate JSReport Designer.
When I read the jsreport doc, I read there is `Tip: You can also drag & drop any file to the entity tree and it gets automatically created as an asset entity.`

![image](https://user-images.githubusercontent.com/89365150/146817931-d9842acb-d303-4668-bd5b-3fb5ed08dc08.png)

But I can't find it and doc.
This feature is not implement in jsreport?

**Comment by pofider** [comment]
This is probably a misunderstanding. The [jsreport designer](https://github.com/jsreport/jsreport-designer) development was suspended and at this moment it doesn't exist. We have plans with it, but the future is unclear now.

The drag and drop mentioned in the tutorial is a simple jsreport studio feature for developers.
It allows you to drop a file to the entity tree and which gets automatically uploaded as an [asset entity](https://jsreport.net/learn/assets)
