### ISSUE TITLE
Render Listeners don't receive or pass on data property of req object

### ISSUE THREAD

**Issue by shoopapa** [jsreport/jsreport#854]
Jsreport V3 doesn't pass render listeners json data. 
I tried getting the data manually through the document store, but what I realized is that this means the data can't be modified before it hits the rendering process, pretty much breaking our basic rendering pipeline. 

This image is just an example of an after render listener not receiving data despite a data object being linked. You can see the dataJson shortid is shown in the template field. 
<img width="1007" alt="Screen Shot 2021-12-21 at 4 27 53 PM" src="https://user-images.githubusercontent.com/45986634/146999905-85788f71-e39b-4708-9d8c-3847126ee332.png">

Thanks in advance!

**Comment by pofider** [comment]
Thank you for the question.

The v3 has the following render pipeline:

- API call is received in the main process, just in a string form, no parsing to object happens so far
- worker thread is allocated
- the request body string is sent to the worker thread where its parsed
- worker returns back to the main process just the req.template, req.context, req.options to the main
- the main process triggers the beforeRenderListeners but without data
- the main process sends to the worker render request
- the worker now does the request processing:
  - beforeRenderLisnteners
  - eval templating engines
  - eval recipe
  - afterRenderListeners
 - worker returns back to the main process the response
 - main process triggers afterRenderListeners
 - main returns to the client

The v3 architecture mostly eliminates unnecessary serializing/deserializing of the input `req.data` between the main process and worker. This was a big bottleneck in the v2. 
The single worker in v3 also keeps the request data in memory for the whole lifetime which gave us chance to add features that wouldn't be possible in v2.

In case you need to work with the data in the `afterRenderListeners`, you should probably implement your own extension, and hook to `afterRenderListeners` in the worker part.

The custom extensions have their own documentation - https://jsreport.net/learn/custom-extension
But you can take immediately a look at one of the simple existing extensions to see how to hook to the worker pipeline.
https://github.com/jsreport/jsreport/tree/master/packages/jsreport-base

**Comment by pofider** [comment]
I'm closing this because I hope I clarified this topic.
However, feel free to continue the discussion here if you have the need.
