### ISSUE TITLE
How to write custom extensions?

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#86]
i love jsreport, is an awesome project!! i would like to contribute writing custom extensions (initially custom recipes), i would love to add a react.js/jsx recipe but the current docs for [writing custom extensions](http://jsreport.net/learn/custom-extension) are not so much clear to me :(, do you have any plans to write more about this soon? seems that is possible to write a extension for every part of jsreport, I'm interested in knowing more about it

**Comment by bjrmatos** [comment]
Sorry, i mean writing a react.js engine for jsreport.

**Comment by pofider** [comment]
Hi, thanks for the interest in writing extensions.

Yes it is true that almost every part of jsreport is an extension. One extension loads templates, one adds API and UI...

The mentioned article is just a first shot right now. It lacks examples of writing an engine or a recipe what is the most common use case. I will try to cover this in the article during the next week.

**Comment by bjrmatos** [comment]
@pofider good news, i'll be waiting for :)

**Comment by pofider** [comment]
Here you find two new articles explaining writing custom engines and custom recipes.

http://jsreport.net/learn/templating-engines
http://jsreport.net/learn/recipes

**Comment by bjrmatos** [comment]
cool!! thnks for your tutorials. maybe is a good idea to put the links in the README :)

**Comment by pofider** [comment]
Updated readme. Closing.
