### ISSUE TITLE
Rendering Pdf is not working.

### ISSUE THREAD

**Issue by best-lucky1030** [jsreport/jsreport#862]
I tried to render json to pdf and zpl, but i got the error like image.

![image](https://user-images.githubusercontent.com/89365150/150609725-b212704d-3ae3-4ca8-a413-8e2fdadf57c1.png)

I asked to lots of users and searched on various communities, but there were no solutions and they couldn't solve this problem.
I am not sure why this was not working on this.
Please let me know the solution.

**Comment by pofider** [comment]
What is ZPL? Please elaborate on your use case. What do you do, what do you expect?

**Comment by best-lucky1030** [comment]
ZPL means `Zebra Programming Language`.
i used json to pdf and zpl for rendering, but got above error.

**Comment by pofider** [comment]
I'm closing because of long inactivity with not enough relevant information being provided.
However, don't hesitate to post further comments.
