### ISSUE TITLE
Import deletes folder siblings

### ISSUE THREAD

**Issue by TimoBosh** [jsreport/jsreport#864]
The import of a template sibling deletes an exististing template folder:

/test/sub/templat1/... exists.
/test/sub/templat2/... should be imported by API or Web-Interface (export.zip / export.jsreport).

After importing template2, template1 is displayed in the frontend, but it's folder /data/test/sub/template1 is gone.

**Comment by pofider** [comment]
Can't replicate this on the latest v 3.3.0.

What I've tried:
- create template /test/sub/templat1
- create template /test/sub/templat2
- export template2
- delete template 2
- import previous export with default merge option
- I see both paths on the disk

**Comment by TimoBosh** [comment]
[example.zip](https://github.com/jsreport/jsreport/files/7926116/example.zip)
Would you mind trying my examples?

**Comment by pofider** [comment]
Thank you. I can't replicate it with your data. We will check what is going on and come back to you.

**Comment by pofider** [comment]
This was fixed in the jsreport 3.4.0
Thank you for reporting it.
