### ISSUE TITLE
Helpers with commented keyword await fails

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#869]
https://playground.jsreport.net/w/anon/kPrUL0sd

**Comment by Smoovsky** [comment]
Hi there, 
It doesn't have to be ```// await```, any helper.js with only comments but no practical code will fail the render, see [https://playground.jsreport.net/w/anon/BRsm2hea]() . Helper.js with tailing comments will also failer the render, see [https://playground.jsreport.net/w/anon/RWIHcrDa]() . It's likely they are the same bug.

**Comment by bjrmatos** [comment]
fixed https://github.com/jsreport/jsreport/commit/ad70680512388d64fb9a3555145b350ad74558bc
