### ISSUE TITLE
Reduce PDF quality

### ISSUE THREAD

**Issue by paulJordaan** [jsreport/jsreport#87]
Hi,
The PDF files being generated end up being very large files. Is there a way to reduce the pdf quality in order to bring down file size?

Perhaps by specifying a quality parameter as documented here http://phantomjs.org/api/webpage/method/render.html.

**Comment by pofider** [comment]
Hi,

right now it is not configurable in jsreport. I will add it in the one of the next releases.

**Comment by paulJordaan** [comment]
Could you perhaps point me to where in the code I could look to add it myself?

**Comment by pofider** [comment]
Search for the `phantom-html-to-pdf` folder and then here:
https://github.com/pofider/phantom-html-to-pdf/blob/master/lib/phantomScript.js#L101

**Comment by paulJordaan** [comment]
Great! Thanks for the help.
