### ISSUE TITLE
Can I use template name instead of short id to locate template?

### ISSUE THREAD

**Issue by Pylipala** [jsreport/jsreport#88]
To get rendered result from https://jsreport-host/api/report, we have to specify parameter shortid for existing template. However, the shortid is a random string which is not friendly enough. When integrate with other system, use meaningful name should be better.

**Comment by pofider** [comment]
Ok. Would it be fine if I add the logic searching by the template name if specified?

**Comment by pofider** [comment]
Released in 0.7.1
