### ISSUE TITLE
winston logger format not a function

### ISSUE THREAD

**Issue by jorisdebock** [jsreport/jsreport#886]
```
  "logger": {
    "file": {
      "transport": "file",
      "level": "debug",
      "format": "winston.format.json()",
```

```
TypeError: this.format is not a function
```

format is passed as a string to winston instead of function

**Comment by bjrmatos** [comment]
hi!

format is not the kind of option you can specify with json, json by its nature can just support native values like string, numbers, booleans, etc. if you want to specify the format you need to do it in code file, i think you can do it in your `server.js` file (or the file that you use to initialize your jsreport/server

```js
const winston = require('winston')
const jsreport = require('jsreport')()

jsreport.options.logger = {
   file: {
     transport: 'file',
     level: 'debug',
     format: winston.format.json()
   }
}

// rest of code...
// ....
```

**Comment by jorisdebock** [comment]
ok solved it by using the after config hook
```
  jsreport.afterConfigLoaded(reporter => {
    if (reporter.options.logger?.file) {
      reporter.options.logger.file.format = winston.format.json()
    }
  })
  ```
