### ISSUE TITLE
Disabling the studio feature still has login page enabled

### ISSUE THREAD

**Issue by rolandbodenstaff** [jsreport/jsreport#890]
I am trying to completely disable the studio feature. When I set the config value extensions_studio_enabled the login page is still enabled. Only when I login it say it's disabled. Is there a way to completely disable the web interface when using the default docker image?

**Comment by pofider** [comment]
The login page is part of the authentication extension, so you would need to disable it as well.

**Comment by rolandbodenstaff** [comment]
But wont that also disable the authentication of the api?

**Comment by pofider** [comment]
yes, it will.  I'm afraid you won't be able to remove the login page without disabling authentication.

We will add this possibility.

**Comment by rolandbodenstaff** [comment]
That would be fantastic!

**Comment by pofider** [comment]
This was just released in jsreport v3.5.0
