### ISSUE TITLE
Blob Storage ignore dataDirectory

### ISSUE THREAD

**Issue by 1Map** [jsreport/jsreport#891]
My Configuration is like:

```
        "blobStorage": {
                "provider": "fs",
                "dataDirectory": "/mycustomfolder/jsreports"
        },
        "tempDirectory": "/mycustomfolder/jsreports_tmp",
```

tempDirectory works 100%, except for the blobStorage.  This still saves everything in the default "data/storage", which is wrong.

What am I doing wrong?

**Comment by pofider** [comment]
This is on the latest jsreport v3?

**Comment by 1Map** [comment]
Yes latest version

**Comment by pofider** [comment]
Seems like that path needs to be relative to the application folder. With relative, it works.
That looks strange, I will check on that in a moment.

**Comment by 1Map** [comment]
Thanks.  Yes, our app runs on SSD Drive and our blobStorage needs to be somewhere else with more space (Our SATA drives - On the same server).  So, it would make sense to set the "dataDirectory" to another folder (with correct permissions of course).  But, that does not seem to work as it keeps saving to the default "data/storage" folder, even with configuration set correctly as well as folder permissions set correctly.
