### ISSUE TITLE
No TypeScript Type for nodejs-client

### ISSUE THREAD

**Issue by reediculous456** [jsreport/jsreport#898]
I have been using the old [jsreport-client](https://www.npmjs.com/package/jsreport-client) package that has TypeScript Types available, however there are critical security vulnerabilities in this package.
I noticed that the package has been moved to [@jsreport/node-client](https://www.npmjs.com/package/@jsreport/nodejs-client) however there are no longer types for the package which is blocking me from making the switch.
Can we get the types brought back?

**Comment by pofider** [comment]
Hi, we need to decide if we will keep types in the definitelytyped or rather move it to our monorepo. Please give us some time. 

You should be able to use it without types till then though.
https://jsreport.net/learn/nodejs-client

**Comment by reediculous456** [comment]
https://www.npmjs.com/package/@types/jsreport__nodejs-client
