### ISSUE TITLE
V3 perfomance issue comparing to V2 (and strange exception behavior as well)

### ISSUE THREAD

**Issue by lichutin-st** [jsreport/jsreport#901]
Hello. I tried JsReport V3 on large html pages (chrome-pdf recipe) and discovered that sometimes it fails with "Page crashed" error. JsReport V2 works fine on the same data.

Then I was trying to create a sample project for this and discovered quite strange performance degradation. My sample document contains about 200k lines with `<p>Some text goes there</p>`. V2 completes conversion in 2 minutes on my machine whereas V3 tries about 30 minutes and then fails with `Report render failed: Report cancelled Error: Report cancelled` error. What's more interesting, c# client doesn't receive this error and continue waiting, but there is no cpu load / jsreport logs anymore, so I'm sure there is nothing to wait for.

It sounds very similar to the problem mentioned in the ticket https://github.com/jsreport/jsreport/issues/761

V2 (jsreport/jsreport:2.11.0-full-patch1) logs
```
jsreportv3pagecrash-jsreportv2-1  | 2022-03-30T06:57:19.894Z - info: Starting rendering request 3 (user: null)
jsreportv3pagecrash-jsreportv2-1  | 2022-03-30T06:57:19.898Z - info: Rendering anonymous template { recipe: chrome-pdf, engine: none }
jsreportv3pagecrash-jsreportv2-1  | 2022-03-30T06:59:06.571Z - info: Rendering request 3 finished in 106677 ms
```

V3 (jsreport/jsreport:3.4.1-full) logs
```
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T06:59:06.844Z - info: Starting rendering request 1 (user: null) rootId=9z0z3k7xwov7vyp, id=9z0z3k7xwov7vyp
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T06:59:06.844Z - info: Rendering anonymous template { recipe: chrome-pdf, engine: none } rootId=9z0z3k7xwov7vyp, id=9z0z3k7xwov7vyp
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T06:59:06.845Z - debug: Data item not defined for this template. rootId=9z0z3k7xwov7vyp, id=9z0z3k7xwov7vyp
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T06:59:06.845Z - debug: Base url not specified, skipping its injection. rootId=9z0z3k7xwov7vyp, id=9z0z3k7xwov7vyp
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T06:59:06.845Z - debug: Rendering engine none rootId=9z0z3k7xwov7vyp, id=9z0z3k7xwov7vyp
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T06:59:07.245Z - debug: Executing recipe chrome-pdf rootId=9z0z3k7xwov7vyp, id=9z0z3k7xwov7vyp
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T06:59:07.346Z - debug: Converting with chrome HeadlessChrome/98.0.4758.0 using chrome-pool strategy rootId=9z0z3k7xwov7vyp, id=9z0z3k7xwov7vyp
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T06:59:07.446Z - debug: Page request: GET (document) file:///tmp/jsreport/autocleanup/1d6e9aed-bda5-4853-906d-e2c7e88dce49-chrome-pdf.html rootId=9z0z3k7xwov7vyp, id=9z0z3k7xwov7vyp
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T06:59:19.568Z - debug: Page request finished: GET (document) file:///tmp/jsreport/autocleanup/1d6e9aed-bda5-4853-906d-e2c7e88dce49-chrome-pdf.html rootId=9z0z3k7xwov7vyp, id=9z0z3k7xwov7vyp
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T06:59:20.369Z - debug: Running chrome with params {"$id":"3","landscape":false,"timeout":10000000,"margin":{},"printBackground":true} rootId=9z0z3k7xwov7vyp, id=9z0z3k7xwov7vyp
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T07:29:06.737Z - warn: Report render failed: Report cancelled Error: Report cancelled
jsreportv3pagecrash-jsreportv3-1  |     at Object.close (/app/node_modules/@jsreport/advanced-workers/lib/threadWorker.js:138:21)
jsreportv3pagecrash-jsreportv3-1  |     at Object.release (/app/node_modules/@jsreport/advanced-workers/lib/pool.js:38:22)
jsreportv3pagecrash-jsreportv3-1  |     at EventEmitter.<anonymous> (/app/node_modules/@jsreport/jsreport-core/lib/main/reporter.js:338:16)
jsreportv3pagecrash-jsreportv3-1  |     at Object.onceWrapper (node:events:639:28)
jsreportv3pagecrash-jsreportv3-1  |     at EventEmitter.emit (node:events:520:28)
jsreportv3pagecrash-jsreportv3-1  |     at EventEmitter.emit (node:domain:475:12)
jsreportv3pagecrash-jsreportv3-1  |     at Socket.<anonymous> (/app/node_modules/@jsreport/jsreport-express/lib/routes.js:68:20)
jsreportv3pagecrash-jsreportv3-1  |     at Object.onceWrapper (node:events:640:26)
jsreportv3pagecrash-jsreportv3-1  |     at Socket.emit (node:events:532:35)
jsreportv3pagecrash-jsreportv3-1  |     at Socket.emit (node:domain:475:12) rootId=9z0z3k7xwov7vyp, id=9z0z3k7xwov7vyp
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T07:29:06.742Z - warn: Error during processing request at http://localhost:35488/api/report, details: Report cancelled, stack: Error: Report cancelled
jsreportv3pagecrash-jsreportv3-1  |     at Object.close (/app/node_modules/@jsreport/advanced-workers/lib/threadWorker.js:138:21)
jsreportv3pagecrash-jsreportv3-1  |     at Object.release (/app/node_modules/@jsreport/advanced-workers/lib/pool.js:38:22)
jsreportv3pagecrash-jsreportv3-1  |     at EventEmitter.<anonymous> (/app/node_modules/@jsreport/jsreport-core/lib/main/reporter.js:338:16)
jsreportv3pagecrash-jsreportv3-1  |     at Object.onceWrapper (node:events:639:28)
jsreportv3pagecrash-jsreportv3-1  |     at EventEmitter.emit (node:events:520:28)
jsreportv3pagecrash-jsreportv3-1  |     at EventEmitter.emit (node:domain:475:12)
jsreportv3pagecrash-jsreportv3-1  |     at Socket.<anonymous> (/app/node_modules/@jsreport/jsreport-express/lib/routes.js:68:20)
jsreportv3pagecrash-jsreportv3-1  |     at Object.onceWrapper (node:events:640:26)
jsreportv3pagecrash-jsreportv3-1  |     at Socket.emit (node:events:532:35)
jsreportv3pagecrash-jsreportv3-1  |     at Socket.emit (node:domain:475:12)
```

**Comment by lichutin-st** [comment]
[JsReportV3PageCrash.zip](https://github.com/jsreport/jsreport/files/8378203/JsReportV3PageCrash.zip)
Here is the c# solution & docker-compose file demonstrating the issue

**Comment by lichutin-st** [comment]
I've just tried `jsreport/jsreport:3.2.0-full` image and it works way better:
```
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T09:07:57.576Z - info: Starting rendering request 1 (user: null) rootId=doyp9vb4a7ouipm, id=doyp9vb4a7ouipm
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T09:07:57.576Z - info: Rendering anonymous template { recipe: chrome-pdf, engine: none } rootId=doyp9vb4a7ouipm, id=doyp9vb4a7ouipm
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T09:07:57.577Z - debug: Data item not defined for this template. rootId=doyp9vb4a7ouipm, id=doyp9vb4a7ouipm
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T09:07:57.577Z - debug: Base url not specified, skipping its injection. rootId=doyp9vb4a7ouipm, id=doyp9vb4a7ouipm
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T09:07:57.577Z - debug: Rendering engine none rootId=doyp9vb4a7ouipm, id=doyp9vb4a7ouipm
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T09:07:57.699Z - debug: Executing recipe chrome-pdf rootId=doyp9vb4a7ouipm, id=doyp9vb4a7ouipm
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T09:07:57.899Z - debug: Converting with chrome HeadlessChrome/93.0.4577.0 using chrome-pool strategy rootId=doyp9vb4a7ouipm, id=doyp9vb4a7ouipm
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T09:07:58.000Z - debug: Page request: GET (document) file:///tmp/jsreport/autocleanup/86fcf461-d594-4e79-8f04-6382cdc0f4f2-chrome-pdf.html rootId=doyp9vb4a7ouipm, id=doyp9vb4a7ouipm
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T09:08:14.637Z - debug: Page request finished: GET (document) file:///tmp/jsreport/autocleanup/86fcf461-d594-4e79-8f04-6382cdc0f4f2-chrome-pdf.html rootId=doyp9vb4a7ouipm, id=doyp9vb4a7ouipm
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T09:08:15.538Z - debug: Running chrome with params {"$id":"3","landscape":false,"timeout":10000000,"margin":{},"printBackground":true} rootId=doyp9vb4a7ouipm, id=doyp9vb4a7ouipm
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T09:12:31.691Z - debug: Skipping storing report. rootId=doyp9vb4a7ouipm, id=doyp9vb4a7ouipm
jsreportv3pagecrash-jsreportv3-1  | 2022-03-30T09:12:31.692Z - info: Rendering request 1 finished in 274393 ms rootId=doyp9vb4a7ouipm, id=doyp9vb4a7ouipm
```

Probably chrome version affects the result.
But 3.2.0 is still much slower than v2

![image](https://user-images.githubusercontent.com/68215827/160801235-e9f96bdd-bace-4805-bb5e-e965c2310b40.png)

**Comment by pofider** [comment]
This just depends on the chrome version as I mentioned [here](https://github.com/jsreport/jsreport/issues/761). Unfortunately, we need to ship the official distribution with the "latest" chrome to assure no vulnerabilities. An older chrome is typically soon rejected by security audits and customers complains they cannot use the software because of the security policies.  I don't see a good option/solution we could do now in this matter.

The 3.4.1 is probably slower, because it uses chrome version that creates tagged, accessible pdfs. This makes big performance impact on your particular test, because it needs to create other 200k extra structures in the pdf. Unfortunately I haven't find an option in chrome to disable it so far.
https://bugs.chromium.org/p/skia/issues/detail?id=8148
https://blog.chromium.org/2020/07/using-chrome-to-generate-more.html

The 3.2.0 doesn't produce tagged pdf, so its faster likely because of that. However I have no idea why the chrome used there is faster than in 2.11.0. 

If this perf change has major impact on your reports, you need to explicitly install the older chrome version which works better for you. [Here](https://github.com/jsreport/jsreport/blob/3.0.0/packages/jsreport/docker/full/Dockerfile) you can find our older Dockerfile that installs custom chrome version.

I wasn't able to replicate the client hanging. I wasn't patient to wait 30minutes, but with 8seconds timeout I get the following error: `The request was canceled due to the configured HttpClient.Timeout of 8 seconds elapsing.`.
The error you see on server `Report render failed: Report cancelled Error: Report cancelled` is correctly saying that the client disconnected.

**Comment by lichutin-st** [comment]
Thanks for your answer.

When the tagged pdf was introduced? Was it 3.4.0 or 3.3.0?

**Comment by pofider** [comment]
It seems like in the 3.4.1.
You can see the chrome version used in the logs.
You can check if pdf is tagged if you open it in a text editor and find there text "/StructTreeRoot"
![image](https://user-images.githubusercontent.com/2041960/160840862-fa260dd4-71bd-4ecd-9c08-fadc1fc7a128.png)

**Comment by lichutin-st** [comment]
>It seems like in the 3.4.1.

3.4.0 also generates `StructTreeRoot` to the output file. 3.3.0 doesn't.

>I found here how the aria tags can be disabled

Looks interesting, thank you.

>If you don't have some new ideas on how to improve the chrome perf, I guess we can close this.

Agree with closing the issue. I'll add a comment if I find something else related to the topic.

**Comment by pofider** [comment]
Ok. I'm closing it now. Don't hesitate to add further comments when something pops up.

**Comment by lichutin-st** [comment]
@pofider I've just tried `aria-hidden="true"` on jsreport 3.6.2. Looks like adding the attribute helps a little, but 3.6.2 is slower almost twice than 3.3.0. I used a couple of concatenated duck-duck-go main pages for pdf generation (30 pdf pages in the result document). I attached updated source files.

Am I doing something wrong or it's performance penalty we can't avoid with the new versions?

[JsReportV3PageCrash_v2.zip](https://github.com/jsreport/jsreport/files/8863026/JsReportV3PageCrash_v2.zip)

**Comment by pofider** [comment]
The HTML you use for the test still contains some `aria-` attributes. I guess this slows down the chrome even when you disable it in the root element. I've tried a long pdf with `aria-hidden=true` in the root and not `aria-` tags inside and the generation time is the same as with the older chrome used in the 3.3.0

**Comment by lichutin-st** [comment]
I tried removing all `aria-` tags from the html but it didn't help. You can easily verify it by using "find & replace" `aria-` to something like `ari-`.

And yes, as you said the workaround with `aria-hidden` works on the first example with a lot of paragraphs. But we have completely different behavior on some complex html docs (like above)

**Comment by pofider** [comment]
I see, I can replicate the same.
However, I have no idea why the chrome performance fluctuates between versions.
We are forced to update because of the security holes so it's something we can't influence.
I will keep an eye on it and hopefully, some more insight gets revealed.
