### ISSUE TITLE
specify absolute path for blobStorage.dataDirectory

### ISSUE THREAD

**Issue by zhwatts** [jsreport/jsreport#907]
Hello, 
Is it possible to configure JS Report to save blob renders to an absolute, non-relative path? 

Currently, I have to specify dataDirectory (from jsreport.config) such that it's relative to the application directory. I'm wanting to save files to a network drive that has its own drive letter. 

I'm running on Windows 2016

What i'd like to do is something like 

```
  "blobStorage": {
    "provider": "fs",
    "dataDirectory": "F:/rendered_reports"
  },
```
or 
```
  "blobStorage": {
    "provider": "fs",
    "dataDirectory": "\\\\UNC_PATH\\rendered_reports"
  },
```

As it stands, I cannot target a disk that is different from the one JSReport is running due to the relativity requirement

**Comment by pofider** [comment]
This works with the latest 3.4.1 version. What version do you use?

**Comment by zhwatts** [comment]
Thanks Jan, i'm on the most current version 3.4.1. When attempting to save blob using UNC path, it still renders to the `storage/reports` directory. 

I've verified the path is accessible to the account running the JSREPORT instance. 

Here is the relevant config object

```
  "blobStorage": {
    "provider": "fs",
    "dataDirectory": "\\\\BLS-SERVER-1950\\jsreport_files\\"
  },
```

And here is a sample request i'm sending
```
   {
      "template": { "shortid": "9FNnBJI1x"  },
      "options":{
            "reports":{
                "save": true,
                "blobName": "_report"
            }
        },
      "data" : {
        "bodyText": "Text",
        "certificationText": "text"
      }
   }
```

**Comment by pofider** [comment]
Thank you.

I see now this was already fixed:
https://github.com/jsreport/jsreport/issues/891
https://github.com/jsreport/jsreport/commit/9f29b2dca5012ed0d3accc5586f72f7fe91cc6fc

We have it in the master but didn't release it yet.
It will be part of the next release. 
Likely in two weeks or something like that.

**Comment by zhwatts** [comment]
Thanks Jan that's good enough for me. I'll keep an eye out for next release!

**Comment by zhwatts** [comment]
Hello, confirmed that this works as expected in version 3.5.0. Thanks!

**Comment by pofider** [comment]
Thank you for confirming.
