### ISSUE TITLE
How can I prevent this problem for permanently

### ISSUE THREAD

**Issue by Arsira-star** [jsreport/jsreport#910]
![1651134425286](https://user-images.githubusercontent.com/65890598/165710922-e51e0e57-aee4-40f8-b79d-9ba898cd1c65.jpg)

I sent margin bottom more and more but this happen all the time how could I fix it.
My content is including Fix content and dynamic data that receive from api

**Comment by pofider** [comment]
I'm not sure I understand the problem. Please share a minimal playground demo replicating the issue so we can take a look. Thank you
https://playground.jsreport.net/

**Comment by pofider** [comment]
I'm closing this because there was no further response.
However feel free to continue comments, we still monitor it.
