### ISSUE TITLE
Missing helper: \"asset\"\n\n(sandbox.js line 11:18)"

### ISSUE THREAD

**Issue by arthurodriguesbatista** [jsreport/jsreport#912]
Here is the following code:

    var jsreport = require('@jsreport/jsreport-core')({
      store: { provider: 'postgres' },
    });
    jsreport.use(
      require('@jsreport/jsreport-postgres-store')({
        host: 'localhost',
        port: 5438,
        database: 'gerente_db',
        user: 'root',
        password: 'root',
      })
    );
    jsreport.use(require('@jsreport/jsreport-assets'));
    jsreport.use(require('@jsreport/jsreport-handlebars')());
    jsreport.use(require('@jsreport/jsreport-express')({ httpPort: 3000 }));
    jsreport.init().then(() => console.log(jsreport));

When I try to render a pdf, I get the following error: Missing helper: \"asset\"\n\n(sandbox.js line 11:18)". But at the same time, I am using @jsreport/jsreport-assets. What other helpers should I add?

**Comment by pofider** [comment]
give it some logging with setting env `DEBUG=jsreport`.
You will notice the assets extension isn't actually applied.

then it's quick to find
```
jsreport.use(require('@jsreport/jsreport-assets'));
```

should be

```
jsreport.use(require('@jsreport/jsreport-assets')());
```

don't know why there isn't some error thrown, we will check it.
