### ISSUE TITLE
async: true breaks in v3.5

### ISSUE THREAD

**Issue by zhwatts** [jsreport/jsreport#915]
Hello, 
in previous version, I could specify option.reports.async: true, and the response from JSReport would be "Async rendering in progress. Use location response header..."

However, after upgrading to v3.5, I see from JSReport logs that it is processing as async, 
> 2022-05-12T20:22:05.387Z - info: Async report is starting to render Grfxh8OyKx3BpuwD

but the response is the full binary of the rendered report. 

I reverted back to previous version and was able to replicate the expected async behaviour. Upon re-upgrading to 3.5, I was given full report data instead of async message. Is this a regression, or is it a new feature?

**Comment by pofider** [comment]
Thank you for reporting this.
Yes it is regression bug, we will try to hotfix it shortly.

**Comment by bjrmatos** [comment]
this is fixed now, you can get the fix on your project by installing manually the jsreport-reports@3.0.4, executing `npm install @jsreport/jsreport@3.0.4`

we will also publish a hotfix release for the jsreport `3.5.1` soon, which will include this fix, when the jsreport `3.5.1` is available you will be able to remove the `@jsreport/jsreport-reports` from your package.json.
