### ISSUE TITLE
SVG resolution in PDF

### ISSUE THREAD

**Issue by piprog** [jsreport/jsreport#92]
Hi Jan,

I have an HTML file that contains some SVG. I use the "phantom-pdf" recipe to convert it to PDF which mostly works perfectly, except that the generated rasterized images have very low resolution (they don't look well even on screen). Is there a way to increase the resolution?

Thanks,
Peter

P.S. I will probably send you a pull request soon: added some functionality to the html-to-xlsx recipe (number formatting, multiple named sheets, etc.) - not 100% polished but very functional and degrades gracefully.

**Comment by pofider** [comment]
Hi,

we could try to play with phantomjs zoomFactor, but I have tried svg in playground and it doesn't look bad in output pdf...
https://playground.jsreport.net/#playground/vBdeOJf3s6/2

**Comment by piprog** [comment]
Thanks Jan for the quick reply. Your example led me to a d!Hack solution:) Thanks!

The problem is that I create my graph with d3/c3 and for some reason the generated clippaths cause the pixellation. I manually deleted the <defs> sections containing the clippaths (got rid of the pixellation) and replaced all "visibility: hidden" with "display:none" (got rid of an extra horizontal line appearing for subgraph x axes that were clipped by the clippaths before) and it is perfect now.

If you'll have some time, this might be interesting to investigate as the problem is general for all c3/d3 graphs, not only for my stuff.

**Comment by pofider** [comment]
Thanks for sharing the hack!

Yes, I was going to check d3 anywa...
