### ISSUE TITLE
Problem with table header

### ISSUE THREAD

**Issue by navneetccna** [jsreport/jsreport#93]
When we generate pdf there is an issue of table header overlapping how to manage it ?

![report 2015-07-15 11-26-34](https://cloud.githubusercontent.com/assets/210475/8691751/798af952-2ae4-11e5-8c1c-44ecbcdaadd8.png)

**Comment by navneetccna** [comment]
please comment on this

**Comment by pofider** [comment]
It is always better to replicate such a problem in jsreport  [playground](https://playground.jsreport.net/), then we can better help you. However this rather looks like a problem with phantomjs rendering so you may rather try their forums.

**Comment by navneetccna** [comment]
ok thanks

**Comment by AlekhyaKotha** [comment]
I am also facing the same issue with generating PDF, the table header is repeating on new page. Here is my sample snipppet - https://playground.jsreport.net/#playground/b1m7jECAEl/1 The table header repeats on the second page.

  My js code,

    jsreport.render(myhtml).then(function(out) {
      out.stream.pipe(res); 
    }).catch(function(e) {    
      res.end(e.message);
    });

Let me know if you got fix on this issue.

**Comment by anshad** [comment]
Same issue for me.

**Comment by pofider** [comment]
@AlekhyaKotha This is the desired function of `thead` I think. You can avoid repeating table header on the next page with:

```css
thead {display: table-row-group;}
```

**Comment by AlekhyaKotha** [comment]
No, this makes the columns to rows. It's not fixing the overlap issue.

**Comment by AlekhyaKotha** [comment]
No, it makes columns to rows but this doesnt fix the overlap issue

Thanks
Alekhya

**Comment by pofider** [comment]
@AlekhyaKotha
The proposed fix avoids printing of the header on the additional pages. 

I am checking the pdf you provided in the playground but I don't see any overlaps on the second page and it seems to be looking good. Could you make a screenshot and point out what is wrong there?

**Comment by anshad** [comment]
![git](https://cloud.githubusercontent.com/assets/4816245/9415898/f938a968-485f-11e5-997a-27971a6b21f6.png)

@pofider Here I can see the problem like this.

**Comment by pofider** [comment]
with the fix I proposed it is like this... did you try it?

![fix](https://cloud.githubusercontent.com/assets/2041960/9416002/5b73f942-4843-11e5-9bee-28afc53b9e3d.png)

**Comment by AlekhyaKotha** [comment]
yeah,I did tried. It worked for this scenario but as the data here is passed dynamically, its pointing the same issue in other fields as shown below.

<img width="1028" alt="screen shot 2015-08-21 at 4 19 20 pm" src="https://cloud.githubusercontent.com/assets/13906195/9419357/9ce11dec-4820-11e5-8523-1848997ddbd5.png">

**Comment by AlmouattazT** [comment]
That's old, but can you try adding &nbps; in your PhantomJS header.
Leaving the report header empty might be the source of your problem

**Comment by bijayraj** [comment]
Adding a margin to the table - `table {margin: 1px;}` fixed this error for me.

**Comment by pofider** [comment]
The bad news is that nobody is able to fix this headers related issues directly in the phantomjs and you need to stick with css workarounds mentioned here on in the [phantomjs repository](https://github.com/ariya/phantomjs/search?q=header+overlapping&type=Issues&utf8=%E2%9C%93).

The good news is that we published new jsreport extension which can merge multiple pdfs into one. This can be used to embed completely dynamic and custom headers into pdf without using native phantomjs headers feature. Or even better, it can be used with [chrome](https://jsreport.net/learn/chrome-pdf).
See the announcement [here](https://jsreport.net/blog/merge-and-concatenate-pdfs).

Thank you for posting workarounds through the time here. I'm closing this now and believe the new announced extension solves this issues.
