### ISSUE TITLE
Handlebar's Docx: string argument in custom helper

### ISSUE THREAD

**Issue by fedoranvar** [jsreport/jsreport#930]
Good day to you!

i've defined custom handlebare helper:

```js
function eq(a,b){
  return a===b
}
function print(a) {
return a
} 
```
with template 
```docx
{{#if (eq name “Bob”)}}true{{else}}false{{/if}}
{{print "Bob"}}
```

but i'm geting in result:
```
false
undefined
```

so string argument treated as `undefined`, but i've tested integer argument and it works ok

How i can pass string argument to custom helper?

thank you!

**Comment by pofider** [comment]
I can't replicate it, please update the following playground workspace and demonstrate the problem
https://playground.jsreport.net/w/anon/ehD31c5u

**Comment by fedoranvar** [comment]
@pofider 

i've figured it out the problem: wrong quotes

for some reason by default OnlyOffice was printing another kind of quotes in editor, so:
```
{{print "Bob"}} // will print bob
{{print “Bob”}} // will print undefined
```
Problem solved.
Thank you!
