### ISSUE TITLE
Build failed when use with electron-react-boilerplate

### ISSUE THREAD

**Issue by MohamedWagih** [jsreport/jsreport#931]
I'm trying to use jsreport in electron app with [electron-react-boilerplate](https://electron-react-boilerplate.js.org/docs/installation).
Everything is working fine in development but it fails to build with this error

` ERROR in ./node_modules/@jsreport/jsreport-core/index.js 28:19-89 Module not found: Error: Can't resolve './test/extensions/validExtensions/listeners/jsreport.config' in 'my_project_path\node_modules\@jsreport\jsreport-core'
 @ ./node_modules/jsreport/index.js 21:13-47
 @ dll renderer renderer[9]`

**Comment by pofider** [comment]
I'm not familiar with that tool, but I guess it is crawling the code and calling all `require` it finds. The particular `require` it fails on is intended to be used just in internal tests so that is why it's failing. You can comment out that or ignore it somehow in the boilerplate configs...
```
// listeners: () => require('./test/extensions/validExtensions/listeners/jsreport.config')
```

**Comment by pofider** [comment]
I've pushed some small changes so this won't fail with the next jsreport update.

**Comment by MohamedWagih** [comment]
Thank you for the explanation @pofider  I'll ignore it and see how it goes.
