### ISSUE TITLE
Report not generating

### ISSUE THREAD

**Issue by navneetccna** [jsreport/jsreport#94]
Some time my jsreport stop working for a particular template when i delete some html from that template and add same html again it start working

also how to debug and test reports and also is there any way to check failure reports and log statistics only show count not the template or report which is failed and reason to failure.

**Comment by pofider** [comment]
Improved statistics with detailed errors and failures should come in the next releases.... Right now you can see these information in the logs (/your-app/logs/)

Debugging helper functions or templating engines is not supported, you need to print the debugging info directly to the report during development.

Could you try to find out which html is causing your template to stop working? Is there something in interesting in the logs for this?

**Comment by navneetccna** [comment]
jsreport read commented code ?

**Comment by pofider** [comment]
Please be more specific.

**Comment by pofider** [comment]
Closing as there is not activity here.
