### ISSUE TITLE
xlsx: 3.2.1 - Error in system-helpers.js 1812

### ISSUE THREAD

**Issue by euangordon** [jsreport/jsreport#943]
Hi,

I am trying to move an xlsx template which is working in JS Reports Online onto our Azure Docker Server Image. Everything else we have moved has worked fine, but we have one xlsx template which is not working.

The error I am getting is shown here:

```
Report "dsnmexcelbackupreport" render failed.

Non-whitespace before first tag.
Line: 0
Column: 5
Char: {

(system-helpers.js line 1812:12)

  1810 |     let result = {}
  1811 |     let err = null
> 1812 |     xml2js.parseString(xml, function (aerr, res) {
       |            ^
  1813 |       result = res
  1814 |       err = aerr
  1815 |     })

(system-helpers.js line 1495:44)

  1493 |       } else {
  1494 |         const content = await jsreport.templatingEngines.waitForAsyncHelper(tagCtx.render(ctx.data))
> 1495 |         ctx.root.$xlsxTemplate[filePath] = xml2json(content)
       |                                            ^
  1496 |       }
  1497 |     })
  1498 |

(system-helpers.js line 1377:7)

  1375 |     // process all the work pending
  1376 |     for (const $work of $workQueue) {
> 1377 |       await $work.execute($work.ctx, $work.tagCtx, ...$work.params)
       |       ^
  1378 |     }
  1379 |
  1380 |     ensureWorksheetOrder(ctx.root.$xlsxTemplate)


Error: Non-whitespace before first tag.
Line: 0
Column: 5
Char: {
    at error (/app/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/app/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/app/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/app/node_modules/sax/lib/sax.js:1010:11)
    at Parser.exports.Parser.Parser.parseString (/app/node_modules/xml2js-preserve-spaces/lib/parser.js:323:31)
    at Parser.parseString (/app/node_modules/xml2js-preserve-spaces/lib/parser.js:5:59)
    at Object.exports.parseString (/app/node_modules/xml2js-preserve-spaces/lib/parser.js:355:19)
    at BaseHandler.apply (/app/node_modules/vm2/lib/bridge.js:479:11)
    at xml2json (system-helpers.js:1812:12)
    at Object.execute (system-helpers.js:1495:44)
    at async Proxy.print (system-helpers.js:1377:7)
```

I am not sure what else would be helpful, but here is a screenshot from JS Reports in case it shows I have done something silly:
![image](https://user-images.githubusercontent.com/32622054/181469996-936e2d4d-a3e9-4ba7-9ade-89fffb6f975f.png)

Also here is my template file:
[dsnmexceltemplate.xlsx](https://github.com/jsreport/jsreport/files/9207678/dsnmexceltemplate.xlsx)

**Comment by pofider** [comment]
I apologize for the problems.
We have this already fixed and we will release the fix together with jsreport 3.7.0 likely the next week.

**Comment by euangordon** [comment]
Okay great. We can wait until next week.

**Comment by euangordon** [comment]
@pofider Could not remember which version you said the fix would be in, so retested after updating to 3.6.2, still there but you said above 3.7.0 so no surprise. 

Is 3.7.0 still coming this week? I will try it as soon as it is ready. Know how to upgrade now!

**Comment by pofider** [comment]
Just subscribe to github releases to get notified.

**Comment by pofider** [comment]
The `3.7.1` should include the fixes. Please try it out and let us know if there are some problems.

**Comment by euangordon** [comment]
@pofider - Confirmed Working in v3.7.1
