### ISSUE TITLE
JS Reports v3.6 & chrome-pdf: 3.1.2 (jsrender)- Setting background color of table tds doesn't work

### ISSUE THREAD

**Issue by euangordon** [jsreport/jsreport#945]
Hi,

We have recently moved our reports over from js reports online to our own js reports Azure docker instance. 

In JS Reports Online, this is what the report looks like:

![image](https://user-images.githubusercontent.com/32622054/182138845-cfeb7fd4-5f0f-4f81-95ea-7c89b48c6c48.png)

However, in JS Reports v3.6 & chrome-pdf: 3.1.2, the background colors on the tds aren't being set:

![image](https://user-images.githubusercontent.com/32622054/182138899-65aa9699-a196-42db-8222-fa82dfa4d475.png)

Both are using the same code, same template, same data.

Code:
```    
<table>
        <tr>
            <th>Code</th>
            <th>Title</th>
            <!--<th>Edition</th>-->
            <th>Status</th>
        </tr>

        {{for Items}}
        <tr>
            <td><b>{{:Code}}</b></td>
            <td>{{:Title}}</td>
            <!--<td>{{:Edition}}</td>-->
            {{if HoldingStatusID === 1}}
                <td style="background-color: #28a745;">{{:HoldingStatus}}</td>
            {{else HoldingStatusID == 2}}
                <td style="background-color: #ffc107;">{{:HoldingStatus}}</td>
            {{else HoldingStatusID == 3}}
                <td style="background-color: #d9534f; color:white;">{{:HoldingStatus}}</td>
            {{else}}
                <td>{{:HoldingStatus}}</td>
            {{/if}}
        </tr>
        {{/for}}
    </table>
```

Data:
`{
	"SectionName": "26- WEST COAST OF ITALY",
	"VesselName": "11 11'",
	"Count": 42,
	"Items": [
		{
			"Code": "121",
			"Title": "Flamborough Head to Withernsea",
			"Edition": "27/04/2017",
			"HoldingStatusID": 1,
			"HoldingStatus": "Active"
		},
		{
			"Code": "129",
			"Title": "Whitby to Flamborough Head",
			"Edition": "01/02/2018",
			"HoldingStatusID": 1,
			"HoldingStatus": "Active"
		},
		{
			"Code": "137",
			"Title": "Haikou Wan",
			"Edition": "15/11/2018",
			"HoldingStatusID": 1,
			"HoldingStatus": "Active"
		},
		{
			"Code": "140",
			"Title": "Crotone, Gallipoli and Bari with Approaches",
			"Edition": "23/04/2015",
			"HoldingStatusID": 1,
			"HoldingStatus": "Active"
		},
		{
			"Code": "144",
			"Title": "Gibraltar",
			"Edition": "19/11/2015",
			"HoldingStatusID": 1,
			"HoldingStatus": "Active"
		},
		{
			"Code": "145",
			"Title": "Ports of Tanger Med and Ksar Sghir",
			"Edition": "26/12/2019",
			"HoldingStatusID": 1,
			"HoldingStatus": "Active"
		},
		{
			"Code": "153",
			"Title": "Approaches to Marseille",
			"Edition": "03/03/2022",
			"HoldingStatusID": 1,
			"HoldingStatus": "Active"
		},
		{
			"Code": "178",
			"Title": "Ports in Algeria",
			"Edition": "26/10/2017",
			"HoldingStatusID": 1,
			"HoldingStatus": "Active"
		},
		{
			"Code": "454",
			"Title": "Kingston Harbour",
			"Edition": "07/03/2019",
			"HoldingStatusID": 1,
			"HoldingStatus": "Active"
		},
		{
			"Code": "670",
			"Title": "Ports in the Gulf of Kachchh",
			"Edition": "10/02/2011",
			"HoldingStatusID": 1,
			"HoldingStatus": "Active"
		},
		{
			"Code": "1123",
			"Title": "Western Approaches to Saint George's Channel and Bristol Channel",
			"Edition": "27/02/2020",
			"HoldingStatusID": 1,
			"HoldingStatus": "Active"
		},
		{
			"Code": "1189",
			"Title": "Approaches to Cartagena",
			"Edition": "20/05/2010",
			"HoldingStatusID": 2,
			"HoldingStatus": "Asleep"
		}
	]
}`

**Comment by pofider** [comment]
This works fine with the official `jsreport/jsreport:3.6.2` image.

**Comment by euangordon** [comment]
Hi Jan, thanks for letting me know. I will try and workout how to upgrade and then try again. :)

**Comment by euangordon** [comment]
@pofider We have updated to 3.6.2 this morning but still no colours showing....

![image](https://user-images.githubusercontent.com/32622054/182340519-f68be1e9-a23d-43c4-b92e-f2a58afd846c.png)

**Comment by pofider** [comment]
Do you use the official docker image?

Try to select the "print background" in the template props
![image](https://user-images.githubusercontent.com/2041960/182342138-2834248c-d34e-46c4-84cf-c52d0ecd4867.png)

Try the template as you shared it originally without all the other styles and images. Does that work?

**Comment by euangordon** [comment]
@pofider Thanks Jan, the "print background" has fixed it. Sorry, hadn't realised that needed to be turned on for this to work.

We are using the official docker image in Azure. Worked out how to upgrade this morning. It was simple once we found the option, but might be worth adding to the documentation?

**Comment by pofider** [comment]
This option is enabled by default so you typically won't deal with it. It got probably "deselected" during migrating from the jo older version.
