### ISSUE TITLE
Landscape mode - width, height do not work

### ISSUE THREAD

**Issue by NameGrey** [jsreport/jsreport#948]
Hi everyone.

I have html page with fixed size width: 842px, height: 595px. I am trying to build a pdf report for that page, however the page is just part of the final report (see picture below)
![image](https://user-images.githubusercontent.com/6246048/183067980-2396b6b2-ed12-4a34-ae80-f2c8438a825d.png)

Blue background is my page I expect being full sized.

Here is an example I have created (width and height do not work and do nothing when I change them):

https://playground.jsreport.net/w/NameGrey/BspPcQG7

Additionally I tried to use "scale". And set it to "1.5" or "1.33333333" or any similar value, but in that case I could see an additional 1px white line in the bottom and right borders.

![image](https://user-images.githubusercontent.com/6246048/183068487-f5a168d7-7fa9-4d41-9dc5-50678faab671.png)

Please assist me with that problem.

**Comment by bjrmatos** [comment]
it seems that when you enable the landscape you have to invert the order of width and height, and also remove the format, and leave it empty

![Screenshot 2022-08-05 at 11 17 32@2x](https://user-images.githubusercontent.com/4262050/183119238-a66b841d-93da-4cdb-8cd0-db143d3ecc72.jpg)

see updated playground https://playground.jsreport.net/w/anon/UdCcLf9A

**Comment by NameGrey** [comment]
@bjrmatos ah sorry, I was too fast to answer you... Actually in your example you do not set "scale" option. If you set "scale" option to 1.5, there will be still visible 1px line at bottom ((

**Comment by bjrmatos** [comment]
> However I would pay attention of the team to that problem (I think it's not obvious for the user). If about exchanging width and height is more or less clear (I tried it), but not clear that it doesn't work with "A4" format...

yes, perhaps the width/height exchange is not so obvious. but this is how the chrome works, perhaps we can add some notes on the docs. about that it does not work when the format field is set, I think we can normalize that behavior, I mean that when pdf width and height are set we can ignore the format field by default, we need to choose which one has more priority so we can ignore the other. chrome by default seems to give it more priority to the format field, that is why it was ignoring the pdf width and height you were using, it this default for the priority makes sense or not that is another question.

> Actually in your example you do not set "scale" option

yes, what I did was to clone your original playground example, which also does not include the scale option.

>If you set "scale" option to 1.5, there will be still visible 1px line at bottom

yes, what I see on playground is that 1px added and a new page added. why do you need the scale? i don't have any solution to that, when you tweak the scale you are changing dimensions outside of the html, so I am not aware of any solution that will give you full background on a container when tweaking the scale option.

**Comment by NameGrey** [comment]
You are right, I do not need "scale" at all)) so I have removed it and all works fine for me. Thank you a lot for your time!
