### ISSUE TITLE
Child Templates circle in using child template

### ISSUE THREAD

**Issue by dcoblentz** [jsreport/jsreport#95]
I have a report structured more or less this way:

Template 1
{#child template2}

Template 2
{#child template3}
{#child template3}

Template 3
....

This configuration triggers an error in the rendering process because it believes a cycle has been detected.

I think it should be possible to expand the childsCircleCache to include a hashed value of the current template and offset in order to more accurately detect a cycle. 

    function convert(str, p1, offset, s, done) {
        var hash = self.hashCode(s + offset);
        if (request.childsCircleCache[p1] && request.childsCircleCache[p1][hash] &&     request.options.isChildRequest) {
            .......
        }
        if( !request.childsCircleCache[p1] ) {
            request.childsCircleCache[p1] = {};
        }
        request.childsCircleCache[p1][hash] = true;
        ....

This works for the above situation, but would fail for the following one:
Template 1
{#child template2}

Template 2
{#child template3}
{#child template3}

Template 3
{#child template 1}

**Comment by pofider** [comment]
Yes, thanks!

Fixed.

**Comment by pofider** [comment]
Release in 0.7.1

**Comment by dcoblentz** [comment]
Thank you!
