### ISSUE TITLE
chrome-pdf recipe , setting headers and footers, too small and not visible.

### ISSUE THREAD

**Issue by mai1x9** [jsreport/jsreport#956]
Header and footer are too small in size. This is a simple pdf with small content and header. 
```
let header = '<h1> Header example </h1>
```
and 

template properties passed to `render`
```
template: {
        content: `<h1> pdf example contents ... </h1>`, // html_code,
        engine: 'handlebars',
        recipe: 'chrome-pdf',
        chrome: {
            "displayHeaderFooter": true,
            headerTemplate: header,
            footerTemplate: footer,
            format: 'A4',
            "marginTop": "50px",
            "marginRight": "20px",
            "marginBottom": "50px",
            "marginLeft": "20px",
            "numberOfWorkers": 4,
            timeout: 30000, // 30 seconds
        }
      }
```

**FInal PDF output:**
The header is too small.

<img width="1644" alt="Screenshot 2022-08-26 at 1 13 02 AM" src="https://user-images.githubusercontent.com/43678329/186754520-caf82087-266a-4c5a-bd2b-59d05e8eb852.png">

**Comment by pofider** [comment]
Please see the docs where its mentioned
https://jsreport.net/learn/chrome-pdf#native-headers-and-footers

**Comment by mai1x9** [comment]
> Please see the docs where its mentioned https://jsreport.net/learn/chrome-pdf#native-headers-and-footers

the docs has no enough information, a simple `h1` tag is not properly visible, and there is no proper documentation on how the header or footer need to be supplied as input.

**Comment by mansubarna** [comment]
Have you found any solution for this? I am also stuck in this issue

**Comment by pofider** [comment]
You need to inline the font size
```
<span style="font-size:20px">hello</span>
```
