### ISSUE TITLE
prepare our images to work with Apple Silicon and update docs

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#957]
Docker + Apple Silicon needs that we use chromium browser instead of chrome browser. we already know the steps needed to handle this, we just need to update our images and the docs to mention what it is needed.

Ref: https://forum.jsreport.net/topic/1900/does-not-work-with-apple-silicon-m1-using-docker-for-desktop-preview/7

**Comment by pofider** [comment]
This is done.

**Comment by apacciaroni-xbs** [comment]
@pofider maybe I'm missing something but even with the latest version (3.8.0), I'm getting this error

**Comment by bjrmatos** [comment]
this is not released yet, just implemented, we are working on releasing 3.9.0 now
