### ISSUE TITLE
afterRender renders phantom-pdf footer separatly

### ISSUE THREAD

**Issue by kdbo** [jsreport/jsreport#98]
Hi,
I am trying to send a mail with a pdf report attached. 
This  report is build from a template (phantom-pdf recipe),which has a html footer.
I created an afterRender function and I am getting two emails, one containing
the correct pdf, including the footer.
But another mail is also generated, with the footer only in the attachment.

In the logs:

>2015-08-17T19:00:21.468Z - info: Rendering template {shortid:4Jnmqo5o, recipe:phantom-pdf,engine:jsrender}
>2015-08-17T19:00:21.993Z - info: Rendering template {shortid:4Jnmqo5o, recipe:html,engine:jsrender}
>2015-08-17T19:00:27.589Z - info: Rendering request 47 finished in 6131 ms

If I remove the footer, the mail is sent only once

>2015-08-17T18:59:45.506Z - info: Rendering template {shortid:4Jnmqo5o, recipe:phantom-pdf,engine:jsrender}
>2015-08-17T18:59:51.458Z - info: Rendering request 46 finished in 5965 ms

here 's my afterRender function:

````javascript
 function afterRender(done){
    var mail = require("nodemailer");
    var moment = require('moment');
    var thisdate = moment().add(1,'days');
    var text = "Hello ,\n";
    text += "\n";
    request.data.resultSet.summary.forEach(function(row){
        text += row.total + ' ' + row.name + "\n"; 
    });
   text += "\n\n\nRegards";
    var transport = mail.createTransport({
        host: "mail.example.com",
        port: 25,
        debug: false,
        ignoreTLS: true
    });
    
    var mailopts = {
            from: {name: 'My Application', address: 'no-reply@xxxxxx.com'}, // sender address
            to: {name: 'My Name', address: 'me@example.com'}, // list of receivers
            subject: "document  "+ thisdate.format('YYYY-MM-DD'), // Subject line
            text: text,
            attachments:[
                {
                    filename: 'mydoc_' + thisdate.format('YYYYMMDD') + '.pdf',
                    content: new Buffer(response.content),
                    contentType: 'application/pdf'
                }
            ]
    };
    
    transport.sendMail(mailopts, function(error, responseStatus){
        if(error) {
            done(error);
            return;
        } else {
            done(responseStatus.message);
        }
    });
    
    
}
`````

**Comment by kdbo** [comment]
I just noticed that it doesn't happen when the pdf is only one page

**Comment by pofider** [comment]
Hi,
thanks for excellent issue.

Here is the solution:
```js
function afterRender(done) {
    //filter out script execution for phantom header
    if (request.options.isChildRequest)
      return done();
      
    //your script
    done();
}
```

Please keep this open, I need to document this behavior before.

**Comment by kdbo** [comment]
Cool ! thanks for the quick response :-)

**Comment by pofider** [comment]
Now it is mentioned also in the docs. Closing.
