### ISSUE TITLE
When exporting the ppt, the size of the image cannot be adapted according to the frame, and the size of the original image is always maintained. This is 

### ISSUE THREAD

**Issue by sparGuan** [jsreport/jsreport#999]
During the test, it was found that the PPT exported by the plug-in could not adapt the size of the image according to the outer border, which caused the image to be too large and deformed when the user edited the PPT. Is there any way to solve the problem that the image size could not be adaptive? Please contact email

as493683987@gmail.com

**Comment by bjrmatos** [comment]
hi! can you share a demo of this problem? you can share your template and code here https://playground.jsreport.net/

**Comment by sparGuan** [comment]
> hi! can you share a demo of this problem? you can share your template and code here https://playground.jsreport.net/

![image](https://user-images.githubusercontent.com/28480563/201799605-775bf163-4cc8-4b25-9167-30baa6827352.png)
you can see the Image Box is bigger
and then the demo is small, How can I do, I want to the Image size can be same Image box
![image](https://user-images.githubusercontent.com/28480563/201799854-85766f1e-b9c4-420c-9f57-c1ababe0166f.png)

**Comment by bjrmatos** [comment]
hi! right now it is not supported, the current implementation uses the same dimensions of the new image.

this will be solved by making the `pptxImage` helper support the same options than [`docxImage`](https://jsreport.net/learn/docx#docximage), with that implemented you can use the `usePlaceholderSize` to make the new image match the dimensions of placeholder.

we will look at this.

**Comment by bjrmatos** [comment]
@sparGuan can you share the pptx file you use for this test? i want to use the same because i tried to create an example and the output i get seems to match the dimensions than the original image.

![Screenshot 2022-11-16 at 3 11 52@2x](https://user-images.githubusercontent.com/4262050/202284540-119960ee-b9ff-4393-a770-d71d1038ff0f.jpg)

even better if you [export your entities](https://jsreport.net/learn/import-export) and share it

**Comment by bjrmatos** [comment]
FYI i was able to reproduce the issue, so i will continue working on the fix
